//! `nim.cfg` emission from a resolved graph (RFC §6 S9; `docs/spec/nimcfg.md` /
//! conformance-fixtures §2). Mirrors `milpa/nimcfg.py:format_nimcfg`.
//!
//! One `--path:"…"` line per resolved dep so the Nim compiler finds each dep's
//! source tree — no nimble involvement. The output is byte-exact and
//! deterministic: emission order is **lexicographic by dep name** (the spec's
//! single canonical ordering rule, resolver-semantics §4.4 — a toposort's
//! sibling tie-break is not reproducible across implementations, lexicographic
//! is, and it matches the lockfile's own dep-entry order).
//!
//! Per-member workspace emission (`write_workspace_nimcfgs`) and feature-flag
//! `-d:` defines (#23) are deferred: workspace lands in S11, and `ResolvedDep`
//! does not yet carry `active_flags`/`flag_defines` (no success fixture resolves
//! a flag-carrying dep — same deferral as `from_graph`'s flag fields).

use milpa_types::{ResolvedDep, ResolvedGraph};

/// The normative `nim.cfg` header (conformance-fixtures §2). Stored without its
/// trailing newline; the join below re-introduces line breaks.
const HEADER: &str =
    "# generated by milpa; do not edit\n# manifest: milpa.kdl\n# lockfile: milpa.lock";

/// Render `graph` into `nim.cfg` text.
///
/// `deps_dir` is the POSIX-relative deps directory (`"_deps"`); paths always use
/// `/` regardless of host OS (nim.cfg syntax is OS-agnostic). `self_src_dir`, when
/// non-empty, adds a leading `--path:"<self_src_dir>"` for the consuming
/// package's own source tree (emitted first so self-modules shadow same-named
/// dep import paths).
pub fn format_nimcfg(graph: &ResolvedGraph, deps_dir: &str, self_src_dir: &str) -> String {
    let mut lines: Vec<String> = vec![HEADER.to_string(), String::new()];

    if !self_src_dir.is_empty() {
        lines.push(format!("--path:\"{self_src_dir}\""));
    }

    let mut ordered: Vec<&ResolvedDep> = graph.deps.iter().collect();
    ordered.sort_by(|a, b| a.name.cmp(&b.name));
    for dep in &ordered {
        lines.push(format!("--path:\"{}\"", path_for(dep, deps_dir)));
    }

    // A trailing blank line (→ final newline) only when there are deps, matching
    // the Python reference's `if graph.deps:` guard.
    if !graph.deps.is_empty() {
        lines.push(String::new());
    }
    lines.join("\n")
}

/// `<deps_dir>/<name>[/<src_dir>]` in POSIX form.
fn path_for(dep: &ResolvedDep, deps_dir: &str) -> String {
    let mut base = format!("{deps_dir}/{}", dep.name);
    if !dep.src_dir.is_empty() {
        base.push('/');
        base.push_str(&dep.src_dir);
    }
    base
}

#[cfg(test)]
mod tests {
    use super::*;
    use milpa_types::{Provenance, Version};

    fn dep(name: &str, src_dir: &str) -> ResolvedDep {
        ResolvedDep {
            name: name.into(),
            identity: "sha256:00".into(),
            version: Version::release(0, 0, 1),
            src_dir: src_dir.into(),
            requires: vec![],
            provenance: Provenance::Git {
                url: "https://e/x.git".into(),
                ref_spec: "main".into(),
                commit_sha: None,
            },
        }
    }

    #[test]
    fn single_dep_with_src_dir() {
        let graph = ResolvedGraph {
            deps: vec![dep("foo", "src")],
        };
        assert_eq!(
            format_nimcfg(&graph, "_deps", ""),
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n\
             \n\
             --path:\"_deps/foo/src\"\n"
        );
    }

    #[test]
    fn no_deps_has_no_trailing_path_block() {
        let graph = ResolvedGraph { deps: vec![] };
        // Header + the single blank line, no trailing newline (no deps).
        assert_eq!(
            format_nimcfg(&graph, "_deps", ""),
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n"
        );
    }

    #[test]
    fn deps_emit_lexicographically_not_in_graph_order() {
        let graph = ResolvedGraph {
            deps: vec![dep("zlib", ""), dep("alpha", "lib")],
        };
        let out = format_nimcfg(&graph, "_deps", "");
        let a = out.find("_deps/alpha/lib").unwrap();
        let z = out.find("_deps/zlib").unwrap();
        assert!(a < z, "alpha must precede zlib");
    }

    #[test]
    fn self_src_dir_is_emitted_before_deps() {
        let graph = ResolvedGraph {
            deps: vec![dep("foo", "src")],
        };
        let out = format_nimcfg(&graph, "_deps", "mysrc");
        let self_idx = out.find("--path:\"mysrc\"").unwrap();
        let dep_idx = out.find("_deps/foo/src").unwrap();
        assert!(self_idx < dep_idx);
    }
}
