"""milpa.lock — reproducible-build snapshot of a resolved dep graph.

The lockfile records two distinct kinds of data per dep:

  - **Identity**: `content_hash` (sha256 of source tree). The
    canonical 'what'. Trust-independent, recomputable from bytes
    alone. This is the field consumers should verify against.
  - **Provenance**: `source` (URL or registry name), `ref`, `tag`,
    `sha`. Descriptive metadata for refetching. Trust-dependent —
    the git server, mirror, or registry could disagree without
    notice.

See docs/identity-and-provenance.md for the model and why the two
are distinct.

Format is KDL (consistent with the manifest milpa.kdl). Schema is
versioned so future format changes don't silently break readers.

Library vs application:
  The lockfile format is identical for both. Whether the lockfile is
  committed to version control depends on the manifest's `kind`:
    library     → don't commit (downstream consumers re-resolve)
    application → commit (deterministic builds)
  That decision belongs to the CLI / manifest layer, not here.
"""

from dataclasses import dataclass
from pathlib import Path

import kdl

from .identity import compute_content_hash
from .resolver import ResolvedDep, ResolvedGraph


LOCKFILE_SCHEMA_VERSION = 1
_HEADER = "// generated by milpa; reproducible build snapshot"


@dataclass(frozen=True)
class LockedDep:
    name: str
    source: str
    ref: str | None
    tag: str | None
    sha: str | None
    content_hash: str | None
    version: str
    src_dir: str
    requires: tuple[str, ...]


@dataclass(frozen=True)
class Lockfile:
    version: int
    deps: tuple[LockedDep, ...]
    strategy: str = "maxver"   # resolution strategy that produced this lockfile


class LockfileError(Exception):
    """Raised on malformed lockfile text or graph/lockfile mismatch."""


def from_graph(graph: ResolvedGraph, *, strategy: str = "maxver") -> Lockfile:
    """Convert a ResolvedGraph into a Lockfile.

    Deps are sorted by name for deterministic output — same graph
    always produces byte-identical lockfile text. `strategy` records
    which resolution strategy produced this lockfile (for diagnostics;
    not used during reproduction since concrete versions are pinned).
    """
    deps = tuple(sorted(
        (_locked_from_resolved(d) for d in graph.deps),
        key=lambda d: d.name,
    ))
    return Lockfile(
        version=LOCKFILE_SCHEMA_VERSION,
        deps=deps,
        strategy=strategy,
    )


def _locked_from_resolved(d: ResolvedDep) -> LockedDep:
    return LockedDep(
        name=d.name,
        source=d.source,
        ref=_infer_ref(d),
        tag=d.tag,
        sha=d.sha,
        content_hash=d.content_hash,
        version=_format_version(d.version),
        src_dir=d.src_dir,
        requires=d.requires,
    )


def _infer_ref(d: ResolvedDep) -> str | None:
    """URL deps record the manifest-declared ref (branch/tag/sha) so
    consumers can see what was originally requested. Registry deps fall
    back to the resolved tag."""
    return d.ref if d.ref is not None else d.tag


def _format_version(v: tuple[int, int, int]) -> str:
    return f"{v[0]}.{v[1]}.{v[2]}"


def parse_lockfile(text: str) -> Lockfile:
    """Parse KDL lockfile text into a Lockfile value.

    Raises LockfileError on malformed input or unsupported schema
    version.
    """
    try:
        doc = kdl.parse(text)
    except kdl.errors.ParseError as e:
        raise LockfileError(f"KDL syntax error: {e}") from e

    schema_version: int | None = None
    deps: list[LockedDep] = []
    strategy: str = "maxver"  # default for pre-strategy lockfiles
    for node in doc.nodes:
        if node.name == "version":
            schema_version = _scalar_int(node, "version")
        elif node.name == "strategy":
            if len(node.args) == 1 and isinstance(node.args[0], str):
                strategy = node.args[0]
        elif node.name == "dep":
            deps.append(_parse_dep(node))
        else:
            # Tolerate unknown top-level nodes for forward compat — the
            # version field gates breaking changes.
            continue

    if schema_version is None:
        raise LockfileError("lockfile missing required 'version' node")
    if schema_version != LOCKFILE_SCHEMA_VERSION:
        raise LockfileError(
            f"unsupported lockfile schema version {schema_version} "
            f"(this milpa understands version {LOCKFILE_SCHEMA_VERSION})"
        )
    return Lockfile(version=schema_version, deps=tuple(deps), strategy=strategy)


def _parse_dep(node: kdl.Node) -> LockedDep:
    if len(node.args) != 1 or not isinstance(node.args[0], str):
        raise LockfileError("dep node requires exactly one string argument (the name)")
    name = node.args[0]
    fields: dict[str, object] = {}
    for child in node.nodes:
        if child.name == "requires":
            fields["requires"] = tuple(a for a in child.args if isinstance(a, str))
            continue
        if len(child.args) != 1:
            raise LockfileError(
                f"dep {name!r} field {child.name!r} must have exactly one value"
            )
        fields[child.name] = child.args[0]
    content_hash = fields.get("content_hash")
    if isinstance(content_hash, str) and content_hash.startswith("sha256:"):
        content_hash = content_hash[len("sha256:"):]
    return LockedDep(
        name=name,
        source=fields.get("source", ""),
        ref=fields.get("ref"),
        tag=fields.get("tag"),
        sha=fields.get("sha"),
        content_hash=content_hash,
        version=fields.get("version", "0.0.0"),
        src_dir=fields.get("src_dir", ""),
        requires=fields.get("requires", ()),
    )


def _scalar_int(node: kdl.Node, field_name: str) -> int:
    if len(node.args) != 1:
        raise LockfileError(f"{field_name!r} takes exactly one value")
    val = node.args[0]
    # kdl-py represents unquoted numbers as Decimal/float; coerce.
    try:
        return int(val)  # type: ignore[arg-type]
    except (TypeError, ValueError) as e:
        raise LockfileError(
            f"{field_name!r} must be an integer (got {val!r})"
        ) from e


def format_lockfile(lockfile: Lockfile) -> str:
    """Render a Lockfile to KDL text."""
    lines = [
        _HEADER,
        f"version {lockfile.version}",
        f'strategy "{lockfile.strategy}"',
        "",
    ]
    for dep in lockfile.deps:
        lines.append(f'dep "{dep.name}" {{')
        lines.append(f'    source "{dep.source}"')
        if dep.ref is not None:
            lines.append(f'    ref "{dep.ref}"')
        if dep.tag is not None:
            lines.append(f'    tag "{dep.tag}"')
        if dep.sha is not None:
            lines.append(f'    sha "{dep.sha}"')
        if dep.content_hash is not None:
            lines.append(f'    content_hash "sha256:{dep.content_hash}"')
        lines.append(f'    version "{dep.version}"')
        lines.append(f'    src_dir "{dep.src_dir}"')
        if dep.requires:
            req_args = " ".join(f'"{r}"' for r in dep.requires)
            lines.append(f'    requires {req_args}')
        else:
            lines.append("    requires")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def write_lockfile(lockfile: Lockfile, path: Path) -> Path:
    """Write lockfile KDL text to `path`. Returns the path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(format_lockfile(lockfile))
    return path


def load_lockfile(path: Path) -> Lockfile:
    """Read and parse a lockfile from disk.

    Raises LockfileError if the file is missing, unreadable, or
    malformed.
    """
    try:
        text = path.read_text()
    except FileNotFoundError as e:
        raise LockfileError(f"lockfile not found: {path}") from e
    except OSError as e:
        raise LockfileError(f"cannot read lockfile {path}: {e}") from e
    return parse_lockfile(text)


def verify_against_graph(
    lockfile: Lockfile,
    graph: ResolvedGraph,
) -> None:
    """Confirm the graph matches the lockfile dep-for-dep.

    Raises LockfileError listing every divergence:
    - extra deps in the graph that aren't locked
    - missing deps that are locked but absent from the graph
    - content_hash or sha mismatches

    Intended consumer (not yet wired): `milpa update` (#18) will
    re-resolve the manifest, then call this to detect what changed
    vs. the locked state. For verifying the on-disk _deps/ directory
    matches the lockfile (no re-resolve), use
    `verify_lockfile_against_deps` instead.
    """
    locked_by_name = {d.name: d for d in lockfile.deps}
    graph_by_name = {d.name: d for d in graph.deps}

    errors: list[str] = []
    for name in graph_by_name.keys() - locked_by_name.keys():
        errors.append(f"unexpected dep {name!r} in resolved graph (not in lockfile)")
    for name in locked_by_name.keys() - graph_by_name.keys():
        errors.append(f"locked dep {name!r} is missing from resolved graph")
    for name in graph_by_name.keys() & locked_by_name.keys():
        locked = locked_by_name[name]
        actual = graph_by_name[name]
        if locked.content_hash != actual.content_hash:
            errors.append(
                f"content_hash mismatch for {name!r}: "
                f"locked={locked.content_hash!r}, actual={actual.content_hash!r}"
            )
        if locked.sha is not None and actual.sha is not None and locked.sha != actual.sha:
            errors.append(
                f"sha mismatch for {name!r}: "
                f"locked={locked.sha!r}, actual={actual.sha!r}"
            )

    if errors:
        raise LockfileError(
            "lockfile does not match resolved graph:\n  " + "\n  ".join(errors)
        )


def verify_lockfile_against_deps(
    lockfile: Lockfile,
    deps_dir: Path,
) -> list[str]:
    """Walk `deps_dir/<name>/` for each locked dep and verify its
    content_hash matches the lockfile's recorded identity.

    Returns a list of divergence messages (empty list = no drift).
    Each message is a single human-readable line suitable for stderr.

    Divergences detected:
      - missing: locked dep has no _deps/<name>/ directory
      - mismatch: directory exists but its content_hash differs from
        the lockfile's recorded identity
      - extra: a non-dotfile / non-dotdir entry in _deps/ that isn't
        a locked dep name (the user manually added something, or a
        stale dep wasn't cleaned up)
    """
    divergences: list[str] = []

    locked_by_name = {d.name: d for d in lockfile.deps}

    # Missing / mismatch: walk every locked dep.
    for name, locked in locked_by_name.items():
        dep_path = deps_dir / name
        if not dep_path.exists():
            divergences.append(f"{name}: missing from {deps_dir}/")
            continue
        if not dep_path.is_dir():
            divergences.append(
                f"{name}: expected directory at {dep_path}, found something else"
            )
            continue
        actual = compute_content_hash(dep_path)
        expected = locked.content_hash
        if expected != actual:
            divergences.append(
                f"{name}: content_hash mismatch — "
                f"lockfile says sha256:{(expected or '<none>')[:16]}..., "
                f"actual sha256:{actual[:16]}..."
            )

    # Extra: anything in _deps/ that isn't a locked name (skip dotfiles).
    if deps_dir.exists() and deps_dir.is_dir():
        for entry in deps_dir.iterdir():
            if entry.name.startswith("."):
                continue
            if entry.name not in locked_by_name:
                divergences.append(
                    f"{entry.name}: extra dep in {deps_dir}/ not in lockfile"
                )

    return divergences
