"""milpa.kdl parser.

Public surface: parse_manifest(text), load_manifest(path), and the
value types Manifest / UrlDep, plus ManifestError for malformed input.
kdl-py is an internal detail; callers see only the typed values.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Literal
from urllib.parse import ParseResult, urlparse

import kdl


Kind = Literal["library", "application"]


@dataclass(frozen=True)
class UrlDep:
    name: str
    git: str
    ref: str


@dataclass(frozen=True)
class NamedDep:
    """A dep declared by name (resolved via the registry).

    Appears in manifests promoted from .nimble files that have
    `requires "results"` or `requires "stew >= 0.5.0"` style lines.
    milpa.kdl-authored manifests use only UrlDep today; named deps
    would be added if/when KDL-level named-dep syntax is introduced.
    """
    name: str
    constraint: str | None   # e.g. ">= 0.5.0" or None for any version


Dep = UrlDep | NamedDep


@dataclass(frozen=True)
class Manifest:
    deps: tuple[Dep, ...]
    kind: Kind


class ManifestError(Exception):
    """Raised when milpa.kdl is malformed or violates the schema."""


# What the parser accepts. These are the source of truth for validation;
# the schema doc at milpa/schema/milpa.schema.kdl documents the same shape
# for humans. Drift between the two is checked indirectly via tests against
# example manifests.
_TOP_LEVEL_NODES = frozenset({"deps", "kind"})
_URL_DEP_PROPS = frozenset({"git", "ref"})
_VALID_KINDS: tuple[Kind, ...] = ("library", "application")
_VALID_GIT_SCHEMES = frozenset({"https", "http", "ssh", "git"})


def parse_manifest(text: str, *, source: str | None = None) -> Manifest:
    """Parse a milpa.kdl source string into a typed Manifest.

    `source` is the file path (or other identifier) used in error
    messages; presently reserved for future use (error catalog work,
    issue #14). Raises `ManifestError` on malformed input or schema
    violations.
    """
    try:
        doc = kdl.parse(text)
    except kdl.errors.ParseError as e:
        raise ManifestError(f"KDL syntax error: {e}") from e
    deps: list[UrlDep] = []
    kind: Kind = "library"
    seen_names: set[str] = set()
    for node in doc.nodes:
        if node.name == "deps":
            for child in node.nodes:
                if child.name in seen_names:
                    raise ManifestError(
                        f"duplicate dep {child.name!r} in manifest"
                    )
                seen_names.add(child.name)
                deps.append(_parse_dep(child))
        elif node.name == "kind":
            kind = _parse_kind(node)
        else:
            allowed = ", ".join(sorted(_TOP_LEVEL_NODES))
            raise ManifestError(
                f"unknown top-level node {node.name!r} "
                f"(allowed: {allowed})"
            )
    return Manifest(deps=tuple(deps), kind=kind)


def load_manifest(path: Path) -> Manifest:
    """Read milpa.kdl from `path` and parse it.

    Raises `ManifestError` if the file is missing, unreadable, or
    malformed. The error message includes the path so the user can
    locate the offending file quickly.
    """
    try:
        text = path.read_text()
    except FileNotFoundError as e:
        raise ManifestError(f"manifest file not found: {path}") from e
    except OSError as e:
        raise ManifestError(f"cannot read manifest {path}: {e}") from e
    return parse_manifest(text, source=str(path))


_MANIFEST_HEADER = "// generated by milpa; edit by hand or via `milpa add` / `milpa remove`"


def format_manifest(m: Manifest) -> str:
    """Render a Manifest to milpa.kdl text.

    Emits a deps {...} block (omitted if no deps) plus the kind line.
    UrlDeps use the recommended `(url)` annotation on the git value;
    NamedDeps emit as `name` alone or `name "<constraint>"`.

    Output is deterministic but does NOT preserve hand-written
    comments — comment-preserving serialization is #15's deliverable.
    """
    lines: list[str] = [_MANIFEST_HEADER, ""]
    if m.deps:
        lines.append("deps {")
        for dep in m.deps:
            lines.append(_format_dep_line(dep))
        lines.append("}")
        lines.append("")
    lines.append(f'kind "{m.kind}"')
    return "\n".join(lines) + "\n"


def _format_dep_line(dep: Dep) -> str:
    """One deps-block child as a single KDL line."""
    if isinstance(dep, UrlDep):
        return f'    {_quote_name(dep.name)} git=(url)"{dep.git}" ref="{dep.ref}"'
    # NamedDep
    if dep.constraint is None:
        return f'    {_quote_name(dep.name)}'
    return f'    {_quote_name(dep.name)} "{dep.constraint}"'


def _quote_name(name: str) -> str:
    """Names always emitted as quoted strings — safe for any value
    (alphanumeric stays parseable as a bare identifier OR a quoted
    string, so we pick quoted for uniformity)."""
    return f'"{name}"'


def _parse_dep(node: kdl.Node) -> Dep:
    """Validate and convert one child of the `deps` block.

    Disambiguation: a child with `git=` property is a UrlDep; without
    it, it's a NamedDep (registry-resolved). Named deps may carry zero
    or one positional string argument for the version constraint.

    Examples:
        chronos git=(url)"..." ref="main"   → UrlDep
        results                              → NamedDep(name, constraint=None)
        stew ">= 0.5.0"                      → NamedDep(name, constraint=">= 0.5.0")
    """
    if "git" in node.props:
        return _parse_url_dep(node)
    return _parse_named_dep(node)


def _parse_url_dep(node: kdl.Node) -> UrlDep:
    """Validate and convert a URL-shaped dep child."""
    name = node.name
    extra = set(node.props.keys()) - _URL_DEP_PROPS
    if extra:
        unknown = ", ".join(repr(p) for p in sorted(extra))
        allowed = ", ".join(sorted(_URL_DEP_PROPS))
        raise ManifestError(
            f"dep {name!r}: unknown property/properties {unknown} "
            f"(allowed: {allowed})"
        )
    if "ref" not in node.props:
        raise ManifestError(f"dep {name!r}: missing required property 'ref'")
    # `git` may be a plain str or a ParseResult (when written with the
    # `(url)` KDL type annotation, kdl-py auto-converts). Normalize to
    # str so UrlDep is shape-stable regardless of annotation choice.
    git_raw = node.props["git"]
    git = git_raw.geturl() if isinstance(git_raw, ParseResult) else git_raw
    _validate_git_url(name, git)
    return UrlDep(name=name, git=git, ref=node.props["ref"])


def _parse_named_dep(node: kdl.Node) -> NamedDep:
    """Validate and convert a named (registry-resolved) dep child.

    Grammar: `<name> [<constraint-string>]`. Zero or one positional
    string argument. No properties (any property other than `git=`,
    which would route to URL path, is an error).
    """
    name = node.name
    if node.props:
        unknown = ", ".join(repr(p) for p in sorted(node.props.keys()))
        raise ManifestError(
            f"dep {name!r}: unknown property/properties {unknown} "
            f"on a named dep (a URL dep must declare 'git=...'; "
            f"a named dep takes only a positional version constraint)"
        )
    if len(node.args) == 0:
        return NamedDep(name=name, constraint=None)
    if len(node.args) == 1:
        constraint = node.args[0]
        if not isinstance(constraint, str):
            raise ManifestError(
                f"dep {name!r}: version constraint must be a quoted string"
            )
        return NamedDep(name=name, constraint=constraint)
    raise ManifestError(
        f"dep {name!r}: named deps take at most one positional argument "
        f"(the version constraint); got {len(node.args)}"
    )


def _parse_kind(node: kdl.Node) -> Kind:
    if len(node.args) != 1:
        raise ManifestError(
            f"'kind' takes exactly one value (got {len(node.args)})"
        )
    value = node.args[0]
    if value not in _VALID_KINDS:
        allowed = ", ".join(repr(k) for k in _VALID_KINDS)
        raise ManifestError(f"invalid kind {value!r} (allowed: {allowed})")
    return value


def _validate_git_url(dep_name: str, url: str) -> None:
    parsed = urlparse(url)
    if not parsed.scheme:
        raise ManifestError(
            f"dep {dep_name!r}: git URL {url!r} has no scheme "
            f"(expected one of: {', '.join(sorted(_VALID_GIT_SCHEMES))})"
        )
    if parsed.scheme not in _VALID_GIT_SCHEMES:
        raise ManifestError(
            f"dep {dep_name!r}: git URL {url!r} has unsupported scheme "
            f"{parsed.scheme!r} "
            f"(expected one of: {', '.join(sorted(_VALID_GIT_SCHEMES))})"
        )


# ---------------------------------------------------------------------------
# .nimble compatibility — auto-promote a .nimble file when no milpa.kdl exists
# ---------------------------------------------------------------------------

def manifest_from_nimble(nm) -> "Manifest":  # nm: NimbleManifest
    """Convert a parsed NimbleManifest to a milpa Manifest.

    Mapping:
      - UrlRequirement   → UrlDep (name derived from URL last segment)
      - NamedRequirement → NamedDep (constraint preserved)
      - `nim` requirements are dropped — the compiler version is the
        v2 toolchain RFC's territory, not source-dep resolution.

    `kind` defaults to "library" since .nimble has no equivalent
    concept. Consumers who want the library/application distinction
    write milpa.kdl.
    """
    # Imported here to avoid a circular import at module load.
    from .nimble_parse import NamedRequirement, UrlRequirement

    deps: list[Dep] = []
    for req in nm.requires:
        if isinstance(req, UrlRequirement):
            name = _name_from_url(req.url)
            deps.append(UrlDep(name=name, git=req.url, ref=req.ref or "main"))
        elif isinstance(req, NamedRequirement):
            if req.name == "nim":
                continue
            deps.append(NamedDep(name=req.name, constraint=req.constraint))
    return Manifest(deps=tuple(deps), kind="library")


def _name_from_url(url: str) -> str:
    """Derive a package name from a git URL.

    `https://github.com/x/foo.git` → `foo`
    `https://github.com/x/foo`     → `foo`
    """
    tail = url.rstrip("/").rsplit("/", 1)[-1]
    if tail.endswith(".git"):
        tail = tail[:-4]
    return tail


def load_or_discover_manifest(project_dir: Path) -> Manifest:
    """Load milpa.kdl if present; otherwise auto-promote a .nimble file.

    Discovery order:
      1. <project_dir>/milpa.kdl — preferred. If present, wins regardless
         of any .nimble files present.
      2. <project_dir>/<project_dir_basename>.nimble — matches Nim
         convention of naming the .nimble after the project.
      3. Any single <project_dir>/*.nimble file — fallback when the
         project dir name doesn't match a .nimble. Ambiguous (multiple
         .nimble files) raises ManifestError.

    Raises ManifestError if no manifest source can be found or if the
    discovered source has parse errors.
    """
    milpa_kdl = project_dir / "milpa.kdl"
    if milpa_kdl.exists():
        return load_manifest(milpa_kdl)

    # Try <project_name>.nimble first
    project_name = project_dir.name
    primary = project_dir / f"{project_name}.nimble"
    if primary.exists():
        return _load_manifest_from_nimble(primary)

    # Fallback: any *.nimble
    candidates = sorted(project_dir.glob("*.nimble"))
    if len(candidates) == 1:
        return _load_manifest_from_nimble(candidates[0])
    if len(candidates) > 1:
        names = ", ".join(c.name for c in candidates)
        raise ManifestError(
            f"multiple .nimble files in {project_dir} ({names}); "
            f"either rename one to match the project directory "
            f"({project_name}.nimble) or add a milpa.kdl"
        )

    raise ManifestError(
        f"no manifest found in {project_dir} — looked for "
        f"milpa.kdl, {project_name}.nimble, and any *.nimble"
    )


def _load_manifest_from_nimble(path: Path) -> Manifest:
    """Read a .nimble file and convert it to a milpa Manifest."""
    from .nimble_parse import NimbleParseError, parse_nimble
    try:
        text = path.read_text()
    except OSError as e:
        raise ManifestError(f"cannot read {path}: {e}") from e
    try:
        nm = parse_nimble(text)
    except NimbleParseError as e:
        raise ManifestError(
            f"failed to parse {path} as a nimble manifest: {e}"
        ) from e
    return manifest_from_nimble(nm)
