"""nim.cfg emission for a resolved dep graph.

Generates a `nim.cfg` file at the consuming project's root with one
`--path:` line per resolved dep. The nim compiler reads this file
automatically when invoked from the project directory and adds the
listed paths to its import search — no nimble involvement needed.
"""

from pathlib import Path

from .resolver import ResolvedDep, ResolvedGraph


_HEADER = (
    "# generated by milpa; do not edit\n"
    "# manifest: milpa.kdl\n"
    "# lockfile: milpa.lock\n"
)


def format_nimcfg(
    graph: ResolvedGraph,
    *,
    deps_dir: Path = Path("_deps"),
) -> str:
    """Render `graph` into nim.cfg text.

    Each dep contributes a `--path:"<deps_dir>/<name>[/<src_dir>]"`
    line. Paths use POSIX separators regardless of host OS — nim.cfg
    syntax is OS-agnostic.
    """
    lines = [_HEADER.rstrip("\n"), ""]
    for dep in graph.deps:
        lines.append(f'--path:"{_path_for(dep, deps_dir)}"')
    if graph.deps:
        lines.append("")
    return "\n".join(lines)


def _path_for(dep: ResolvedDep, deps_dir: Path) -> str:
    base = deps_dir.as_posix() + "/" + dep.name
    if dep.src_dir:
        base += "/" + dep.src_dir
    return base


def write_nimcfg(
    graph: ResolvedGraph,
    *,
    project_root: Path,
    deps_dir: Path = Path("_deps"),
) -> Path:
    """Write `nim.cfg` at `project_root/nim.cfg`. Returns the path.

    Idempotent — same graph always produces the same bytes.
    """
    target = project_root / "nim.cfg"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(format_nimcfg(graph, deps_dir=deps_dir))
    return target
