"""nim.cfg emission for a resolved dep graph.

Generates a `nim.cfg` file at the consuming project's root with one
`--path:` line per resolved dep. The nim compiler reads this file
automatically when invoked from the project directory and adds the
listed paths to its import search — no nimble involvement needed.
"""

from pathlib import Path

from .resolver import ResolvedDep, ResolvedGraph


_HEADER = (
    "# generated by milpa; do not edit\n"
    "# manifest: milpa.kdl\n"
    "# lockfile: milpa.lock\n"
)


def format_nimcfg(
    graph: ResolvedGraph,
    *,
    deps_dir: Path = Path("_deps"),
    self_src_dir: str = "",
) -> str:
    """Render `graph` into nim.cfg text.

    Each dep contributes a `--path:"<deps_dir>/<name>[/<src_dir>]"`
    line. Paths use POSIX separators regardless of host OS — nim.cfg
    syntax is OS-agnostic.

    `self_src_dir` adds a `--path:"<self_src_dir>"` line for the
    consuming package's own source tree. Emitted before dep paths so
    self-modules shadow any same-named dep import paths.
    """
    lines = [_HEADER.rstrip("\n"), ""]
    if self_src_dir:
        lines.append(f'--path:"{self_src_dir}"')
    # Emission order is lexicographic by dep name — the spec's single
    # canonical ordering rule (resolver-semantics.md §4.4). A toposort
    # would also be deterministic but its sibling tie-break is not
    # reproducible across implementations; lexicographic is, and it
    # matches the lockfile's own dep-entry order. Nim search-path order
    # is not semantically load-bearing (deps live in disjoint dirs).
    ordered = sorted(graph.deps, key=lambda d: d.name)
    for dep in ordered:
        lines.append(f'--path:"{_path_for(dep, deps_dir)}"')
    # Feature flag defines (#23). For each active flag on a dep:
    #   - If dep.flag_defines has an explicit override for this flag,
    #     emit those literal -d: strings.
    #   - Otherwise use the convention `-d:<dep_name>_<flag_name>`.
    flag_lines: list[str] = []
    for dep in ordered:
        explicit = dict(dep.flag_defines)
        for flag in sorted(dep.active_flags):
            if flag in explicit:
                for d in explicit[flag]:
                    flag_lines.append(f'-d:{d}')
            else:
                flag_lines.append(f'-d:{dep.name}_{flag}')
    if flag_lines:
        lines.append("")
        lines.extend(flag_lines)
    if graph.deps:
        lines.append("")
    return "\n".join(lines)


def _path_for(dep: ResolvedDep, deps_dir: Path) -> str:
    base = deps_dir.as_posix() + "/" + dep.name
    if dep.src_dir:
        base += "/" + dep.src_dir
    return base


def write_nimcfg(
    graph: ResolvedGraph,
    *,
    project_root: Path,
    deps_dir: Path = Path("_deps"),
    self_src_dir: str = "",
) -> Path:
    """Write `nim.cfg` at `project_root/nim.cfg`. Returns the path.

    Idempotent — same graph always produces the same bytes.
    """
    target = project_root / "nim.cfg"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        format_nimcfg(graph, deps_dir=deps_dir, self_src_dir=self_src_dir)
    )
    return target


# ---------------------------------------------------------------------------
# Workspace emission — per-member nim.cfg pointing at shared _deps/
# (W4 / #76)
# ---------------------------------------------------------------------------

def member_dep_closure(
    graph: ResolvedGraph, member_name: str,
) -> list[ResolvedDep]:
    """Transitive closure from `member_name` in `graph`, excluding the
    member itself. Returns deps in topological order (deps before
    dependents) so consumers can emit them in a deterministic --path:
    sequence.

    The graph already encodes per-member reachability via each
    ResolvedDep's `requires` field; this function just walks it.
    """
    by_name = {d.name: d for d in graph.deps}
    if member_name not in by_name:
        return []

    visited: set[str] = set()
    order: list[str] = []

    def visit(name: str) -> None:
        if name in visited or name not in by_name:
            return
        visited.add(name)
        for req in by_name[name].requires:
            visit(req)
        order.append(name)

    # Walk requires from the member, but DON'T include the member itself
    # in the closure (you don't --path: your own src).
    for req in by_name[member_name].requires:
        visit(req)
    return [by_name[n] for n in order]


def write_workspace_nimcfgs(
    workspace,  # Workspace from milpa.workspace
    graph: ResolvedGraph,
) -> list[Path]:
    """Emit one nim.cfg per workspace member at <root>/<member-path>/nim.cfg.

    Each member's nim.cfg lists only its transitively-reachable deps
    (Nim isolation per-member). --path: lines use relative paths from
    the member's directory:
      - external deps     → <root>/_deps/<dep>/<src>
      - member references → <root>/<other-member-path>/<src>

    POSIX path separators regardless of host OS — nim.cfg syntax is
    OS-agnostic.

    Returns the list of written paths, in member declaration order.
    """
    import os

    deps_dir = workspace.root / "_deps"
    member_dir_by_name = {m.name: m.directory for m in workspace.members}
    written: list[Path] = []

    for member in workspace.members:
        target = member.directory / "nim.cfg"
        target.parent.mkdir(parents=True, exist_ok=True)
        lines = [_HEADER.rstrip("\n"), ""]

        # Lexicographic emission order — same canonical rule as the
        # single-package nim.cfg (resolver-semantics.md §4.4). The
        # closure is computed via toposort for reachability; emission
        # sorts by name so the output is reproducible across impls.
        closure = sorted(
            member_dep_closure(graph, member.name), key=lambda d: d.name
        )
        for dep in closure:
            dep_target = _absolute_path_for_dep(
                dep, deps_dir=deps_dir, member_dir_by_name=member_dir_by_name,
            )
            rel = os.path.relpath(dep_target, member.directory)
            # Normalize to POSIX separators
            rel_posix = Path(rel).as_posix()
            lines.append(f'--path:"{rel_posix}"')

        if closure:
            lines.append("")
        target.write_text("\n".join(lines))
        written.append(target)

    return written


def _absolute_path_for_dep(
    dep: ResolvedDep, *,
    deps_dir: Path,
    member_dir_by_name: dict[str, Path],
) -> Path:
    """Compute the absolute on-disk path for a dep's source tree.

    Member deps resolve to the member's directory (with src_dir
    appended if declared). External deps resolve to deps_dir/<name>
    (with src_dir appended if declared)."""
    if dep.source.startswith("member:"):
        base = member_dir_by_name[dep.name]
    else:
        base = deps_dir / dep.name
    if dep.src_dir:
        return base / dep.src_dir
    return base
