#!/usr/bin/env python3
"""Corpus-regeneration tool — identity B-cutover (RFC identity-conformance-authority).

Re-emits every ``expected/milpa.lock`` and ``expected/content_hash`` (+ the
``milpa hash`` ``expected/stdout``) in the shared ``conformance/spec-v1`` corpus
under **epoch 2** (the canonical content Merkle DAG, spec/identity.md §1.8), by
driving the production conformance harness in *bless mode* (single source of
truth — the regenerated bytes are exactly what the harness later compares).

Cross-impl byte-match is then confirmed by running milpa-rust against the
regenerated corpus (``./dev-rust test -p milpa-conformance``); a regenerated value
the two impls disagree on is a hard failure. Pass ``--verify-rust`` to have this
tool run that gate itself.

HARD GUARD (must be code-reviewed as carefully as the DAG builder — a wrong tool
silently rewrites the authority): before touching the corpus, the tool asserts the
production builder reproduces TWO independently hand-frozen cross-transport pins
(empty-root + nested) AND the B-cutover STEP-1 invariant (a git-materialized
on-disk tree hashed through the production identity site equals the git
object-store enumeration equals the nested pin). A builder regression therefore
cannot pass the guard.

SCOPE — internal only. It NEVER regenerates the dag-oracle fixtures (329–333):
those ARE the conformance authority's pins. It NEVER touches error fixtures (no
computed output). It does NOT touch tianguis's index, Rekor, any consumer lock, or
amoxtli (the deliberately-deferred external half).

GC NOTE: the epoch-1 ``<root>/sha256/`` CAS subtree is now bulk garbage — every
production identity is ``dag-sha256:`` and admits under ``<root>/dag-sha256/``.
Pruning it is NOT done here; tracked by ``docs/rfc-store-gc.md``.

Usage:
    uv run python tools/regen_corpus.py [--verify-rust]
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

_THIS = Path(__file__).resolve()
_PYTHON_IMPL = _THIS.parents[1]            # impls/python
_REPO_ROOT = _THIS.parents[3]             # repo root
sys.path.insert(0, str(_PYTHON_IMPL / "tests"))   # import the harness module
sys.path.insert(0, str(_REPO_ROOT))               # harness/ package

# Independently hand-frozen cross-transport pins (the oracle — NOT derived from
# the impl under test; see conformance/spec-v1/_oracle/dag_sha256_reference.py).
_EMPTY_ROOT_PIN = "dag-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
_NESTED_PIN = "dag-sha256:e3213019260649b72bb0295aaec004eb20a625dd55fcd4bac9e35df96bce316f"


def _guard() -> None:
    """Refuse to regenerate unless the builder reproduces both pins + the invariant."""
    from milpa.dag_identity import (
        MODE_EXECUTABLE,
        MODE_REGULAR,
        MODE_SYMLINK,
        MaterializedEntry,
        compute_dag_identity,
    )
    from milpa.fetchers.git import enumerate_git_entries, materialize_git_tree
    from milpa.identity import compute_content_hash, enumerate_local_entries

    # Pin 1: empty-root.
    got_empty = compute_dag_identity([])
    assert got_empty == _EMPTY_ROOT_PIN, f"empty-root pin drift: {got_empty}"

    # Pin 2: nested (staged seam → builder).
    nested = [
        MaterializedEntry("a.txt", MODE_REGULAR, b"alpha\n"),
        MaterializedEntry("a/b.txt", MODE_REGULAR, b"beta\n"),
        MaterializedEntry("a/run.sh", MODE_EXECUTABLE, b"#!/bin/sh\necho hi\n"),
        MaterializedEntry("link", MODE_SYMLINK, b"a/b.txt"),
    ]
    got_nested = compute_dag_identity(nested)
    assert got_nested == _NESTED_PIN, f"nested pin drift: {got_nested}"

    # STEP-1 invariant: real git materialization → on-disk identity == object-store
    # == nested pin (the load-bearing invariant of the clean cutover).
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        repo = td / "nested"
        repo.mkdir()
        (repo / "a.txt").write_text("alpha\n")
        (repo / "a").mkdir()
        (repo / "a/b.txt").write_text("beta\n")
        (repo / "a/run.sh").write_text("#!/bin/sh\necho hi\n")
        os.chmod(repo / "a/run.sh", 0o755)
        os.symlink("a/b.txt", repo / "link")

        def _git(*a: str) -> None:
            subprocess.run(
                ["git", "-C", str(repo), "-c", "user.email=t@t", "-c", "user.name=t",
                 "-c", "core.autocrlf=false", *a],
                check=True, capture_output=True, text=True,
            )

        _git("init", "-q", "-b", "main")
        _git("add", "-A")
        _git("commit", "-q", "-m", "nested")
        commit = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "main"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
        clone = td / "clone"
        subprocess.run(
            ["git", "clone", "-q", "--no-checkout", f"file://{repo.resolve()}", str(clone)],
            check=True, capture_output=True, text=True,
        )
        obj_entries, _ = enumerate_git_entries(clone, commit, submodule_fetch=None)
        assert compute_dag_identity(obj_entries) == _NESTED_PIN, "object-store invariant drift"
        dest = td / "dest"
        dest.mkdir()
        materialize_git_tree(clone, commit, dest, submodule_fetch=None)
        assert compute_content_hash(dest) == _NESTED_PIN, (
            "STEP-1 invariant FAILED: git-materialized on-disk tree != object-store pin"
        )
        assert compute_dag_identity(enumerate_local_entries(dest)) == _NESTED_PIN

    print("guard: builder reproduces empty-root + nested pins and the STEP-1 invariant OK")


def _dep_block_identity(lock_text: str, dep: str) -> str | None:
    """The first ``identity "..."`` inside the ``dep "<dep>" {`` block, or None."""
    import re

    m = re.search(rf'dep "{re.escape(dep)}"\s*\{{', lock_text)
    if not m:
        return None
    im = re.search(r'identity "([^"]+)"', lock_text[m.end():])
    return im.group(1) if im else None


def _regen_input_locks() -> tuple[list[str], list[tuple[str, str]]]:
    """Phase A — regenerate INPUT ``<fixture>/milpa.lock`` identities under epoch 2.

    Frozen / verify / update fixtures carry a pre-authored lockfile whose dep
    identities must equal the epoch-2 content hash of the tree the impl
    materializes for each dep — otherwise an identity check fires before the
    behaviour under test. The authoritative identity is recomputed by the SAME
    production paths the impl uses:

      * workspace members      → ``compute_content_hash(member.abs_dir)``.
      * frozen external deps    → ``compute_content_hash(cas-seed/<tree>)`` (the
                                  store is seeded from ``cas-seed/`` by content hash,
                                  so the seed-dir name is a label, not the key).
      * verify / update deps    → materialized via the production fetcher at the
                                  dep's recorded provenance (mocked transport).

    Pure roundtrip / parse / opaque-vector locks (lock-roundtrip, parse-lockfile,
    and error fixtures whose identity is a hand-authored test vector) are left
    untouched — their identities are not computed from any tree.
    """
    import test_conformance as tc
    from harness.inputs import resolve_project_dir
    from milpa.fetchers.git import GitProvenance
    from milpa.identity import compute_content_hash
    from milpa.lockfile import parse_lockfile
    from milpa.workspace import load_workspace

    # Error fixtures where the identity drift / mismatch IS the behaviour under
    # test: their pinned identity MUST stay different from the on-disk hash, so
    # the tool must NOT "correct" it (that would silence the intended error).
    # (e.g. fixture-086 pins a synthetic dag-sha256:0…99 that genuinely differs
    # from libfoo's epoch-2 hash — leaving it alone keeps the drift.)
    _IDENTITY_DRIFT_ERRORS = frozenset(
        {
            "FROZEN-MEMBER-IDENTITY-DRIFT",
            "FROZEN-IDENTITY-NOT-IN-STORE",
            "CAS-IDENTITY-MISMATCH",
        }
    )

    regenerated: list[str] = []
    failures: list[tuple[str, str]] = []

    for fx in tc._ALL_FIXTURES:
        if fx.cmd not in ("frozen", "verify", "update"):
            continue
        if fx.expected_error in _IDENTITY_DRIFT_ERRORS:
            continue
        lock_path = fx.dir / "milpa.lock"
        if not lock_path.is_file():
            continue
        text = lock_path.read_text()
        if 'identity "dag-sha256:' not in text:
            continue

        # Member identities (workspace fixtures).
        new_by_name: dict[str, str] = {}
        root = fx.dir
        pd = fx.dir / "project-dir"
        if pd.is_file():
            root = resolve_project_dir(fx.dir, pd.read_text(encoding="utf-8").strip())
        try:
            ws = load_workspace(root)
            for m in ws.members:
                new_by_name[m.manifest.name] = compute_content_hash(m.abs_dir)
        except Exception:  # noqa: BLE001 — single-package manifest, no members
            pass

        try:
            lock = parse_lockfile(text)
        except Exception as e:  # noqa: BLE001
            failures.append((fx.id, f"input-lock parse: {e!r}"))
            continue

        seeds: dict[str, str] = {}
        seed_root = fx.dir / "cas-seed"
        if seed_root.is_dir():
            seeds = {
                s.name: compute_content_hash(s)
                for s in sorted(seed_root.iterdir())
                if s.is_dir()
            }

        import tempfile as _tf

        with _tf.TemporaryDirectory() as td:
            tdp = Path(td)
            env = None
            for d in lock.deps:
                if d.identity is None or d.name in new_by_name:
                    continue
                if fx.cmd == "frozen":
                    # Frozen reads dep content from the cas-seed-populated store.
                    if d.name in seeds:
                        new_by_name[d.name] = seeds[d.name]
                    elif len(seeds) == 1:
                        new_by_name[d.name] = next(iter(seeds.values()))
                    continue
                # verify / update: materialize via the production fetcher.
                prov = d.provenances[0] if d.provenances else None
                kind = getattr(prov, "kind", None)
                if kind != "git":
                    continue  # local/member/tarball-as-needed handled elsewhere
                if env is None:
                    env = tc._build_env(fx.dir, tdp, no_index=fx.no_index)
                gp = GitProvenance(
                    url=prov.url, ref=prov.ref, commit_sha=getattr(prov, "commit_sha", None)
                )
                dest = tdp / "_deps" / d.name
                if dest.exists():
                    import shutil as _sh

                    _sh.rmtree(dest)
                dest.parent.mkdir(parents=True, exist_ok=True)
                try:
                    res = env.fetcher.inner.fetch(d.name, gp, dest=dest)
                except Exception as e:  # noqa: BLE001
                    failures.append((fx.id, f"materialize {d.name}: {e!r}"))
                    continue
                if res.identity:
                    new_by_name[d.name] = res.identity

        # Rewrite: replace each dep's stale identity with the recomputed one in the
        # input lock AND the expected lock (frozen reproduces the input lock).
        touched = False
        for d in lock.deps:
            new_id = new_by_name.get(d.name)
            old_id = _dep_block_identity(text, d.name)
            if not new_id or not old_id or old_id == new_id:
                continue
            for lk in (lock_path, fx.dir / "expected" / "milpa.lock"):
                if lk.is_file():
                    t = lk.read_text()
                    if old_id in t:
                        lk.write_text(t.replace(old_id, new_id))
                        touched = True
            text = lock_path.read_text()
        if touched:
            regenerated.append(fx.id)

    return regenerated, failures


def _regen_index_content_hashes() -> tuple[list[str], list[tuple[str, str]]]:
    """Phase A2 — regenerate ``index.kdl`` ``content_hash`` pins under epoch 2.

    A tianguis index pins each package version's source-tree identity
    (``content_hash``). Under epoch 2 those pins are stale; an impl that fetches a
    named dep and gates its materialized identity against the index pin raises
    ``FETCH-PROVENANCE-DIVERGENCE`` before reaching the behaviour under test. Each
    pin is recomputed by materializing the indexed provenance via the production
    fetcher (mocked transport) — the same identity the resolver records.

    Index entries whose provenance is intentionally bad / unmocked (the
    ``TNG-*`` validation error fixtures) never materialize: their fetch fails and
    the pin is left untouched (the fixture errors before the pin is read).
    """
    import shutil
    import tempfile

    import test_conformance as tc
    from milpa.fetchers.git import GitProvenance
    from milpa.registry import GitIndexProvenance, parse_index

    regenerated: list[str] = []
    failures: list[tuple[str, str]] = []

    for fx in tc._ALL_FIXTURES:
        idx_path = fx.dir / "index.kdl"
        if not idx_path.is_file():
            continue
        text = idx_path.read_text()
        if 'content_hash "dag-sha256:' not in text:
            continue
        try:
            index = parse_index(text)
        except Exception:  # noqa: BLE001 — malformed-index error fixtures
            continue

        with tempfile.TemporaryDirectory() as td:
            tdp = Path(td)
            env = None
            for pkg in index.packages:
                for ver in pkg.versions:
                    old = ver.content_hash
                    if not old.startswith("dag-sha256:"):
                        continue
                    prov = ver.provenances[0] if ver.provenances else None
                    if not isinstance(prov, GitIndexProvenance):
                        continue
                    if env is None:
                        try:
                            env = tc._build_env(fx.dir, tdp, no_index=fx.no_index)
                        except Exception:  # noqa: BLE001
                            break
                    gp = GitProvenance(url=prov.url, ref=prov.ref, commit_sha=prov.commit_sha)
                    dest = tdp / "_deps" / f"{pkg.name}@{ver.version}"
                    if dest.exists():
                        shutil.rmtree(dest)
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    try:
                        res = env.fetcher.inner.fetch(pkg.name, gp, dest=dest)
                    except Exception:  # noqa: BLE001 — bad/unmocked provenance
                        continue
                    if res.identity and res.identity != old:
                        text = text.replace(old, res.identity)

        if text != idx_path.read_text():
            idx_path.write_text(text)
            regenerated.append(fx.id)
    return regenerated, failures


def _regen_inprocess() -> tuple[list[str], list[tuple[str, str]]]:
    """Drive the in-process harness in bless mode over every computed fixture.

    Covers resolve / fetch / frozen / lock / check-certificate / verify
    (expected/milpa.lock + nim.cfg + _deps_structure) and the git-protocol / hash
    tiers (expected/content_hash, expected/stdout). dag-oracle fixtures (the
    authority pins) and error fixtures (no computed output) are skipped.
    """
    import test_conformance as tc

    regenerated: list[str] = []
    failures: list[tuple[str, str]] = []
    tc._REGEN_MODE = True
    try:
        for fx in tc._ALL_FIXTURES:
            if fx.cmd == "dag-oracle":
                continue                       # authority pins — never regenerate
            if tc._is_cli_only(fx):
                continue                       # CLI verbs handled separately
            if not fx.is_success:
                continue                       # error fixtures carry no computed output
            with tempfile.TemporaryDirectory() as td:
                try:
                    verdict, msg = tc._execute_fixture(fx, Path(td))
                except Exception as e:  # noqa: BLE001 — surface, don't swallow
                    failures.append((fx.id, f"exception: {e!r}"))
                    continue
            if verdict == "pass":
                regenerated.append(fx.id)
            elif verdict == "fail":
                failures.append((fx.id, msg))
            # "skip" → nothing to regenerate (e.g. not-yet-wired); ignore.
    finally:
        tc._REGEN_MODE = False
    return regenerated, failures


def _regen_cli() -> tuple[list[str], list[tuple[str, str]]]:
    """Regenerate the CLI-verb (add/remove/update) fixtures' expected/milpa.lock by
    driving the REAL milpa-py CLI through the black-box harness and copying the
    produced lock. These re-resolve from mocked-fetches, so the lock identities are
    recomputed under epoch 2 (none of these fixtures are build-mode)."""
    import test_conformance as tc
    from harness.descriptors import build_descriptors
    from harness.runner import run_fixture

    py = next(d for d in build_descriptors(_REPO_ROOT) if d.name == "python")

    regenerated: list[str] = []
    failures: list[tuple[str, str]] = []
    for fx in tc._ALL_FIXTURES:
        if fx.cmd not in {"add", "remove", "update"}:
            continue
        expected_lock = fx.dir / "expected" / "milpa.lock"
        if not expected_lock.is_file():
            continue
        res = run_fixture(fx.dir, py)
        try:
            produced = Path(res.scratch_dir) / "milpa.lock"
            if res.returncode != 0 or not produced.is_file():
                failures.append((fx.id, f"CLI rc={res.returncode}, stderr={res.stderr[:200]!r}"))
                continue
            shutil.copyfile(produced, expected_lock)
            regenerated.append(fx.id)
        finally:
            res.cleanup()
    return regenerated, failures


def _verify_rust() -> int:
    """Run the Rust conformance suite against the regenerated corpus (byte-match)."""
    print("verify-rust: running ./dev-rust test -p milpa-conformance ...")
    proc = subprocess.run(
        ["./dev-rust", "test", "-p", "milpa-conformance"],
        cwd=str(_REPO_ROOT),
    )
    if proc.returncode == 0:
        print("verify-rust: milpa-rust byte-matches every regenerated value OK")
    else:
        print("verify-rust: milpa-rust DISAGREES with a regenerated value (rc != 0)")
    return proc.returncode


def main(argv: list[str]) -> int:
    verify_rust = "--verify-rust" in argv

    _guard()

    # Phase A — INPUT locks (frozen/verify/update) must be epoch-2-consistent
    # BEFORE the in-process / CLI phases run them.
    input_ok, input_fail = _regen_input_locks()
    # Phase A2 — index.kdl content_hash pins.
    index_ok, index_fail = _regen_index_content_hashes()
    print(f"regenerated (index pins):  {len(index_ok)} fixtures")
    # Phase B — in-process bless of computed expected/ outputs.
    inproc_ok, inproc_fail = _regen_inprocess()
    # Phase C — CLI-verb (add/remove/update) expected/milpa.lock.
    cli_ok, cli_fail = _regen_cli()

    print(f"regenerated (input locks): {len(input_ok)} fixtures")
    print(f"regenerated (in-process):  {len(inproc_ok)} fixtures")
    print(f"regenerated (CLI verbs):   {len(cli_ok)} fixtures")

    failures = input_fail + index_fail + inproc_fail + cli_fail
    if failures:
        print(f"\n{len(failures)} fixture(s) did NOT regenerate cleanly:")
        for fid, msg in failures:
            print(f"  - {fid}: {msg.splitlines()[0] if msg else ''}")
        print(
            "\nNOTE: error fixtures whose trigger moved under epoch 2 (e.g. a "
            "fixture-086-style sha256: drift now failing at parse) are re-pinned by "
            "hand, not here — review the list above."
        )

    rc = 0
    if verify_rust:
        rc = _verify_rust()
    return 1 if failures and rc == 0 else rc


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
