"""The machine-readable error channel — Gap-1 (RFC differential-
conformance-harness) R1–R4.

On any diagnosed failure the CLI MUST emit exactly one terminal
`milpa-error: <SLUG>` line to stderr; an exit-0 run MUST NOT emit one;
an exception escaping the typed handlers routes to the MILPA-INTERNAL
sentinel; argument-parse failures exit 2 (a usage/crash-class verdict
with no `milpa-error:` line).

These drive the CLI through its public entry point `main(argv)` and
read the slug off captured stderr — the same channel a language-neutral
black-box runner observes (cli-contract.md §3.1).
"""

import re

import pytest

from milpa.cli import main

_SLUG_LINE = re.compile(r"^milpa-error: ([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+)$", re.M)


def _slug_lines(stderr: str) -> list[str]:
    """Return every full-line `milpa-error: <SLUG>` match's slug."""
    return _SLUG_LINE.findall(stderr)


def test_manifest_syntax_error_emits_terminal_slug_line(tmp_path, capsys):
    """`fetch` over a malformed milpa.kdl exits 1 with exactly one
    `milpa-error: MAN-KDL-SYNTAX` line (the R1/R2 channel)."""
    (tmp_path / "milpa.kdl").write_text('name "x"\ndeps {\n')  # unbalanced

    rc = main(["-C", str(tmp_path), "fetch"])

    assert rc == 1
    err = capsys.readouterr().err
    assert _slug_lines(err) == ["MAN-KDL-SYNTAX"]


def test_successful_run_emits_no_slug_line(tmp_path, capsys):
    """R3: an exit-0 run MUST NOT emit a `milpa-error:` line."""
    rc = main(["-C", str(tmp_path), "clean"])  # idempotent, exits 0

    assert rc == 0
    assert _slug_lines(capsys.readouterr().err) == []


def test_show_without_lockfile_emits_lock_file_not_found(tmp_path, capsys):
    """A missing lockfile is a diagnosed condition, not an internal error:
    `show` exits 1 with the LOCK-FILE-NOT-FOUND slug."""
    rc = main(["-C", str(tmp_path), "show"])

    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["LOCK-FILE-NOT-FOUND"]


def test_unexpected_exception_routes_to_internal_sentinel(
    tmp_path, capsys, monkeypatch
):
    """R3 net: an exception with no `.code` escaping a verb is rendered
    as the MILPA-INTERNAL sentinel and exits 1 (not a silent crash)."""
    def boom(*a, **k):
        raise RuntimeError("unexpected")

    monkeypatch.setattr("milpa.cli.cmd_show", boom)
    rc = main(["-C", str(tmp_path), "show"])

    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["MILPA-INTERNAL"]


def test_argument_parse_error_exits_2_with_no_slug_line(tmp_path, capsys):
    """R4: an argument-parse / usage error exits 2 (crash-class verdict)
    and emits NO `milpa-error:` line."""
    with pytest.raises(SystemExit) as exc:
        main(["-s", "bogus", "-C", str(tmp_path), "fetch"])

    assert exc.value.code == 2
    assert _slug_lines(capsys.readouterr().err) == []


def test_malformed_named_dep_constraint_emits_man_dep_named_constraint(
    tmp_path, capsys
):
    """A syntactically invalid NamedDep constraint must surface as
    MAN-DEP-NAMED-CONSTRAINT (not MILPA-INTERNAL) through the CLI.

    This is the black-box signal: the parse-boundary validation is in
    effect when the manifest is loaded, before any resolve-time code
    runs. Regression guard against the old behaviour where ValueError
    from VersionSet.from_constraint escaped to the MILPA-INTERNAL
    catch-all."""
    (tmp_path / "milpa.kdl").write_text(
        'name "x"\ndeps {\n    z "@@@bad"\n}\n'
    )

    rc = main(["-C", str(tmp_path), "fetch"])

    assert rc == 1
    err = capsys.readouterr().err
    assert _slug_lines(err) == ["MAN-DEP-NAMED-CONSTRAINT"]


# ---------------------------------------------------------------------------
# Slice 1e — slug coverage for remaining exit-1 paths
# ---------------------------------------------------------------------------


def _minimal_manifest(path, name="x"):
    """Write the simplest valid milpa.kdl (no deps) into path."""
    (path / "milpa.kdl").write_text(f'name "{name}"\n')


def _minimal_lockfile(path):
    """Write a minimal valid milpa.lock (no deps) into path."""
    (path / "milpa.lock").write_text(
        '// generated by milpa; reproducible build snapshot\n'
        'version 1\n'
        'strategy "maxver"\n'
    )


def test_frozen_no_lockfile_emits_slug(tmp_path, capsys):
    """--frozen fetch with no lockfile → FROZEN-NO-LOCKFILE."""
    _minimal_manifest(tmp_path)
    rc = main(["-C", str(tmp_path), "--frozen", "fetch"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["FROZEN-NO-LOCKFILE"]


def test_verify_missing_deps_dir_emits_slug(tmp_path, capsys):
    """verify with lockfile present but no _deps/ → VERIFY-DEPS-DIR-MISSING."""
    _minimal_manifest(tmp_path)
    _minimal_lockfile(tmp_path)
    # deliberately no _deps/ directory
    rc = main(["-C", str(tmp_path), "verify"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["VERIFY-DEPS-DIR-MISSING"]


def test_verify_divergence_emits_lock_graph_mismatch(tmp_path, capsys):
    """verify when _deps/ has unexpected entries → LOCK-GRAPH-MISMATCH."""
    _minimal_manifest(tmp_path)
    _minimal_lockfile(tmp_path)
    deps_dir = tmp_path / "_deps"
    deps_dir.mkdir()
    # create an entry that the (empty) lockfile doesn't know about
    (deps_dir / "phantom").mkdir()
    rc = main(["-C", str(tmp_path), "verify"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["LOCK-GRAPH-MISMATCH"]


def test_remove_dep_not_declared_emits_slug(tmp_path, capsys):
    """remove of an undeclared dep → MAN-REMOVE-DEP-ABSENT."""
    _minimal_manifest(tmp_path)
    rc = main(["-C", str(tmp_path), "remove", "nonexistent"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["MAN-REMOVE-DEP-ABSENT"]


def test_add_dep_already_declared_emits_slug(tmp_path, capsys, monkeypatch):
    """add --git for an already-declared dep → MAN-ADD-DEP-EXISTS."""
    (tmp_path / "milpa.kdl").write_text(
        'name "mypkg"\n'
        'deps {\n'
        '  existing git="https://example.com/r" ref="main"\n'
        '}\n'
    )
    # Prevent the default-branch network call from firing
    monkeypatch.setattr(
        "milpa.cli._git_default_branch", lambda url: "main"
    )
    rc = main(["-C", str(tmp_path), "add", "--git", "https://example.com/r",
               "existing"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["MAN-ADD-DEP-EXISTS"]


def test_add_no_flag_exits_2_with_no_slug(tmp_path, capsys):
    """add with neither --git nor --mirror → exit 2, NO slug line."""
    _minimal_manifest(tmp_path)
    rc = main(["-C", str(tmp_path), "add", "somedep"])
    assert rc == 2
    assert _slug_lines(capsys.readouterr().err) == []


def test_update_dep_not_in_lockfile_emits_slug(tmp_path, capsys):
    """update <dep> where dep is absent from lockfile → LOCK-DEP-NOT-FOUND."""
    _minimal_manifest(tmp_path)
    _minimal_lockfile(tmp_path)
    rc = main(["-C", str(tmp_path), "update", "missingdep"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["LOCK-DEP-NOT-FOUND"]


def test_add_mirror_no_lockfile_emits_slug(tmp_path, capsys):
    """add --mirror with no lockfile → LOCK-FILE-NOT-FOUND."""
    _minimal_manifest(tmp_path)
    rc = main(["-C", str(tmp_path), "add", "--mirror",
               "https://example.com/mirror", "somedep"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["LOCK-FILE-NOT-FOUND"]


# ---------------------------------------------------------------------------
# Bug #119 — invalid workspace manifests must propagate real error codes
# ---------------------------------------------------------------------------


def test_workspace_with_kind_emits_workspace_has_deps_or_kind(tmp_path, capsys):
    """A workspace manifest that also declares `kind` must emit
    MAN-WORKSPACE-HAS-DEPS-OR-KIND, not be silently swallowed into a
    generic "no manifest" path (bug #119 regression).

    Previously `find_workspace_root` swallowed the ManifestError from
    `parse_workspace_or_manifest`, so the CLI fell through to the package
    parse path and emitted the wrong slug (or crashed).
    """
    (tmp_path / "milpa.kdl").write_text(
        'name "x"\n'
        'kind "library"\n'
        'workspace {\n'
        '    member "a"\n'
        '}\n'
    )
    rc = main(["-C", str(tmp_path), "fetch"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["MAN-WORKSPACE-HAS-DEPS-OR-KIND"]


def test_workspace_with_unknown_member_node_emits_unknown_node(tmp_path, capsys):
    """A workspace block with an unrecognised child node emits
    MAN-WORKSPACE-UNKNOWN-NODE (#119)."""
    (tmp_path / "milpa.kdl").write_text(
        'workspace {\n'
        '    bogus "y"\n'
        '}\n'
    )
    rc = main(["-C", str(tmp_path), "fetch"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["MAN-WORKSPACE-UNKNOWN-NODE"]


def test_workspace_member_without_arg_emits_member_arity(tmp_path, capsys):
    """A `member` node with no argument emits MAN-WORKSPACE-MEMBER-ARITY (#119)."""
    (tmp_path / "milpa.kdl").write_text(
        'workspace {\n'
        '    member\n'
        '}\n'
    )
    rc = main(["-C", str(tmp_path), "fetch"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["MAN-WORKSPACE-MEMBER-ARITY"]


def test_workspace_duplicate_member_emits_member_duplicate(tmp_path, capsys):
    """Duplicate `member` entries emit MAN-WORKSPACE-MEMBER-DUPLICATE (#119)."""
    (tmp_path / "milpa.kdl").write_text(
        'workspace {\n'
        '    member "a"\n'
        '    member "a"\n'
        '}\n'
    )
    rc = main(["-C", str(tmp_path), "fetch"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["MAN-WORKSPACE-MEMBER-DUPLICATE"]


def test_workspace_unknown_top_level_node_emits_unknown_top_level(tmp_path, capsys):
    """An unknown top-level node in a workspace manifest emits
    MAN-WORKSPACE-UNKNOWN-TOP-LEVEL (#119)."""
    (tmp_path / "milpa.kdl").write_text(
        'workspace {\n'
        '    member "a"\n'
        '}\n'
        'bogus "y"\n'
    )
    rc = main(["-C", str(tmp_path), "fetch"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["MAN-WORKSPACE-UNKNOWN-TOP-LEVEL"]


def test_workspace_with_deps_block_emits_has_deps_or_kind(tmp_path, capsys):
    """A workspace manifest that also declares a `deps` block emits
    MAN-WORKSPACE-HAS-DEPS-OR-KIND (#119 / fixture-105)."""
    (tmp_path / "milpa.kdl").write_text(
        'name "ws"\n'
        'workspace {\n'
        '    member "a"\n'
        '}\n'
        'deps {\n'
        '    foo git=(url)"https://github.com/example/foo.git" ref="main"\n'
        '}\n'
    )
    rc = main(["-C", str(tmp_path), "fetch"])
    assert rc == 1
    assert _slug_lines(capsys.readouterr().err) == ["MAN-WORKSPACE-HAS-DEPS-OR-KIND"]
