"""Tests for milpa.nimcfg — format_nimcfg and format_workspace_nimcfgs.

Spec authority: lockfile-schema.md §7.1–7.4, §7.6.

Coverage:
  - §7.1  header emitted unconditionally (even no-deps)
  - §7.2  POSIX path separators
  - §7.3  --path: line form (deps_dir/name[/src_dir])
  - §7.4  emission order: self src-dir first, then deps lexicographic
  - §7.4  no-deps → header only, trailing \\n
  - §7.4  self src-dir only (no deps) → header + blank + self path
  - §7.5  feature-flag -d: defines — S6 (#23)
  - §7.6  format_workspace_nimcfgs: per-member relative paths

Corpus fixtures:
  - fixture-003  single URL dep with src_dir "src"
  - fixture-116  self src_dir "src" + one dep with src_dir "src"
  - fixture-063  three named deps sorted lexicographically (X/Y/Z)
  - fixture-115  no deps — header-only nim.cfg
  - fixture-117  workspace two-member success: member-b depends on member-a
  - fixture-197  S6 explicit defines: dep with active flag + explicit defines
  - fixture-198  S6 childless-convention: dep with active flag + no defines
"""

from pathlib import Path

from milpa.lockfile import ResolvedDep, ResolvedGraph
from milpa.nimcfg import build_flag_defines, format_nimcfg, format_workspace_nimcfgs

# ---------------------------------------------------------------------------
# Fixtures helpers
# ---------------------------------------------------------------------------

_CONFORMANCE = Path(__file__).parent.parent.parent.parent / "conformance" / "spec-v1"


def _expected_nimcfg(fixture_name: str, subpath: str = "nim.cfg") -> str:
    """Load an expected nim.cfg from the conformance corpus."""
    path = _CONFORMANCE / fixture_name / "expected" / subpath
    return path.read_text()


def _dep(
    name: str,
    src_dir: str = "",
    requires: tuple[str, ...] = (),
    active_flags: tuple[str, ...] = (),
) -> ResolvedDep:
    """Build a minimal ResolvedDep suitable for nimcfg tests."""
    return ResolvedDep(
        name=name,
        identity=None,
        version="0.0.1",
        src_dir=src_dir,
        requires=requires,
        active_flags=active_flags,
    )


# ---------------------------------------------------------------------------
# §7.1  Header
# ---------------------------------------------------------------------------


class TestHeader:
    """The normative three-line header MUST be emitted unconditionally (§7.1)."""

    _HEADER = (
        "# generated by milpa; do not edit\n"
        "# manifest: milpa.kdl\n"
        "# lockfile: milpa.lock\n"
    )

    def test_header_present_with_no_deps(self) -> None:
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph)
        assert out.startswith(self._HEADER.rstrip("\n"))

    def test_header_present_with_deps(self) -> None:
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph)
        assert out.startswith("# generated by milpa; do not edit\n")
        assert "# manifest: milpa.kdl\n" in out
        assert "# lockfile: milpa.lock\n" in out

    def test_header_is_exactly_three_lines(self) -> None:
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph)
        header_block = out.split("\n\n")[0]  # up to first blank line (or all)
        lines = header_block.splitlines()
        assert lines[0] == "# generated by milpa; do not edit"
        assert lines[1] == "# manifest: milpa.kdl"
        assert lines[2] == "# lockfile: milpa.lock"


# ---------------------------------------------------------------------------
# §7.2  POSIX path separators
# ---------------------------------------------------------------------------


class TestPosixPaths:
    """All --path: lines MUST use / regardless of host OS (§7.2)."""

    def test_no_backslashes_in_dep_path(self) -> None:
        graph = ResolvedGraph(deps=(_dep("mydep", "some/sub"),))
        out = format_nimcfg(graph, deps_dir=Path("_deps"))
        # Every --path: line must not contain backslash
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        assert all("\\" not in ln for ln in path_lines)

    def test_forward_slash_separator(self) -> None:
        graph = ResolvedGraph(deps=(_dep("lib", "sources"),))
        out = format_nimcfg(graph, deps_dir=Path("_deps"))
        assert '--path:"_deps/lib/sources"' in out

    def test_deps_dir_uses_posix(self) -> None:
        # Even if Path() uses native sep on Windows, as_posix() must be used.
        graph = ResolvedGraph(deps=(_dep("x", ""),))
        out = format_nimcfg(graph, deps_dir=Path("vendor") / "deps")
        assert '--path:"vendor/deps/x"' in out


# ---------------------------------------------------------------------------
# §7.3  --path: line form
# ---------------------------------------------------------------------------


class TestPathLineForm:
    """--path:"<deps_dir>/<name>[/<src_dir>]" form (§7.3)."""

    def test_empty_src_dir_omits_trailing_slash(self) -> None:
        graph = ResolvedGraph(deps=(_dep("zlib", ""),))
        out = format_nimcfg(graph)
        assert '--path:"_deps/zlib"' in out
        assert '--path:"_deps/zlib/"' not in out

    def test_src_dir_appended_with_slash(self) -> None:
        graph = ResolvedGraph(deps=(_dep("chronos", "chronos"),))
        out = format_nimcfg(graph)
        assert '--path:"_deps/chronos/chronos"' in out

    def test_custom_deps_dir(self) -> None:
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph, deps_dir=Path("third_party"))
        assert '--path:"third_party/foo/src"' in out

    def test_nested_src_dir(self) -> None:
        graph = ResolvedGraph(deps=(_dep("pkg", "lib/nim"),))
        out = format_nimcfg(graph)
        assert '--path:"_deps/pkg/lib/nim"' in out


# ---------------------------------------------------------------------------
# §7.4  Emission order
# ---------------------------------------------------------------------------


class TestEmissionOrder:
    """Emission order: self src-dir first, then deps sorted lexicographically (§7.4)."""

    def test_no_deps_header_only(self) -> None:
        """No-deps: header only, trailing \\n (no blank line after header)."""
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph)
        # Must not contain --path:
        assert "--path:" not in out
        # Must end with a single \n (not \n\n)
        assert out.endswith("milpa.lock\n")
        assert not out.endswith("milpa.lock\n\n")

    def test_no_deps_no_blank_line_after_header(self) -> None:
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph)
        # No double-newline
        assert "\n\n" not in out

    def test_self_src_dir_before_deps(self) -> None:
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph, self_src_dir="src")
        self_idx = out.index('--path:"src"')
        dep_idx = out.index('--path:"_deps/foo/src"')
        assert self_idx < dep_idx

    def test_self_src_dir_only_no_deps(self) -> None:
        """Self src-dir with no deps: header + blank line + self path line."""
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph, self_src_dir="src")
        assert "--path:" in out
        lines = out.splitlines()
        # 0: # generated…, 1: # manifest…, 2: # lockfile…, 3: (blank), 4: --path:"src"
        assert lines[3] == ""
        assert lines[4] == '--path:"src"'

    def test_deps_lexicographic_order(self) -> None:
        """Deps sorted lexicographically regardless of graph construction order."""
        # Graph has deps in reverse-alpha order
        graph = ResolvedGraph(deps=(_dep("zlib"), _dep("alpha"), _dep("mod")))
        out = format_nimcfg(graph)
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        names_in_output = [ln.split("/")[1].rstrip('"') for ln in path_lines]
        assert names_in_output == sorted(names_in_output)

    def test_trailing_newline_single_dep(self) -> None:
        """File ends with exactly one trailing \\n (§7.4 NOTE)."""
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph)
        assert out.endswith("\n")
        assert not out.endswith("\n\n")

    def test_blank_line_separates_header_from_paths(self) -> None:
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph)
        lines = out.splitlines()
        # line 3 (index 3) must be blank
        assert lines[3] == ""
        # line 4 is the first --path:
        assert lines[4].startswith("--path:")

    def test_multiple_deps_sorted(self) -> None:
        graph = ResolvedGraph(
            deps=(_dep("zz", ""), _dep("aa", "src"), _dep("mm", "lib"))
        )
        out = format_nimcfg(graph)
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        assert path_lines[0] == '--path:"_deps/aa/src"'
        assert path_lines[1] == '--path:"_deps/mm/lib"'
        assert path_lines[2] == '--path:"_deps/zz"'


# ---------------------------------------------------------------------------
# Corpus fixture cross-checks
# ---------------------------------------------------------------------------


class TestCorpusFixtures:
    """Assert exact byte match against conformance corpus expected/nim.cfg files.

    These fixtures exercise the normative output format end-to-end.
    Graph data is reconstructed from the fixture's milpa.kdl + lockfile
    information so the exact dep names and src_dirs are matched.
    """

    def test_fixture_003_single_url_dep(self) -> None:
        """fixture-003: single dep named 'foo' with src_dir 'src'."""
        # From conformance/spec-v1/fixture-003-single-url-dep/expected/milpa.lock:
        #   dep "foo" { src_dir "src" ... }
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        expected = _expected_nimcfg("fixture-003-single-url-dep")
        assert format_nimcfg(graph) == expected

    def test_fixture_115_no_deps(self) -> None:
        """fixture-115: conditional dep excluded → no deps in graph."""
        # expected/nim.cfg is header-only (no --path: lines)
        graph = ResolvedGraph(deps=())
        expected = _expected_nimcfg("fixture-115-conditional-dep-excluded")
        assert format_nimcfg(graph) == expected

    def test_fixture_116_self_src_dir(self) -> None:
        """fixture-116: manifest declares src_dir 'src'; dep 'foo' src_dir 'src'."""
        # From the fixture milpa.kdl: name "myapp" src_dir "src" + dep foo
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        expected = _expected_nimcfg("fixture-116-src-dir-self-path")
        assert format_nimcfg(graph, self_src_dir="src") == expected

    def test_fixture_063_three_deps_sorted(self) -> None:
        """fixture-063: three named deps X, Y, Z each with src_dir 'src'."""
        # From the expected lockfile: X, Y, Z all with src_dir "src"
        graph = ResolvedGraph(
            deps=(_dep("X", "src"), _dep("Y", "src"), _dep("Z", "src"))
        )
        expected = _expected_nimcfg("fixture-063-canonical-selection")
        assert format_nimcfg(graph) == expected

    def test_fixture_180_src_dir_no_deps(self) -> None:
        """fixture-180: src_dir 'src' with zero deps → header + blank + path + trailing \\n.

        Regression for cross-impl byte divergence: Rust guarded the trailing
        newline on `graph.deps.is_empty()` instead of whether any --path: line
        was emitted (self_src_dir alone must also produce the trailing \\n).
        """
        graph = ResolvedGraph(deps=())
        expected = _expected_nimcfg("fixture-180-nimcfg-src-dir-no-deps")
        assert format_nimcfg(graph, self_src_dir="src") == expected


# ---------------------------------------------------------------------------
# §7.5  Feature-flag -d: defines — S6 (#23, un-deferred)
# ---------------------------------------------------------------------------


class TestFeatureDefines:
    """§7.5 -d: defines emitted for active flags when flag_defines is provided.

    RFC #23 §3.6 normative rules:
    - Defines block separated from --path: block by a blank line.
    - -d: lines are lexicographically ordered across all active flags of all deps.
    - Explicit defines: active flag with defines=("ssl", "useOpenSSL") emits
      -d:ssl and -d:useOpenSSL.
    - Childless-convention: active flag with defines=() emits -d:<pkg>_<flag>.
    - No -d: block when no active flags have defines (empty flag_defines or
      no active flags in graph).
    - --path: lines unchanged (defines do not affect path output).
    """

    def test_no_defines_when_flag_defines_absent(self) -> None:
        """No flag_defines arg → no -d: lines (backward compat)."""
        graph = ResolvedGraph(
            deps=(_dep("pkg", "src", active_flags=("tls",)),)
        )
        out = format_nimcfg(graph)
        assert "-d:" not in out

    def test_no_defines_when_flag_defines_empty(self) -> None:
        """flag_defines={} → no -d: lines (dep has no flag table)."""
        graph = ResolvedGraph(
            deps=(_dep("pkg", "src", active_flags=("tls",)),)
        )
        out = format_nimcfg(graph, flag_defines={})
        assert "-d:" not in out

    def test_explicit_defines_emitted(self) -> None:
        """Active flag with explicit defines emits its symbols as -d: lines."""
        graph = ResolvedGraph(
            deps=(_dep("ssl-lib", "src", active_flags=("tls",)),)
        )
        flag_defines = {"ssl-lib": {"tls": ("ssl", "useOpenSSL")}}
        out = format_nimcfg(graph, flag_defines=flag_defines)
        assert "-d:ssl\n" in out or out.endswith("-d:ssl")
        assert "-d:useOpenSSL" in out

    def test_childless_convention(self) -> None:
        """Active flag with no defines emits -d:<pkg>_<flag>."""
        graph = ResolvedGraph(
            deps=(_dep("mylib", "src", active_flags=("http",)),)
        )
        flag_defines = {"mylib": {"http": ()}}
        out = format_nimcfg(graph, flag_defines=flag_defines)
        assert "-d:mylib_http" in out

    def test_defines_block_separated_by_blank_line(self) -> None:
        """The -d: block is separated from the --path: block by a blank line."""
        graph = ResolvedGraph(
            deps=(_dep("pkg", "src", active_flags=("feat",)),)
        )
        flag_defines = {"pkg": {"feat": ("myDefine",)}}
        out = format_nimcfg(graph, flag_defines=flag_defines)
        # Verify: --path: line appears before a blank line before -d: line
        assert "--path:" in out
        assert "-d:myDefine" in out
        path_pos = out.index("--path:")
        define_pos = out.index("-d:myDefine")
        assert define_pos > path_pos, "-d: block must come after --path: block"
        between = out[path_pos:define_pos]
        assert "\n\n" in between, "-d: block must be separated by blank line"

    def test_defines_lexicographically_ordered(self) -> None:
        """All emitted -d: symbols are lexicographically sorted across all deps."""
        graph = ResolvedGraph(
            deps=(
                _dep("lib-a", "src", active_flags=("feat-z",)),
                _dep("lib-b", "src", active_flags=("feat-a",)),
            )
        )
        flag_defines = {
            "lib-a": {"feat-z": ("zzz", "aaa")},
            "lib-b": {"feat-a": ("mmm",)},
        }
        out = format_nimcfg(graph, flag_defines=flag_defines)
        d_lines = [l for l in out.splitlines() if l.startswith("-d:")]
        assert d_lines == sorted(d_lines), f"expected lex order, got {d_lines}"

    def test_active_flags_do_not_affect_path_output(self) -> None:
        """Flags on a dep must not alter the --path: lines."""
        graph_no_flags = ResolvedGraph(deps=(_dep("pkg", "src"),))
        graph_with_flags = ResolvedGraph(
            deps=(_dep("pkg", "src", active_flags=("flag",)),)
        )
        # Without flag_defines, both produce identical output.
        assert format_nimcfg(graph_no_flags) == format_nimcfg(graph_with_flags)

    def test_no_defines_block_when_no_active_flags(self) -> None:
        """When no deps have active flags, no blank line + -d: block appended."""
        graph = ResolvedGraph(
            deps=(_dep("pkg", "src"),)
        )
        flag_defines = {"pkg": {"tls": ("ssl",)}}
        out = format_nimcfg(graph, flag_defines=flag_defines)
        assert "-d:" not in out
        # File ends with single trailing newline (§7.4 NOTE).
        assert out.endswith("\n")
        assert not out.endswith("\n\n")

    def test_inactive_flag_not_emitted(self) -> None:
        """A flag present in flag_defines but NOT in dep.active_flags is not emitted."""
        graph = ResolvedGraph(
            deps=(_dep("pkg", "src", active_flags=("active-feat",)),)
        )
        flag_defines = {
            "pkg": {
                "active-feat": ("emitted",),
                "inactive-feat": ("not-emitted",),
            }
        }
        out = format_nimcfg(graph, flag_defines=flag_defines)
        assert "-d:emitted" in out
        assert "-d:not-emitted" not in out

    def test_multiple_flags_same_dep(self) -> None:
        """Multiple active flags on one dep all have their defines emitted."""
        graph = ResolvedGraph(
            deps=(_dep("pkg", "src", active_flags=("feat-a", "feat-b")),)
        )
        flag_defines = {
            "pkg": {
                "feat-a": ("symbolA",),
                "feat-b": ("symbolB",),
            }
        }
        out = format_nimcfg(graph, flag_defines=flag_defines)
        assert "-d:symbolA" in out
        assert "-d:symbolB" in out

    def test_no_deps_no_defines_block(self) -> None:
        """Zero-dep graph produces header only (no -d: block even with flag_defines)."""
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph, flag_defines={"some-dep": {"f": ("x",)}})
        assert "-d:" not in out

    def test_path_only_fixture_unchanged(self) -> None:
        """Existing --path:-only fixture output is byte-identical with flag_defines=None."""
        graph = ResolvedGraph(
            deps=(
                _dep("alpha"),
                _dep("beta", "src"),
            )
        )
        out_before = format_nimcfg(graph)
        out_after = format_nimcfg(graph, flag_defines=None)
        assert out_before == out_after


# ---------------------------------------------------------------------------
# §7.5  build_flag_defines — product function (RFC #23 S6 SSOT)
# ---------------------------------------------------------------------------


class TestBuildFlagDefines:
    """build_flag_defines is a PRODUCT function in milpa.nimcfg (not a test helper).

    These tests exercise the real map-builder against on-disk dep manifests so
    that any future regression where the CLI stops building the map is caught
    at this layer — not discovered from a missing -d: line in a released binary.

    S6 anti-regression: the CLI calls build_flag_defines (not None), so if this
    function regresses the corpus tests AND the CLI both break.  Having a
    dedicated unit test here pins the product behaviour independent of the corpus.
    """

    def test_returns_empty_for_dep_with_no_manifest(self, tmp_path: Path) -> None:
        """A dep whose _deps/<name>/milpa.kdl does not exist → empty map (warn-and-skip)."""
        deps_dir = tmp_path / "_deps"
        deps_dir.mkdir()
        graph = ResolvedGraph(deps=(_dep("somelib", active_flags=("tls",)),))
        result = build_flag_defines(graph, deps_dir)
        # No milpa.kdl for somelib → not in result.
        assert result == {}

    def test_returns_flag_table_for_dep_with_manifest(self, tmp_path: Path) -> None:
        """A dep with a milpa.kdl that declares flags → flag_name → defines tuple."""
        deps_dir = tmp_path / "_deps"
        (deps_dir / "chronos").mkdir(parents=True)
        (deps_dir / "chronos" / "milpa.kdl").write_text(
            'name "chronos"\n'
            'kind "library"\n'
            "flags {\n"
            '    tls default=#false {\n'
            '        defines "ssl" "useOpenSSL"\n'
            "    }\n"
            "}\n",
            encoding="utf-8",
        )
        graph = ResolvedGraph(deps=(_dep("chronos", active_flags=("tls",)),))
        result = build_flag_defines(graph, deps_dir)
        assert "chronos" in result
        assert result["chronos"]["tls"] == ("ssl", "useOpenSSL")

    def test_childless_flag_returns_empty_tuple(self, tmp_path: Path) -> None:
        """A flag with no defines child → empty tuple (childless-convention)."""
        deps_dir = tmp_path / "_deps"
        (deps_dir / "mylib").mkdir(parents=True)
        (deps_dir / "mylib" / "milpa.kdl").write_text(
            'name "mylib"\n'
            'kind "library"\n'
            "flags {\n"
            '    http default=#false\n'
            "}\n",
            encoding="utf-8",
        )
        graph = ResolvedGraph(deps=(_dep("mylib", active_flags=("http",)),))
        result = build_flag_defines(graph, deps_dir)
        assert result["mylib"]["http"] == ()

    def test_cli_path_emits_defines_not_none(self, tmp_path: Path) -> None:
        """Anti-regression: the same call-chain the CLI uses must emit -d: lines.

        This test replicates the CLI's logic (build_flag_defines → format_nimcfg)
        so that if either step regresses (e.g. someone reintroduces flag_defines=None
        in cli.py) this test fails before the user notices missing -d: lines.
        """
        deps_dir = tmp_path / "_deps"
        (deps_dir / "bearssl").mkdir(parents=True)
        (deps_dir / "bearssl" / "milpa.kdl").write_text(
            'name "bearssl"\n'
            'kind "library"\n'
            "flags {\n"
            '    ssl default=#false {\n'
            '        defines "ssl"\n'
            "    }\n"
            "}\n",
            encoding="utf-8",
        )
        graph = ResolvedGraph(deps=(_dep("bearssl", active_flags=("ssl",)),))

        # This is the exact call sequence the CLI uses (cli.py fetch/lock path).
        flag_defines = build_flag_defines(graph, deps_dir)
        nimcfg_text = format_nimcfg(
            graph,
            deps_dir=Path("_deps"),
            self_src_dir="",
            flag_defines=flag_defines,
        )

        assert "-d:ssl" in nimcfg_text, (
            "CLI-path emission must include -d: defines for active flags; "
            "check that cli.py passes build_flag_defines(graph, deps_dir) "
            "and not None to format_nimcfg"
        )


# ---------------------------------------------------------------------------
# §7.6  format_workspace_nimcfgs — per-member relative paths (S9d)
# ---------------------------------------------------------------------------


class TestWorkspaceNimcfgs:
    """format_workspace_nimcfgs emits per-member nim.cfg with relative paths (§7.6)."""

    def _make_workspace(
        self,
        tmp_path: Path,
        members: list[tuple[str, str, str]],  # (name, rel_path, src_dir)
    ) -> object:
        """Build a minimal LoadedWorkspace stub for testing."""
        from milpa.manifest import Manifest, WorkspaceManifest
        from milpa.workspace import LoadedMember, LoadedWorkspace

        loaded_members = []
        for name, rel_path, src_dir in members:
            abs_dir = tmp_path / rel_path
            abs_dir.mkdir(parents=True, exist_ok=True)
            manifest = Manifest(
                name=name,
                kind="library",
                src_dir=src_dir,
                deps=(),
            )
            loaded_members.append(LoadedMember(
                rel_path=rel_path,
                abs_dir=abs_dir,
                manifest=manifest,
            ))

        ws_manifest = WorkspaceManifest(
            members=tuple(m.rel_path for m in loaded_members),
        )
        return LoadedWorkspace(
            root_dir=tmp_path,
            workspace_manifest=ws_manifest,
            members=tuple(loaded_members),
        )

    def test_member_with_no_deps_but_src_dir_emits_self_path(self, tmp_path: Path) -> None:
        """A member with src_dir but no transitive deps emits self-src-dir path (S7 #93).

        S7: even with no external deps, if the member has src_dir set it emits
        --path:"<src_dir>" so self-modules are discoverable by the Nim compiler.
        """
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [("liba", "member-a", "src")])
        graph = ResolvedGraph(deps=(
            ResolvedDep(
                name="liba",
                identity="sha256:" + "0" * 64,
                version="0.0.1",
                src_dir="src",
                requires=(),
                provenances=(MemberProvenanceRecord(name="liba"),),
            ),
        ))
        result = format_workspace_nimcfgs(ws, graph)
        assert "member-a" in result
        nimcfg = result["member-a"]
        assert nimcfg == (
            "# generated by milpa; do not edit\n"
            "# manifest: milpa.kdl\n"
            "# lockfile: milpa.lock\n"
            "\n"
            '--path:"src"\n'
        )

    def test_member_with_no_deps_no_src_dir_emits_header_only(self, tmp_path: Path) -> None:
        """A member with no src_dir and no transitive deps gets header-only nim.cfg."""
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [("liba", "member-a", "")])
        graph = ResolvedGraph(deps=(
            ResolvedDep(
                name="liba",
                identity="sha256:" + "0" * 64,
                version="0.0.1",
                src_dir="",
                requires=(),
                provenances=(MemberProvenanceRecord(name="liba"),),
            ),
        ))
        result = format_workspace_nimcfgs(ws, graph)
        assert "member-a" in result
        nimcfg = result["member-a"]
        assert nimcfg == (
            "# generated by milpa; do not edit\n"
            "# manifest: milpa.kdl\n"
            "# lockfile: milpa.lock\n"
        )

    def test_member_dep_uses_relative_path(self, tmp_path: Path) -> None:
        """A member dep uses a relative path from the member's directory.

        fixture-117: member-b depends on member-a (src_dir="src").
        member-b is at <root>/member-b/; member-a at <root>/member-a/.
        Expected: --path:"../member-a/src"
        """
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [
            ("liba", "member-a", "src"),
            ("libb", "member-b", "src"),
        ])
        graph = ResolvedGraph(deps=(
            ResolvedDep(
                name="liba",
                identity="sha256:" + "a" * 64,
                version="0.0.1",
                src_dir="src",
                requires=(),
                provenances=(MemberProvenanceRecord(name="liba"),),
            ),
            ResolvedDep(
                name="libb",
                identity="sha256:" + "b" * 64,
                version="0.0.1",
                src_dir="src",
                requires=("liba",),
                provenances=(MemberProvenanceRecord(name="libb"),),
            ),
        ))
        result = format_workspace_nimcfgs(ws, graph)
        assert "member-b" in result
        nimcfg_b = result["member-b"]
        # member-b depends on liba (src_dir="src") → ../member-a/src
        assert '--path:"../member-a/src"' in nimcfg_b

    def test_all_members_returned(self, tmp_path: Path) -> None:
        """All declared members appear in the returned dict."""
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [
            ("liba", "member-a", ""),
            ("libb", "member-b", ""),
        ])
        graph = ResolvedGraph(deps=(
            ResolvedDep(
                name="liba",
                identity="sha256:" + "0" * 64,
                version="0.0.1",
                src_dir="",
                requires=(),
                provenances=(MemberProvenanceRecord(name="liba"),),
            ),
            ResolvedDep(
                name="libb",
                identity="sha256:" + "1" * 64,
                version="0.0.1",
                src_dir="",
                requires=(),
                provenances=(MemberProvenanceRecord(name="libb"),),
            ),
        ))
        result = format_workspace_nimcfgs(ws, graph)
        assert set(result.keys()) == {"member-a", "member-b"}

    # S11 §3.8: workspace feature unification — unified -d: defines in per-member nim.cfg
    # -------------------------------------------------------------------------------------

    def test_s11_unified_defines_both_members_see_shared_dep_flag(
        self, tmp_path: Path
    ) -> None:
        """S11: both members see the unified -d: defines for a shared external dep.

        When depX has active_flags=("tls",) and the flag_defines map is provided,
        EVERY member that includes depX in its transitive closure emits -d:ssl.
        The active_flags are workspace-wide union (from the shared dep_active_flags
        map in the resolver), not per-member.
        """
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [
            ("liba", "member-a", "src"),
            ("libb", "member-b", "src"),
        ])
        # Both members depend on the same external dep "extlib" with active flags.
        extlib = ResolvedDep(
            name="extlib",
            identity="sha256:" + "e" * 64,
            version="0.0.1",
            src_dir="src",
            requires=(),
            active_flags=("tls",),  # workspace-wide union
        )
        liba_dep = ResolvedDep(
            name="liba",
            identity="sha256:" + "a" * 64,
            version="0.0.1",
            src_dir="src",
            requires=("extlib",),
            provenances=(MemberProvenanceRecord(name="liba"),),
        )
        libb_dep = ResolvedDep(
            name="libb",
            identity="sha256:" + "b" * 64,
            version="0.0.1",
            src_dir="src",
            requires=("extlib",),
            provenances=(MemberProvenanceRecord(name="libb"),),
        )
        graph = ResolvedGraph(deps=(extlib, liba_dep, libb_dep))
        # Unified flag_defines map (SSOT — built from dep manifests).
        flag_defines = {"extlib": {"tls": ("ssl", "useOpenSSL")}}

        result = format_workspace_nimcfgs(ws, graph, flag_defines=flag_defines)

        # member-a: depends on extlib → sees -d:ssl and -d:useOpenSSL
        assert "-d:ssl" in result["member-a"]
        assert "-d:useOpenSSL" in result["member-a"]
        # member-b: depends on extlib → same unified defines
        assert "-d:ssl" in result["member-b"]
        assert "-d:useOpenSSL" in result["member-b"]

    def test_s11_no_defines_when_no_flag_defines(self, tmp_path: Path) -> None:
        """Without flag_defines arg, no -d: lines emitted (backward compat)."""
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [("liba", "member-a", "")])
        extlib = ResolvedDep(
            name="extlib",
            identity="sha256:" + "e" * 64,
            version="0.0.1",
            src_dir="",
            requires=(),
            active_flags=("tls",),
        )
        liba_dep = ResolvedDep(
            name="liba",
            identity="sha256:" + "a" * 64,
            version="0.0.1",
            src_dir="",
            requires=("extlib",),
            provenances=(MemberProvenanceRecord(name="liba"),),
        )
        graph = ResolvedGraph(deps=(extlib, liba_dep))
        result = format_workspace_nimcfgs(ws, graph)  # no flag_defines
        assert "-d:" not in result["member-a"]

    def test_s11_childless_convention_in_workspace(self, tmp_path: Path) -> None:
        """S11: childless-convention (-d:<pkg>_<flag>) applies in workspace nim.cfg."""
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [("liba", "member-a", "")])
        extlib = ResolvedDep(
            name="extlib",
            identity="sha256:" + "e" * 64,
            version="0.0.1",
            src_dir="",
            requires=(),
            active_flags=("http",),
        )
        liba_dep = ResolvedDep(
            name="liba",
            identity="sha256:" + "a" * 64,
            version="0.0.1",
            src_dir="",
            requires=("extlib",),
            provenances=(MemberProvenanceRecord(name="liba"),),
        )
        graph = ResolvedGraph(deps=(extlib, liba_dep))
        flag_defines = {"extlib": {"http": ()}}  # childless — no explicit defines
        result = format_workspace_nimcfgs(ws, graph, flag_defines=flag_defines)
        assert "-d:extlib_http" in result["member-a"]

    def test_s11_defines_lexicographically_sorted(self, tmp_path: Path) -> None:
        """S11: -d: symbols in workspace nim.cfg are lexicographically sorted."""
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [("liba", "member-a", "")])
        extlib = ResolvedDep(
            name="extlib",
            identity="sha256:" + "e" * 64,
            version="0.0.1",
            src_dir="",
            requires=(),
            active_flags=("feat",),
        )
        liba_dep = ResolvedDep(
            name="liba",
            identity="sha256:" + "a" * 64,
            version="0.0.1",
            src_dir="",
            requires=("extlib",),
            provenances=(MemberProvenanceRecord(name="liba"),),
        )
        graph = ResolvedGraph(deps=(extlib, liba_dep))
        # Multiple symbols — must be lex-sorted in output
        flag_defines = {"extlib": {"feat": ("zzz", "aaa", "mmm")}}
        result = format_workspace_nimcfgs(ws, graph, flag_defines=flag_defines)
        d_lines = [l for l in result["member-a"].splitlines() if l.startswith("-d:")]
        assert d_lines == sorted(d_lines)

    def test_s11_member_not_in_closure_doesnt_see_other_members_flags(
        self, tmp_path: Path
    ) -> None:
        """A member that doesn't depend on extlib doesn't see its -d: lines."""
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [
            ("liba", "member-a", ""),  # depends on extlib
            ("libb", "member-b", ""),  # does NOT depend on extlib
        ])
        extlib = ResolvedDep(
            name="extlib",
            identity="sha256:" + "e" * 64,
            version="0.0.1",
            src_dir="",
            requires=(),
            active_flags=("tls",),
        )
        liba_dep = ResolvedDep(
            name="liba",
            identity="sha256:" + "a" * 64,
            version="0.0.1",
            src_dir="",
            requires=("extlib",),
            provenances=(MemberProvenanceRecord(name="liba"),),
        )
        libb_dep = ResolvedDep(
            name="libb",
            identity="sha256:" + "b" * 64,
            version="0.0.1",
            src_dir="",
            requires=(),  # no extlib dependency
            provenances=(MemberProvenanceRecord(name="libb"),),
        )
        graph = ResolvedGraph(deps=(extlib, liba_dep, libb_dep))
        flag_defines = {"extlib": {"tls": ("ssl",)}}
        result = format_workspace_nimcfgs(ws, graph, flag_defines=flag_defines)
        # member-a sees -d:ssl (extlib in its closure)
        assert "-d:ssl" in result["member-a"]
        # member-b does NOT see -d:ssl (extlib not in its closure)
        assert "-d:ssl" not in result["member-b"]

    def test_s11_defines_block_separated_by_blank_line(self, tmp_path: Path) -> None:
        """S11: -d: block in workspace nim.cfg is separated from --path: by blank line."""
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [("liba", "member-a", "src")])
        extlib = ResolvedDep(
            name="extlib",
            identity="sha256:" + "e" * 64,
            version="0.0.1",
            src_dir="src",
            requires=(),
            active_flags=("feat",),
        )
        liba_dep = ResolvedDep(
            name="liba",
            identity="sha256:" + "a" * 64,
            version="0.0.1",
            src_dir="src",
            requires=("extlib",),
            provenances=(MemberProvenanceRecord(name="liba"),),
        )
        graph = ResolvedGraph(deps=(extlib, liba_dep))
        flag_defines = {"extlib": {"feat": ("myDefine",)}}
        result = format_workspace_nimcfgs(ws, graph, flag_defines=flag_defines)
        nimcfg = result["member-a"]
        path_pos = nimcfg.index("--path:")
        define_pos = nimcfg.index("-d:myDefine")
        between = nimcfg[path_pos:define_pos]
        assert "\n\n" in between, "-d: block must be separated from --path: by blank line"


# ---------------------------------------------------------------------------
# S7 — #93 per-member self_src_dir (workspace-completion RFC §3.D)
# ---------------------------------------------------------------------------


class TestWorkspaceSelfSrcDir:
    """S7: format_workspace_nimcfgs emits self-src-dir first for each member (§3.D).

    Ordering is normative (Breadth-P3d): self-src_dir FIRST, then all deps
    lex-sorted by name — exactly the single-package format_nimcfg rule.
    """

    def _make_workspace(
        self,
        tmp_path: Path,
        members: list[tuple[str, str, str]],  # (name, rel_path, src_dir)
    ) -> object:
        from milpa.manifest import Manifest, WorkspaceManifest
        from milpa.workspace import LoadedMember, LoadedWorkspace

        loaded_members = []
        for name, rel_path, src_dir in members:
            abs_dir = tmp_path / rel_path
            abs_dir.mkdir(parents=True, exist_ok=True)
            manifest = Manifest(
                name=name,
                kind="library",
                src_dir=src_dir,
                deps=(),
            )
            loaded_members.append(LoadedMember(
                rel_path=rel_path,
                abs_dir=abs_dir,
                manifest=manifest,
            ))

        ws_manifest = WorkspaceManifest(
            members=tuple(m.rel_path for m in loaded_members),
        )
        return LoadedWorkspace(
            root_dir=tmp_path,
            workspace_manifest=ws_manifest,
            members=tuple(loaded_members),
        )

    def test_s7_member_self_src_dir_emitted_before_deps(self, tmp_path: Path) -> None:
        """S7: member A has src_dir='src'; its nim.cfg emits --path:'src' FIRST.

        Scenario (3-member chain: A→B, B→C):
          - A has src_dir='src'; B and C have no src_dir.
          - A's nim.cfg must emit --path:'src' before any dep paths.
          - B's nim.cfg has no self src-dir to emit (B has no src_dir).
          - C's nim.cfg is header-only (no deps).
        """
        from milpa.lockfile import MemberProvenanceRecord

        ws = self._make_workspace(tmp_path, [
            ("pkg-a", "member-a", "src"),   # A has src_dir
            ("pkg-b", "member-b", ""),       # B has no src_dir
            ("pkg-c", "member-c", ""),       # C has no src_dir
        ])
        dep_c = ResolvedDep(
            name="pkg-c",
            identity="sha256:" + "c" * 64,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(MemberProvenanceRecord(name="pkg-c"),),
        )
        dep_b = ResolvedDep(
            name="pkg-b",
            identity="sha256:" + "b" * 64,
            version="0.0.1",
            src_dir="",
            requires=("pkg-c",),
            provenances=(MemberProvenanceRecord(name="pkg-b"),),
        )
        dep_a = ResolvedDep(
            name="pkg-a",
            identity="sha256:" + "a" * 64,
            version="0.0.1",
            src_dir="src",
            requires=("pkg-b",),
            provenances=(MemberProvenanceRecord(name="pkg-a"),),
        )
        graph = ResolvedGraph(deps=(dep_a, dep_b, dep_c))
        result = format_workspace_nimcfgs(ws, graph)

        nimcfg_a = result["member-a"]
        lines = [l for l in nimcfg_a.splitlines() if l.startswith("--path:")]

        # self src-dir must be FIRST
        assert lines[0] == '--path:"src"', (
            f"Expected self src-dir first in A's nim.cfg, got: {lines}"
        )
        # then dep paths lex-sorted by name: pkg-b before pkg-c
        assert '--path:"../member-b"' in nimcfg_a
        assert '--path:"../member-c"' in nimcfg_a
        pkg_b_pos = nimcfg_a.index('../member-b')
        pkg_c_pos = nimcfg_a.index('../member-c')
        assert pkg_b_pos < pkg_c_pos, "deps must be lex-sorted: pkg-b before pkg-c"

        # B has no src_dir — no self path in B's nim.cfg
        nimcfg_b = result["member-b"]
        b_path_lines = [l for l in nimcfg_b.splitlines() if l.startswith("--path:")]
        assert b_path_lines == ['--path:"../member-c"'], (
            f"B has no src_dir; expected only pkg-c dep path, got: {b_path_lines}"
        )

        # C has no deps — header only
        nimcfg_c = result["member-c"]
        assert "--path:" not in nimcfg_c

    def test_s7_self_src_dir_first_ordering_is_normative(self, tmp_path: Path) -> None:
        """S7: self-src path appears before ALL dep paths (ordering, not just presence).

        Even when there are many deps, the member's own src_dir must be the very
        first --path: line. This pins the normative self-first ordering (Breadth-P3d).
        """
        from milpa.lockfile import MemberProvenanceRecord

        ws = self._make_workspace(tmp_path, [
            ("owner", "member-owner", "src"),
            ("dep-alpha", "member-alpha", ""),
            ("dep-beta", "member-beta", ""),
        ])
        dep_alpha = ResolvedDep(
            name="dep-alpha",
            identity="sha256:" + "a" * 64,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(MemberProvenanceRecord(name="dep-alpha"),),
        )
        dep_beta = ResolvedDep(
            name="dep-beta",
            identity="sha256:" + "b" * 64,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(MemberProvenanceRecord(name="dep-beta"),),
        )
        owner = ResolvedDep(
            name="owner",
            identity="sha256:" + "0" * 64,
            version="0.0.1",
            src_dir="src",
            requires=("dep-alpha", "dep-beta"),
            provenances=(MemberProvenanceRecord(name="owner"),),
        )
        graph = ResolvedGraph(deps=(owner, dep_alpha, dep_beta))
        result = format_workspace_nimcfgs(ws, graph)

        nimcfg_owner = result["member-owner"]
        path_lines = [l for l in nimcfg_owner.splitlines() if l.startswith("--path:")]

        # self src FIRST
        assert path_lines[0] == '--path:"src"', (
            f"self src-dir must be the very first --path: line, got: {path_lines}"
        )
        # remaining lines are lex-sorted by dep name (dep-alpha < dep-beta)
        assert path_lines[1] == '--path:"../member-alpha"'
        assert path_lines[2] == '--path:"../member-beta"'

    def test_s7_member_without_src_dir_unchanged(self, tmp_path: Path) -> None:
        """S7: a member with no src_dir still emits only dep paths (no regression)."""
        from milpa.lockfile import MemberProvenanceRecord

        ws = self._make_workspace(tmp_path, [
            ("pkg-a", "member-a", ""),   # no src_dir
            ("pkg-b", "member-b", ""),
        ])
        dep_b = ResolvedDep(
            name="pkg-b",
            identity="sha256:" + "b" * 64,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(MemberProvenanceRecord(name="pkg-b"),),
        )
        dep_a = ResolvedDep(
            name="pkg-a",
            identity="sha256:" + "a" * 64,
            version="0.0.1",
            src_dir="",
            requires=("pkg-b",),
            provenances=(MemberProvenanceRecord(name="pkg-a"),),
        )
        graph = ResolvedGraph(deps=(dep_a, dep_b))
        result = format_workspace_nimcfgs(ws, graph)

        nimcfg_a = result["member-a"]
        path_lines = [l for l in nimcfg_a.splitlines() if l.startswith("--path:")]
        # no src_dir → no self-path prepended; only dep path
        assert path_lines == ['--path:"../member-b"']


# ---------------------------------------------------------------------------
# Idempotence + determinism
# ---------------------------------------------------------------------------


class TestDeterminism:
    """Same graph always produces byte-identical output (§2.4 / §7.2)."""

    def test_same_graph_same_output(self) -> None:
        deps = (_dep("b", "src"), _dep("a", "lib"), _dep("c", ""))
        graph = ResolvedGraph(deps=deps)
        assert format_nimcfg(graph) == format_nimcfg(graph)

    def test_graph_order_independent(self) -> None:
        """Permuting the deps tuple must not change the output."""
        g1 = ResolvedGraph(deps=(_dep("aa"), _dep("bb"), _dep("cc")))
        g2 = ResolvedGraph(deps=(_dep("cc"), _dep("aa"), _dep("bb")))
        g3 = ResolvedGraph(deps=(_dep("bb"), _dep("cc"), _dep("aa")))
        result = format_nimcfg(g1)
        assert format_nimcfg(g2) == result
        assert format_nimcfg(g3) == result


# ---------------------------------------------------------------------------
# B-nimcfg: alias --path: lines (Phase B, rfc-content-addressed-identity.md)
# ---------------------------------------------------------------------------


def _dep_with_aliases(
    name: str,
    src_dir: str = "",
    aliases: tuple[str, ...] = (),
) -> ResolvedDep:
    """Build a minimal ResolvedDep with aliases for B-nimcfg tests."""
    return ResolvedDep(
        name=name,
        identity=None,
        version="0.0.1",
        src_dir=src_dir,
        requires=(),
        aliases=aliases,
    )


class TestAliasPathLines:
    """B-nimcfg: each alias emits its own --path: line (Phase B)."""

    def test_single_alias_emits_two_path_lines(self) -> None:
        """A dep with one alias → canonical --path: + alias --path:, canonical first."""
        graph = ResolvedGraph(deps=(_dep_with_aliases("foo", "src", aliases=("bar",)),))
        out = format_nimcfg(graph)
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        assert '--path:"_deps/foo/src"' in path_lines
        assert '--path:"_deps/bar/src"' in path_lines
        # canonical first
        foo_idx = path_lines.index('--path:"_deps/foo/src"')
        bar_idx = path_lines.index('--path:"_deps/bar/src"')
        assert foo_idx < bar_idx, "canonical --path: must come before alias --path:"

    def test_two_aliases_lex_ordered_after_canonical(self) -> None:
        """Two aliases: canonical first, then aliases lex-sorted."""
        graph = ResolvedGraph(
            deps=(_dep_with_aliases("foo", "src", aliases=("bar", "qux")),)
        )
        out = format_nimcfg(graph)
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        assert path_lines[0] == '--path:"_deps/foo/src"'
        assert path_lines[1] == '--path:"_deps/bar/src"'
        assert path_lines[2] == '--path:"_deps/qux/src"'

    def test_alias_path_uses_same_src_dir_as_canonical(self) -> None:
        """Alias --path: uses the canonical dep's src_dir."""
        graph = ResolvedGraph(
            deps=(_dep_with_aliases("mylib", "mylib", aliases=("legacy-mylib",)),)
        )
        out = format_nimcfg(graph)
        assert '--path:"_deps/legacy-mylib/mylib"' in out

    def test_no_alias_unchanged_behavior(self) -> None:
        """A dep with no aliases emits exactly one --path: line (unchanged)."""
        graph = ResolvedGraph(deps=(_dep_with_aliases("foo", "src"),))
        out = format_nimcfg(graph)
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        assert path_lines == ['--path:"_deps/foo/src"']

    def test_multiple_deps_aliases_interleaved_correctly(self) -> None:
        """Two non-aliased deps + one aliased dep: ordering is correct overall.

        Lex order of canonical names first, then for each canonical: canonical
        --path: immediately followed by alias --path: lines (lex-sorted aliases).
        But wait: the spec says overall dep iteration is lex by canonical name;
        within each dep we emit canonical then aliases in lex order.
        So the overall output for deps [foo(aliases=bar), zzz] should be:
          --path:"_deps/foo/..."
          --path:"_deps/bar/..."   ← alias of foo
          --path:"_deps/zzz"
        """
        graph = ResolvedGraph(deps=(
            _dep_with_aliases("zzz", ""),
            _dep_with_aliases("foo", "src", aliases=("bar",)),
        ))
        out = format_nimcfg(graph)
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        # lex order: foo before zzz; bar is foo's alias (after foo's canonical)
        assert path_lines == [
            '--path:"_deps/foo/src"',
            '--path:"_deps/bar/src"',
            '--path:"_deps/zzz"',
        ]

    def test_fixture_173_nim_cfg(self) -> None:
        """fixture-173: dedup of foo+bar → nim.cfg has both --path: lines."""
        # foo is canonical (aliases=("bar",)), bar is the alias.
        graph = ResolvedGraph(
            deps=(_dep_with_aliases("foo", "src", aliases=("bar",)),)
        )
        expected = _expected_nimcfg("fixture-173-dedup-same-content-aliases")
        assert format_nimcfg(graph) == expected
