"""Tests for milpa.manifest_writer — slice 10d.

Covers:
- mutate_manifest_file: normal path, guards (file-not-found, nimble-refused,
  workspace-refused), atomic write (tmp file cleaned up on failure).
- WriteResult comment_lost heuristic.
- format_manifest canonical output (header, field ordering, dep forms).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from milpa.errors import (
    MAN_MUTATE_FILE_NOT_FOUND,
    MAN_MUTATE_NIMBLE_REFUSED,
    MAN_MUTATE_WORKSPACE_REFUSED,
    MilpaError,
)
from milpa.manifest import (
    FlagDecl,
    LocalDep,
    GitTarget,
    Manifest,
    MemberDep,
    NamedDep,
    Override,
    TarballDep,
    UrlDep,
    format_manifest,
    parse_manifest,
)
from milpa.manifest_writer import WriteResult, mutate_manifest_file

# ---------------------------------------------------------------------------
# format_manifest canonical output tests
# ---------------------------------------------------------------------------


def test_format_manifest_header_present() -> None:
    """format_manifest always emits the canonical header line."""
    m = Manifest(name="myapp", deps=())
    text = format_manifest(m)
    assert text.startswith(
        "// generated by milpa; edit by hand or via `milpa add` / `milpa remove`\n"
    )


def test_format_manifest_kind_is_last() -> None:
    """kind is always the last field (Rust canonical ordering)."""
    m = Manifest(name="myapp", deps=(), kind="application")
    text = format_manifest(m)
    lines = [ln for ln in text.rstrip("\n").splitlines() if ln.strip()]
    assert lines[-1] == 'kind "application"'


def test_format_manifest_minimal_no_kind_block_when_library() -> None:
    """A minimal library manifest serializes as header + name + kind."""
    m = Manifest(name="mylib", deps=())
    text = format_manifest(m)
    assert 'name "mylib"' in text
    assert 'kind "library"' in text


def test_format_manifest_url_dep_quoted_name_and_url() -> None:
    """UrlDep: name is double-quoted, git URL carries (url) annotation."""
    dep = UrlDep(name="foo", git="https://github.com/example/foo.git", ref="main")
    m = Manifest(name="myapp", deps=(dep,), kind="application")
    text = format_manifest(m)
    assert '"foo" git=(url)"https://github.com/example/foo.git" ref="main"' in text


def test_format_manifest_url_dep_with_mirror_block() -> None:
    """A UrlDep with mirrors renders as a multi-line block."""
    dep = UrlDep(
        name="foo",
        git="https://github.com/example/foo.git",
        ref="main",
        mirrors=("https://mirror.example.com/foo.git",),
    )
    m = Manifest(name="myapp", deps=(dep,))
    text = format_manifest(m)
    assert "mirror (url)" in text
    assert "https://mirror.example.com/foo.git" in text


def test_format_manifest_named_dep_with_constraint() -> None:
    """NamedDep with constraint: both name and constraint are double-quoted."""
    dep = NamedDep(name="chronos", constraint=">= 3.0.0")
    m = Manifest(name="myapp", deps=(dep,))
    text = format_manifest(m)
    assert '"chronos" ">= 3.0.0"' in text


def test_format_manifest_named_dep_no_constraint() -> None:
    """NamedDep without constraint: only the name is quoted."""
    dep = NamedDep(name="stew", constraint=None)
    m = Manifest(name="myapp", deps=(dep,))
    text = format_manifest(m)
    assert '    "stew"' in text
    # Should NOT have a second quoted arg.
    for line in text.splitlines():
        if '"stew"' in line:
            assert '">=' not in line


def test_format_manifest_local_dep() -> None:
    """LocalDep serializes with local= property."""
    dep = LocalDep(name="mylocal", path="../local-pkg")
    m = Manifest(name="myapp", deps=(dep,))
    text = format_manifest(m)
    assert '"mylocal" local="../local-pkg"' in text


def test_format_manifest_tarball_dep() -> None:
    """TarballDep serializes with tarball=(url) and optional sha256."""
    dep = TarballDep(
        name="archive",
        url="https://example.com/archive.tar.gz",
        sha256="abc123",
    )
    m = Manifest(name="myapp", deps=(dep,))
    text = format_manifest(m)
    assert 'tarball=(url)"https://example.com/archive.tar.gz"' in text
    assert 'sha256="abc123"' in text


def test_format_manifest_member_dep() -> None:
    """MemberDep serializes as member "<name>"."""
    dep = MemberDep(name="subpkg")
    m = Manifest(name="myapp", deps=(dep,))
    text = format_manifest(m)
    assert '    member "subpkg"' in text


def test_format_manifest_flag_decl_default_false() -> None:
    """FlagDecl default=False renders as default=#false."""
    fd = FlagDecl(name="myflag", default=False)
    m = Manifest(name="myapp", deps=(), flags=(fd,))
    text = format_manifest(m)
    assert '"myflag" default=#false' in text


def test_format_manifest_flag_decl_default_true() -> None:
    """FlagDecl default=True renders as default=#true."""
    fd = FlagDecl(name="myflag", default=True)
    m = Manifest(name="myapp", deps=(), flags=(fd,))
    text = format_manifest(m)
    assert '"myflag" default=#true' in text


def test_format_manifest_spec_version_only_when_explicit() -> None:
    """spec-version emitted only when spec_version_explicit=True (§4.4)."""
    m_implicit = Manifest(name="myapp", deps=(), spec_version_explicit=False)
    m_explicit = Manifest(name="myapp", deps=(), spec_version_explicit=True)
    assert "spec-version" not in format_manifest(m_implicit)
    assert "spec-version 1" in format_manifest(m_explicit)


def test_format_manifest_override_block() -> None:
    """Override block renders pkg with git=(url) and ref."""
    ov = Override(name="foo", target=GitTarget(git="https://github.com/fork/foo.git", ref="dev"))
    m = Manifest(name="myapp", deps=(), overrides=(ov,))
    text = format_manifest(m)
    assert 'pkg "foo"' in text
    assert 'git=(url)"https://github.com/fork/foo.git"' in text
    assert 'ref="dev"' in text


def test_format_manifest_comment_warning_emitted(capsys: pytest.CaptureFixture[str]) -> None:
    """had_comments=True → warning on stderr."""
    m = Manifest(name="myapp", deps=(), had_comments=True)
    format_manifest(m)
    captured = capsys.readouterr()
    assert "comments are not preserved" in captured.err


def test_format_manifest_roundtrip_url_dep() -> None:
    """UrlDep round-trips through format→parse."""
    dep = UrlDep(name="foo", git="https://github.com/example/foo.git", ref="main")
    m = Manifest(name="myapp", deps=(dep,), kind="application")
    text = format_manifest(m)
    reparsed = parse_manifest(text)
    assert len(reparsed.deps) == 1
    pd = reparsed.deps[0]
    assert isinstance(pd, UrlDep)
    assert pd.git == dep.git
    assert pd.ref == dep.ref
    assert pd.name == dep.name


# ---------------------------------------------------------------------------
# mutate_manifest_file tests
# ---------------------------------------------------------------------------


def test_mutate_file_not_found(tmp_path: Path) -> None:
    """Raises MAN-MUTATE-FILE-NOT-FOUND if the file does not exist."""
    missing = tmp_path / "milpa.kdl"
    with pytest.raises(MilpaError) as exc_info:
        mutate_manifest_file(missing, lambda m: m)
    assert exc_info.value.slug == MAN_MUTATE_FILE_NOT_FOUND


def test_mutate_nimble_refused(tmp_path: Path) -> None:
    """Raises MAN-MUTATE-NIMBLE-REFUSED for a .nimble file."""
    nimble = tmp_path / "myapp.nimble"
    nimble.write_text("version = \"1.0.0\"\n")
    with pytest.raises(MilpaError) as exc_info:
        mutate_manifest_file(nimble, lambda m: m)
    assert exc_info.value.slug == MAN_MUTATE_NIMBLE_REFUSED


def test_mutate_workspace_refused(tmp_path: Path) -> None:
    """Raises MAN-MUTATE-WORKSPACE-REFUSED for a workspace manifest."""
    kdl = tmp_path / "milpa.kdl"
    kdl.write_text('workspace {\n    member "pkgA"\n}\n')
    with pytest.raises(MilpaError) as exc_info:
        mutate_manifest_file(kdl, lambda m: m)
    assert exc_info.value.slug == MAN_MUTATE_WORKSPACE_REFUSED


def test_mutate_identity(tmp_path: Path) -> None:
    """Identity mutation leaves the file with the canonical re-render."""
    kdl = tmp_path / "milpa.kdl"
    kdl.write_text('name "myapp"\nkind "library"\n')
    result = mutate_manifest_file(kdl, lambda m: m)
    assert isinstance(result, WriteResult)
    assert result.path == kdl
    # File should contain canonical format.
    text = kdl.read_text()
    assert 'name "myapp"' in text
    assert text.startswith("// generated by milpa")


def test_mutate_adds_dep(tmp_path: Path) -> None:
    """Mutation that adds a UrlDep is reflected in the written file."""
    kdl = tmp_path / "milpa.kdl"
    kdl.write_text('name "myapp"\nkind "library"\n')

    new_dep = UrlDep(name="bar", git="https://github.com/example/bar.git", ref="main")

    from dataclasses import replace

    def add_dep(m: Manifest) -> Manifest:
        return replace(m, deps=m.deps + (new_dep,))

    mutate_manifest_file(kdl, add_dep)
    text = kdl.read_text()
    assert '"bar"' in text
    assert "github.com/example/bar.git" in text


def test_mutate_removes_dep(tmp_path: Path) -> None:
    """Mutation that removes a dep is reflected in the written file."""
    kdl = tmp_path / "milpa.kdl"
    kdl.write_text(
        'name "myapp"\nkind "library"\n'
        'deps {\n    foo git=(url)"https://github.com/example/foo.git" ref="main"\n}\n'
    )

    from dataclasses import replace

    def remove_foo(m: Manifest) -> Manifest:
        return replace(m, deps=tuple(d for d in m.deps if d.name != "foo"))

    mutate_manifest_file(kdl, remove_foo)
    text = kdl.read_text()
    assert "foo" not in text


def test_mutate_atomic_write(tmp_path: Path) -> None:
    """No .tmp file left behind after a successful atomic write."""
    kdl = tmp_path / "milpa.kdl"
    kdl.write_text('name "myapp"\nkind "library"\n')
    mutate_manifest_file(kdl, lambda m: m)
    tmp = kdl.with_suffix(".kdl.tmp")
    assert not tmp.exists(), ".tmp file should be cleaned up after os.replace()"


def test_mutate_comment_loss_count(tmp_path: Path) -> None:
    """comments_lost heuristic counts // lines dropped."""
    kdl = tmp_path / "milpa.kdl"
    kdl.write_text(
        '// my comment\n// another comment\nname "myapp"\nkind "library"\n'
    )
    result = mutate_manifest_file(kdl, lambda m: m)
    # The input had 2 comment lines; the canonical re-render has 1 (the header).
    assert result.comments_lost == 1
