"""Tests for milpa.nimcfg — format_nimcfg and format_workspace_nimcfgs.

Spec authority: lockfile-schema.md §7.1–7.4, §7.6.

Coverage:
  - §7.1  header emitted unconditionally (even no-deps)
  - §7.2  POSIX path separators
  - §7.3  --path: line form (deps_dir/name[/src_dir])
  - §7.4  emission order: self src-dir first, then deps lexicographic
  - §7.4  no-deps → header only, trailing \\n
  - §7.4  self src-dir only (no deps) → header + blank + self path
  - §7.5  feature-flag defines DEFERRED — documented test
  - §7.6  format_workspace_nimcfgs: per-member relative paths

Corpus fixtures:
  - fixture-003  single URL dep with src_dir "src"
  - fixture-116  self src_dir "src" + one dep with src_dir "src"
  - fixture-063  three named deps sorted lexicographically (X/Y/Z)
  - fixture-115  no deps — header-only nim.cfg
  - fixture-117  workspace two-member success: member-b depends on member-a
"""

from pathlib import Path

from milpa.lockfile import ResolvedDep, ResolvedGraph
from milpa.nimcfg import format_nimcfg, format_workspace_nimcfgs

# ---------------------------------------------------------------------------
# Fixtures helpers
# ---------------------------------------------------------------------------

_CONFORMANCE = Path(__file__).parent.parent.parent.parent / "conformance" / "spec-v1"


def _expected_nimcfg(fixture_name: str, subpath: str = "nim.cfg") -> str:
    """Load an expected nim.cfg from the conformance corpus."""
    path = _CONFORMANCE / fixture_name / "expected" / subpath
    return path.read_text()


def _dep(
    name: str,
    src_dir: str = "",
    requires: tuple[str, ...] = (),
    active_flags: tuple[str, ...] = (),
) -> ResolvedDep:
    """Build a minimal ResolvedDep suitable for nimcfg tests."""
    return ResolvedDep(
        name=name,
        identity=None,
        version="0.0.1",
        src_dir=src_dir,
        requires=requires,
        active_flags=active_flags,
    )


# ---------------------------------------------------------------------------
# §7.1  Header
# ---------------------------------------------------------------------------


class TestHeader:
    """The normative three-line header MUST be emitted unconditionally (§7.1)."""

    _HEADER = (
        "# generated by milpa; do not edit\n"
        "# manifest: milpa.kdl\n"
        "# lockfile: milpa.lock\n"
    )

    def test_header_present_with_no_deps(self) -> None:
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph)
        assert out.startswith(self._HEADER.rstrip("\n"))

    def test_header_present_with_deps(self) -> None:
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph)
        assert out.startswith("# generated by milpa; do not edit\n")
        assert "# manifest: milpa.kdl\n" in out
        assert "# lockfile: milpa.lock\n" in out

    def test_header_is_exactly_three_lines(self) -> None:
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph)
        header_block = out.split("\n\n")[0]  # up to first blank line (or all)
        lines = header_block.splitlines()
        assert lines[0] == "# generated by milpa; do not edit"
        assert lines[1] == "# manifest: milpa.kdl"
        assert lines[2] == "# lockfile: milpa.lock"


# ---------------------------------------------------------------------------
# §7.2  POSIX path separators
# ---------------------------------------------------------------------------


class TestPosixPaths:
    """All --path: lines MUST use / regardless of host OS (§7.2)."""

    def test_no_backslashes_in_dep_path(self) -> None:
        graph = ResolvedGraph(deps=(_dep("mydep", "some/sub"),))
        out = format_nimcfg(graph, deps_dir=Path("_deps"))
        # Every --path: line must not contain backslash
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        assert all("\\" not in ln for ln in path_lines)

    def test_forward_slash_separator(self) -> None:
        graph = ResolvedGraph(deps=(_dep("lib", "sources"),))
        out = format_nimcfg(graph, deps_dir=Path("_deps"))
        assert '--path:"_deps/lib/sources"' in out

    def test_deps_dir_uses_posix(self) -> None:
        # Even if Path() uses native sep on Windows, as_posix() must be used.
        graph = ResolvedGraph(deps=(_dep("x", ""),))
        out = format_nimcfg(graph, deps_dir=Path("vendor") / "deps")
        assert '--path:"vendor/deps/x"' in out


# ---------------------------------------------------------------------------
# §7.3  --path: line form
# ---------------------------------------------------------------------------


class TestPathLineForm:
    """--path:"<deps_dir>/<name>[/<src_dir>]" form (§7.3)."""

    def test_empty_src_dir_omits_trailing_slash(self) -> None:
        graph = ResolvedGraph(deps=(_dep("zlib", ""),))
        out = format_nimcfg(graph)
        assert '--path:"_deps/zlib"' in out
        assert '--path:"_deps/zlib/"' not in out

    def test_src_dir_appended_with_slash(self) -> None:
        graph = ResolvedGraph(deps=(_dep("chronos", "chronos"),))
        out = format_nimcfg(graph)
        assert '--path:"_deps/chronos/chronos"' in out

    def test_custom_deps_dir(self) -> None:
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph, deps_dir=Path("third_party"))
        assert '--path:"third_party/foo/src"' in out

    def test_nested_src_dir(self) -> None:
        graph = ResolvedGraph(deps=(_dep("pkg", "lib/nim"),))
        out = format_nimcfg(graph)
        assert '--path:"_deps/pkg/lib/nim"' in out


# ---------------------------------------------------------------------------
# §7.4  Emission order
# ---------------------------------------------------------------------------


class TestEmissionOrder:
    """Emission order: self src-dir first, then deps sorted lexicographically (§7.4)."""

    def test_no_deps_header_only(self) -> None:
        """No-deps: header only, trailing \\n (no blank line after header)."""
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph)
        # Must not contain --path:
        assert "--path:" not in out
        # Must end with a single \n (not \n\n)
        assert out.endswith("milpa.lock\n")
        assert not out.endswith("milpa.lock\n\n")

    def test_no_deps_no_blank_line_after_header(self) -> None:
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph)
        # No double-newline
        assert "\n\n" not in out

    def test_self_src_dir_before_deps(self) -> None:
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph, self_src_dir="src")
        self_idx = out.index('--path:"src"')
        dep_idx = out.index('--path:"_deps/foo/src"')
        assert self_idx < dep_idx

    def test_self_src_dir_only_no_deps(self) -> None:
        """Self src-dir with no deps: header + blank line + self path line."""
        graph = ResolvedGraph(deps=())
        out = format_nimcfg(graph, self_src_dir="src")
        assert "--path:" in out
        lines = out.splitlines()
        # 0: # generated…, 1: # manifest…, 2: # lockfile…, 3: (blank), 4: --path:"src"
        assert lines[3] == ""
        assert lines[4] == '--path:"src"'

    def test_deps_lexicographic_order(self) -> None:
        """Deps sorted lexicographically regardless of graph construction order."""
        # Graph has deps in reverse-alpha order
        graph = ResolvedGraph(deps=(_dep("zlib"), _dep("alpha"), _dep("mod")))
        out = format_nimcfg(graph)
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        names_in_output = [ln.split("/")[1].rstrip('"') for ln in path_lines]
        assert names_in_output == sorted(names_in_output)

    def test_trailing_newline_single_dep(self) -> None:
        """File ends with exactly one trailing \\n (§7.4 NOTE)."""
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph)
        assert out.endswith("\n")
        assert not out.endswith("\n\n")

    def test_blank_line_separates_header_from_paths(self) -> None:
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        out = format_nimcfg(graph)
        lines = out.splitlines()
        # line 3 (index 3) must be blank
        assert lines[3] == ""
        # line 4 is the first --path:
        assert lines[4].startswith("--path:")

    def test_multiple_deps_sorted(self) -> None:
        graph = ResolvedGraph(
            deps=(_dep("zz", ""), _dep("aa", "src"), _dep("mm", "lib"))
        )
        out = format_nimcfg(graph)
        path_lines = [ln for ln in out.splitlines() if ln.startswith("--path:")]
        assert path_lines[0] == '--path:"_deps/aa/src"'
        assert path_lines[1] == '--path:"_deps/mm/lib"'
        assert path_lines[2] == '--path:"_deps/zz"'


# ---------------------------------------------------------------------------
# Corpus fixture cross-checks
# ---------------------------------------------------------------------------


class TestCorpusFixtures:
    """Assert exact byte match against conformance corpus expected/nim.cfg files.

    These fixtures exercise the normative output format end-to-end.
    Graph data is reconstructed from the fixture's milpa.kdl + lockfile
    information so the exact dep names and src_dirs are matched.
    """

    def test_fixture_003_single_url_dep(self) -> None:
        """fixture-003: single dep named 'foo' with src_dir 'src'."""
        # From conformance/spec-v1/fixture-003-single-url-dep/expected/milpa.lock:
        #   dep "foo" { src_dir "src" ... }
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        expected = _expected_nimcfg("fixture-003-single-url-dep")
        assert format_nimcfg(graph) == expected

    def test_fixture_115_no_deps(self) -> None:
        """fixture-115: conditional dep excluded → no deps in graph."""
        # expected/nim.cfg is header-only (no --path: lines)
        graph = ResolvedGraph(deps=())
        expected = _expected_nimcfg("fixture-115-conditional-dep-excluded")
        assert format_nimcfg(graph) == expected

    def test_fixture_116_self_src_dir(self) -> None:
        """fixture-116: manifest declares src_dir 'src'; dep 'foo' src_dir 'src'."""
        # From the fixture milpa.kdl: name "myapp" src_dir "src" + dep foo
        graph = ResolvedGraph(deps=(_dep("foo", "src"),))
        expected = _expected_nimcfg("fixture-116-src-dir-self-path")
        assert format_nimcfg(graph, self_src_dir="src") == expected

    def test_fixture_063_three_deps_sorted(self) -> None:
        """fixture-063: three named deps X, Y, Z each with src_dir 'src'."""
        # From the expected lockfile: X, Y, Z all with src_dir "src"
        graph = ResolvedGraph(
            deps=(_dep("X", "src"), _dep("Y", "src"), _dep("Z", "src"))
        )
        expected = _expected_nimcfg("fixture-063-canonical-selection")
        assert format_nimcfg(graph) == expected


# ---------------------------------------------------------------------------
# §7.5  Feature-flag defines — DEFERRED (#23)
# ---------------------------------------------------------------------------


class TestFeatureFlagsDeferral:
    """§7.5 defines are deferred — no -d: output regardless of active_flags."""

    def test_active_flags_not_emitted(self) -> None:
        """Active flags on a dep MUST NOT produce -d: output until #23 is done."""
        graph = ResolvedGraph(
            deps=(_dep("pkg", "src", active_flags=("feature_x", "feature_y")),)
        )
        out = format_nimcfg(graph)
        assert "-d:" not in out, (
            "§7.5 feature-flag emission is deferred (#23); "
            "if this test starts failing the deferral has been lifted "
            "and the test should be replaced with correct -d: assertions"
        )

    def test_active_flags_do_not_affect_path_output(self) -> None:
        """Flags on a dep must not alter the --path: lines."""
        graph_no_flags = ResolvedGraph(deps=(_dep("pkg", "src"),))
        graph_with_flags = ResolvedGraph(
            deps=(_dep("pkg", "src", active_flags=("flag",)),)
        )
        assert format_nimcfg(graph_no_flags) == format_nimcfg(graph_with_flags)


# ---------------------------------------------------------------------------
# §7.6  format_workspace_nimcfgs — per-member relative paths (S9d)
# ---------------------------------------------------------------------------


class TestWorkspaceNimcfgs:
    """format_workspace_nimcfgs emits per-member nim.cfg with relative paths (§7.6)."""

    def _make_workspace(
        self,
        tmp_path: Path,
        members: list[tuple[str, str, str]],  # (name, rel_path, src_dir)
    ) -> object:
        """Build a minimal LoadedWorkspace stub for testing."""
        from milpa.manifest import Manifest, WorkspaceManifest
        from milpa.workspace import LoadedMember, LoadedWorkspace

        loaded_members = []
        for name, rel_path, src_dir in members:
            abs_dir = tmp_path / rel_path
            abs_dir.mkdir(parents=True, exist_ok=True)
            manifest = Manifest(
                name=name,
                kind="library",
                src_dir=src_dir,
                deps=(),
            )
            loaded_members.append(LoadedMember(
                rel_path=rel_path,
                abs_dir=abs_dir,
                manifest=manifest,
            ))

        ws_manifest = WorkspaceManifest(
            members=tuple(m.rel_path for m in loaded_members),
        )
        return LoadedWorkspace(
            root_dir=tmp_path,
            workspace_manifest=ws_manifest,
            members=tuple(loaded_members),
        )

    def test_member_with_no_deps_emits_header_only(self, tmp_path: Path) -> None:
        """A member with no transitive deps gets header-only nim.cfg."""
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [("liba", "member-a", "src")])
        graph = ResolvedGraph(deps=(
            ResolvedDep(
                name="liba",
                identity="sha256:" + "0" * 64,
                version="0.0.1",
                src_dir="src",
                requires=(),
                provenance=MemberProvenanceRecord(name="liba"),
            ),
        ))
        result = format_workspace_nimcfgs(ws, graph)
        assert "member-a" in result
        nimcfg = result["member-a"]
        assert nimcfg == (
            "# generated by milpa; do not edit\n"
            "# manifest: milpa.kdl\n"
            "# lockfile: milpa.lock\n"
        )

    def test_member_dep_uses_relative_path(self, tmp_path: Path) -> None:
        """A member dep uses a relative path from the member's directory.

        fixture-117: member-b depends on member-a (src_dir="src").
        member-b is at <root>/member-b/; member-a at <root>/member-a/.
        Expected: --path:"../member-a/src"
        """
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [
            ("liba", "member-a", "src"),
            ("libb", "member-b", "src"),
        ])
        graph = ResolvedGraph(deps=(
            ResolvedDep(
                name="liba",
                identity="sha256:" + "a" * 64,
                version="0.0.1",
                src_dir="src",
                requires=(),
                provenance=MemberProvenanceRecord(name="liba"),
            ),
            ResolvedDep(
                name="libb",
                identity="sha256:" + "b" * 64,
                version="0.0.1",
                src_dir="src",
                requires=("liba",),
                provenance=MemberProvenanceRecord(name="libb"),
            ),
        ))
        result = format_workspace_nimcfgs(ws, graph)
        assert "member-b" in result
        nimcfg_b = result["member-b"]
        # member-b depends on liba (src_dir="src") → ../member-a/src
        assert '--path:"../member-a/src"' in nimcfg_b

    def test_all_members_returned(self, tmp_path: Path) -> None:
        """All declared members appear in the returned dict."""
        from milpa.lockfile import MemberProvenanceRecord
        ws = self._make_workspace(tmp_path, [
            ("liba", "member-a", ""),
            ("libb", "member-b", ""),
        ])
        graph = ResolvedGraph(deps=(
            ResolvedDep(
                name="liba",
                identity="sha256:" + "0" * 64,
                version="0.0.1",
                src_dir="",
                requires=(),
                provenance=MemberProvenanceRecord(name="liba"),
            ),
            ResolvedDep(
                name="libb",
                identity="sha256:" + "1" * 64,
                version="0.0.1",
                src_dir="",
                requires=(),
                provenance=MemberProvenanceRecord(name="libb"),
            ),
        ))
        result = format_workspace_nimcfgs(ws, graph)
        assert set(result.keys()) == {"member-a", "member-b"}


# ---------------------------------------------------------------------------
# Idempotence + determinism
# ---------------------------------------------------------------------------


class TestDeterminism:
    """Same graph always produces byte-identical output (§2.4 / §7.2)."""

    def test_same_graph_same_output(self) -> None:
        deps = (_dep("b", "src"), _dep("a", "lib"), _dep("c", ""))
        graph = ResolvedGraph(deps=deps)
        assert format_nimcfg(graph) == format_nimcfg(graph)

    def test_graph_order_independent(self) -> None:
        """Permuting the deps tuple must not change the output."""
        g1 = ResolvedGraph(deps=(_dep("aa"), _dep("bb"), _dep("cc")))
        g2 = ResolvedGraph(deps=(_dep("cc"), _dep("aa"), _dep("bb")))
        g3 = ResolvedGraph(deps=(_dep("bb"), _dep("cc"), _dep("aa")))
        result = format_nimcfg(g1)
        assert format_nimcfg(g2) == result
        assert format_nimcfg(g3) == result
