"""Tests for lockfile.py — slices 4a, 4b, 4c, 4e.

Structure:
  - 4a: type sanity (ProvenanceRecord variants, LockedDep, Lockfile,
        ResolvedDep, ResolvedGraph)
  - 4b: parse_lockfile — all LOCK-* slugs, strategy/maxver fallback,
        self_mirrors, each provenance kind, parse round-trips; property tests
  - 4c: from_graph + format_lockfile — byte-exact gate against fixture-118,
        _kdl_str SSOT escaping; property tests
  - 4e: verify_against_graph, verify_lockfile_against_deps; property tests
"""

from __future__ import annotations

from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from milpa.errors import (
    LOCK_DEP_FIELD_ARITY,
    LOCK_DEP_IDENTITY_INVALID,
    LOCK_DEP_NAME_ARITY,
    LOCK_FIELD_ARITY,
    LOCK_FIELD_TYPE,
    LOCK_GRAPH_MISMATCH,
    LOCK_KDL_SYNTAX,
    LOCK_PROV_FIELD_ARITY,
    LOCK_PROV_FIELD_MISSING,
    LOCK_PROV_KIND_MISSING,
    LOCK_PROV_KIND_UNKNOWN,
    LOCK_VERSION_MISSING,
    LOCK_VERSION_UNSUPPORTED,
    MilpaError,
)
from milpa.lockfile import (
    LOCKFILE_SCHEMA_VERSION,
    CondRequire,
    GitProvenanceRecord,
    LocalProvenanceRecord,
    LockedDep,
    Lockfile,
    MemberProvenanceRecord,
    OciProvenanceRecord,
    RegistryProvenanceRecord,
    ResolvedDep,
    ResolvedGraph,
    TarballProvenanceRecord,
    _kdl_str,
    format_lockfile,
    from_graph,
    parse_lockfile,
    verify_against_graph,
    verify_lockfile_against_deps,
)
from milpa.predicate import Predicate

# ---------------------------------------------------------------------------
# Fixture paths
# ---------------------------------------------------------------------------

_CONFORMANCE = (
    Path(__file__).parent.parent.parent.parent / "conformance" / "spec-v1"
)


def _fixture(name: str) -> Path:
    return _CONFORMANCE / name


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_VALID_SHA256 = "a" * 64
_VALID_IDENTITY = f"sha256:{_VALID_SHA256}"

_MINIMAL_LOCKFILE = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"
"""

_FULL_GIT_DEP = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {{
    identity "{_VALID_IDENTITY}"
    version "1.2.3"
    src_dir "src"
    requires "bar" "baz"
    provenance {{
        kind "git"
        url "https://github.com/example/foo.git"
        ref "main"
        commit_sha "deadbeef1234567890deadbeef1234567890dead"
    }}
}}
"""


def _make_resolved_dep(
    name: str = "foo",
    *,
    identity: str | None = _VALID_IDENTITY,
    version: str = "0.0.1",
    src_dir: str = "",
    requires: tuple[str, ...] = (),
    provenance: object = None,
    active_flags: tuple[str, ...] = (),
    self_mirrors: tuple[str, ...] = (),
) -> ResolvedDep:
    return ResolvedDep(
        name=name,
        identity=identity,
        version=version,
        src_dir=src_dir,
        requires=requires,
        provenance=provenance,  # type: ignore[arg-type]
        active_flags=active_flags,
        self_mirrors=self_mirrors,
    )


# ---------------------------------------------------------------------------
# 4a — Type model
# ---------------------------------------------------------------------------


class TestProvenanceRecordVariants:
    def test_git_record_defaults(self) -> None:
        r = GitProvenanceRecord(url="https://example.com/foo.git")
        assert r.kind == "git"
        assert r.url == "https://example.com/foo.git"
        assert r.ref is None
        assert r.commit_sha is None

    def test_git_record_full(self) -> None:
        r = GitProvenanceRecord(
            url="https://example.com/foo.git",
            ref="main",
            commit_sha="abc" * 13 + "d",
        )
        assert r.ref == "main"
        assert r.commit_sha == "abc" * 13 + "d"

    def test_tarball_record(self) -> None:
        r = TarballProvenanceRecord(url="https://example.com/foo.tar.gz")
        assert r.kind == "tarball"
        assert r.sha256 is None

    def test_tarball_record_with_sha(self) -> None:
        r = TarballProvenanceRecord(url="https://example.com/foo.tar.gz", sha256="abc123")
        assert r.sha256 == "abc123"

    def test_local_record(self) -> None:
        r = LocalProvenanceRecord(path="../locallib")
        assert r.kind == "local"
        assert r.path == "../locallib"

    def test_member_record(self) -> None:
        r = MemberProvenanceRecord(name="mylib")
        assert r.kind == "member"
        assert r.name == "mylib"

    def test_oci_record(self) -> None:
        r = OciProvenanceRecord(
            registry="ghcr.io",
            repository="example/foo",
            digest="sha256:abc",
        )
        assert r.kind == "oci"
        assert r.registry == "ghcr.io"
        assert r.repository == "example/foo"
        assert r.digest == "sha256:abc"

    def test_registry_record_compat(self) -> None:
        r = RegistryProvenanceRecord(name="foo", tag="v1.0.0")
        assert r.kind == "registry"
        assert r.name == "foo"
        assert r.tag == "v1.0.0"
        assert r.commit_sha is None

    def test_records_are_frozen(self) -> None:
        r = GitProvenanceRecord(url="https://example.com/foo.git")
        with pytest.raises((AttributeError, TypeError)):
            r.url = "mutated"  # type: ignore[misc]


class TestLockedDepAndLockfile:
    def test_locked_dep_defaults(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        assert dep.active_flags == ()
        assert dep.self_mirrors == ()

    def test_lockfile_defaults(self) -> None:
        lf = Lockfile(deps=())
        assert lf.strategy == "maxver"
        assert lf.version == LOCKFILE_SCHEMA_VERSION

    def test_resolved_dep_fields(self) -> None:
        d = _make_resolved_dep("bar", version="1.0.0", src_dir="src")
        assert d.name == "bar"
        assert d.version == "1.0.0"
        assert d.src_dir == "src"

    def test_resolved_graph_wraps_deps(self) -> None:
        d1 = _make_resolved_dep("a")
        d2 = _make_resolved_dep("b")
        g = ResolvedGraph(deps=(d1, d2))
        assert len(g.deps) == 2


# ---------------------------------------------------------------------------
# 4b — parse_lockfile: happy paths
# ---------------------------------------------------------------------------


class TestParseLockfileHappy:
    def test_minimal_lockfile_no_deps(self) -> None:
        lf = parse_lockfile(_MINIMAL_LOCKFILE)
        assert lf.version == 1
        assert lf.strategy == "maxver"
        assert lf.deps == ()

    def test_strategy_override(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "minver"
"""
        lf = parse_lockfile(text)
        assert lf.strategy == "minver"

    def test_strategy_absent_defaults_maxver(self) -> None:
        """Pre-v1.0 lockfiles may omit the strategy node — must default maxver."""
        text = """\
// generated by milpa; reproducible build snapshot
version 1
"""
        lf = parse_lockfile(text)
        assert lf.strategy == "maxver"

    def test_git_dep_full(self) -> None:
        lf = parse_lockfile(_FULL_GIT_DEP)
        assert len(lf.deps) == 1
        dep = lf.deps[0]
        assert dep.name == "foo"
        assert dep.identity == _VALID_IDENTITY
        assert dep.version == "1.2.3"
        assert dep.src_dir == "src"
        assert dep.requires == ("bar", "baz")
        prov = dep.provenances[0]
        assert isinstance(prov, GitProvenanceRecord)
        assert prov.url == "https://github.com/example/foo.git"
        assert prov.ref == "main"
        assert prov.commit_sha == "deadbeef1234567890deadbeef1234567890dead"

    def test_git_dep_optional_fields_absent(self) -> None:
        text = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {{
    identity "{_VALID_IDENTITY}"
    version "1.0.0"
    src_dir ""
    requires
    provenance {{
        kind "git"
        url "https://example.com/foo.git"
    }}
}}
"""
        lf = parse_lockfile(text)
        prov = lf.deps[0].provenances[0]
        assert isinstance(prov, GitProvenanceRecord)
        assert prov.ref is None
        assert prov.commit_sha is None

    def test_tarball_dep_with_sha256(self) -> None:
        text = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "zlib" {{
    identity "{_VALID_IDENTITY}"
    version "0.0.1"
    src_dir ""
    requires
    provenance {{
        kind "tarball"
        url "https://example.com/zlib.tar.gz"
        sha256 "abc123def456"
    }}
}}
"""
        lf = parse_lockfile(text)
        prov = lf.deps[0].provenances[0]
        assert isinstance(prov, TarballProvenanceRecord)
        assert prov.url == "https://example.com/zlib.tar.gz"
        assert prov.sha256 == "abc123def456"

    def test_tarball_dep_no_sha256(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "zlib" {
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "tarball"
        url "https://example.com/zlib.tar.gz"
    }
}
"""
        lf = parse_lockfile(text)
        prov = lf.deps[0].provenances[0]
        assert isinstance(prov, TarballProvenanceRecord)
        assert prov.sha256 is None

    def test_local_dep(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "locallib" {
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "local"
        path "../locallib"
    }
}
"""
        lf = parse_lockfile(text)
        prov = lf.deps[0].provenances[0]
        assert isinstance(prov, LocalProvenanceRecord)
        assert prov.path == "../locallib"

    def test_member_dep(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "mylib" {
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "member"
        name "mylib"
    }
}
"""
        lf = parse_lockfile(text)
        prov = lf.deps[0].provenances[0]
        assert isinstance(prov, MemberProvenanceRecord)
        assert prov.name == "mylib"

    def test_oci_dep(self) -> None:
        text = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "myimg" {{
    identity "{_VALID_IDENTITY}"
    version "0.0.1"
    src_dir ""
    requires
    provenance {{
        kind "oci"
        registry "ghcr.io"
        repository "example/myimg"
        digest "sha256:abcdef"
    }}
}}
"""
        lf = parse_lockfile(text)
        prov = lf.deps[0].provenances[0]
        assert isinstance(prov, OciProvenanceRecord)
        assert prov.registry == "ghcr.io"
        assert prov.repository == "example/myimg"
        assert prov.digest == "sha256:abcdef"

    def test_registry_dep_read_compat(self) -> None:
        """Read-compat: registry provenance kind must still parse."""
        text = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {{
    identity "{_VALID_IDENTITY}"
    version "1.0.0"
    src_dir ""
    requires
    provenance {{
        kind "registry"
        name "foo"
        tag "v1.0.0"
        commit_sha "abcdef1234567890abcdef1234567890abcdef12"
    }}
}}
"""
        lf = parse_lockfile(text)
        prov = lf.deps[0].provenances[0]
        assert isinstance(prov, RegistryProvenanceRecord)
        assert prov.name == "foo"
        assert prov.tag == "v1.0.0"

    def test_self_mirrors_plain_string(self) -> None:
        text = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {{
    identity "{_VALID_IDENTITY}"
    version "1.0.0"
    src_dir ""
    requires
    self_mirrors "https://mirror.example.com/foo.git"
    provenance {{
        kind "git"
        url "https://github.com/example/foo.git"
    }}
}}
"""
        lf = parse_lockfile(text)
        assert lf.deps[0].self_mirrors == ("https://mirror.example.com/foo.git",)

    def test_self_mirrors_url_annotated(self) -> None:
        text = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {{
    identity "{_VALID_IDENTITY}"
    version "1.0.0"
    src_dir ""
    requires
    self_mirrors (url)"https://mirror.example.com/foo.git"
    provenance {{
        kind "git"
        url "https://github.com/example/foo.git"
    }}
}}
"""
        lf = parse_lockfile(text)
        assert lf.deps[0].self_mirrors == ("https://mirror.example.com/foo.git",)

    def test_identity_absent_is_none(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "git"
        url "https://example.com/foo.git"
    }
}
"""
        lf = parse_lockfile(text)
        assert lf.deps[0].identity is None

    def test_version_absent_defaults_zero(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {
    src_dir ""
    requires
    provenance {
        kind "git"
        url "https://example.com/foo.git"
    }
}
"""
        lf = parse_lockfile(text)
        assert lf.deps[0].version == "0.0.0"

    def test_active_flags_parsed(self) -> None:
        text = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {{
    identity "{_VALID_IDENTITY}"
    version "1.0.0"
    src_dir ""
    requires
    active_flags "ssl" "threads"
    provenance {{
        kind "git"
        url "https://example.com/foo.git"
    }}
}}
"""
        lf = parse_lockfile(text)
        assert lf.deps[0].active_flags == ("ssl", "threads")

    def test_multiple_deps_preserves_order(self) -> None:
        text = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "zebra" {{
    identity "{_VALID_IDENTITY}"
    version "1.0.0"
    src_dir ""
    requires
    provenance {{
        kind "git"
        url "https://example.com/zebra.git"
    }}
}}

dep "apple" {{
    identity "{_VALID_IDENTITY}"
    version "2.0.0"
    src_dir ""
    requires
    provenance {{
        kind "git"
        url "https://example.com/apple.git"
    }}
}}
"""
        lf = parse_lockfile(text)
        assert [d.name for d in lf.deps] == ["zebra", "apple"]


# ---------------------------------------------------------------------------
# 4b — parse_lockfile: error paths (LOCK-* slugs)
# ---------------------------------------------------------------------------


class TestParseLockfileErrors:
    def _raises(self, slug: str, text: str) -> MilpaError:
        with pytest.raises(MilpaError) as exc_info:
            parse_lockfile(text)
        err = exc_info.value
        assert err.slug == slug, (
            f"Expected slug {slug!r}, got {err.slug!r}\n  message: {err.message}"
        )
        return err

    # LOCK-KDL-SYNTAX (fixture-066)
    def test_kdl_syntax_error(self) -> None:
        text = (_fixture("fixture-066-lock-kdl-syntax") / "milpa.lock").read_text()
        self._raises(LOCK_KDL_SYNTAX, text)

    # LOCK-VERSION-MISSING (fixture-067)
    def test_version_missing(self) -> None:
        text = (_fixture("fixture-067-lock-version-missing") / "milpa.lock").read_text()
        self._raises(LOCK_VERSION_MISSING, text)

    # LOCK-VERSION-UNSUPPORTED (fixture-068)
    def test_version_unsupported(self) -> None:
        text = (_fixture("fixture-068-lock-version-unsupported") / "milpa.lock").read_text()
        self._raises(LOCK_VERSION_UNSUPPORTED, text)

    # LOCK-FIELD-TYPE (fixture-070)
    def test_field_type_version_not_int(self) -> None:
        text = (_fixture("fixture-070-lock-field-type") / "milpa.lock").read_text()
        self._raises(LOCK_FIELD_TYPE, text)

    # LOCK-FIELD-ARITY — version with wrong arity (inline, no corpus fixture)
    def test_field_arity_version_no_args(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version
strategy "maxver"
"""
        self._raises(LOCK_FIELD_ARITY, text)

    # LOCK-DEP-NAME-ARITY (fixture-071)
    def test_dep_name_arity_missing(self) -> None:
        text = (_fixture("fixture-071-lock-dep-name-arity") / "milpa.lock").read_text()
        self._raises(LOCK_DEP_NAME_ARITY, text)

    # LOCK-DEP-FIELD-ARITY (fixture-072)
    def test_dep_field_arity_extra_arg(self) -> None:
        text = (_fixture("fixture-072-lock-dep-field-arity") / "milpa.lock").read_text()
        self._raises(LOCK_DEP_FIELD_ARITY, text)

    # LOCK-DEP-IDENTITY-INVALID (fixture-073)
    def test_dep_identity_invalid(self) -> None:
        text = (_fixture("fixture-073-lock-dep-identity-invalid") / "milpa.lock").read_text()
        self._raises(LOCK_DEP_IDENTITY_INVALID, text)

    def test_dep_identity_invalid_bad_algorithm(self) -> None:
        text = f"""\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {{
    identity "md5:{"a" * 32}"
    version "0.0.1"
    src_dir ""
    requires
    provenance {{
        kind "git"
        url "https://example.com/foo.git"
    }}
}}
"""
        self._raises(LOCK_DEP_IDENTITY_INVALID, text)

    def test_dep_identity_invalid_wrong_length(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {
    identity "sha256:abc"
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "git"
        url "https://example.com/foo.git"
    }
}
"""
        self._raises(LOCK_DEP_IDENTITY_INVALID, text)

    # LOCK-PROV-KIND-MISSING (fixture-075)
    def test_prov_kind_missing(self) -> None:
        text = (_fixture("fixture-075-lock-prov-kind-missing") / "milpa.lock").read_text()
        self._raises(LOCK_PROV_KIND_MISSING, text)

    # LOCK-PROV-KIND-UNKNOWN (fixture-076)
    def test_prov_kind_unknown(self) -> None:
        text = (_fixture("fixture-076-lock-prov-kind-unknown") / "milpa.lock").read_text()
        self._raises(LOCK_PROV_KIND_UNKNOWN, text)

    # LOCK-PROV-FIELD-MISSING (fixture-077)
    def test_prov_field_missing_url(self) -> None:
        text = (_fixture("fixture-077-lock-prov-field-missing") / "milpa.lock").read_text()
        self._raises(LOCK_PROV_FIELD_MISSING, text)

    def test_prov_field_missing_oci_registry(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "oci"
        repository "example/foo"
        digest "sha256:abc"
    }
}
"""
        self._raises(LOCK_PROV_FIELD_MISSING, text)

    def test_prov_field_missing_oci_repository(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "oci"
        registry "ghcr.io"
        digest "sha256:abc"
    }
}
"""
        self._raises(LOCK_PROV_FIELD_MISSING, text)

    def test_prov_field_missing_oci_digest(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "oci"
        registry "ghcr.io"
        repository "example/foo"
    }
}
"""
        self._raises(LOCK_PROV_FIELD_MISSING, text)

    def test_prov_field_arity_wrong(self) -> None:
        text = """\
// generated by milpa; reproducible build snapshot
version 1
strategy "maxver"

dep "foo" {
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "git" "extra"
        url "https://example.com/foo.git"
    }
}
"""
        self._raises(LOCK_PROV_FIELD_ARITY, text)


# ---------------------------------------------------------------------------
# 4b — Property tests: parse round-trips
# ---------------------------------------------------------------------------

# Strategies for Hypothesis
_safe_str = st.text(
    alphabet=st.characters(
        whitelist_categories=("Lu", "Ll", "Nd"),
        whitelist_characters="/_-.@",
    ),
    min_size=1,
    max_size=20,
)
_dep_name_st = st.from_regex(r"[a-z][a-z0-9_-]{0,15}", fullmatch=True)
_sha256_st = st.just("a" * 64)
_version_st = st.from_regex(r"[0-9]+\.[0-9]+\.[0-9]+", fullmatch=True)
_url_st = st.just("https://example.com/foo.git")
_src_dir_st = st.one_of(st.just(""), st.just("src"), st.just("lib"))


def _make_simple_lockfile(deps: list[tuple[str, str, str, str]]) -> str:
    """Build a minimal lockfile text with git deps."""
    lines = [
        "// generated by milpa; reproducible build snapshot",
        "version 1",
        'strategy "maxver"',
        "",
    ]
    for name, version, src_dir, identity in deps:
        lines.append(f'dep "{name}" {{')
        lines.append(f'    identity "sha256:{identity}"')
        lines.append(f'    version "{version}"')
        lines.append(f'    src_dir "{src_dir}"')
        lines.append("    requires")
        lines.append("    provenance {")
        lines.append('        kind "git"')
        lines.append('        url "https://example.com/foo.git"')
        lines.append("    }")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


@given(
    name=_dep_name_st,
    version=_version_st,
    src_dir=_src_dir_st,
    sha=_sha256_st,
)
@settings(max_examples=50)
def test_parse_roundtrip_single_git_dep(
    name: str,
    version: str,
    src_dir: str,
    sha: str,
) -> None:
    """A lockfile with a single git dep parses correctly."""
    text = _make_simple_lockfile([(name, version, src_dir, sha)])
    lf = parse_lockfile(text)
    assert len(lf.deps) == 1
    dep = lf.deps[0]
    assert dep.name == name
    assert dep.version == version
    assert dep.src_dir == src_dir
    assert dep.identity == f"sha256:{sha}"


@given(
    names=st.lists(
        _dep_name_st, min_size=1, max_size=5, unique=True
    ),
)
@settings(max_examples=30)
def test_parse_multiple_deps_returns_all(names: list[str]) -> None:
    """Multiple dep blocks all parse."""
    text = _make_simple_lockfile([(n, "1.0.0", "", "a" * 64) for n in names])
    lf = parse_lockfile(text)
    assert len(lf.deps) == len(names)
    parsed_names = {d.name for d in lf.deps}
    assert parsed_names == set(names)


# ---------------------------------------------------------------------------
# 4c — _kdl_str escaper (SSOT)
# ---------------------------------------------------------------------------


class TestKdlStr:
    def test_simple_string(self) -> None:
        assert _kdl_str("hello") == '"hello"'

    def test_escapes_backslash(self) -> None:
        assert _kdl_str("a\\b") == '"a\\\\b"'

    def test_escapes_double_quote(self) -> None:
        assert _kdl_str('a"b') == '"a\\"b"'

    def test_escapes_both(self) -> None:
        assert _kdl_str('v1"x\\y') == '"v1\\"x\\\\y"'

    def test_escapes_control_chars(self) -> None:
        # U+0000 → \u{0}, U+0001 → \u{1}, U+001f → \u{1f}
        assert _kdl_str("\x00") == '"\\u{0}"'
        assert _kdl_str("\x01") == '"\\u{1}"'
        assert _kdl_str("\x1f") == '"\\u{1f}"'

    def test_newline_is_control_char(self) -> None:
        assert _kdl_str("\n") == '"\\u{a}"'

    def test_tab_is_control_char(self) -> None:
        assert _kdl_str("\t") == '"\\u{9}"'

    def test_non_ascii_passthrough(self) -> None:
        # Characters above U+001F and below U+0080 are verbatim;
        # non-ASCII unicode (≥ U+0020) also verbatim
        assert _kdl_str("héllo") == '"héllo"'

    def test_empty_string(self) -> None:
        assert _kdl_str("") == '""'


# ---------------------------------------------------------------------------
# 4c — from_graph + format_lockfile
# ---------------------------------------------------------------------------


class TestFromGraph:
    def _git_prov(
        self,
        url: str = "https://example.com/foo.git",
        ref: str | None = None,
        sha: str | None = None,
    ) -> GitProvenanceRecord:
        return GitProvenanceRecord(url=url, ref=ref, commit_sha=sha)

    def test_empty_graph(self) -> None:
        g = ResolvedGraph(deps=())
        lf = from_graph(g)
        assert lf.deps == ()
        assert lf.strategy == "maxver"

    def test_single_dep(self) -> None:
        prov = self._git_prov(ref="main", sha="dead" * 10)
        d = _make_resolved_dep("foo", version="1.0.0", provenance=prov)
        g = ResolvedGraph(deps=(d,))
        lf = from_graph(g)
        assert len(lf.deps) == 1
        dep = lf.deps[0]
        assert dep.name == "foo"
        assert dep.version == "1.0.0"

    def test_deps_sorted_lexicographically(self) -> None:
        deps = tuple(
            _make_resolved_dep(n, provenance=self._git_prov())
            for n in ["zebra", "apple", "mango"]
        )
        g = ResolvedGraph(deps=deps)
        lf = from_graph(g)
        names = [d.name for d in lf.deps]
        assert names == ["apple", "mango", "zebra"]

    def test_requires_sorted_lexicographically(self) -> None:
        prov = self._git_prov()
        d = _make_resolved_dep("foo", requires=("zoo", "ant", "bee"), provenance=prov)
        g = ResolvedGraph(deps=(d,))
        lf = from_graph(g)
        assert lf.deps[0].requires == ("ant", "bee", "zoo")

    def test_strategy_passed_through(self) -> None:
        g = ResolvedGraph(deps=())
        lf = from_graph(g, strategy="minver")
        assert lf.strategy == "minver"

    def test_no_provenance_dep_gets_empty_provenances(self) -> None:
        d = _make_resolved_dep("foo", provenance=None)
        g = ResolvedGraph(deps=(d,))
        lf = from_graph(g)
        assert lf.deps[0].provenances == ()

    def test_active_flags_and_mirrors_passed_through(self) -> None:
        prov = self._git_prov()
        d = _make_resolved_dep(
            "foo",
            provenance=prov,
            active_flags=("ssl",),
            self_mirrors=("https://mirror.example.com/foo.git",),
        )
        g = ResolvedGraph(deps=(d,))
        lf = from_graph(g)
        dep = lf.deps[0]
        assert dep.active_flags == ("ssl",)
        assert dep.self_mirrors == ("https://mirror.example.com/foo.git",)


class TestFormatLockfile:
    def test_header_present(self) -> None:
        lf = Lockfile(deps=())
        text = format_lockfile(lf)
        assert text.startswith("// generated by milpa; reproducible build snapshot\n")

    def test_version_line(self) -> None:
        lf = Lockfile(deps=())
        text = format_lockfile(lf)
        assert "version 1\n" in text

    def test_strategy_line(self) -> None:
        lf = Lockfile(deps=(), strategy="maxver")
        text = format_lockfile(lf)
        assert 'strategy "maxver"\n' in text

    def test_empty_lockfile_ends_with_newline(self) -> None:
        lf = Lockfile(deps=())
        text = format_lockfile(lf)
        assert text.endswith("\n")

    def test_dep_block_present(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=_VALID_IDENTITY,
            version="1.0.0",
            src_dir="src",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert 'dep "foo" {' in text
        assert f'    identity "{_VALID_IDENTITY}"' in text
        assert '    version "1.0.0"' in text
        assert '    src_dir "src"' in text
        assert "    requires" in text

    def test_requires_args_quoted(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=("bar", "baz"),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '    requires "bar" "baz"' in text

    def test_active_flags_emitted(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
            active_flags=("ssl",),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '    active_flags "ssl"' in text

    def test_active_flags_absent_when_empty(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert "active_flags" not in text

    def test_self_mirrors_url_annotated(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
            self_mirrors=("https://mirror.example.com/foo.git",),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '    self_mirrors (url)"https://mirror.example.com/foo.git"' in text

    def test_self_mirrors_absent_when_empty(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert "self_mirrors" not in text

    def test_identity_absent_when_none(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert "identity" not in text

    def test_dep_block_followed_by_blank_line(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert text.endswith("}\n")

    def test_tarball_provenance_emitted(self) -> None:
        prov = TarballProvenanceRecord(
            url="https://example.com/zlib.tar.gz",
            sha256="abc123",
        )
        dep = LockedDep(
            name="zlib",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '        kind "tarball"' in text
        assert '        url "https://example.com/zlib.tar.gz"' in text
        assert '        sha256 "abc123"' in text

    def test_tarball_sha256_absent_when_none(self) -> None:
        prov = TarballProvenanceRecord(url="https://example.com/zlib.tar.gz")
        dep = LockedDep(
            name="zlib",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert "sha256" not in text

    def test_local_provenance_emitted(self) -> None:
        prov = LocalProvenanceRecord(path="../locallib")
        dep = LockedDep(
            name="locallib",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '        kind "local"' in text
        assert '        path "../locallib"' in text

    def test_member_provenance_emitted(self) -> None:
        prov = MemberProvenanceRecord(name="mylib")
        dep = LockedDep(
            name="mylib",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '        kind "member"' in text
        assert '        name "mylib"' in text

    def test_oci_provenance_emitted(self) -> None:
        prov = OciProvenanceRecord(
            registry="ghcr.io",
            repository="example/foo",
            digest="sha256:abcdef",
        )
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '        kind "oci"' in text
        assert '        registry "ghcr.io"' in text
        assert '        repository "example/foo"' in text
        assert '        digest "sha256:abcdef"' in text

    def test_git_optional_fields_absent_when_none(self) -> None:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=None,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert "ref" not in text
        assert "commit_sha" not in text


# ---------------------------------------------------------------------------
# 4c — Fixture-118 byte-exact gate
#
# Spec-canonical test: hand-craft a ResolvedGraph whose dep's ref carries
# both `"` and `\`, call from_graph + format_lockfile, and assert byte-equality
# against conformance/spec-v1/fixture-118-lock-string-escaping/expected/milpa.lock.
# ---------------------------------------------------------------------------


class TestFixture118ByteExact:
    _FIXTURE_PATH = _fixture("fixture-118-lock-string-escaping") / "expected" / "milpa.lock"

    def test_fixture_118_byte_exact(self) -> None:
        """format_lockfile must produce the exact bytes of fixture-118/expected/milpa.lock."""
        # The fixture's manifest declares:
        #   foo git=(url)"https://github.com/example/foo.git" ref="v1\"x\\y"
        # After KDL unescaping: ref = v1"x\y
        # The mocked-fetch entry provides:
        #   sha = abcdef1234567890abcdef1234567890abcdef12
        #   identity = sha256:19f1b5dadf5a74f44e39f7403a519a8a560fbd61b97425d4ade643ee4a52fa59
        #   nimble: version = "1.0.0", srcDir = "src"
        prov = GitProvenanceRecord(
            url="https://github.com/example/foo.git",
            ref='v1"x\\y',                          # literal double-quote + backslash
            commit_sha="abcdef1234567890abcdef1234567890abcdef12",
        )
        dep = ResolvedDep(
            name="foo",
            identity="sha256:19f1b5dadf5a74f44e39f7403a519a8a560fbd61b97425d4ade643ee4a52fa59",
            version="0.0.1",
            src_dir="src",
            requires=(),
            provenance=prov,
        )
        graph = ResolvedGraph(deps=(dep,))
        lf = from_graph(graph, strategy="maxver")
        got = format_lockfile(lf)

        expected = self._FIXTURE_PATH.read_text()
        assert got == expected, (
            f"Byte-exact mismatch with fixture-118.\n"
            f"Expected ({len(expected)} chars):\n{expected!r}\n\n"
            f"Got ({len(got)} chars):\n{got!r}"
        )

    def test_fixture_118_round_trips(self) -> None:
        """Parsing the fixture-118 expected lockfile recovers the ref with escapes intact."""
        expected = self._FIXTURE_PATH.read_text()
        lf = parse_lockfile(expected)
        dep = lf.deps[0]
        prov = dep.provenances[0]
        assert isinstance(prov, GitProvenanceRecord)
        # KDL unescaping: `v1\"x\\y` → v1"x\y
        assert prov.ref == 'v1"x\\y', f"Expected 'v1\"x\\\\y', got {prov.ref!r}"

    def test_format_parse_round_trip(self) -> None:
        """from_graph → format_lockfile → parse_lockfile is identity."""
        prov = GitProvenanceRecord(
            url="https://github.com/example/foo.git",
            ref='v1"x\\y',
            commit_sha="abcdef1234567890abcdef1234567890abcdef12",
        )
        dep = ResolvedDep(
            name="foo",
            identity="sha256:19f1b5dadf5a74f44e39f7403a519a8a560fbd61b97425d4ade643ee4a52fa59",
            version="0.0.1",
            src_dir="src",
            requires=(),
            provenance=prov,
        )
        graph = ResolvedGraph(deps=(dep,))
        lf = from_graph(graph, strategy="maxver")
        text = format_lockfile(lf)
        lf2 = parse_lockfile(text)
        assert len(lf2.deps) == 1
        dep2 = lf2.deps[0]
        prov2 = dep2.provenances[0]
        assert isinstance(prov2, GitProvenanceRecord)
        assert prov2.ref == 'v1"x\\y'


# ---------------------------------------------------------------------------
# 4c — Property tests: from_graph → format_lockfile → parse_lockfile round-trip
# ---------------------------------------------------------------------------

_prov_st = st.just(
    GitProvenanceRecord(url="https://example.com/foo.git", ref="main")
)
_resolved_dep_st = st.builds(
    ResolvedDep,
    name=_dep_name_st,
    identity=st.just(_VALID_IDENTITY),
    version=_version_st,
    src_dir=_src_dir_st,
    requires=st.just(()),
    provenance=_prov_st,
)


@given(
    deps=st.lists(_resolved_dep_st, min_size=0, max_size=4, unique_by=lambda d: d.name)
)
@settings(max_examples=50)
def test_from_graph_format_parse_roundtrip(deps: list[ResolvedDep]) -> None:
    """from_graph → format_lockfile → parse_lockfile → names/versions/identities preserved."""
    graph = ResolvedGraph(deps=tuple(deps))
    lf = from_graph(graph)
    text = format_lockfile(lf)
    lf2 = parse_lockfile(text)
    assert len(lf2.deps) == len(deps)
    names1 = {d.name for d in lf.deps}
    names2 = {d.name for d in lf2.deps}
    assert names1 == names2


@given(
    deps=st.lists(_resolved_dep_st, min_size=0, max_size=4, unique_by=lambda d: d.name)
)
@settings(max_examples=30)
def test_format_lockfile_deterministic(deps: list[ResolvedDep]) -> None:
    """Same graph always produces identical bytes."""
    graph = ResolvedGraph(deps=tuple(deps))
    lf = from_graph(graph)
    t1 = format_lockfile(lf)
    t2 = format_lockfile(lf)
    assert t1 == t2


# ---------------------------------------------------------------------------
# 4e — verify_against_graph
# ---------------------------------------------------------------------------


class TestVerifyAgainstGraph:
    def _make_lockfile_with(self, name: str, identity: str | None) -> Lockfile:
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name=name,
            identity=identity,
            version="1.0.0",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        return Lockfile(deps=(dep,))

    def _make_graph_with(self, name: str, identity: str | None) -> ResolvedGraph:
        d = ResolvedDep(
            name=name,
            identity=identity,
            version="1.0.0",
            src_dir="",
            requires=(),
        )
        return ResolvedGraph(deps=(d,))

    def test_matching_graph_and_lock_succeeds(self) -> None:
        lf = self._make_lockfile_with("foo", _VALID_IDENTITY)
        g = self._make_graph_with("foo", _VALID_IDENTITY)
        verify_against_graph(lf, g)  # must not raise

    def test_empty_both_succeeds(self) -> None:
        lf = Lockfile(deps=())
        g = ResolvedGraph(deps=())
        verify_against_graph(lf, g)

    def test_dep_in_graph_not_in_lock_raises(self) -> None:
        lf = Lockfile(deps=())
        g = self._make_graph_with("foo", _VALID_IDENTITY)
        with pytest.raises(MilpaError) as exc_info:
            verify_against_graph(lf, g)
        assert exc_info.value.slug == LOCK_GRAPH_MISMATCH
        assert "foo" in exc_info.value.message

    def test_dep_in_lock_not_in_graph_raises(self) -> None:
        lf = self._make_lockfile_with("foo", _VALID_IDENTITY)
        g = ResolvedGraph(deps=())
        with pytest.raises(MilpaError) as exc_info:
            verify_against_graph(lf, g)
        assert exc_info.value.slug == LOCK_GRAPH_MISMATCH
        assert "foo" in exc_info.value.message

    def test_identity_mismatch_raises(self) -> None:
        lf = self._make_lockfile_with("foo", _VALID_IDENTITY)
        other_identity = f"sha256:{'b' * 64}"
        g = self._make_graph_with("foo", other_identity)
        with pytest.raises(MilpaError) as exc_info:
            verify_against_graph(lf, g)
        assert exc_info.value.slug == LOCK_GRAPH_MISMATCH

    def test_none_identity_matches_none(self) -> None:
        lf = self._make_lockfile_with("foo", None)
        g = self._make_graph_with("foo", None)
        verify_against_graph(lf, g)  # must not raise

    def test_multiple_errors_collected(self) -> None:
        """All mismatches are reported, not just the first."""
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep1 = LockedDep(
            name="foo",
            identity=_VALID_IDENTITY,
            version="1.0.0",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        dep2 = LockedDep(
            name="bar",
            identity=_VALID_IDENTITY,
            version="1.0.0",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep1, dep2))
        # Graph has neither foo nor bar; has baz instead
        g = ResolvedGraph(
            deps=(
                ResolvedDep(
                    name="baz",
                    identity=_VALID_IDENTITY,
                    version="1.0.0",
                    src_dir="",
                    requires=(),
                ),
            )
        )
        with pytest.raises(MilpaError) as exc_info:
            verify_against_graph(lf, g)
        err = exc_info.value
        assert err.slug == LOCK_GRAPH_MISMATCH
        # Multiple dep names should appear in the message
        msg = err.message
        assert "foo" in msg or "bar" in msg or "baz" in msg


# ---------------------------------------------------------------------------
# 4e — Property tests: verify_against_graph
# ---------------------------------------------------------------------------


@given(
    deps=st.lists(_resolved_dep_st, min_size=0, max_size=4, unique_by=lambda d: d.name)
)
@settings(max_examples=40)
def test_verify_against_graph_roundtrip(deps: list[ResolvedDep]) -> None:
    """from_graph then verify_against_graph with same graph must not raise."""
    graph = ResolvedGraph(deps=tuple(deps))
    lf = from_graph(graph)
    verify_against_graph(lf, graph)  # must not raise


# ---------------------------------------------------------------------------
# 4e — verify_lockfile_against_deps (filesystem)
# ---------------------------------------------------------------------------


class TestVerifyLockfileAgainstDeps:
    def test_empty_lockfile_no_deps_dir(self, tmp_path: Path) -> None:
        deps_dir = tmp_path / "_deps"
        # No _deps/ dir: no deps, no divergences
        lf = Lockfile(deps=())
        result = verify_lockfile_against_deps(lf, deps_dir)
        assert result == []

    def test_missing_dep_reported(self, tmp_path: Path) -> None:
        deps_dir = tmp_path / "_deps"
        deps_dir.mkdir()
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=_VALID_IDENTITY,
            version="1.0.0",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        result = verify_lockfile_against_deps(lf, deps_dir)
        assert len(result) == 1
        assert "foo" in result[0]
        assert "missing" in result[0]

    def test_extra_dep_in_deps_dir_reported(self, tmp_path: Path) -> None:
        deps_dir = tmp_path / "_deps"
        deps_dir.mkdir()
        extra = deps_dir / "extra"
        extra.mkdir()
        lf = Lockfile(deps=())
        result = verify_lockfile_against_deps(lf, deps_dir)
        assert len(result) == 1
        assert "extra" in result[0]

    def test_hidden_entries_ignored(self, tmp_path: Path) -> None:
        deps_dir = tmp_path / "_deps"
        deps_dir.mkdir()
        hidden = deps_dir / ".hidden"
        hidden.mkdir()
        lf = Lockfile(deps=())
        result = verify_lockfile_against_deps(lf, deps_dir)
        assert result == []

    def test_dep_not_a_directory_reported(self, tmp_path: Path) -> None:
        deps_dir = tmp_path / "_deps"
        deps_dir.mkdir()
        (deps_dir / "foo").write_text("not a dir")
        prov = GitProvenanceRecord(url="https://example.com/foo.git")
        dep = LockedDep(
            name="foo",
            identity=_VALID_IDENTITY,
            version="1.0.0",
            src_dir="",
            requires=(),
            provenances=(prov,),
        )
        lf = Lockfile(deps=(dep,))
        result = verify_lockfile_against_deps(lf, deps_dir)
        assert len(result) == 1
        assert "foo" in result[0]

    def test_all_divergences_collected(self, tmp_path: Path) -> None:
        """All mismatches are collected (not fail-fast)."""
        deps_dir = tmp_path / "_deps"
        deps_dir.mkdir()

        def _make_dep(name: str) -> LockedDep:
            prov = GitProvenanceRecord(url="https://example.com/foo.git")
            return LockedDep(
                name=name,
                identity=_VALID_IDENTITY,
                version="1.0.0",
                src_dir="",
                requires=(),
                provenances=(prov,),
            )

        lf = Lockfile(deps=(_make_dep("foo"), _make_dep("bar")))
        result = verify_lockfile_against_deps(lf, deps_dir)
        # Both foo and bar should be reported as missing
        assert len(result) == 2
        names_in_report = {r.split(":")[0] for r in result}
        assert "foo" in names_in_report
        assert "bar" in names_in_report


# ---------------------------------------------------------------------------
# S4 — CondRequire data model + formatter + parser + round-trip
# (RFC rfc-conditional-requires.md §3.4 / §3.4.1 / §3.4.2 / §3.4.3)
# ---------------------------------------------------------------------------


def _make_prov() -> GitProvenanceRecord:
    return GitProvenanceRecord(url="https://example.com/foo.git")


def _make_dep_with_cond(
    name: str = "qux",
    requires: tuple[str, ...] = ("bar", "extra"),
    cond_requires: tuple[CondRequire, ...] = (),
) -> LockedDep:
    return LockedDep(
        name=name,
        identity=_VALID_IDENTITY,
        version="1.0.0",
        src_dir="src",
        requires=requires,
        provenances=(_make_prov(),),
        cond_requires=cond_requires,
    )


class TestCondRequireDataModel:
    """Cycle 1: CondRequire / LockedDep.cond_requires data model + equality."""

    def test_cond_require_equality(self) -> None:
        p = Predicate(name="platform", values=("linux",), negated=False)
        cr1 = CondRequire(name="extra", predicates=(p,))
        cr2 = CondRequire(name="extra", predicates=(p,))
        assert cr1 == cr2

    def test_cond_require_inequality_name(self) -> None:
        p = Predicate(name="platform", values=("linux",), negated=False)
        cr1 = CondRequire(name="extra", predicates=(p,))
        cr2 = CondRequire(name="other", predicates=(p,))
        assert cr1 != cr2

    def test_cond_require_inequality_predicates(self) -> None:
        p1 = Predicate(name="platform", values=("linux",), negated=False)
        p2 = Predicate(name="platform", values=("macosx",), negated=False)
        cr1 = CondRequire(name="extra", predicates=(p1,))
        cr2 = CondRequire(name="extra", predicates=(p2,))
        assert cr1 != cr2

    def test_locked_dep_cond_requires_default_empty(self) -> None:
        dep = _make_dep_with_cond()
        assert dep.cond_requires == ()

    def test_locked_dep_cond_requires_set(self) -> None:
        p = Predicate(name="platform", values=("linux",), negated=False)
        cr = CondRequire(name="extra", predicates=(p,))
        dep = _make_dep_with_cond(cond_requires=(cr,))
        assert dep.cond_requires == (cr,)

    def test_locked_dep_equality_respects_cond_requires(self) -> None:
        p = Predicate(name="platform", values=("linux",), negated=False)
        cr = CondRequire(name="extra", predicates=(p,))
        dep1 = _make_dep_with_cond(cond_requires=(cr,))
        dep2 = _make_dep_with_cond(cond_requires=())
        assert dep1 != dep2

    def test_resolved_dep_cond_requires_default_empty(self) -> None:
        rd = ResolvedDep(
            name="foo",
            identity=_VALID_IDENTITY,
            version="1.0.0",
            src_dir="",
            requires=(),
        )
        assert rd.cond_requires == ()


class TestCondRequireFormatter:
    """Cycle 2: byte-exact emission of each canonical cond-require shape."""

    def test_no_cond_requires_emits_nothing_new(self) -> None:
        """Dep with empty cond_requires → output identical to pre-S4 (requires line unchanged)."""
        dep = _make_dep_with_cond(requires=("bar",), cond_requires=())
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert "cond-require" not in text
        assert '    requires "bar"' in text

    def test_single_predicate_inline_not_negated(self) -> None:
        """cond-require "extra" platform="linux" — inline form."""
        p = Predicate(name="platform", values=("linux",), negated=False)
        cr = CondRequire(name="extra", predicates=(p,))
        dep = _make_dep_with_cond(cond_requires=(cr,))
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '    cond-require "extra" platform="linux"' in text

    def test_single_predicate_inline_negated(self) -> None:
        """cond-require "extra" platform=(not)"linux" — negated form."""
        p = Predicate(name="platform", values=("linux",), negated=True)
        cr = CondRequire(name="extra", predicates=(p,))
        dep = _make_dep_with_cond(cond_requires=(cr,))
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '    cond-require "extra" platform=(not)"linux"' in text

    def test_single_nim_predicate(self) -> None:
        """cond-require "extra" nim=">=1.4.0" — nim version predicate."""
        p = Predicate(name="nim", values=(">=1.4.0",), negated=False)
        cr = CondRequire(name="extra", predicates=(p,))
        dep = _make_dep_with_cond(cond_requires=(cr,))
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        assert '    cond-require "extra" nim=">=1.4.0"' in text

    def test_multi_predicate_block_form(self) -> None:
        """Multiple predicates → { when … } block form (pinned byte-exact)."""
        p1 = Predicate(name="platform", values=("macosx",), negated=False)
        p2 = Predicate(name="platform", values=("linux",), negated=True)
        cr = CondRequire(name="macstuff", predicates=(p1, p2))
        dep = _make_dep_with_cond(requires=("bar", "macstuff"), cond_requires=(cr,))
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        # Pinned exact block (RFC §3.4.1 canonical shape)
        expected_block = (
            '    cond-require "macstuff" {\n'
            '        when platform="macosx"\n'
            '        when platform=(not)"linux"\n'
            '    }'
        )
        assert expected_block in text

    def test_cond_require_after_requires_line(self) -> None:
        """cond-require nodes appear immediately after the requires line."""
        p = Predicate(name="platform", values=("linux",), negated=False)
        cr = CondRequire(name="extra", predicates=(p,))
        dep = _make_dep_with_cond(requires=("bar", "extra"), cond_requires=(cr,))
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        req_pos = text.index('    requires "bar" "extra"')
        cr_pos = text.index('    cond-require "extra"')
        assert cr_pos > req_pos

    def test_requires_line_unchanged_with_cond(self) -> None:
        """requires line is byte-identical whether or not cond_requires is set."""
        dep_no_cond = _make_dep_with_cond(requires=("bar", "extra"), cond_requires=())
        dep_with_cond = _make_dep_with_cond(
            requires=("bar", "extra"),
            cond_requires=(CondRequire(
                name="extra",
                predicates=(Predicate(name="platform", values=("linux",), negated=False),),
            ),),
        )
        text_no = format_lockfile(Lockfile(deps=(dep_no_cond,)))
        text_with = format_lockfile(Lockfile(deps=(dep_with_cond,)))
        # Both must contain the same requires line
        assert '    requires "bar" "extra"' in text_no
        assert '    requires "bar" "extra"' in text_with

    def test_multiple_cond_requires_sorted_by_name(self) -> None:
        """Multiple cond-requires are emitted in lexicographic name order."""
        pz = Predicate(name="platform", values=("linux",), negated=False)
        pa = Predicate(name="arch", values=("amd64",), negated=False)
        cr_z = CondRequire(name="zlib", predicates=(pz,))
        cr_a = CondRequire(name="asm", predicates=(pa,))
        # Pass in reverse order — emit must be sorted
        dep = _make_dep_with_cond(
            requires=("asm", "zlib"),
            cond_requires=(cr_z, cr_a),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        asm_pos = text.index('cond-require "asm"')
        zlib_pos = text.index('cond-require "zlib"')
        assert asm_pos < zlib_pos


class TestCondRequireParser:
    """Cycle 3: parse each canonical shape back to CondRequire/Predicate."""

    def _lockfile_with_dep(self, dep_body: str) -> str:
        return (
            "// generated by milpa; reproducible build snapshot\n"
            "version 1\n"
            'strategy "maxver"\n'
            "\n"
            f'dep "qux" {{\n'
            f"    identity \"{_VALID_IDENTITY}\"\n"
            f'    version "1.0.0"\n'
            f'    src_dir "src"\n'
            f'    requires "bar" "extra"\n'
            f"{dep_body}"
            f"    provenance {{\n"
            f'        kind "git"\n'
            f'        url "https://example.com/qux.git"\n'
            f"    }}\n"
            f"}}\n"
        )

    def test_inline_not_negated(self) -> None:
        """cond-require "extra" platform="linux" parses correctly."""
        text = self._lockfile_with_dep('    cond-require "extra" platform="linux"\n')
        lf = parse_lockfile(text)
        dep = lf.deps[0]
        assert len(dep.cond_requires) == 1
        cr = dep.cond_requires[0]
        assert cr.name == "extra"
        assert len(cr.predicates) == 1
        p = cr.predicates[0]
        assert p.name == "platform"
        assert p.values == ("linux",)
        assert p.negated is False

    def test_inline_negated(self) -> None:
        """cond-require "extra" platform=(not)"linux" parses negated=True."""
        text = self._lockfile_with_dep('    cond-require "extra" platform=(not)"linux"\n')
        lf = parse_lockfile(text)
        dep = lf.deps[0]
        assert len(dep.cond_requires) == 1
        cr = dep.cond_requires[0]
        p = cr.predicates[0]
        assert p.name == "platform"
        assert p.values == ("linux",)
        assert p.negated is True

    def test_block_multi_clause(self) -> None:
        """Block form with two when children parses to two-predicate CondRequire."""
        block = (
            '    cond-require "macstuff" {\n'
            '        when platform="macosx"\n'
            '        when platform=(not)"linux"\n'
            "    }\n"
        )
        text = self._lockfile_with_dep(block)
        lf = parse_lockfile(text)
        dep = lf.deps[0]
        assert len(dep.cond_requires) == 1
        cr = dep.cond_requires[0]
        assert cr.name == "macstuff"
        assert len(cr.predicates) == 2
        assert cr.predicates[0] == Predicate(name="platform", values=("macosx",), negated=False)
        assert cr.predicates[1] == Predicate(name="platform", values=("linux",), negated=True)

    def test_no_cond_require_nodes(self) -> None:
        """Dep with no cond-require child nodes → cond_requires == ()."""
        text = self._lockfile_with_dep("")
        lf = parse_lockfile(text)
        dep = lf.deps[0]
        assert dep.cond_requires == ()

    def test_requires_parsing_unchanged(self) -> None:
        """requires line is parsed correctly even when cond-require is present."""
        text = self._lockfile_with_dep('    cond-require "extra" platform="linux"\n')
        lf = parse_lockfile(text)
        dep = lf.deps[0]
        assert dep.requires == ("bar", "extra")


class TestCondRequireRoundTrip:
    """Cycle 4: parse(format(lf)) == lf and format(parse(text)) == text."""

    def test_round_trip_inline_single(self) -> None:
        """parse_lockfile(format_lockfile(lf)) == lf for inline single predicate."""
        p = Predicate(name="platform", values=("linux",), negated=False)
        cr = CondRequire(name="extra", predicates=(p,))
        dep = _make_dep_with_cond(cond_requires=(cr,))
        lf = Lockfile(deps=(dep,))
        parsed = parse_lockfile(format_lockfile(lf))
        assert parsed.deps[0].cond_requires == lf.deps[0].cond_requires

    def test_round_trip_negated(self) -> None:
        """Round-trip preserves negated=True."""
        p = Predicate(name="platform", values=("linux",), negated=True)
        cr = CondRequire(name="extra", predicates=(p,))
        dep = _make_dep_with_cond(cond_requires=(cr,))
        lf = Lockfile(deps=(dep,))
        parsed = parse_lockfile(format_lockfile(lf))
        assert parsed.deps[0].cond_requires[0].predicates[0].negated is True

    def test_round_trip_block_multi(self) -> None:
        """Round-trip preserves multi-predicate block form."""
        p1 = Predicate(name="platform", values=("macosx",), negated=False)
        p2 = Predicate(name="platform", values=("linux",), negated=True)
        cr = CondRequire(name="macstuff", predicates=(p1, p2))
        dep = _make_dep_with_cond(requires=("bar", "macstuff"), cond_requires=(cr,))
        lf = Lockfile(deps=(dep,))
        parsed = parse_lockfile(format_lockfile(lf))
        assert parsed.deps[0].cond_requires == lf.deps[0].cond_requires

    def test_format_parse_format_identity(self) -> None:
        """format(parse(text)) == text for a hand-written canonical sample."""
        # Pin the exact canonical text from the RFC §3.4.1 example.
        sample = (
            "// generated by milpa; reproducible build snapshot\n"
            "version 1\n"
            'strategy "maxver"\n'
            "\n"
            'dep "qux" {\n'
            f'    identity "{_VALID_IDENTITY}"\n'
            '    version "1.0.0"\n'
            '    src_dir "src"\n'
            '    requires "bar" "extra"\n'
            '    cond-require "extra" platform="linux"\n'
            "    provenance {\n"
            '        kind "git"\n'
            '        url "https://example.com/qux.git"\n'
            "    }\n"
            "}\n"
        )
        lf = parse_lockfile(sample)
        re_formatted = format_lockfile(lf)
        assert re_formatted == sample

    def test_format_parse_format_block_multi(self) -> None:
        """format(parse(text)) == text for a hand-written multi-clause block sample."""
        sample = (
            "// generated by milpa; reproducible build snapshot\n"
            "version 1\n"
            'strategy "maxver"\n'
            "\n"
            'dep "qux" {\n'
            f'    identity "{_VALID_IDENTITY}"\n'
            '    version "1.0.0"\n'
            '    src_dir "src"\n'
            '    requires "bar" "macstuff"\n'
            '    cond-require "macstuff" {\n'
            '        when platform="macosx"\n'
            '        when platform=(not)"linux"\n'
            "    }\n"
            "    provenance {\n"
            '        kind "git"\n'
            '        url "https://example.com/qux.git"\n'
            "    }\n"
            "}\n"
        )
        lf = parse_lockfile(sample)
        re_formatted = format_lockfile(lf)
        assert re_formatted == sample


    def test_same_name_two_cond_requires_round_trips(self) -> None:
        """LockedDep with two CondRequire of same name round-trips byte-identically.

        C1 fix: same dep in ≥2 when-branches → two CondRequire entries with the
        same name.  They must sort deterministically (by predicate string, not just
        name) and parse back to exactly the same two entries.
        """
        p_linux = Predicate(name="platform", values=("linux",), negated=False)
        p_mac = Predicate(name="platform", values=("macosx",), negated=False)
        cr_linux = CondRequire(name="foo", predicates=(p_linux,))
        cr_mac = CondRequire(name="foo", predicates=(p_mac,))
        dep = _make_dep_with_cond(
            requires=("foo",),
            # Pass in reverse order to verify sort is applied
            cond_requires=(cr_mac, cr_linux),
        )
        lf = Lockfile(deps=(dep,))
        text = format_lockfile(lf)
        # Both entries must appear
        assert text.count('cond-require "foo"') == 2
        # Round-trip: parse(format) must re-produce both CondRequire entries.
        # The emitter sorts by (name, predicate-string), so we compare against
        # the sorted order (not the original insertion order in lf.deps[0]).
        parsed = parse_lockfile(text)
        assert len(parsed.deps[0].cond_requires) == 2
        assert set(parsed.deps[0].cond_requires) == {cr_linux, cr_mac}

    def test_same_name_two_cond_requires_deterministic_sort(self) -> None:
        """Same-name CondRequire entries emit in predicate-string order (total sort key).

        Verifies that regardless of insertion order, the emitter always produces
        the same byte sequence when the logical content is identical.
        """
        p_linux = Predicate(name="platform", values=("linux",), negated=False)
        p_mac = Predicate(name="platform", values=("macosx",), negated=False)
        cr_linux = CondRequire(name="foo", predicates=(p_linux,))
        cr_mac = CondRequire(name="foo", predicates=(p_mac,))
        dep_order1 = _make_dep_with_cond(requires=("foo",), cond_requires=(cr_linux, cr_mac))
        dep_order2 = _make_dep_with_cond(requires=("foo",), cond_requires=(cr_mac, cr_linux))
        text1 = format_lockfile(Lockfile(deps=(dep_order1,)))
        text2 = format_lockfile(Lockfile(deps=(dep_order2,)))
        # Same logical content → byte-identical output regardless of cond_requires order
        assert text1 == text2


class TestEdgesetToTermsRequiresPredicates:
    """Cycle 5: edgeset_to_terms propagates predicates → requires_predicates dict."""

    def test_no_predicates_gives_empty_dict(self) -> None:
        from milpa.dep_decl import EdgeSet, EdgeSource, NamedRequire
        from milpa.edge_sources import edgeset_to_terms
        from milpa.version import Version

        V = Version(major=99, minor=0, patch=0, pre=[], build="")
        es = EdgeSet(
            requires=[NamedRequire(name="stew", constraint_str=">= 0.1.0")],
            src_dir="",
            source=EdgeSource.NIMBLE_FALLBACK,
        )
        _, _, requires_predicates = edgeset_to_terms(es, {}, V)
        assert requires_predicates == {}

    def test_predicate_bearing_entry_recorded(self) -> None:
        """NamedRequire with predicates → requires_predicates carries them.

        New shape (C1 fix): requires_predicates maps name → list[tuple[Predicate,...]]
        so that same-name entries in ≥2 branches accumulate rather than overwrite.
        """
        from milpa.dep_decl import EdgeSet, EdgeSource, NamedRequire
        from milpa.edge_sources import edgeset_to_terms
        from milpa.version import Version

        p = Predicate(name="platform", values=("linux",), negated=False)
        V = Version(major=99, minor=0, patch=0, pre=[], build="")
        es = EdgeSet(
            requires=[NamedRequire(name="extra", constraint_str="", predicates=(p,))],
            src_dir="",
            source=EdgeSource.NIMBLE_FALLBACK,
        )
        _, _, requires_predicates = edgeset_to_terms(es, {}, V)
        assert "extra" in requires_predicates
        # New shape: list of tuples (one per occurrence)
        assert requires_predicates["extra"] == [(p,)]

    def test_predicate_same_name_two_branches_accumulates(self) -> None:
        """Same dep name in two when branches → two predicate-tuples in the list.

        C1 root-cause fix: requires_predicates[name] is now a list so that
        same-name deps in different when-branches both record their predicates.
        """
        from milpa.dep_decl import EdgeSet, EdgeSource, NamedRequire
        from milpa.edge_sources import edgeset_to_terms
        from milpa.version import Version

        p_linux = Predicate(name="platform", values=("linux",), negated=False)
        p_mac = Predicate(name="platform", values=("macosx",), negated=False)
        V = Version(major=99, minor=0, patch=0, pre=[], build="")
        # Same dep name "foo" appearing in two branches
        es = EdgeSet(
            requires=[
                NamedRequire(name="foo", constraint_str="", predicates=(p_linux,)),
                NamedRequire(name="foo", constraint_str="", predicates=(p_mac,)),
            ],
            src_dir="",
            source=EdgeSource.NIMBLE_FALLBACK,
        )
        dep_terms, requires_names, requires_predicates = edgeset_to_terms(es, {}, V)
        # Dep appears once in the solver (one term, one requires_name)
        assert requires_names.count("foo") == 1
        # Both predicate sets are recorded
        assert "foo" in requires_predicates
        assert len(requires_predicates["foo"]) == 2
        assert (p_linux,) in requires_predicates["foo"]
        assert (p_mac,) in requires_predicates["foo"]

    def test_cond_requires_in_locked_dep_via_resolved_dep(self) -> None:
        """_locked_from_resolved copies cond_requires from ResolvedDep."""
        from milpa.lockfile import _locked_from_resolved

        p = Predicate(name="platform", values=("linux",), negated=False)
        cr = CondRequire(name="extra", predicates=(p,))
        rd = ResolvedDep(
            name="qux",
            identity=_VALID_IDENTITY,
            version="1.0.0",
            src_dir="src",
            requires=("bar", "extra"),
            cond_requires=(cr,),
        )
        locked = _locked_from_resolved(rd)
        assert locked.cond_requires == (cr,)


class TestVerifyIgnoresCondRequires:
    """Cycle 6: verify_against_graph does NOT consult cond_requires."""

    def test_verify_passes_with_cond_require_in_lockfile(self) -> None:
        """Lockfile with cond-require still verifies against a graph without it."""
        p = Predicate(name="platform", values=("linux",), negated=False)
        cr = CondRequire(name="extra", predicates=(p,))
        prov = GitProvenanceRecord(url="https://example.com/qux.git")
        locked = LockedDep(
            name="qux",
            identity=_VALID_IDENTITY,
            version="1.0.0",
            src_dir="src",
            requires=("bar", "extra"),
            provenances=(prov,),
            cond_requires=(cr,),
        )
        lf = Lockfile(deps=(locked,))
        # Graph has the dep with the same identity, no cond_requires field involved
        graph = ResolvedGraph(
            deps=(ResolvedDep(
                name="qux",
                identity=_VALID_IDENTITY,
                version="1.0.0",
                src_dir="src",
                requires=("bar", "extra"),
            ),)
        )
        verify_against_graph(lf, graph)  # must not raise


# ---------------------------------------------------------------------------
# C1-ssot — cond_require_sort_key is the single SSOT for sort order
# ---------------------------------------------------------------------------


class TestCondRequireSortKeySsot:
    """C1-ssot: unified sort key helper; fixture-171 ordering preserved.

    cond_require_sort_key delegates to _format_predicate_prop so the sort
    string cannot drift from the emitted string even if a value contains
    characters that need KDL escaping.
    """

    def _make_cr(self, name: str, pred_name: str, value: str) -> CondRequire:
        p = Predicate(name=pred_name, values=(value,), negated=False)
        return CondRequire(name=name, predicates=(p,))

    def test_sort_key_delegates_to_format_predicate_prop(self) -> None:
        """Sort key string matches what _format_predicate_prop would emit."""
        from milpa.lockfile import cond_require_sort_key, _format_predicate_prop

        cr = self._make_cr("bar", "platform", "linux")
        name_key, pred_key = cond_require_sort_key(cr)
        assert name_key == "bar"
        # pred_key must equal the formatter output (including KDL quoting)
        assert pred_key == _format_predicate_prop(cr.predicates[0])

    def test_fixture_171_linux_before_macosx(self) -> None:
        """fixture-171: same-name bar entries sort linux before macosx (C1 fix)."""
        from milpa.lockfile import cond_require_sort_key

        cr_linux = self._make_cr("bar", "platform", "linux")
        cr_macosx = self._make_cr("bar", "platform", "macosx")
        key_linux = cond_require_sort_key(cr_linux)
        key_macosx = cond_require_sort_key(cr_macosx)
        assert key_linux < key_macosx, (
            f"linux sort key {key_linux!r} must precede macosx {key_macosx!r}"
        )

    def test_fixture_171_bytes_unchanged(self) -> None:
        """format_lockfile produces the fixture-171 expected bytes unchanged."""
        import pathlib

        fixture = pathlib.Path(__file__).parent.parent.parent.parent / (
            "conformance/spec-v1/fixture-171-nimble-when-same-name-multi-branch"
            "/expected/milpa.lock"
        )
        expected = fixture.read_text()
        lf = parse_lockfile(expected)
        assert format_lockfile(lf) == expected


# ---------------------------------------------------------------------------
# M1 — predicate name whitelist on parse
# ---------------------------------------------------------------------------


class TestCondRequirePredicateWhitelist:
    """M1: unknown predicate keys in cond-require are dropped on parse."""

    def _lockfile_with_cr(self, cr_body: str) -> str:
        return (
            "// generated by milpa; reproducible build snapshot\n"
            "version 1\n"
            'strategy "maxver"\n'
            "\n"
            'dep "foo" {\n'
            '    version "0.0.1"\n'
            '    src_dir ""\n'
            "    requires\n"
            f"{cr_body}"
            "    provenance {\n"
            '        kind "local"\n'
            '        path "../foo"\n'
            "    }\n"
            "}\n"
        )

    def test_unknown_key_dropped_inline(self) -> None:
        """cond-require with unknown key → predicate dropped → cond_requires empty."""
        text = self._lockfile_with_cr('    cond-require "bar" evilkey="value"\n')
        lf = parse_lockfile(text)
        # evilkey is outside the whitelist → predicate dropped → CondRequire has no
        # predicates → entire CondRequire is skipped (returns None).
        assert lf.deps[0].cond_requires == ()

    def test_known_key_kept_inline(self) -> None:
        """cond-require with known key → predicate accepted."""
        text = self._lockfile_with_cr('    cond-require "bar" platform="linux"\n')
        lf = parse_lockfile(text)
        assert len(lf.deps[0].cond_requires) == 1
        assert lf.deps[0].cond_requires[0].predicates[0].name == "platform"

    def test_unknown_key_dropped_block_form(self) -> None:
        """Block-form when with unknown key → predicate dropped → CondRequire skipped."""
        text = self._lockfile_with_cr(
            '    cond-require "bar" {\n'
            '        when evilkey="value"\n'
            "    }\n"
        )
        lf = parse_lockfile(text)
        assert lf.deps[0].cond_requires == ()

    def test_mixed_block_form_unknown_dropped_known_kept(self) -> None:
        """Block form with one unknown + one known key: only known predicate accepted."""
        text = self._lockfile_with_cr(
            '    cond-require "bar" {\n'
            '        when evilkey="bad"\n'
            '        when platform="linux"\n'
            "    }\n"
        )
        lf = parse_lockfile(text)
        assert len(lf.deps[0].cond_requires) == 1
        preds = lf.deps[0].cond_requires[0].predicates
        assert len(preds) == 1
        assert preds[0].name == "platform"

    def test_all_five_known_keys_accepted(self) -> None:
        """All five whitelist members are accepted: platform, arch, nim, milpa, flag."""
        for key in ("platform", "arch", "nim", "milpa", "flag"):
            text = self._lockfile_with_cr(f'    cond-require "bar" {key}="value"\n')
            lf = parse_lockfile(text)
            assert len(lf.deps[0].cond_requires) == 1, f"{key!r} should be accepted"
            assert lf.deps[0].cond_requires[0].predicates[0].name == key


# ---------------------------------------------------------------------------
# M4 — single-value invariant enforced at emit time
# ---------------------------------------------------------------------------


class TestCondRequireSingleValueInvariant:
    """M4: _format_predicate_prop raises ValueError (not bare assert) on bad arity.

    A bare ``assert`` is stripped under ``python -O`` and gives a silent wrong
    result.  The guard is a real ``ValueError`` so it fires in all execution
    modes (M4 fix).
    """

    def test_single_value_ok(self) -> None:
        """Normal single-value predicate does not raise."""
        from milpa.lockfile import _format_predicate_prop
        p = Predicate(name="platform", values=("linux",), negated=False)
        result = _format_predicate_prop(p)
        assert result == 'platform="linux"'

    def test_multi_value_raises_value_error(self) -> None:
        """Multi-value predicate raises ValueError (not AssertionError) — M4 fix."""
        from milpa.lockfile import _format_predicate_prop
        p = Predicate(name="platform", values=("linux", "macosx"), negated=False)
        with pytest.raises(ValueError, match="single-value"):
            _format_predicate_prop(p)

    def test_zero_value_raises_value_error(self) -> None:
        """Zero-value predicate raises ValueError (not AssertionError) — M4 fix."""
        from milpa.lockfile import _format_predicate_prop
        p = Predicate(name="platform", values=(), negated=False)
        with pytest.raises(ValueError, match="single-value"):
            _format_predicate_prop(p)


# ---------------------------------------------------------------------------
# M7 — malformed cond-require parse: no panic / crash
# ---------------------------------------------------------------------------


class TestCondRequireMalformedParse:
    """M7: robust handling of malformed cond-require nodes on parse."""

    def _lockfile_with_cr(self, cr_body: str) -> str:
        return (
            "// generated by milpa; reproducible build snapshot\n"
            "version 1\n"
            'strategy "maxver"\n'
            "\n"
            'dep "foo" {\n'
            '    version "0.0.1"\n'
            '    src_dir ""\n'
            "    requires\n"
            f"{cr_body}"
            "    provenance {\n"
            '        kind "local"\n'
            '        path "../foo"\n'
            "    }\n"
            "}\n"
        )

    def test_no_name_arg_skipped(self) -> None:
        """cond-require with no positional name arg → skipped, no crash."""
        # KDL: `cond-require platform="linux"` has no positional arg before the prop.
        text = self._lockfile_with_cr('    cond-require platform="linux"\n')
        lf = parse_lockfile(text)
        assert lf.deps[0].cond_requires == ()

    def test_block_non_when_child_skipped(self) -> None:
        """Block-form child node that is not 'when' is silently skipped."""
        text = self._lockfile_with_cr(
            '    cond-require "bar" {\n'
            '        totally-unknown platform="linux"\n'
            '        when platform="macosx"\n'
            "    }\n"
        )
        lf = parse_lockfile(text)
        assert len(lf.deps[0].cond_requires) == 1
        assert lf.deps[0].cond_requires[0].predicates[0].values == ("macosx",)

    def test_when_with_no_props_yields_no_predicate(self) -> None:
        """Block-form 'when' child with no props → empty predicates → CondRequire skipped."""
        text = self._lockfile_with_cr(
            '    cond-require "bar" {\n'
            "        when\n"
            "    }\n"
        )
        lf = parse_lockfile(text)
        assert lf.deps[0].cond_requires == ()


# ---------------------------------------------------------------------------
# H4 — Hypothesis PBT: cond-require round-trip (format → parse → format)
# ---------------------------------------------------------------------------

# Predicate-name alphabet: only known whitelisted keys.
_pred_name_st = st.sampled_from(["platform", "arch", "nim", "milpa", "flag"])

# Values: KDL-safe text (no control chars, no quotes/backslash that would
# confuse the comparison, just alphanumeric + safe punctuation).
_pred_value_st = st.text(
    alphabet=st.characters(
        whitelist_categories=("Lu", "Ll", "Nd"),
        whitelist_characters="._-+",
    ),
    min_size=1,
    max_size=16,
)

_predicate_st = st.builds(
    Predicate,
    name=_pred_name_st,
    values=st.builds(tuple, st.lists(_pred_value_st, min_size=1, max_size=1)),
    negated=st.booleans(),
)

_cond_require_st = st.builds(
    CondRequire,
    name=_dep_name_st,
    predicates=st.builds(
        tuple,
        st.lists(_predicate_st, min_size=1, max_size=3),
    ),
)


def _make_dep_with_cond_requires(
    dep_name: str,
    cond_requires: tuple[CondRequire, ...],
) -> LockedDep:
    return LockedDep(
        name=dep_name,
        identity=_VALID_IDENTITY,
        version="1.0.0",
        src_dir="src",
        requires=tuple(sorted({cr.name for cr in cond_requires})),
        provenances=(GitProvenanceRecord(url="https://example.com/foo.git"),),
        cond_requires=cond_requires,
    )


@given(
    dep_name=_dep_name_st,
    cond_requires=st.lists(
        _cond_require_st, min_size=0, max_size=4
    ).map(tuple),
)
@settings(max_examples=100)
def test_cond_require_format_parse_format_roundtrip(
    dep_name: str,
    cond_requires: tuple[CondRequire, ...],
) -> None:
    """format(parse(format(lf))) == format(lf) — cond-require round-trip.

    H4: the format → parse → format path must be byte-identical for any
    CondRequire-bearing LockedDep.  Single-value predicates only (v0 invariant).
    """
    dep = _make_dep_with_cond_requires(dep_name, cond_requires)
    lf = Lockfile(deps=(dep,))
    text1 = format_lockfile(lf)
    lf2 = parse_lockfile(text1)
    text2 = format_lockfile(lf2)
    assert text1 == text2, (
        f"Round-trip not byte-identical.\n"
        f"text1:\n{text1!r}\n\ntext2:\n{text2!r}"
    )


@given(
    deps=st.lists(
        st.builds(
            lambda name, crs: _make_dep_with_cond_requires(name, crs),
            name=_dep_name_st,
            crs=st.lists(_cond_require_st, min_size=1, max_size=3).map(tuple),
        ),
        min_size=1,
        max_size=3,
        unique_by=lambda d: d.name,
    )
)
@settings(max_examples=60)
def test_cond_require_format_parse_format_multiple_deps(
    deps: list[LockedDep],
) -> None:
    """Multiple deps with cond_requires: format → parse → format is byte-identical."""
    lf = Lockfile(deps=tuple(sorted(deps, key=lambda d: d.name)))
    text1 = format_lockfile(lf)
    lf2 = parse_lockfile(text1)
    text2 = format_lockfile(lf2)
    assert text1 == text2
