"""D5 (resolution-semantics RFC §3 Axis D / §5, §6 D-D3) — the lockfile
top-level ``exclude_newer`` field: record + round-trip, the manifest-sourced
``FROZEN-EXCLUDE-NEWER-MISMATCH`` baseline (mirrors C3b's own
``FROZEN-STRATEGY-MISMATCH`` fix EXACTLY), and no-silent-drop:

- ``--locked`` treats "present in the old lock, absent from the new
  resolve" as drift (``RES-LOCKED-DRIFT``).
- ``update``/``remove`` (which re-resolve with no CLI ``--exclude-newer``
  surface) CARRY FORWARD the prior lockfile's recorded ``exclude_newer``
  rather than dropping it.

Mirrors ``test_c3b_frozen_strategy_baseline.py``'s infra (mocked git fetch,
no index, no network) and ``test_d2_exclude_newer_cli.py``'s CLI-level
conventions.
"""

from __future__ import annotations

import contextlib
import io
import os
from datetime import datetime, timezone
from pathlib import Path

from milpa.fetchers.mocked import url_key
from milpa.lockfile import Lockfile, ResolvedGraph, format_lockfile, from_graph, load_lockfile, parse_lockfile
from milpa.registry import _parse_timestamp

_UNSAFE_NO_INDEX_ENV = {"MILPA_INDEX_URL": ""}
_TS = datetime(2026, 1, 1, tzinfo=timezone.utc)


def _make_git_mock(mocked_dir: Path, url: str, ref: str, *, sha: str, marker: str) -> None:
    d = mocked_dir / url_key(url, ref)
    content = d / "content"
    content.mkdir(parents=True)
    (content / "foo.nim").write_text(f"# foo {marker}\n", encoding="utf-8")
    (d / "foo.nimble").write_text(
        '# Package\nauthor = "e"\ndescription = "d"\nlicense = "MIT"\n', encoding="utf-8"
    )
    (d / "sha").write_text(sha, encoding="utf-8")


def _run_main(argv: list[str], mocked_fetches_dir: Path, project_dir: Path) -> tuple[int, str, str]:
    from milpa.cli import main

    old_env = os.environ.copy()
    try:
        os.environ["MILPA_MOCKED_FETCHES"] = str(mocked_fetches_dir)
        os.environ["MILPA_CACHE_DIR"] = str(project_dir / ".milpa-cache")
        os.environ.update(_UNSAFE_NO_INDEX_ENV)
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            rc = main(argv)
        return rc, out.getvalue(), err.getvalue()
    finally:
        os.environ.clear()
        os.environ.update(old_env)


def _manifest_kdl(*, resolution_block: str = "") -> str:
    return (
        'name "myapp"\nkind "application"\n'
        f"{resolution_block}"
        "deps {\n"
        '    foo git=(url)"https://example.com/foo.git" ref="v1.0.0"\n'
        "}\n"
    )


def _setup_project(tmp_path: Path, *, resolution_block: str = "") -> tuple[Path, Path]:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    (project_dir / "milpa.kdl").write_text(
        _manifest_kdl(resolution_block=resolution_block), encoding="utf-8"
    )
    mocked_dir = tmp_path / "mocked-fetches"
    mocked_dir.mkdir()
    _make_git_mock(
        mocked_dir, "https://example.com/foo.git", "v1.0.0", sha="a" * 40, marker="v1"
    )
    return project_dir, mocked_dir


# ---------------------------------------------------------------------------
# Record + round-trip (unit level)
# ---------------------------------------------------------------------------


class TestLockfileExcludeNewerRoundTrip:
    def test_absent_by_default(self) -> None:
        lock = parse_lockfile("version 1\nstrategy \"maxver\"\n")
        assert lock.exclude_newer is None

    def test_parses_present_node(self) -> None:
        lock = parse_lockfile(
            'version 1\nstrategy "maxver"\nexclude_newer "2026-01-01T00:00:00Z"\n'
        )
        assert lock.exclude_newer == _parse_timestamp("2026-01-01T00:00:00Z")

    def test_omitted_from_emission_when_absent(self) -> None:
        lock = Lockfile(deps=(), strategy="maxver", exclude_newer=None)
        text = format_lockfile(lock)
        assert "exclude_newer" not in text

    def test_emitted_right_after_strategy_when_present(self) -> None:
        lock = Lockfile(deps=(), strategy="maxver", exclude_newer=_TS)
        text = format_lockfile(lock)
        assert text == (
            "// generated by milpa; reproducible build snapshot\n"
            "version 1\n"
            'strategy "maxver"\n'
            'exclude_newer "2026-01-01T00:00:00Z"\n'
        )

    def test_round_trips_through_format_and_parse(self) -> None:
        lock = Lockfile(deps=(), strategy="maxver", exclude_newer=_TS)
        text = format_lockfile(lock)
        reparsed = parse_lockfile(text)
        assert reparsed.exclude_newer == _TS

    def test_from_graph_carries_exclude_newer_through(self) -> None:
        graph = ResolvedGraph(deps=())
        lock = from_graph(graph, strategy="maxver", exclude_newer=_TS)
        assert lock.exclude_newer == _TS
        lock_none = from_graph(graph, strategy="maxver")
        assert lock_none.exclude_newer is None

    def test_malformed_arity_raises_lock_field_arity(self) -> None:
        from milpa.errors import MilpaError

        try:
            parse_lockfile('version 1\nstrategy "maxver"\nexclude_newer "a" "b"\n')
            assert False, "expected LOCK-FIELD-ARITY"
        except MilpaError as e:
            assert e.slug == "LOCK-FIELD-ARITY"

    def test_malformed_type_raises_lock_field_type(self) -> None:
        from milpa.errors import MilpaError

        try:
            parse_lockfile('version 1\nstrategy "maxver"\nexclude_newer 42\n')
            assert False, "expected LOCK-FIELD-TYPE"
        except MilpaError as e:
            assert e.slug == "LOCK-FIELD-TYPE"

    def test_unparseable_timestamp_raises_lock_field_type(self) -> None:
        from milpa.errors import MilpaError

        try:
            parse_lockfile('version 1\nstrategy "maxver"\nexclude_newer "not-a-date"\n')
            assert False, "expected LOCK-FIELD-TYPE"
        except MilpaError as e:
            assert e.slug == "LOCK-FIELD-TYPE"


# ---------------------------------------------------------------------------
# End-to-end: fetch --exclude-newer records + round-trips through milpa.lock
# ---------------------------------------------------------------------------


class TestFetchRecordsExcludeNewer:
    def test_fetch_with_exclude_newer_records_it_in_lockfile(self, tmp_path: Path) -> None:
        project_dir, mocked_dir = _setup_project(tmp_path)
        rc, _out, err = _run_main(
            ["-C", str(project_dir), "fetch", "--exclude-newer", "2026-01-01T00:00:00Z"],
            mocked_dir,
            project_dir,
        )
        assert rc == 0, f"fetch must succeed; stderr={err!r}"
        lock = load_lockfile(project_dir / "milpa.lock")
        assert lock.exclude_newer == _parse_timestamp("2026-01-01T00:00:00Z")

    def test_fetch_with_no_exclude_newer_omits_it(self, tmp_path: Path) -> None:
        project_dir, mocked_dir = _setup_project(tmp_path)
        rc, _out, err = _run_main(
            ["-C", str(project_dir), "fetch"], mocked_dir, project_dir
        )
        assert rc == 0, f"fetch must succeed; stderr={err!r}"
        lock = load_lockfile(project_dir / "milpa.lock")
        assert lock.exclude_newer is None


# ---------------------------------------------------------------------------
# FROZEN-EXCLUDE-NEWER-MISMATCH — manifest-sourced baseline from the start
# (mirrors C3b's own FROZEN-STRATEGY-MISMATCH fix exactly)
# ---------------------------------------------------------------------------


class TestFrozenBaselineFollowsManifestExcludeNewer:
    def test_frozen_passes_with_matching_manifest_and_lock(self, tmp_path: Path) -> None:
        project_dir, mocked_dir = _setup_project(
            tmp_path,
            resolution_block='resolution {\n    exclude-newer "2026-01-01T00:00:00Z"\n}\n',
        )
        rc, _out, err = _run_main(
            ["-C", str(project_dir), "fetch", "--exclude-newer", "2026-01-01T00:00:00Z"],
            mocked_dir,
            project_dir,
        )
        assert rc == 0, f"fetch must succeed; stderr={err!r}"
        lock = load_lockfile(project_dir / "milpa.lock")
        assert lock.exclude_newer == _parse_timestamp("2026-01-01T00:00:00Z")

        rc, _out, err = _run_main(
            ["-C", str(project_dir), "--frozen", "fetch"], mocked_dir, project_dir
        )
        assert rc == 0, (
            f"frozen fetch must succeed on a genuinely-consistent exclude-newer lock; "
            f"stderr={err!r}"
        )
        assert "milpa-error:" not in err

    def test_frozen_default_baseline_unchanged_with_no_resolution_block(
        self, tmp_path: Path
    ) -> None:
        project_dir, mocked_dir = _setup_project(tmp_path)
        rc, _out, _err = _run_main(
            ["-C", str(project_dir), "fetch"], mocked_dir, project_dir
        )
        assert rc == 0
        lock = load_lockfile(project_dir / "milpa.lock")
        assert lock.exclude_newer is None

        rc, _out, err = _run_main(
            ["-C", str(project_dir), "--frozen", "fetch"], mocked_dir, project_dir
        )
        assert rc == 0, f"frozen fetch must succeed with no recorded exclude_newer; stderr={err!r}"


class TestFrozenStillCatchesGenuineExcludeNewerDivergence:
    def test_frozen_fails_when_manifest_exclude_newer_changes_after_lock(
        self, tmp_path: Path
    ) -> None:
        project_dir, mocked_dir = _setup_project(
            tmp_path,
            resolution_block='resolution {\n    exclude-newer "2026-01-01T00:00:00Z"\n}\n',
        )
        rc, _out, _err = _run_main(
            ["-C", str(project_dir), "fetch", "--exclude-newer", "2026-01-01T00:00:00Z"],
            mocked_dir,
            project_dir,
        )
        assert rc == 0
        lock = load_lockfile(project_dir / "milpa.lock")
        assert lock.exclude_newer == _parse_timestamp("2026-01-01T00:00:00Z")

        # Mutate the manifest's declared exclude-newer WITHOUT re-resolving.
        (project_dir / "milpa.kdl").write_text(
            _manifest_kdl(
                resolution_block='resolution {\n    exclude-newer "2020-01-01T00:00:00Z"\n}\n'
            ),
            encoding="utf-8",
        )

        rc, _out, err = _run_main(
            ["-C", str(project_dir), "--frozen", "fetch"], mocked_dir, project_dir
        )
        assert rc == 1
        assert "FROZEN-EXCLUDE-NEWER-MISMATCH" in err

    def test_frozen_fails_when_manifest_adds_exclude_newer_lock_has_none(
        self, tmp_path: Path
    ) -> None:
        project_dir, mocked_dir = _setup_project(tmp_path)
        rc, _out, _err = _run_main(
            ["-C", str(project_dir), "fetch"], mocked_dir, project_dir
        )
        assert rc == 0
        lock = load_lockfile(project_dir / "milpa.lock")
        assert lock.exclude_newer is None

        (project_dir / "milpa.kdl").write_text(
            _manifest_kdl(
                resolution_block='resolution {\n    exclude-newer "2026-01-01T00:00:00Z"\n}\n'
            ),
            encoding="utf-8",
        )

        rc, _out, err = _run_main(
            ["-C", str(project_dir), "--frozen", "fetch"], mocked_dir, project_dir
        )
        assert rc == 1
        assert "FROZEN-EXCLUDE-NEWER-MISMATCH" in err


# ---------------------------------------------------------------------------
# resolve_workspace_frozen — same fix, the workspace-root code path
# ---------------------------------------------------------------------------


def _make_workspace_with_resolution(
    tmp_path: Path, *, resolution_block: str = ""
) -> "object":
    from milpa.workspace import load_workspace

    root_dir = tmp_path / "project"
    root_dir.mkdir()
    (root_dir / "milpa.kdl").write_text(
        'workspace {\n    member "mylib"\n}\n' f"{resolution_block}",
        encoding="utf-8",
    )
    lib_dir = root_dir / "mylib"
    lib_dir.mkdir()
    (lib_dir / "milpa.kdl").write_text(
        'name "mylib"\nkind "library"\n', encoding="utf-8"
    )
    return load_workspace(root_dir), lib_dir


class TestWorkspaceFrozenBaselineFollowsRootExcludeNewer:
    def test_workspace_frozen_passes_with_matching_root_and_lock(
        self, tmp_path: Path
    ) -> None:
        from milpa.cas import CAStore
        from milpa.context import MilpaEnv
        from milpa.identity import compute_content_hash
        from milpa.lockfile import LockedDep, MemberProvenanceRecord
        from milpa.frozen import resolve_workspace_frozen

        workspace, lib_dir = _make_workspace_with_resolution(
            tmp_path,
            resolution_block='resolution {\n    exclude-newer "2026-01-01T00:00:00Z"\n}\n',
        )
        member_identity = compute_content_hash(lib_dir)
        member_locked = LockedDep(
            name="mylib",
            identity=member_identity,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(MemberProvenanceRecord(name="mylib"),),
            aliases=(),
        )
        lockfile = Lockfile(
            deps=(member_locked,),
            strategy="maxver",
            exclude_newer=_parse_timestamp("2026-01-01T00:00:00Z"),
        )

        cas_root = tmp_path / ".cas"
        cas_root.mkdir()
        env = MilpaEnv(fetcher=None, index=None, store=CAStore(cas_root))  # type: ignore[arg-type]
        deps_dir = tmp_path / "_deps"

        graph = resolve_workspace_frozen(workspace, lockfile, env, deps_dir)
        assert graph is not None

    def test_workspace_frozen_fails_on_genuine_root_divergence(
        self, tmp_path: Path
    ) -> None:
        from milpa.cas import CAStore
        from milpa.context import MilpaEnv
        from milpa.errors import FROZEN_EXCLUDE_NEWER_MISMATCH, MilpaError
        from milpa.identity import compute_content_hash
        from milpa.lockfile import LockedDep, MemberProvenanceRecord
        from milpa.frozen import resolve_workspace_frozen

        workspace, lib_dir = _make_workspace_with_resolution(
            tmp_path,
            resolution_block='resolution {\n    exclude-newer "2026-01-01T00:00:00Z"\n}\n',
        )
        member_identity = compute_content_hash(lib_dir)
        member_locked = LockedDep(
            name="mylib",
            identity=member_identity,
            version="0.0.1",
            src_dir="",
            requires=(),
            provenances=(MemberProvenanceRecord(name="mylib"),),
            aliases=(),
        )
        lockfile = Lockfile(
            deps=(member_locked,),
            strategy="maxver",
            exclude_newer=_parse_timestamp("2020-01-01T00:00:00Z"),
        )

        cas_root = tmp_path / ".cas"
        cas_root.mkdir()
        env = MilpaEnv(fetcher=None, index=None, store=CAStore(cas_root))  # type: ignore[arg-type]
        deps_dir = tmp_path / "_deps"

        try:
            resolve_workspace_frozen(workspace, lockfile, env, deps_dir)
            assert False, "expected FROZEN-EXCLUDE-NEWER-MISMATCH"
        except MilpaError as e:
            assert e.slug == FROZEN_EXCLUDE_NEWER_MISMATCH


# ---------------------------------------------------------------------------
# No-silent-drop (D-D3): update/remove carry forward; --locked flags a drop.
# ---------------------------------------------------------------------------


class TestNoSilentDropUpdateRemove:
    def test_update_carries_forward_exclude_newer(self, tmp_path: Path) -> None:
        project_dir, mocked_dir = _setup_project(tmp_path)
        rc, _out, err = _run_main(
            ["-C", str(project_dir), "fetch", "--exclude-newer", "2026-01-01T00:00:00Z"],
            mocked_dir,
            project_dir,
        )
        assert rc == 0, f"fetch must succeed; stderr={err!r}"
        lock = load_lockfile(project_dir / "milpa.lock")
        assert lock.exclude_newer == _parse_timestamp("2026-01-01T00:00:00Z")

        # Bare `update` — no CLI flag, manifest has no resolution{} block.
        rc, _out, err = _run_main(
            ["-C", str(project_dir), "update"], mocked_dir, project_dir
        )
        assert rc == 0, f"update must succeed; stderr={err!r}"
        new_lock = load_lockfile(project_dir / "milpa.lock")
        assert new_lock.exclude_newer == _parse_timestamp("2026-01-01T00:00:00Z"), (
            "bare `update` must carry forward the prior lock's exclude_newer, not drop it"
        )

    def test_remove_carries_forward_exclude_newer(self, tmp_path: Path) -> None:
        project_dir = tmp_path / "project"
        project_dir.mkdir()
        (project_dir / "milpa.kdl").write_text(
            'name "myapp"\nkind "application"\ndeps {\n'
            '    foo git=(url)"https://example.com/foo.git" ref="v1.0.0"\n'
            '    bar git=(url)"https://example.com/bar.git" ref="v1.0.0"\n'
            "}\n",
            encoding="utf-8",
        )
        mocked_dir = tmp_path / "mocked-fetches"
        mocked_dir.mkdir()
        _make_git_mock(
            mocked_dir, "https://example.com/foo.git", "v1.0.0", sha="a" * 40, marker="foo"
        )
        _make_git_mock(
            mocked_dir, "https://example.com/bar.git", "v1.0.0", sha="b" * 40, marker="bar"
        )

        rc, _out, err = _run_main(
            ["-C", str(project_dir), "fetch", "--exclude-newer", "2026-01-01T00:00:00Z"],
            mocked_dir,
            project_dir,
        )
        assert rc == 0, f"fetch must succeed; stderr={err!r}"
        lock = load_lockfile(project_dir / "milpa.lock")
        assert lock.exclude_newer == _parse_timestamp("2026-01-01T00:00:00Z")

        rc, _out, err = _run_main(
            ["-C", str(project_dir), "remove", "bar"], mocked_dir, project_dir
        )
        assert rc == 0, f"remove must succeed; stderr={err!r}"
        new_lock = load_lockfile(project_dir / "milpa.lock")
        assert new_lock.exclude_newer == _parse_timestamp("2026-01-01T00:00:00Z"), (
            "single-package `remove` must carry forward the prior lock's exclude_newer"
        )


class TestLockedFlagsDroppedExcludeNewerAsDrift:
    def test_locked_flags_dropped_exclude_newer(self, tmp_path: Path) -> None:
        project_dir, mocked_dir = _setup_project(tmp_path)
        rc, _out, err = _run_main(
            ["-C", str(project_dir), "fetch", "--exclude-newer", "2026-01-01T00:00:00Z"],
            mocked_dir,
            project_dir,
        )
        assert rc == 0, f"fetch must succeed; stderr={err!r}"
        lock = load_lockfile(project_dir / "milpa.lock")
        assert lock.exclude_newer == _parse_timestamp("2026-01-01T00:00:00Z")

        # `--locked` this time WITHOUT --exclude-newer: the manifest has no
        # resolution{} block either, so the effective (2-tier, fetch/lock-
        # scoped) value is None — a real drop from the committed lock.
        rc, _out, err = _run_main(
            ["-C", str(project_dir), "fetch", "--locked"], mocked_dir, project_dir
        )
        assert rc == 1
        assert "RES-LOCKED-DRIFT" in err

    def test_locked_passes_when_exclude_newer_unchanged(self, tmp_path: Path) -> None:
        project_dir, mocked_dir = _setup_project(tmp_path)
        rc, _out, err = _run_main(
            ["-C", str(project_dir), "fetch", "--exclude-newer", "2026-01-01T00:00:00Z"],
            mocked_dir,
            project_dir,
        )
        assert rc == 0, f"fetch must succeed; stderr={err!r}"

        rc, _out, err = _run_main(
            [
                "-C", str(project_dir), "fetch", "--locked",
                "--exclude-newer", "2026-01-01T00:00:00Z",
            ],
            mocked_dir,
            project_dir,
        )
        assert rc == 0, f"--locked with an unchanged exclude_newer must pass; stderr={err!r}"
