"""W4 — per-member nim.cfg emission tests.

write_workspace_nimcfgs takes a Workspace + ResolvedGraph and writes
one nim.cfg per member at <root>/<member-path>/nim.cfg. Each member's
nim.cfg lists only its transitively-reachable deps, with --path: lines
using relative paths from the member's directory to the dep's location
(either <root>/_deps/<dep>/<src> for external deps or
<root>/<other-member>/<src> for workspace-internal member references).

See #25 + W4 (#76).
"""

from pathlib import Path

import pytest

from dataclasses import dataclass, field

from milpa.fetchers import FetcherRegistry
from milpa.fetchers.git import GitProvenance, GitReceipt
from milpa.manifest import (
    Manifest, MemberDep, NamedDep, UrlDep,
)
from milpa.nimcfg import member_dep_closure, write_workspace_nimcfgs
from milpa.resolver import ResolvedDep, ResolvedGraph, resolve_workspace
from milpa.workspace import LoadedMember, Workspace


@dataclass
class _FakeFetcher:
    by_url_ref: dict[tuple[str, str], tuple[str, str]]
    calls: list = field(default_factory=list)

    def can_handle(self, p):
        return isinstance(p, GitProvenance)

    def fetch(self, name, p, *, dest):
        self.calls.append((name, p.url, p.ref))
        sha, nimble_text = self.by_url_ref[(p.url, p.ref)]
        dest.mkdir(parents=True, exist_ok=True)
        (dest / f"{name}.nimble").write_text(nimble_text)
        return GitReceipt(commit_sha=sha)


def _registry(by_url_ref):
    reg = FetcherRegistry()
    reg.register(_FakeFetcher(by_url_ref))
    return reg


def _empty_manifest(name: str, src_dir: str = "") -> Manifest:
    return Manifest(deps=(), kind="library", name=name, src_dir=src_dir)


def _member(name: str, root: Path, src_dir: str = "",
            deps: tuple = ()) -> LoadedMember:
    d = root / name
    d.mkdir(parents=True, exist_ok=True)
    return LoadedMember(
        name=name, path=name, directory=d,
        manifest=Manifest(
            deps=deps, kind="library", name=name, src_dir=src_dir,
        ),
    )


def test_write_workspace_nimcfgs_one_member_no_deps(tmp_path):
    """Tracer: a 1-member workspace where the member has no deps →
    one empty (header-only) nim.cfg at <root>/<member>/nim.cfg."""
    ws = Workspace(root=tmp_path, members=(_member("fresco", tmp_path),))
    graph = resolve_workspace(
        ws, deps_dir=tmp_path / "_deps",
    )

    paths = write_workspace_nimcfgs(ws, graph)

    expected = tmp_path / "fresco" / "nim.cfg"
    assert paths == [expected]
    assert expected.exists()
    # Header present; no --path: lines (member has no deps)
    text = expected.read_text()
    assert "generated by milpa" in text
    assert "--path:" not in text


def test_member_with_url_dep_emits_relative_path_into_deps(tmp_path):
    """Member at <root>/fresco/ with a URL dep → nim.cfg has
    `--path:"../_deps/<dep>/<src>"` (relative path up one level to
    workspace root, then down into _deps/)."""
    fresco = _member("fresco", tmp_path, deps=(
        UrlDep(name="chronos", git="https://example.com/x.git", ref="main"),
    ))
    ws = Workspace(root=tmp_path, members=(fresco,))
    reg = _registry({
        ("https://example.com/x.git", "main"): (
            "csha", 'srcDir = "src"\n',
        ),
    })

    graph = resolve_workspace(
        ws, deps_dir=tmp_path / "_deps", fetcher=reg,
    )
    write_workspace_nimcfgs(ws, graph)

    text = (tmp_path / "fresco" / "nim.cfg").read_text()
    assert '--path:"../_deps/chronos/src"' in text


def test_member_to_member_ref_emits_relative_path_to_sibling(tmp_path):
    """fresco's nim.cfg with `member "intonaco"` references intonaco's
    directory directly — NOT through _deps/. The relative path skips
    _deps/ entirely: from <root>/fresco/ to <root>/intonaco/ is `../intonaco`."""
    fresco = _member("fresco", tmp_path, deps=(MemberDep(name="intonaco"),))
    intonaco = _member("intonaco", tmp_path)
    ws = Workspace(root=tmp_path, members=(fresco, intonaco))

    graph = resolve_workspace(
        ws, deps_dir=tmp_path / "_deps",
    )
    write_workspace_nimcfgs(ws, graph)

    text = (tmp_path / "fresco" / "nim.cfg").read_text()
    # No src_dir declared → bare directory path
    assert '--path:"../intonaco"' in text
    # And NOT through _deps/
    assert "_deps/intonaco" not in text


def test_per_member_closure_isolates_dep_visibility(tmp_path):
    """Nim isolation per-member: an external dep reachable only via
    intonaco appears in intonaco's nim.cfg but NOT in fresco's."""
    # fresco has NO deps; intonaco has chronos.
    fresco = _member("fresco", tmp_path)
    intonaco = _member("intonaco", tmp_path, deps=(
        UrlDep(name="chronos", git="https://example.com/x.git", ref="main"),
    ))
    ws = Workspace(root=tmp_path, members=(fresco, intonaco))
    reg = _registry({
        ("https://example.com/x.git", "main"): ("csha", 'srcDir = "src"\n'),
    })

    graph = resolve_workspace(
        ws, deps_dir=tmp_path / "_deps", fetcher=reg,
    )
    write_workspace_nimcfgs(ws, graph)

    fresco_cfg = (tmp_path / "fresco" / "nim.cfg").read_text()
    intonaco_cfg = (tmp_path / "intonaco" / "nim.cfg").read_text()

    # chronos in intonaco's, NOT in fresco's
    assert "chronos" in intonaco_cfg
    assert "chronos" not in fresco_cfg
    # And fresco has no --path: lines at all (it has no deps)
    assert "--path:" not in fresco_cfg


def test_deeper_member_paths_emit_deeper_relpaths(tmp_path):
    """A member declared at packages/fresco/ (depth 2) needs `../../`
    to reach <root>/_deps/. The relative-path computation must
    handle arbitrary depth, not just direct children."""
    member_dir = tmp_path / "packages" / "fresco"
    member_dir.mkdir(parents=True)
    member = LoadedMember(
        name="fresco", path="packages/fresco",
        directory=member_dir,
        manifest=Manifest(
            deps=(UrlDep(name="chronos", git="https://example.com/x.git", ref="main"),),
            kind="library", name="fresco",
        ),
    )
    ws = Workspace(root=tmp_path, members=(member,))
    reg = _registry({
        ("https://example.com/x.git", "main"): ("csha", 'srcDir = "src"\n'),
    })

    graph = resolve_workspace(
        ws, deps_dir=tmp_path / "_deps", fetcher=reg,
    )
    write_workspace_nimcfgs(ws, graph)

    text = (member_dir / "nim.cfg").read_text()
    assert '--path:"../../_deps/chronos/src"' in text


def test_member_with_src_dir_appears_in_consumer_path(tmp_path):
    """When intonaco declares `src_dir "src"` in its milpa.kdl, fresco's
    nim.cfg references intonaco via the src subdir, not the bare dir.
    This is how Nim packages with src/ layout get correctly resolved
    from workspace members."""
    fresco = _member("fresco", tmp_path, deps=(MemberDep(name="intonaco"),))
    intonaco = _member("intonaco", tmp_path, src_dir="src")
    ws = Workspace(root=tmp_path, members=(fresco, intonaco))

    graph = resolve_workspace(
        ws, deps_dir=tmp_path / "_deps",
    )
    write_workspace_nimcfgs(ws, graph)

    text = (tmp_path / "fresco" / "nim.cfg").read_text()
    assert '--path:"../intonaco/src"' in text
