"""nim.cfg emission tests."""

from pathlib import Path

import pytest

from milpa.nimcfg import format_nimcfg, write_nimcfg
from milpa.resolver import ResolvedDep, ResolvedGraph


def _dep(name, src_dir="", source="src", ref=None, sha=None,
         version=(0, 0, 1), identity=None, requires=()):
    return ResolvedDep(
        name=name, source=source, ref=ref, sha=sha, version=version,
        identity=identity, src_dir=src_dir, requires=requires,
    )


def test_one_dep_with_srcdir_emits_path():
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    text = format_nimcfg(graph)
    assert '--path:"_deps/foo/src"' in text


def test_no_srcdir_emits_repo_root_path():
    # chronos's shape — source at the repo root, no srcDir line.
    graph = ResolvedGraph(deps=(_dep("chronos", src_dir=""),))
    text = format_nimcfg(graph)
    assert '--path:"_deps/chronos"' in text
    # No trailing slash, no spurious src segment
    assert '--path:"_deps/chronos/"' not in text


def test_multiple_deps_in_graph_order():
    graph = ResolvedGraph(deps=(
        _dep("alpha", src_dir="src"),
        _dep("bravo"),
        _dep("charlie", src_dir="src"),
    ))
    text = format_nimcfg(graph)
    a_idx = text.index('alpha')
    b_idx = text.index('bravo')
    c_idx = text.index('charlie')
    assert a_idx < b_idx < c_idx


def test_header_comment_present():
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    text = format_nimcfg(graph)
    assert text.startswith("# generated by milpa")
    assert "milpa.kdl" in text   # manifest reference
    assert "milpa.lock" in text  # lockfile reference


def test_write_nimcfg_writes_to_disk(tmp_path):
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    path = write_nimcfg(graph, project_root=tmp_path)
    assert path == tmp_path / "nim.cfg"
    assert path.exists()
    content = path.read_text()
    assert '--path:"_deps/foo/src"' in content
    assert content.startswith("# generated by milpa")


def test_write_nimcfg_is_idempotent(tmp_path):
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"), _dep("bar")))
    p1 = write_nimcfg(graph, project_root=tmp_path)
    first = p1.read_bytes()
    p2 = write_nimcfg(graph, project_root=tmp_path)
    assert p1 == p2
    assert p2.read_bytes() == first


def test_empty_graph_produces_header_only():
    graph = ResolvedGraph(deps=())
    text = format_nimcfg(graph)
    assert text.startswith("# generated by milpa")
    assert "--path:" not in text


def test_custom_deps_dir_used_in_paths():
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    text = format_nimcfg(graph, deps_dir=Path("vendor/nim"))
    assert '--path:"vendor/nim/foo/src"' in text


def test_self_src_dir_emits_path_for_owning_package():
    """When the consumer declares its own src_dir, nim.cfg includes
    --path:"<self_src_dir>" so the consumer's own modules resolve via
    `import myPkg/foo` without a separate tests/nim.cfg.
    """
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    text = format_nimcfg(graph, self_src_dir="src")
    assert '--path:"src"' in text
    # Self path appears before dep paths so the consumer's own modules
    # shadow any same-named dep in surprise cases (defensible ordering).
    assert text.index('--path:"src"') < text.index('--path:"_deps/foo/src"')


def test_self_src_dir_empty_omits_self_path():
    """No src_dir declared → no self --path: line."""
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    text = format_nimcfg(graph, self_src_dir="")
    # The dep path still appears; only the self path is absent.
    assert '--path:"_deps/foo/src"' in text
    self_lines = [l for l in text.splitlines() if l == '--path:"src"']
    assert self_lines == []


def test_self_src_dir_with_empty_graph():
    """A package with no deps but its own src still gets a self path."""
    graph = ResolvedGraph(deps=())
    text = format_nimcfg(graph, self_src_dir="src")
    assert '--path:"src"' in text


def test_write_nimcfg_forwards_self_src_dir(tmp_path):
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    path = write_nimcfg(graph, project_root=tmp_path, self_src_dir="src")
    content = path.read_text()
    assert '--path:"src"' in content
