"""Lockfile tests — KDL round-trip + verification against ResolvedGraph."""

from pathlib import Path

import pytest

from milpa.lockfile import (
    LockedDep,
    Lockfile,
    LockfileError,
    format_lockfile,
    from_graph,
    load_lockfile,
    parse_lockfile,
    verify_against_graph,
    write_lockfile,
)
from milpa.resolver import ResolvedDep, ResolvedGraph


def _dep(name, *, source="https://example.com/x.git", ref="main",
         tag=None, sha="abc123", content_hash="hash_x",
         version=(0, 0, 1), src_dir="src", requires=()):
    return ResolvedDep(
        name=name, source=source, ref=ref, tag=tag, sha=sha,
        version=version, content_hash=content_hash,
        src_dir=src_dir, requires=requires,
    )


def test_format_lockfile_emits_dep_name_and_sha():
    graph = ResolvedGraph(deps=(_dep("chronos", sha="abc123def"),))
    lockfile = from_graph(graph)
    text = format_lockfile(lockfile)
    assert "chronos" in text
    assert "abc123def" in text


def test_format_lockfile_has_header_and_version():
    graph = ResolvedGraph(deps=(_dep("foo"),))
    text = format_lockfile(from_graph(graph))
    assert text.startswith("// generated by milpa")
    assert "version 1" in text


def test_format_lockfile_deps_sorted_by_name_regardless_of_graph_order():
    # Construct in z, a, m order; output must be a, m, z.
    graph = ResolvedGraph(deps=(_dep("zebra"), _dep("alpha"), _dep("mid")))
    text = format_lockfile(from_graph(graph))
    a_idx = text.index('"alpha"')
    m_idx = text.index('"mid"')
    z_idx = text.index('"zebra"')
    assert a_idx < m_idx < z_idx


def test_parse_lockfile_reads_single_dep():
    text = '''// header
version 1

dep "chronos" {
    source "https://example.com/chronos.git"
    ref "main"
    sha "abc123"
    content_hash "sha256:deadbeef"
    version "0.0.1"
    src_dir ""
    requires
}
'''
    lockfile = parse_lockfile(text)
    assert lockfile.version == 1
    assert len(lockfile.deps) == 1
    dep = lockfile.deps[0]
    assert dep.name == "chronos"
    assert dep.source == "https://example.com/chronos.git"
    assert dep.ref == "main"
    assert dep.sha == "abc123"
    assert dep.content_hash == "deadbeef"     # algorithm prefix stripped
    assert dep.version == "0.0.1"
    assert dep.src_dir == ""
    assert dep.requires == ()


def test_format_parse_round_trip():
    graph = ResolvedGraph(deps=(
        _dep("chronos", source="https://example.com/chronos.git",
             ref="feat/x", sha="abc", content_hash="hash_c", src_dir=""),
        _dep("intonaco", source="https://example.com/intonaco.git",
             ref="main", sha="def", content_hash="hash_i", src_dir="src",
             requires=("chronos",)),
    ))
    lockfile = from_graph(graph)
    round_tripped = parse_lockfile(format_lockfile(lockfile))
    assert round_tripped == lockfile


def test_parse_lockfile_rejects_unknown_schema_version():
    text = 'version 99\n'
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(text)
    assert "99" in str(exc.value) or "version" in str(exc.value).lower()


def test_write_and_load_round_trip(tmp_path):
    graph = ResolvedGraph(deps=(
        _dep("alpha", sha="aaa", content_hash="hash_a"),
        _dep("bravo", sha="bbb", content_hash="hash_b", requires=("alpha",)),
    ))
    lockfile = from_graph(graph)
    path = write_lockfile(lockfile, tmp_path / "milpa.lock")
    assert path == tmp_path / "milpa.lock"
    assert path.exists()
    loaded = load_lockfile(path)
    assert loaded == lockfile


def test_verify_against_graph_passes_for_matching_graph():
    graph = ResolvedGraph(deps=(
        _dep("foo", sha="abc", content_hash="hash_foo"),
    ))
    lockfile = from_graph(graph)
    # No exception
    verify_against_graph(lockfile, graph)


def test_verify_against_graph_raises_on_content_hash_mismatch():
    graph_locked = ResolvedGraph(deps=(
        _dep("foo", sha="abc", content_hash="hash_original"),
    ))
    lockfile = from_graph(graph_locked)
    graph_drifted = ResolvedGraph(deps=(
        _dep("foo", sha="abc", content_hash="hash_TAMPERED"),
    ))
    with pytest.raises(LockfileError) as exc:
        verify_against_graph(lockfile, graph_drifted)
    assert "foo" in str(exc.value)
    assert "hash" in str(exc.value).lower() or "content" in str(exc.value).lower()


def test_verify_against_graph_raises_on_missing_or_extra_dep():
    locked_graph = ResolvedGraph(deps=(_dep("foo"), _dep("bar")))
    lockfile = from_graph(locked_graph)

    # Graph missing 'bar'
    missing = ResolvedGraph(deps=(_dep("foo"),))
    with pytest.raises(LockfileError) as exc:
        verify_against_graph(lockfile, missing)
    assert "bar" in str(exc.value)

    # Graph has an extra dep 'baz'
    extra = ResolvedGraph(deps=(_dep("foo"), _dep("bar"), _dep("baz")))
    with pytest.raises(LockfileError) as exc:
        verify_against_graph(lockfile, extra)
    assert "baz" in str(exc.value)


def test_empty_graph_produces_empty_valid_lockfile():
    lockfile = from_graph(ResolvedGraph(deps=()))
    text = format_lockfile(lockfile)
    assert "version 1" in text
    assert "dep " not in text
    round_tripped = parse_lockfile(text)
    assert round_tripped == lockfile
    assert round_tripped.deps == ()
