"""nim.cfg emission tests."""

from pathlib import Path

import pytest

from milpa.nimcfg import format_nimcfg, write_nimcfg
from milpa.resolver import ResolvedDep, ResolvedGraph


def _dep(name, src_dir="", source="src", ref=None, sha=None, tag=None,
         version=(0, 0, 1), content_hash=None, requires=()):
    return ResolvedDep(
        name=name, source=source, ref=ref, tag=tag, sha=sha, version=version,
        content_hash=content_hash, src_dir=src_dir, requires=requires,
    )


def test_one_dep_with_srcdir_emits_path():
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    text = format_nimcfg(graph)
    assert '--path:"_deps/foo/src"' in text


def test_no_srcdir_emits_repo_root_path():
    # chronos's shape — source at the repo root, no srcDir line.
    graph = ResolvedGraph(deps=(_dep("chronos", src_dir=""),))
    text = format_nimcfg(graph)
    assert '--path:"_deps/chronos"' in text
    # No trailing slash, no spurious src segment
    assert '--path:"_deps/chronos/"' not in text


def test_multiple_deps_in_graph_order():
    graph = ResolvedGraph(deps=(
        _dep("alpha", src_dir="src"),
        _dep("bravo"),
        _dep("charlie", src_dir="src"),
    ))
    text = format_nimcfg(graph)
    a_idx = text.index('alpha')
    b_idx = text.index('bravo')
    c_idx = text.index('charlie')
    assert a_idx < b_idx < c_idx


def test_header_comment_present():
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    text = format_nimcfg(graph)
    assert text.startswith("# generated by milpa")
    assert "milpa.kdl" in text   # manifest reference
    assert "milpa.lock" in text  # lockfile reference


def test_write_nimcfg_writes_to_disk(tmp_path):
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    path = write_nimcfg(graph, project_root=tmp_path)
    assert path == tmp_path / "nim.cfg"
    assert path.exists()
    content = path.read_text()
    assert '--path:"_deps/foo/src"' in content
    assert content.startswith("# generated by milpa")


def test_write_nimcfg_is_idempotent(tmp_path):
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"), _dep("bar")))
    p1 = write_nimcfg(graph, project_root=tmp_path)
    first = p1.read_bytes()
    p2 = write_nimcfg(graph, project_root=tmp_path)
    assert p1 == p2
    assert p2.read_bytes() == first


def test_empty_graph_produces_header_only():
    graph = ResolvedGraph(deps=())
    text = format_nimcfg(graph)
    assert text.startswith("# generated by milpa")
    assert "--path:" not in text


def test_custom_deps_dir_used_in_paths():
    graph = ResolvedGraph(deps=(_dep("foo", src_dir="src"),))
    text = format_nimcfg(graph, deps_dir=Path("vendor/nim"))
    assert '--path:"vendor/nim/foo/src"' in text
