"""Lockfile tests — KDL round-trip + verification against ResolvedGraph.

Schema is v2 (#33) — structured identity + provenance blocks.
Legacy v1 reader exercised in test_lockfile_v2.py.
"""

from pathlib import Path

import pytest

from milpa.lockfile import (
    GitProvenanceRecord,
    LockedDep,
    Lockfile,
    LockfileError,
    format_lockfile,
    from_graph,
    load_lockfile,
    parse_lockfile,
    verify_against_graph,
    write_lockfile,
)
from milpa.resolver import ResolvedDep, ResolvedGraph


_VALID_HASH = "sha256:" + "f" * 64


def _dep(name, *, source="https://example.com/x.git", ref="main",
         sha="abc123", identity=None,
         version=(0, 0, 1), src_dir="src", requires=()):
    """Helper for ResolvedDep construction (flat-field shape)."""
    if identity is None:
        identity = _VALID_HASH
    return ResolvedDep(
        name=name, source=source, ref=ref, sha=sha,
        version=version, identity=identity,
        src_dir=src_dir, requires=requires,
    )


def _locked_git(name, *, identity=_VALID_HASH, url="https://example.com/x.git",
                ref="main", commit_sha=None, version="0.0.1",
                src_dir="src", requires=()):
    """Helper for LockedDep construction in tests that need direct
    structured-lockfile shape."""
    return LockedDep(
        name=name,
        identity=identity,
        version=version,
        src_dir=src_dir,
        requires=requires,
        provenances=(GitProvenanceRecord(
            url=url, ref=ref, commit_sha=commit_sha,
        ),),
    )


def test_format_lockfile_emits_dep_name_and_sha():
    graph = ResolvedGraph(deps=(_dep("chronos", sha="abc123def"),))
    lockfile = from_graph(graph)
    text = format_lockfile(lockfile)
    assert "chronos" in text
    # commit_sha shows up inside the git provenance block
    assert "abc123def" in text


def test_format_lockfile_has_header_and_version():
    graph = ResolvedGraph(deps=(_dep("foo"),))
    text = format_lockfile(from_graph(graph))
    assert text.startswith("// generated by milpa")
    assert "version 1" in text


def test_format_lockfile_deps_sorted_by_name_regardless_of_graph_order():
    graph = ResolvedGraph(deps=(_dep("zebra"), _dep("alpha"), _dep("mid")))
    text = format_lockfile(from_graph(graph))
    a_idx = text.index('"alpha"')
    m_idx = text.index('"mid"')
    z_idx = text.index('"zebra"')
    assert a_idx < m_idx < z_idx


def test_format_parse_round_trip():
    """ResolvedGraph → from_graph → format_lockfile → parse_lockfile
    is round-trip stable. v2 schema preserves identity-vs-provenance
    separation."""
    graph = ResolvedGraph(deps=(
        _dep("chronos", source="https://example.com/chronos.git",
             ref="feat/x", sha="abc", identity="sha256:" + "c" * 64, src_dir=""),
        _dep("intonaco", source="https://example.com/intonaco.git",
             ref="main", sha="def", identity="sha256:" + "1" * 64, src_dir="src",
             requires=("chronos",)),
    ))
    lockfile = from_graph(graph)
    round_tripped = parse_lockfile(format_lockfile(lockfile))
    assert round_tripped == lockfile


def test_parse_lockfile_rejects_unknown_schema_version():
    text = 'version 99\n'
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(text)
    assert "99" in str(exc.value) or "version" in str(exc.value).lower()
    assert exc.value.code == "LOCK-VERSION-UNSUPPORTED"


def test_write_and_load_round_trip(tmp_path):
    graph = ResolvedGraph(deps=(
        _dep("alpha", sha="aaa", identity="sha256:" + "a" * 64),
        _dep("bravo", sha="bbb", identity="sha256:" + "b" * 64, requires=("alpha",)),
    ))
    lockfile = from_graph(graph)
    path = write_lockfile(lockfile, tmp_path / "milpa.lock")
    assert path == tmp_path / "milpa.lock"
    assert path.exists()
    loaded = load_lockfile(path)
    assert loaded == lockfile


def test_verify_against_graph_passes_for_matching_graph():
    graph = ResolvedGraph(deps=(
        _dep("foo", sha="abc", identity="sha256:" + "0" * 64),
    ))
    lockfile = from_graph(graph)
    verify_against_graph(lockfile, graph)  # no exception


def test_verify_against_graph_raises_on_identity_mismatch():
    graph_locked = ResolvedGraph(deps=(
        _dep("foo", sha="abc", identity="sha256:" + "0" * 64),
    ))
    lockfile = from_graph(graph_locked)
    graph_drifted = ResolvedGraph(deps=(
        _dep("foo", sha="abc", identity="sha256:" + "1" * 64),
    ))
    with pytest.raises(LockfileError) as exc:
        verify_against_graph(lockfile, graph_drifted)
    assert "foo" in str(exc.value)
    assert "identity" in str(exc.value).lower()
    assert exc.value.code == "LOCK-GRAPH-MISMATCH"


def test_verify_against_graph_raises_on_missing_or_extra_dep():
    locked_graph = ResolvedGraph(deps=(_dep("foo"), _dep("bar")))
    lockfile = from_graph(locked_graph)

    missing = ResolvedGraph(deps=(_dep("foo"),))
    with pytest.raises(LockfileError) as exc:
        verify_against_graph(lockfile, missing)
    assert "bar" in str(exc.value)

    extra = ResolvedGraph(deps=(_dep("foo"), _dep("bar"), _dep("baz")))
    with pytest.raises(LockfileError) as exc:
        verify_against_graph(lockfile, extra)
    assert "baz" in str(exc.value)


def test_empty_graph_produces_empty_valid_lockfile():
    lockfile = from_graph(ResolvedGraph(deps=()))
    text = format_lockfile(lockfile)
    assert "version 1" in text
    assert "dep " not in text
    round_tripped = parse_lockfile(text)
    assert round_tripped == lockfile
    assert round_tripped.deps == ()


def test_lockfile_records_strategy():
    """Lockfile records which resolution strategy produced it."""
    graph = ResolvedGraph(deps=(_dep("foo"),))
    lockfile = from_graph(graph, strategy="minver")
    text = format_lockfile(lockfile)
    assert 'strategy "minver"' in text
    parsed = parse_lockfile(text)
    assert parsed.strategy == "minver"


def test_lockfile_without_strategy_field_parses_as_maxver():
    """Pre-strategy lockfiles default to maxver — no schema bump."""
    text = '''// older lockfile, pre-strategy
version 1

dep "foo" {
    identity "sha256:''' + "0" * 64 + '''"
    version "0.0.1"
    src_dir "src"
    requires
    provenance {
        kind "git"
        url "https://example.com/x.git"
        ref "main"
        commit_sha "abc"
    }
}
'''
    parsed = parse_lockfile(text)
    assert parsed.strategy == "maxver"


def test_parse_lockfile_rejects_unsupported_algorithm():
    """parse_identity-driven rejection at lockfile load time: an
    md5-encoded identity is unsupported and surfaces as a
    LockfileError naming the algorithm."""
    text = '''version 1

dep "foo" {
    identity "md5:''' + "f" * 32 + '''"
    version "0.0.1"
    src_dir ""
    requires
    provenance {
        kind "git"
        url "https://example.com/x.git"
        ref "main"
        commit_sha "abc"
    }
}
'''
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(text)
    msg = str(exc.value).lower()
    assert "md5" in msg
    assert "unsupported" in msg
    assert exc.value.code == "LOCK-DEP-IDENTITY-INVALID"


# ---------------------------------------------------------------------------
# Error-catalog code coverage (LOCK-* bijection)
# ---------------------------------------------------------------------------

def test_lock_kdl_syntax_code():
    """LOCK-KDL-SYNTAX: malformed KDL text."""
    with pytest.raises(LockfileError) as exc:
        parse_lockfile("this is not { kdl")
    assert exc.value.code == "LOCK-KDL-SYNTAX"


def test_lock_version_missing_code():
    """LOCK-VERSION-MISSING: no version node in lockfile."""
    with pytest.raises(LockfileError) as exc:
        parse_lockfile('dep "foo" { }')
    assert exc.value.code == "LOCK-VERSION-MISSING"


def test_lock_file_not_found_code(tmp_path):
    """LOCK-FILE-NOT-FOUND: lockfile path doesn't exist."""
    from milpa.lockfile import load_lockfile
    with pytest.raises(LockfileError) as exc:
        load_lockfile(tmp_path / "no_such_file.lock")
    assert exc.value.code == "LOCK-FILE-NOT-FOUND"


def test_lock_field_arity_code():
    """LOCK-FIELD-ARITY: version node with wrong arity."""
    with pytest.raises(LockfileError) as exc:
        parse_lockfile("version 1 2\n")
    assert exc.value.code == "LOCK-FIELD-ARITY"


def test_lock_field_type_code():
    """LOCK-FIELD-TYPE: version node with non-integer value."""
    with pytest.raises(LockfileError) as exc:
        parse_lockfile('version "notanint"\n')
    assert exc.value.code == "LOCK-FIELD-TYPE"


def _minimal_dep_block(extra: str = "") -> str:
    """KDL text for a minimal valid lockfile with one dep, plus optional extra
    text injected into the dep block."""
    return (
        "version 1\n"
        'dep "foo" {\n'
        '    version "0.0.1"\n'
        '    src_dir "src"\n'
        '    requires\n'
        f"{extra}"
        "    provenance {\n"
        '        kind "git"\n'
        '        url "https://example.com/foo.git"\n'
        '        ref "main"\n'
        "    }\n"
        "}\n"
    )


def test_lock_dep_name_arity_code():
    """LOCK-DEP-NAME-ARITY: dep node without a name arg."""
    text = (
        "version 1\n"
        "dep {\n"
        '    version "0.0.1"\n'
        '    src_dir ""\n'
        "    requires\n"
        "    provenance {\n"
        '        kind "git"\n'
        '        url "https://x.com/y.git"\n'
        "    }\n"
        "}\n"
    )
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(text)
    assert exc.value.code == "LOCK-DEP-NAME-ARITY"


def test_lock_dep_field_arity_code():
    """LOCK-DEP-FIELD-ARITY: dep child field (e.g. version) with wrong arity."""
    text = (
        "version 1\n"
        'dep "foo" {\n'
        '    version "a" "b"\n'
        '    src_dir "src"\n'
        "    requires\n"
        "    provenance {\n"
        '        kind "git"\n'
        '        url "https://example.com/foo.git"\n'
        '        ref "main"\n'
        "    }\n"
        "}\n"
    )
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(text)
    assert exc.value.code == "LOCK-DEP-FIELD-ARITY"


def test_lock_prov_field_arity_code():
    """LOCK-PROV-FIELD-ARITY: provenance child with wrong arity."""
    text = (
        "version 1\n"
        'dep "foo" {\n'
        '    version "0.0.1"\n'
        '    src_dir "src"\n'
        "    requires\n"
        "    provenance {\n"
        '        kind "git" "extra"\n'
        "    }\n"
        "}\n"
    )
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(text)
    assert exc.value.code == "LOCK-PROV-FIELD-ARITY"


def test_lock_prov_kind_missing_code():
    """LOCK-PROV-KIND-MISSING: provenance block without a kind field."""
    text = (
        "version 1\n"
        'dep "foo" {\n'
        '    version "0.0.1"\n'
        '    src_dir "src"\n'
        "    requires\n"
        "    provenance {\n"
        '        url "https://example.com/foo.git"\n'
        "    }\n"
        "}\n"
    )
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(text)
    assert exc.value.code == "LOCK-PROV-KIND-MISSING"


def test_lock_prov_kind_unknown_code():
    """LOCK-PROV-KIND-UNKNOWN: provenance block with unrecognized kind."""
    text = (
        "version 1\n"
        'dep "foo" {\n'
        '    version "0.0.1"\n'
        '    src_dir "src"\n'
        "    requires\n"
        "    provenance {\n"
        '        kind "hg"\n'
        "    }\n"
        "}\n"
    )
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(text)
    assert exc.value.code == "LOCK-PROV-KIND-UNKNOWN"


def test_lock_prov_field_missing_code():
    """LOCK-PROV-FIELD-MISSING: git provenance without the required url."""
    text = (
        "version 1\n"
        'dep "foo" {\n'
        '    version "0.0.1"\n'
        '    src_dir "src"\n'
        "    requires\n"
        "    provenance {\n"
        '        kind "git"\n'
        "    }\n"
        "}\n"
    )
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(text)
    assert exc.value.code == "LOCK-PROV-FIELD-MISSING"
