//! `nim.cfg` emission from a resolved graph (RFC §6 S9; `spec/nimcfg.md` /
//! conformance-fixtures §2). Mirrors `milpa/nimcfg.py:format_nimcfg`.
//!
//! One `--path:"…"` line per resolved dep so the Nim compiler finds each dep's
//! source tree — no nimble involvement. The output is byte-exact and
//! deterministic: emission order is **lexicographic by dep name** (the spec's
//! single canonical ordering rule, resolver-semantics §4.4 — a toposort's
//! sibling tie-break is not reproducible across implementations, lexicographic
//! is, and it matches the lockfile's own dep-entry order).
//!
//! Per-member workspace emission (`write_workspace_nimcfgs`) and feature-flag
//! `-d:` defines (#23) are deferred: workspace lands in S11, and `ResolvedDep`
//! does not yet carry `active_flags`/`flag_defines` (no success fixture resolves
//! a flag-carrying dep — same deferral as `from_graph`'s flag fields).

use std::collections::{BTreeSet, HashMap};
use std::path::{Path, PathBuf};

use milpa_types::{ResolvedDep, ResolvedGraph};

use crate::workspace::LoadedWorkspace;

/// The normative `nim.cfg` header (conformance-fixtures §2). Stored without its
/// trailing newline; the join below re-introduces line breaks.
const HEADER: &str =
    "# generated by milpa; do not edit\n# manifest: milpa.kdl\n# lockfile: milpa.lock";

/// Render `graph` into `nim.cfg` text.
///
/// `deps_dir` is the POSIX-relative deps directory (`"_deps"`); paths always use
/// `/` regardless of host OS (nim.cfg syntax is OS-agnostic). `self_src_dir`, when
/// non-empty, adds a leading `--path:"<self_src_dir>"` for the consuming
/// package's own source tree (emitted first so self-modules shadow same-named
/// dep import paths).
pub fn format_nimcfg(graph: &ResolvedGraph, deps_dir: &str, self_src_dir: &str) -> String {
    let mut lines: Vec<String> = vec![HEADER.to_string(), String::new()];

    if !self_src_dir.is_empty() {
        lines.push(format!("--path:\"{self_src_dir}\""));
    }

    let mut ordered: Vec<&ResolvedDep> = graph.deps.iter().collect();
    ordered.sort_by(|a, b| a.name.cmp(&b.name));
    for dep in &ordered {
        lines.push(format!("--path:\"{}\"", path_for(dep, deps_dir)));
        // B-nimcfg: emit one --path: per alias (already lex-sorted on dep.aliases).
        // Each alias path mirrors the canonical: _deps/<alias>[/<src_dir>].
        for alias in &dep.aliases {
            let mut alias_path = format!("{deps_dir}/{alias}");
            if !dep.src_dir.is_empty() {
                alias_path.push('/');
                alias_path.push_str(&dep.src_dir);
            }
            lines.push(format!("--path:\"{alias_path}\""));
        }
    }

    // A trailing blank line (→ final newline) whenever any --path: line was
    // emitted (self_src_dir OR deps). Mirrors Python's `if path_lines:` guard —
    // keying on the dep list alone was wrong: self_src_dir alone (zero deps)
    // still needs the final \n (§7.4 NOTE: files end with a single trailing \n).
    // `lines` starts with [HEADER, ""] (length 2); any --path: push makes it > 2.
    if lines.len() > 2 {
        lines.push(String::new());
    }
    lines.join("\n")
}

/// `<deps_dir>/<name>[/<src_dir>]` in POSIX form.
fn path_for(dep: &ResolvedDep, deps_dir: &str) -> String {
    let mut base = format!("{deps_dir}/{}", dep.name);
    if !dep.src_dir.is_empty() {
        base.push('/');
        base.push_str(&dep.src_dir);
    }
    base
}

// ---------------------------------------------------------------------------
// Workspace: per-member nim.cfg (W4 / lockfile §7.6)
// ---------------------------------------------------------------------------

/// Render one `nim.cfg` per workspace member, keyed by the member's as-declared
/// workspace-relative `path`. Mirrors `nimcfg.py:format_workspace_nimcfgs`: each
/// member lists only its transitively-reachable deps (Nim per-member isolation),
/// with POSIX-relative `--path:` lines from the member's directory — external
/// deps under `<root>/_deps/<name>[/src]`, member refs under
/// `<root>/<other-member-path>[/src]`. There is **no** root `nim.cfg`.
pub fn format_workspace_nimcfgs(
    workspace: &LoadedWorkspace,
    graph: &ResolvedGraph,
) -> Vec<(String, String)> {
    let deps_dir = workspace.root.join("_deps");
    let member_dir: HashMap<&str, &Path> = workspace
        .members
        .iter()
        .map(|m| (m.name.as_str(), m.directory.as_path()))
        .collect();

    let mut out: Vec<(String, String)> = Vec::new();
    for member in &workspace.members {
        let mut lines: Vec<String> = vec![HEADER.to_string(), String::new()];
        let mut closure = member_dep_closure(graph, &member.name);
        closure.sort_by(|a, b| a.name.cmp(&b.name));
        for dep in &closure {
            let target = dep_target(dep, &deps_dir, &member_dir);
            let rel = relpath(&target, &member.directory);
            lines.push(format!("--path:\"{}\"", posix(&rel)));
        }
        if !closure.is_empty() {
            lines.push(String::new());
        }
        out.push((member.path.clone(), lines.join("\n")));
    }
    out
}

/// The on-disk source path of a dep: a member resolves to its member directory,
/// an external dep to `<deps_dir>/<name>`; `src_dir` is appended when declared.
fn dep_target(dep: &ResolvedDep, deps_dir: &Path, member_dir: &HashMap<&str, &Path>) -> PathBuf {
    let base = match member_dir.get(dep.name.as_str()) {
        Some(dir) => dir.to_path_buf(),
        None => deps_dir.join(&dep.name),
    };
    if dep.src_dir.is_empty() {
        base
    } else {
        base.join(&dep.src_dir)
    }
}

/// Transitive closure reachable from `member_name` (excluding the member itself),
/// in topological order. Mirrors `nimcfg.py:member_dep_closure`.
fn member_dep_closure<'a>(graph: &'a ResolvedGraph, member_name: &str) -> Vec<&'a ResolvedDep> {
    let by_name: HashMap<&str, &ResolvedDep> =
        graph.deps.iter().map(|d| (d.name.as_str(), d)).collect();
    let mut visited: BTreeSet<String> = BTreeSet::new();
    let mut order: Vec<&ResolvedDep> = Vec::new();

    fn visit<'a>(
        name: &str,
        by_name: &HashMap<&str, &'a ResolvedDep>,
        visited: &mut BTreeSet<String>,
        order: &mut Vec<&'a ResolvedDep>,
    ) {
        if visited.contains(name) {
            return;
        }
        let Some(dep) = by_name.get(name) else {
            return;
        };
        visited.insert(name.to_string());
        for req in &dep.requires {
            visit(req, by_name, visited, order);
        }
        order.push(dep);
    }

    if let Some(member) = by_name.get(member_name) {
        for req in &member.requires {
            visit(req, &by_name, &mut visited, &mut order);
        }
    }
    order
}

/// Lexical relative path from `base` (a directory) to `target`, like Python's
/// `os.path.relpath(target, start=base)`. Both are expected absolute.
fn relpath(target: &Path, base: &Path) -> PathBuf {
    use std::path::Component;
    let t: Vec<Component> = target.components().collect();
    let b: Vec<Component> = base.components().collect();
    let common = t.iter().zip(b.iter()).take_while(|(a, c)| a == c).count();
    let mut out = PathBuf::new();
    for _ in 0..(b.len() - common) {
        out.push("..");
    }
    for comp in &t[common..] {
        out.push(comp.as_os_str());
    }
    if out.as_os_str().is_empty() {
        out.push(".");
    }
    out
}

/// Render a path with POSIX separators (nim.cfg syntax is OS-agnostic).
fn posix(p: &Path) -> String {
    p.components()
        .map(|c| c.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use milpa_types::{ProvenanceRecord, Version};

    fn dep(name: &str, src_dir: &str) -> ResolvedDep {
        ResolvedDep {
            name: name.into(),
            identity: "sha256:00".into(),
            version: Version::release(0, 0, 1),
            src_dir: src_dir.into(),
            requires: vec![],
            provenances: vec![ProvenanceRecord::Git {
                url: "https://e/x.git".into(),
                ref_spec: Some("main".into()),
                commit_sha: None,
                origin: "observed".into(),
            }],
            dep_decl: None,
            cond_requires: vec![],
            aliases: vec![],
        }
    }

    #[test]
    fn single_dep_with_src_dir() {
        let graph = ResolvedGraph {
            deps: vec![dep("foo", "src")],
        };
        assert_eq!(
            format_nimcfg(&graph, "_deps", ""),
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n\
             \n\
             --path:\"_deps/foo/src\"\n"
        );
    }

    #[test]
    fn no_deps_has_no_trailing_path_block() {
        let graph = ResolvedGraph { deps: vec![] };
        // No self_src_dir, no deps → header only, trailing \n (no --path: block).
        assert_eq!(
            format_nimcfg(&graph, "_deps", ""),
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n"
        );
    }

    /// fixture-180: self_src_dir "src" with zero deps → trailing \n present.
    /// Regression for the cross-impl byte divergence where Rust keyed the
    /// trailing-newline guard on `graph.deps.is_empty()` instead of whether
    /// any --path: line was emitted.
    #[test]
    fn self_src_dir_no_deps_has_trailing_newline() {
        let graph = ResolvedGraph { deps: vec![] };
        assert_eq!(
            format_nimcfg(&graph, "_deps", "src"),
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n\
             \n\
             --path:\"src\"\n"
        );
    }

    #[test]
    fn deps_emit_lexicographically_not_in_graph_order() {
        let graph = ResolvedGraph {
            deps: vec![dep("zlib", ""), dep("alpha", "lib")],
        };
        let out = format_nimcfg(&graph, "_deps", "");
        let a = out.find("_deps/alpha/lib").unwrap();
        let z = out.find("_deps/zlib").unwrap();
        assert!(a < z, "alpha must precede zlib");
    }

    #[test]
    fn self_src_dir_is_emitted_before_deps() {
        let graph = ResolvedGraph {
            deps: vec![dep("foo", "src")],
        };
        let out = format_nimcfg(&graph, "_deps", "mysrc");
        let self_idx = out.find("--path:\"mysrc\"").unwrap();
        let dep_idx = out.find("_deps/foo/src").unwrap();
        assert!(self_idx < dep_idx);
    }

    fn dep_with_aliases(name: &str, src_dir: &str, aliases: Vec<String>) -> ResolvedDep {
        ResolvedDep {
            name: name.into(),
            identity: "sha256:00".into(),
            version: Version::release(0, 0, 1),
            src_dir: src_dir.into(),
            requires: vec![],
            provenances: vec![ProvenanceRecord::Git {
                url: "https://e/x.git".into(),
                ref_spec: Some("main".into()),
                commit_sha: None,
                origin: "observed".into(),
            }],
            dep_decl: None,
            cond_requires: vec![],
            aliases,
        }
    }

    /// B-nimcfg: single alias → canonical --path: + alias --path:, canonical first.
    #[test]
    fn alias_emits_path_line_after_canonical() {
        let graph = ResolvedGraph {
            deps: vec![dep_with_aliases("foo", "src", vec!["bar".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "");
        let path_lines: Vec<&str> = out
            .lines()
            .filter(|l| l.starts_with("--path:"))
            .collect();
        assert_eq!(path_lines.len(), 2, "expected 2 --path: lines; got {path_lines:?}");
        assert_eq!(path_lines[0], "--path:\"_deps/foo/src\"");
        assert_eq!(path_lines[1], "--path:\"_deps/bar/src\"");
    }

    /// B-nimcfg: two aliases → canonical first, then aliases lex-sorted.
    #[test]
    fn two_aliases_lex_ordered() {
        let graph = ResolvedGraph {
            deps: vec![dep_with_aliases("foo", "src", vec!["bar".into(), "qux".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "");
        let path_lines: Vec<&str> = out
            .lines()
            .filter(|l| l.starts_with("--path:"))
            .collect();
        assert_eq!(path_lines.len(), 3);
        assert_eq!(path_lines[0], "--path:\"_deps/foo/src\"");
        assert_eq!(path_lines[1], "--path:\"_deps/bar/src\"");
        assert_eq!(path_lines[2], "--path:\"_deps/qux/src\"");
    }

    /// B-nimcfg: no alias → unchanged single --path: line.
    #[test]
    fn no_alias_unchanged() {
        let graph = ResolvedGraph {
            deps: vec![dep_with_aliases("foo", "src", vec![])],
        };
        let out = format_nimcfg(&graph, "_deps", "");
        let path_lines: Vec<&str> = out
            .lines()
            .filter(|l| l.starts_with("--path:"))
            .collect();
        assert_eq!(path_lines.len(), 1);
        assert_eq!(path_lines[0], "--path:\"_deps/foo/src\"");
    }

    /// B-nimcfg: fixture-173 exact byte match.
    #[test]
    fn fixture_173_byte_exact() {
        let graph = ResolvedGraph {
            deps: vec![dep_with_aliases("foo", "src", vec!["bar".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "");
        assert_eq!(
            out,
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n\
             \n\
             --path:\"_deps/foo/src\"\n\
             --path:\"_deps/bar/src\"\n"
        );
    }
}
