//! `nim.cfg` emission from a resolved graph (RFC §6 S9; `spec/nimcfg.md` /
//! conformance-fixtures §2). Mirrors `milpa/nimcfg.py:format_nimcfg`.
//!
//! One `--path:"…"` line per resolved dep so the Nim compiler finds each dep's
//! source tree — no nimble involvement. The output is byte-exact and
//! deterministic: emission order is **lexicographic by dep name** (the spec's
//! single canonical ordering rule, resolver-semantics §4.4 — a toposort's
//! sibling tie-break is not reproducible across implementations, lexicographic
//! is, and it matches the lockfile's own dep-entry order).
//!
//! Feature-flag `-d:` defines (§7.5) are un-deferred by RFC #23 S6: callers
//! pass a `flag_defines` map (`dep_name → flag_name → defines_symbols`), built
//! from each dep's manifest (SSOT — defines live in manifests, not the lockfile).
//! When `None`, no `-d:` lines are emitted (backward-compat for callers that do
//! not supply the map).

use std::collections::{BTreeSet, HashMap};
use std::path::{Path, PathBuf};

use milpa_types::{ResolvedDep, ResolvedGraph};

use crate::workspace::LoadedWorkspace;

/// The normative `nim.cfg` header (conformance-fixtures §2). Stored without its
/// trailing newline; the join below re-introduces line breaks.
const HEADER: &str =
    "# generated by milpa; do not edit\n# manifest: milpa.kdl\n# lockfile: milpa.lock";

/// Render `graph` into `nim.cfg` text.
///
/// `deps_dir` is the POSIX-relative deps directory (`"_deps"`); paths always use
/// `/` regardless of host OS (nim.cfg syntax is OS-agnostic). `self_src_dir`, when
/// non-empty, adds a leading `--path:"<self_src_dir>"` for the consuming
/// package's own source tree (emitted first so self-modules shadow same-named
/// dep import paths).
///
/// `flag_defines` maps `dep_name → flag_name → defines_symbols`. When `Some`,
/// active flags for each dep are looked up and their symbols emitted as `-d:` lines
/// in a block separated from the `--path:` block by a blank line (§7.5, RFC #23 S6).
/// Symbols are lexicographically sorted across all active flags of all deps.
/// A flag with no explicit defines uses the childless convention: `-d:<pkg>_<flag>`.
/// When `None`, no `-d:` lines are emitted (backward-compat for callers that do not
/// supply manifest flag tables).
pub fn format_nimcfg(
    graph: &ResolvedGraph,
    deps_dir: &str,
    self_src_dir: &str,
    flag_defines: Option<&HashMap<String, HashMap<String, Vec<String>>>>,
) -> String {
    let mut lines: Vec<String> = vec![HEADER.to_string(), String::new()];

    if !self_src_dir.is_empty() {
        lines.push(format!("--path:\"{self_src_dir}\""));
    }

    let mut ordered: Vec<&ResolvedDep> = graph.deps.iter().collect();
    ordered.sort_by(|a, b| a.name.cmp(&b.name));
    for dep in &ordered {
        lines.push(format!("--path:\"{}\"", path_for(dep, deps_dir)));
        // B-nimcfg: emit one --path: per alias (already lex-sorted on dep.aliases).
        // Each alias path mirrors the canonical: _deps/<alias>[/<src_dir>].
        for alias in &dep.aliases {
            let mut alias_path = format!("{deps_dir}/{alias}");
            if !dep.src_dir.is_empty() {
                alias_path.push('/');
                alias_path.push_str(&dep.src_dir);
            }
            lines.push(format!("--path:\"{alias_path}\""));
        }
    }

    // §7.5 feature-flag defines — un-deferred (RFC #23 S6).
    // Collect all -d: symbols across all deps with active flags.
    let mut define_symbols: Vec<String> = Vec::new();
    if let Some(fd_map) = flag_defines {
        for dep in &ordered {
            if dep.active_flags.is_empty() {
                continue;
            }
            let empty_map = HashMap::new();
            let dep_flag_table = fd_map.get(&dep.name).unwrap_or(&empty_map);
            for flag_name in &dep.active_flags {
                if let Some(syms) = dep_flag_table.get(flag_name) {
                    if syms.is_empty() {
                        // Childless-convention: -d:<pkg>_<flag>
                        define_symbols.push(format!("{}_{}", dep.name, flag_name));
                    } else {
                        define_symbols.extend(syms.iter().cloned());
                    }
                }
                // Flag not in dep_flag_table: skip (dep has no manifest, or flag
                // not declared — matches Python's warn-and-skip behavior).
            }
        }
        // Lexicographic order across all emitted symbols (reproducibility, §3.6).
        define_symbols.sort();
    }

    // A trailing blank line (→ final newline) whenever any --path: line was
    // emitted (self_src_dir OR deps). Mirrors Python's `if path_lines:` guard —
    // keying on the dep list alone was wrong: self_src_dir alone (zero deps)
    // still needs the final \n (§7.4 NOTE: files end with a single trailing \n).
    // `lines` starts with [HEADER, ""] (length 2); any --path: push makes it > 2.
    if lines.len() > 2 {
        if !define_symbols.is_empty() {
            // Blank line separator between --path: block and -d: block (§7.5).
            lines.push(String::new());
            for sym in &define_symbols {
                lines.push(format!("-d:{sym}"));
            }
        }
        lines.push(String::new());
    }
    lines.join("\n")
}

/// `<deps_dir>/<name>[/<src_dir>]` in POSIX form.
fn path_for(dep: &ResolvedDep, deps_dir: &str) -> String {
    let mut base = format!("{deps_dir}/{}", dep.name);
    if !dep.src_dir.is_empty() {
        base.push('/');
        base.push_str(&dep.src_dir);
    }
    base
}

// ---------------------------------------------------------------------------
// build_flag_defines — product function (RFC #23 S6 SSOT)
// ---------------------------------------------------------------------------

/// Build the `flag_defines` map for [`format_nimcfg`] (§7.5 S6, RFC #23 §3.6).
///
/// Reads each dep's `milpa.kdl` from `deps_dir/<name>/milpa.kdl` (SSOT —
/// defines live in the manifest, not the lockfile).  Missing or unparseable
/// manifests produce an empty flag table for that dep (warn-and-skip, not an
/// error — not every dep has a `milpa.kdl`).
///
/// Returns `dep_name → flag_name → defines_symbols`.
///
/// This is the SINGLE map-builder for S6.  Both the real CLI (`milpa fetch` /
/// `milpa lock`) and the conformance test harness call this function; there
/// must be no parallel copy in either crate.
pub fn build_flag_defines(
    graph: &milpa_types::ResolvedGraph,
    deps_dir: &std::path::Path,
) -> HashMap<String, HashMap<String, Vec<String>>> {
    let mut result: HashMap<String, HashMap<String, Vec<String>>> = HashMap::new();
    for dep in &graph.deps {
        let manifest_path = deps_dir.join(&dep.name).join("milpa.kdl");
        let text = match std::fs::read_to_string(&manifest_path) {
            Ok(t) => t,
            Err(_) => continue,
        };
        let manifest = match crate::parse_document(&text) {
            Ok(milpa_manifest::ManifestDoc::Package(m)) => m,
            _ => continue,
        };
        let flag_map: HashMap<String, Vec<String>> = manifest
            .flags
            .into_iter()
            .map(|f| (f.name, f.defines))
            .collect();
        result.insert(dep.name.clone(), flag_map);
    }
    result
}

// ---------------------------------------------------------------------------
// Workspace: per-member nim.cfg (W4 / lockfile §7.6)
// ---------------------------------------------------------------------------

/// Render one `nim.cfg` per workspace member, keyed by the member's as-declared
/// workspace-relative `path`. Mirrors `nimcfg.py:format_workspace_nimcfgs`: each
/// member lists only its transitively-reachable deps (Nim per-member isolation),
/// with POSIX-relative `--path:` lines from the member's directory — external
/// deps under `<root>/_deps/<name>[/src]`, member refs under
/// `<root>/<other-member-path>[/src]`. There is **no** root `nim.cfg`.
///
/// S11 (RFC #23 §3.8): when `flag_defines` is `Some`, each member's nim.cfg
/// includes `-d:` defines for ALL flags active on shared deps in the workspace
/// graph (the unified `dep.active_flags`). Symbols are lexicographically sorted
/// across all active flags of all deps in the member's transitive closure
/// (reproducibility, §3.6). When `None`, no `-d:` lines are emitted
/// (backward-compat for callers that don't supply manifest flag tables).
pub fn format_workspace_nimcfgs(
    workspace: &LoadedWorkspace,
    graph: &ResolvedGraph,
    flag_defines: Option<&HashMap<String, HashMap<String, Vec<String>>>>,
) -> Vec<(String, String)> {
    let deps_dir = workspace.root.join("_deps");
    let member_dir: HashMap<&str, &Path> = workspace
        .members
        .iter()
        .map(|m| (m.name.as_str(), m.directory.as_path()))
        .collect();

    let mut out: Vec<(String, String)> = Vec::new();
    for member in &workspace.members {
        let mut lines: Vec<String> = vec![HEADER.to_string(), String::new()];
        let mut closure = member_dep_closure(graph, &member.name);
        closure.sort_by(|a, b| a.name.cmp(&b.name));
        for dep in &closure {
            let target = dep_target(dep, &deps_dir, &member_dir);
            let rel = relpath(&target, &member.directory);
            lines.push(format!("--path:\"{}\"", posix(&rel)));
        }

        // S11 §3.8: collect unified -d: defines from active_flags on closure deps.
        // Uses the same logic as format_nimcfg §7.5 — active_flags on each dep
        // are already the workspace-wide union (merged by the shared dep_active_flags
        // map in the resolver).
        let mut define_symbols: Vec<String> = Vec::new();
        if let Some(fd_map) = flag_defines {
            let empty_map = HashMap::new();
            for dep in &closure {
                if dep.active_flags.is_empty() {
                    continue;
                }
                let dep_flag_table = fd_map.get(&dep.name).unwrap_or(&empty_map);
                for flag_name in &dep.active_flags {
                    if let Some(syms) = dep_flag_table.get(flag_name) {
                        if syms.is_empty() {
                            // Childless-convention: -d:<pkg>_<flag>
                            define_symbols.push(format!("{}_{}", dep.name, flag_name));
                        } else {
                            define_symbols.extend(syms.iter().cloned());
                        }
                    }
                    // Flag not in dep_flag_table: skip (no manifest or undeclared).
                }
            }
            define_symbols.sort();
        }

        if !closure.is_empty() {
            if !define_symbols.is_empty() {
                // Blank line separator between --path: block and -d: block (§7.5).
                lines.push(String::new());
                for sym in &define_symbols {
                    lines.push(format!("-d:{sym}"));
                }
            }
            lines.push(String::new());
        }
        out.push((member.path.clone(), lines.join("\n")));
    }
    out
}

/// The on-disk source path of a dep: a member resolves to its member directory,
/// an external dep to `<deps_dir>/<name>`; `src_dir` is appended when declared.
fn dep_target(dep: &ResolvedDep, deps_dir: &Path, member_dir: &HashMap<&str, &Path>) -> PathBuf {
    let base = match member_dir.get(dep.name.as_str()) {
        Some(dir) => dir.to_path_buf(),
        None => deps_dir.join(&dep.name),
    };
    if dep.src_dir.is_empty() {
        base
    } else {
        base.join(&dep.src_dir)
    }
}

/// Transitive closure reachable from `member_name` (excluding the member itself),
/// in topological order. Mirrors `nimcfg.py:member_dep_closure`.
fn member_dep_closure<'a>(graph: &'a ResolvedGraph, member_name: &str) -> Vec<&'a ResolvedDep> {
    let by_name: HashMap<&str, &ResolvedDep> =
        graph.deps.iter().map(|d| (d.name.as_str(), d)).collect();
    let mut visited: BTreeSet<String> = BTreeSet::new();
    let mut order: Vec<&ResolvedDep> = Vec::new();

    fn visit<'a>(
        name: &str,
        by_name: &HashMap<&str, &'a ResolvedDep>,
        visited: &mut BTreeSet<String>,
        order: &mut Vec<&'a ResolvedDep>,
    ) {
        if visited.contains(name) {
            return;
        }
        let Some(dep) = by_name.get(name) else {
            return;
        };
        visited.insert(name.to_string());
        for req in &dep.requires {
            visit(req, by_name, visited, order);
        }
        order.push(dep);
    }

    if let Some(member) = by_name.get(member_name) {
        for req in &member.requires {
            visit(req, &by_name, &mut visited, &mut order);
        }
    }
    order
}

/// Lexical relative path from `base` (a directory) to `target`, like Python's
/// `os.path.relpath(target, start=base)`. Both are expected absolute.
fn relpath(target: &Path, base: &Path) -> PathBuf {
    use std::path::Component;
    let t: Vec<Component> = target.components().collect();
    let b: Vec<Component> = base.components().collect();
    let common = t.iter().zip(b.iter()).take_while(|(a, c)| a == c).count();
    let mut out = PathBuf::new();
    for _ in 0..(b.len() - common) {
        out.push("..");
    }
    for comp in &t[common..] {
        out.push(comp.as_os_str());
    }
    if out.as_os_str().is_empty() {
        out.push(".");
    }
    out
}

/// Render a path with POSIX separators (nim.cfg syntax is OS-agnostic).
fn posix(p: &Path) -> String {
    p.components()
        .map(|c| c.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use milpa_types::{ProvenanceRecord, Version};

    fn dep(name: &str, src_dir: &str) -> ResolvedDep {
        ResolvedDep {
            name: name.into(),
            identity: "sha256:00".into(),
            version: Version::release(0, 0, 1),
            src_dir: src_dir.into(),
            requires: vec![],
            provenances: vec![ProvenanceRecord::Git {
                url: "https://e/x.git".into(),
                ref_spec: Some("main".into()),
                commit_sha: None,
                origin: "observed".into(),
            }],
            dep_decl: None,
            cond_requires: vec![],
            aliases: vec![],
            active_flags: vec![],
        }
    }

    #[test]
    fn single_dep_with_src_dir() {
        let graph = ResolvedGraph {
            deps: vec![dep("foo", "src")],
        };
        assert_eq!(
            format_nimcfg(&graph, "_deps", "", None),
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n\
             \n\
             --path:\"_deps/foo/src\"\n"
        );
    }

    #[test]
    fn no_deps_has_no_trailing_path_block() {
        let graph = ResolvedGraph { deps: vec![] };
        // No self_src_dir, no deps → header only, trailing \n (no --path: block).
        assert_eq!(
            format_nimcfg(&graph, "_deps", "", None),
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n"
        );
    }

    /// fixture-180: self_src_dir "src" with zero deps → trailing \n present.
    /// Regression for the cross-impl byte divergence where Rust keyed the
    /// trailing-newline guard on `graph.deps.is_empty()` instead of whether
    /// any --path: line was emitted.
    #[test]
    fn self_src_dir_no_deps_has_trailing_newline() {
        let graph = ResolvedGraph { deps: vec![] };
        assert_eq!(
            format_nimcfg(&graph, "_deps", "src", None),
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n\
             \n\
             --path:\"src\"\n"
        );
    }

    #[test]
    fn deps_emit_lexicographically_not_in_graph_order() {
        let graph = ResolvedGraph {
            deps: vec![dep("zlib", ""), dep("alpha", "lib")],
        };
        let out = format_nimcfg(&graph, "_deps", "", None);
        let a = out.find("_deps/alpha/lib").unwrap();
        let z = out.find("_deps/zlib").unwrap();
        assert!(a < z, "alpha must precede zlib");
    }

    #[test]
    fn self_src_dir_is_emitted_before_deps() {
        let graph = ResolvedGraph {
            deps: vec![dep("foo", "src")],
        };
        let out = format_nimcfg(&graph, "_deps", "mysrc", None);
        let self_idx = out.find("--path:\"mysrc\"").unwrap();
        let dep_idx = out.find("_deps/foo/src").unwrap();
        assert!(self_idx < dep_idx);
    }

    fn dep_with_aliases(name: &str, src_dir: &str, aliases: Vec<String>) -> ResolvedDep {
        ResolvedDep {
            name: name.into(),
            identity: "sha256:00".into(),
            version: Version::release(0, 0, 1),
            src_dir: src_dir.into(),
            requires: vec![],
            provenances: vec![ProvenanceRecord::Git {
                url: "https://e/x.git".into(),
                ref_spec: Some("main".into()),
                commit_sha: None,
                origin: "observed".into(),
            }],
            dep_decl: None,
            cond_requires: vec![],
            aliases,
            active_flags: vec![],
        }
    }

    /// B-nimcfg: single alias → canonical --path: + alias --path:, canonical first.
    #[test]
    fn alias_emits_path_line_after_canonical() {
        let graph = ResolvedGraph {
            deps: vec![dep_with_aliases("foo", "src", vec!["bar".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "", None);
        let path_lines: Vec<&str> = out
            .lines()
            .filter(|l| l.starts_with("--path:"))
            .collect();
        assert_eq!(path_lines.len(), 2, "expected 2 --path: lines; got {path_lines:?}");
        assert_eq!(path_lines[0], "--path:\"_deps/foo/src\"");
        assert_eq!(path_lines[1], "--path:\"_deps/bar/src\"");
    }

    /// B-nimcfg: two aliases → canonical first, then aliases lex-sorted.
    #[test]
    fn two_aliases_lex_ordered() {
        let graph = ResolvedGraph {
            deps: vec![dep_with_aliases("foo", "src", vec!["bar".into(), "qux".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "", None);
        let path_lines: Vec<&str> = out
            .lines()
            .filter(|l| l.starts_with("--path:"))
            .collect();
        assert_eq!(path_lines.len(), 3);
        assert_eq!(path_lines[0], "--path:\"_deps/foo/src\"");
        assert_eq!(path_lines[1], "--path:\"_deps/bar/src\"");
        assert_eq!(path_lines[2], "--path:\"_deps/qux/src\"");
    }

    /// B-nimcfg: no alias → unchanged single --path: line.
    #[test]
    fn no_alias_unchanged() {
        let graph = ResolvedGraph {
            deps: vec![dep_with_aliases("foo", "src", vec![])],
        };
        let out = format_nimcfg(&graph, "_deps", "", None);
        let path_lines: Vec<&str> = out
            .lines()
            .filter(|l| l.starts_with("--path:"))
            .collect();
        assert_eq!(path_lines.len(), 1);
        assert_eq!(path_lines[0], "--path:\"_deps/foo/src\"");
    }

    /// B-nimcfg: fixture-173 exact byte match.
    #[test]
    fn fixture_173_byte_exact() {
        let graph = ResolvedGraph {
            deps: vec![dep_with_aliases("foo", "src", vec!["bar".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "", None);
        assert_eq!(
            out,
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n\
             \n\
             --path:\"_deps/foo/src\"\n\
             --path:\"_deps/bar/src\"\n"
        );
    }

    // -------------------------------------------------------------------------
    // §7.5 S6 — feature-flag -d: defines (RFC #23 §3.6)
    // -------------------------------------------------------------------------

    fn dep_with_flags(name: &str, active_flags: Vec<String>) -> ResolvedDep {
        ResolvedDep {
            name: name.into(),
            identity: "sha256:00".into(),
            version: Version::release(0, 0, 1),
            src_dir: String::new(),
            requires: vec![],
            provenances: vec![ProvenanceRecord::Git {
                url: "https://e/x.git".into(),
                ref_spec: Some("main".into()),
                commit_sha: None,
                origin: "observed".into(),
            }],
            dep_decl: None,
            cond_requires: vec![],
            aliases: vec![],
            active_flags,
        }
    }

    /// No flag_defines (None) → no -d: lines.
    #[test]
    fn no_defines_when_flag_defines_none() {
        let graph = ResolvedGraph {
            deps: vec![dep_with_flags("pkg", vec!["tls".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "", None);
        assert!(!out.contains("-d:"));
    }

    /// Explicit defines: active flag with symbols emits -d: lines.
    #[test]
    fn explicit_defines_emitted() {
        let mut fd: HashMap<String, HashMap<String, Vec<String>>> = HashMap::new();
        let mut flags = HashMap::new();
        flags.insert("tls".into(), vec!["ssl".into(), "useOpenSSL".into()]);
        fd.insert("ssl-lib".into(), flags);

        let graph = ResolvedGraph {
            deps: vec![dep_with_flags("ssl-lib", vec!["tls".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "", Some(&fd));
        assert!(out.contains("-d:ssl\n"));
        assert!(out.contains("-d:useOpenSSL\n") || out.ends_with("-d:useOpenSSL\n"));
    }

    /// Childless-convention: active flag with no defines emits -d:<pkg>_<flag>.
    #[test]
    fn childless_convention() {
        let mut fd: HashMap<String, HashMap<String, Vec<String>>> = HashMap::new();
        let mut flags = HashMap::new();
        flags.insert("http".into(), vec![]);
        fd.insert("mylib".into(), flags);

        let graph = ResolvedGraph {
            deps: vec![dep_with_flags("mylib", vec!["http".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "", Some(&fd));
        assert!(out.contains("-d:mylib_http"), "got: {out:?}");
    }

    /// Defines block is separated from --path: block by a blank line.
    #[test]
    fn defines_block_blank_line_separation() {
        let mut fd: HashMap<String, HashMap<String, Vec<String>>> = HashMap::new();
        let mut flags = HashMap::new();
        flags.insert("feat".into(), vec!["myDefine".into()]);
        fd.insert("pkg".into(), flags);

        let graph = ResolvedGraph {
            deps: vec![dep_with_flags("pkg", vec!["feat".into()])],
        };
        let out = format_nimcfg(&graph, "_deps", "", Some(&fd));
        let path_pos = out.find("--path:").unwrap();
        let define_pos = out.find("-d:myDefine").unwrap();
        assert!(define_pos > path_pos);
        let between = &out[path_pos..define_pos];
        assert!(between.contains("\n\n"), "expected blank line separator; got {between:?}");
    }

    /// All -d: symbols are lexicographically sorted across all deps.
    #[test]
    fn defines_lexicographically_ordered() {
        let mut fd: HashMap<String, HashMap<String, Vec<String>>> = HashMap::new();
        let mut flags_a = HashMap::new();
        flags_a.insert("feat-z".into(), vec!["zzz".into(), "aaa".into()]);
        fd.insert("lib-a".into(), flags_a);
        let mut flags_b = HashMap::new();
        flags_b.insert("feat-a".into(), vec!["mmm".into()]);
        fd.insert("lib-b".into(), flags_b);

        let graph = ResolvedGraph {
            deps: vec![
                dep_with_flags("lib-a", vec!["feat-z".into()]),
                dep_with_flags("lib-b", vec!["feat-a".into()]),
            ],
        };
        let out = format_nimcfg(&graph, "_deps", "", Some(&fd));
        let d_lines: Vec<&str> = out.lines().filter(|l| l.starts_with("-d:")).collect();
        let mut expected = d_lines.clone();
        expected.sort();
        assert_eq!(d_lines, expected, "expected lex order; got {d_lines:?}");
    }

    /// No active flags → no -d: block even with flag_defines provided.
    #[test]
    fn no_active_flags_no_defines_block() {
        let mut fd: HashMap<String, HashMap<String, Vec<String>>> = HashMap::new();
        let mut flags = HashMap::new();
        flags.insert("tls".into(), vec!["ssl".into()]);
        fd.insert("pkg".into(), flags);

        let graph = ResolvedGraph {
            deps: vec![dep("pkg", "")],  // dep() has active_flags = vec![]
        };
        let out = format_nimcfg(&graph, "_deps", "", Some(&fd));
        assert!(!out.contains("-d:"));
    }

    /// fixture-197 byte-exact: two deps — one explicit defines, one childless.
    /// Mirrors the conformance fixture-197-s6-nimcfg-defines expected/nim.cfg.
    #[test]
    fn fixture_197_byte_exact() {
        let mut fd: HashMap<String, HashMap<String, Vec<String>>> = HashMap::new();
        let mut ssl_flags = HashMap::new();
        ssl_flags.insert("tls".into(), vec!["ssl".into(), "useOpenSSL".into()]);
        fd.insert("lib-ssl".into(), ssl_flags);
        let mut childless_flags = HashMap::new();
        childless_flags.insert("http".into(), vec![]);
        fd.insert("lib-childless".into(), childless_flags);

        let graph = ResolvedGraph {
            deps: vec![
                dep_with_flags("lib-childless", vec!["http".into()]),
                dep_with_flags("lib-ssl", vec!["tls".into()]),
            ],
        };
        let out = format_nimcfg(&graph, "_deps", "", Some(&fd));
        assert_eq!(
            out,
            "# generated by milpa; do not edit\n\
             # manifest: milpa.kdl\n\
             # lockfile: milpa.lock\n\
             \n\
             --path:\"_deps/lib-childless\"\n\
             --path:\"_deps/lib-ssl\"\n\
             \n\
             -d:lib-childless_http\n\
             -d:ssl\n\
             -d:useOpenSSL\n"
        );
    }
}
