"""milpa.lock — reproducible-build snapshot of a resolved dep graph.

Owns:
  - ProvenanceRecord discriminated union (6 variants + 1 read-compat variant)
  - LockedDep, Lockfile — lockfile data model
  - ResolvedDep, ResolvedGraph — resolver output types (owned here to avoid
    forward-import cycles: resolver.py imports and *produces* these types;
    lockfile.py owns them so from_graph/verify need no fetcher/resolver import)
  - parse_lockfile(text) -> Lockfile
  - from_graph(graph, *, strategy) -> Lockfile
  - format_lockfile(lock) -> str  — byte-exact hand-rolled templating (SSOT)
  - verify_against_graph(lockfile, graph) -> None
  - verify_lockfile_against_deps(lockfile, deps_dir) -> list[str]

Layering: lockfile.py ← resolver.py (resolver imports ResolvedDep/ResolvedGraph
from lockfile, not the other way). See RFC §4.2.

Format: KDL 2.0 via kdl_io.parse_kdl(text, context="lockfile") for parsing.
Emission is hand-rolled string templating — the lockfile NEVER goes through a
KDL AST emitter. _kdl_str is the single source of truth for string escaping.

ProvenanceRecord kinds (lockfile-schema.md §4):
    git      — §4.1: url (req), ref (opt), commit_sha (opt)
    tarball  — §4.2: url (req), sha256 (opt, TOFU receipt)
    local    — §4.3: path (req, as-declared relative)
    member   — §4.4: name (req, workspace member name)
    oci      — §4.5: registry/repository/digest (all req)
    registry — §4.6: read-compat only; writer never emits this kind
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from milpa.predicate import Predicate
from milpa.errors import (
    CAS_STORE_IO_ERROR,
    LOCK_DEP_FIELD_ARITY,
    LOCK_DEP_IDENTITY_INVALID,
    LOCK_DEP_NAME_ARITY,
    LOCK_DEP_NAME_INVALID,
    LOCK_DEPDECL_PIN_MISSING,
    LOCK_FIELD_ARITY,
    LOCK_FIELD_TYPE,
    LOCK_GRAPH_MISMATCH,
    LOCK_PROV_FIELD_ARITY,
    LOCK_PROV_FIELD_MISSING,
    LOCK_PROV_KIND_MISSING,
    LOCK_PROV_KIND_UNKNOWN,
    LOCK_SRC_DIR_UNSAFE,
    LOCK_VERSION_MISSING,
    LOCK_VERSION_UNSUPPORTED,
    VERIFY_ALIAS_SYMLINK_MISSING,
    VERIFY_EDGE_MISMATCH,
    MilpaError,
)
from milpa.identity import compute_content_hash, parse_identity
from milpa.manifest import contains_unsafe_char, valid_dep_name
from milpa.kdl_io import (
    KdlNode,
    node_args,
    node_children,
    node_name,
    node_prop_str,
    node_prop_tag,
    node_props,
    nodes,
    parse_kdl,
    value_as_int,
    value_as_str,
)

# ---------------------------------------------------------------------------
# Schema constant
# ---------------------------------------------------------------------------

LOCKFILE_SCHEMA_VERSION: int = 1
_HEADER = "// generated by milpa; reproducible build snapshot"

# ---------------------------------------------------------------------------
# ProvenanceRecord — 6 variants + 1 read-compat (lockfile-schema.md §4)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class GitProvenanceRecord:
    """Provenance for a git-fetched dep (§4.1).

    url is required. ref and commit_sha are optional — omitted when None.
    commit_sha is the resolved SHA from the fetch receipt, not the manifest ref.
    origin: "observed" (milpa fetched+verified) or "declared" (claimed mirror,
    unverified until first use). Default "observed". Per-lockfile annotation —
    never a CAS-entry property.
    """

    url: str
    ref: str | None = None
    commit_sha: str | None = None
    origin: str = "observed"
    kind: str = field(default="git", init=False)


@dataclass(frozen=True)
class TarballProvenanceRecord:
    """Provenance for a tarball-fetched dep (§4.2).

    url is required. sha256 is optional on first fetch (TOFU model — §5);
    once pinned it is preserved on all subsequent lockfile writes.
    sha256 records the archive hash (transport integrity), NOT the identity
    (source-tree hash). These are orthogonal fields.
    origin: "observed" or "declared". Default "observed".
    """

    url: str
    sha256: str | None = None
    origin: str = "observed"
    kind: str = field(default="tarball", init=False)


@dataclass(frozen=True)
class LocalProvenanceRecord:
    """Provenance for a local-path dep (§4.3).

    path is the as-declared relative path from the project root. NOT resolved
    to absolute — portability across machines with the same workspace layout.
    origin: "observed" or "declared". Default "observed".
    """

    path: str
    origin: str = "observed"
    kind: str = field(default="local", init=False)


@dataclass(frozen=True)
class MemberProvenanceRecord:
    """Provenance for a workspace-internal member reference (§4.4).

    origin: "observed" or "declared". Default "observed".
    """

    name: str
    origin: str = "observed"
    kind: str = field(default="member", init=False)


@dataclass(frozen=True)
class OciProvenanceRecord:
    """Provenance for an OCI-artifact dep (§4.5).

    All three fields are required. digest is the immutable content-addressed
    pin (e.g. sha256:…).
    origin: "observed" or "declared". Default "observed".
    """

    registry: str
    repository: str
    digest: str
    origin: str = "observed"
    kind: str = field(default="oci", init=False)


@dataclass(frozen=True)
class RegistryProvenanceRecord:
    """READ-COMPAT ONLY (lockfile-schema.md §4.6).

    The writer never emits this kind — named deps now resolve to git/oci via
    tianguis. The parser must still accept `registry` provenance blocks in
    existing lockfiles. This class is retained until straggler old lockfiles are
    regenerated; it will be removed in a future schema version.
    origin: "observed" or "declared". Default "observed".
    """

    name: str
    tag: str | None = None
    commit_sha: str | None = None
    origin: str = "observed"
    kind: str = field(default="registry", init=False)


#: Discriminated union of all provenance record variants.
ProvenanceRecord = (
    GitProvenanceRecord
    | TarballProvenanceRecord
    | LocalProvenanceRecord
    | MemberProvenanceRecord
    | OciProvenanceRecord
    | RegistryProvenanceRecord
)

# ---------------------------------------------------------------------------
# CondRequire — conditional-require annotation (S4, RFC cond-requires §3.4)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CondRequire:
    """One conditional require annotation on a locked dep (additive, §3.4.1).

    ``name`` is the require name (must also appear in ``LockedDep.requires``).
    ``predicates`` is the non-empty ordered tuple of Predicate clauses (AND).
    Sorted by name across all cond_requires on a dep (lexicographic).

    Never consulted by ``frozen``/``verify``/``nimcfg`` — they read
    ``requires`` only.  Present so #110 can read the annotation for
    build-time activation.
    """

    name: str
    predicates: tuple[Predicate, ...]


# ---------------------------------------------------------------------------
# Lockfile data model
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LockedDep:
    """A single dep entry in a lockfile (lockfile-schema.md §3).

    identity: multihash-encoded content hash (sha256:<64hex>). May be None for
      deps not yet content-hashed (Phase A partial).
    version: semver string. Parser default when absent: "0.0.0". Emitter writes
      "0.0.1" for non-versioned dep kinds (url/tarball/local/member/oci).
    src_dir: relative path from dep root to Nim source dir. Empty string = root.
    requires: direct transitive dep names, sorted lexicographically.
    provenances: one or more ProvenanceRecord per dep (Phase D). Each record
      carries an origin ("observed"|"declared"). Emitted in canonical sort order
      (declared < observed; git < tarball < oci < local < member < registry).
    active_flags: feature flags active for this dep; omitted from KDL when empty.
    """

    name: str
    identity: str | None
    version: str
    src_dir: str
    requires: tuple[str, ...]
    provenances: tuple[ProvenanceRecord, ...]
    active_flags: tuple[str, ...] = ()
    # S6: additive dep_decl pin (§3.7). Emitted only when present (dep resolved
    # via DepDeclEdgeSource). Forward-compat: older/absent = None = fine; no
    # lockfile schema bump (lockfile-schema.md §3.7).
    dep_decl: str | None = None
    # S4: additive cond-require annotations (RFC cond-requires §3.4.1).
    # Sorted by name. Never consulted by frozen/verify/nimcfg. Omitted when empty.
    cond_requires: tuple[CondRequire, ...] = ()
    # Phase B: alternate dep names when one content-identity is reached via
    # multiple manifest names (dedup). Lexicographically sorted. Omitted from
    # KDL entirely when empty. See lockfile-schema.md §3.8.
    aliases: tuple[str, ...] = ()


@dataclass(frozen=True)
class Lockfile:
    """Parsed or constructed lockfile."""

    deps: tuple[LockedDep, ...]
    strategy: str = "maxver"
    version: int = LOCKFILE_SCHEMA_VERSION


# ---------------------------------------------------------------------------
# ResolvedDep + ResolvedGraph
#
# These types are defined here (not in resolver.py) to avoid a forward import
# cycle: resolver.py imports and *produces* these; lockfile.py consumes them
# in from_graph/verify_against_graph. The layering mirrors Rust's milpa_types
# crate which co-locates Lockfile/ResolvedGraph types.
#
# Minimal fields — only what from_graph and verify_against_graph actually need.
# resolver.py (S9) will import these and populate them.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ResolvedDep:
    """A single dep in a resolved graph.

    name:        dep name
    identity:    multihash-encoded content hash (may be None)
    version:     resolved version string (e.g. "1.2.3", "0.0.1" for non-versioned)
    src_dir:     relative path to Nim sources within the dep root
    requires:    names of direct transitive deps (order not guaranteed — sorted
                 by from_graph when building LockedDep)
    provenances: tuple of ProvenanceRecord — at least one "observed" record
                 (the fetched+verified candidate) plus zero or more "declared"
                 records (manifest mirrors + prior declared mirrors, deduped vs
                 observed). Empty only for the synthetic root dep. D-lifecycle.
    active_flags: feature flags active for this dep
    """

    name: str
    identity: str | None
    version: str
    src_dir: str
    requires: tuple[str, ...]
    provenances: tuple[ProvenanceRecord, ...] = ()
    active_flags: tuple[str, ...] = ()
    # S6: the dep_decl hash this resolution was computed against (from the index
    # pointer, carried through _Candidate → ResolvedDep → LockedDep → lockfile).
    # None for non-indexed deps (URL/tarball/local/member) and for named deps
    # whose index entry has no dep_decl pointer yet.
    dep_decl: str | None = None
    # S4: conditional require annotations propagated from edgeset_to_terms
    # requires_predicates dict (RFC cond-requires §3.4.3). Sorted by name.
    cond_requires: tuple[CondRequire, ...] = ()
    # Phase B: alternate dep names when one content-identity is reached via
    # multiple manifest names (dedup). Lexicographically sorted. Empty for
    # non-deduped deps. Canonical = BFS-insertion-order first.
    aliases: tuple[str, ...] = ()


@dataclass(frozen=True)
class ResolvedGraph:
    """Complete set of resolved deps produced by the resolver.

    ``cert`` carries the ``SolveSuccess`` certificate (``solver.py``) when
    the resolver builds it.  Typed ``Any`` to avoid a circular import
    (lockfile.py ← resolver.py ← solver.py; lockfile.py MUST NOT import
    solver.py).  The CLI's certificate flag reads this field; all other
    consumers ignore it.  ``None`` means no certificate was built.
    """

    deps: tuple[ResolvedDep, ...]
    cert: Any = None  # SolveSuccess | None


# ---------------------------------------------------------------------------
# 4a helpers — _validate_identity (lockfile parse uses its own inline raising)
# ---------------------------------------------------------------------------


def _parse_dep_identity_str(val: Any, dep_name: str) -> str:
    """Validate a multihash identity string for a lockfile dep.

    Delegates to ``identity.parse_identity`` (SSOT for all 5 checks per
    identity.md §2.2) and re-raises any ``MilpaError`` as
    ``LOCK_DEP_IDENTITY_INVALID``, matching the lockfile error catalog.
    This mirrors how Rust's ``parse_dep`` wraps ``parse_identity``
    (lockfile.rs ~line 139).
    """
    try:
        return parse_identity(val)
    except MilpaError as e:
        raise MilpaError(
            LOCK_DEP_IDENTITY_INVALID,
            f"dep {dep_name!r}: invalid identity — {e}",
            dep=dep_name,
            identity=val if isinstance(val, str) else repr(val),
        ) from e


# ---------------------------------------------------------------------------
# Provenance sort key (lockfile-schema.md §4.0)
#
# SSOT for canonical provenance ordering in BOTH parse-side (self_mirrors
# conversion) and emit-side (format_lockfile). BOTH impls MUST use this key
# identically to guarantee zero cross-impl byte divergence.
#
# Key: (origin_rank, kind_rank, primary, secondary)
#   origin_rank: declared=0, observed=1
#   kind_rank:   git=0, tarball=1, oci=2, local=3, member=4, registry=5
#   (primary, secondary): per-kind fields, bytewise over post-escape KDL form
# ---------------------------------------------------------------------------

_ORIGIN_RANK: dict[str, int] = {"declared": 0, "observed": 1}
_KIND_RANK: dict[str, int] = {
    "git": 0,
    "tarball": 1,
    "oci": 2,
    "local": 3,
    "member": 4,
    "registry": 5,
}


def _provenance_sort_key(p: "ProvenanceRecord") -> tuple[int, int, str, str]:
    """Total sort key for a ProvenanceRecord (lockfile-schema.md §4.0).

    SSOT for canonical provenance ordering: (origin_rank, kind_rank, primary, secondary).
    All comparisons are bytewise over the post-escape KDL string form.
    Used by format_lockfile (emitter) — BOTH impls MUST use the identical key.
    """
    origin_rank = _ORIGIN_RANK.get(p.origin, 99)
    kind_rank = _KIND_RANK.get(p.kind, 99)
    # Compute (primary, secondary) per kind — bytewise over KDL-escaped string form.
    if isinstance(p, GitProvenanceRecord):
        primary = _kdl_str(p.url)
        secondary = _kdl_str(p.ref) if p.ref is not None else ""
    elif isinstance(p, TarballProvenanceRecord):
        primary = _kdl_str(p.url)
        secondary = ""
    elif isinstance(p, OciProvenanceRecord):
        primary = _kdl_str(p.registry + "/" + p.repository)
        secondary = _kdl_str(p.digest)
    elif isinstance(p, LocalProvenanceRecord):
        primary = _kdl_str(p.path)
        secondary = ""
    elif isinstance(p, MemberProvenanceRecord):
        primary = _kdl_str(p.name)
        secondary = ""
    elif isinstance(p, RegistryProvenanceRecord):
        primary = _kdl_str(p.name)
        secondary = _kdl_str(p.tag) if p.tag is not None else ""
    else:
        primary = ""
        secondary = ""
    return (origin_rank, kind_rank, primary, secondary)


# ---------------------------------------------------------------------------
# 4b — parse_lockfile
# ---------------------------------------------------------------------------


def parse_lockfile(text: str) -> Lockfile:
    """Parse KDL 2.0 lockfile text into a ``Lockfile`` value.

    Raises ``MilpaError`` with LOCK-* slugs on any parse error.
    Defaults: strategy = "maxver" (tolerates pre-v1.0 lockfiles without the
    strategy node, per lockfile-schema.md §2.2).
    """
    doc = parse_kdl(text, context="lockfile")

    deps: list[LockedDep] = []
    strategy: str = "maxver"
    schema_version: int | None = None

    for node in nodes(doc):
        name = node_name(node)
        if name == "version":
            schema_version = _parse_top_version(node)
        elif name == "strategy":
            strategy = _parse_top_strategy(node)
        elif name == "dep":
            deps.append(_parse_dep(node))
        # Any other top-level node is silently ignored for forward compat

    if schema_version is None:
        raise MilpaError(
            LOCK_VERSION_MISSING,
            "lockfile missing required 'version' node",
        )
    if schema_version != LOCKFILE_SCHEMA_VERSION:
        raise MilpaError(
            LOCK_VERSION_UNSUPPORTED,
            f"unsupported lockfile schema version {schema_version} "
            f"(this milpa understands version {LOCKFILE_SCHEMA_VERSION})",
            got=schema_version,
            supported=LOCKFILE_SCHEMA_VERSION,
        )

    return Lockfile(deps=tuple(deps), strategy=strategy, version=schema_version)


def _parse_top_version(node: KdlNode) -> int:
    """Parse the top-level ``version`` node → schema version integer."""
    args = node_args(node)
    if len(args) != 1:
        raise MilpaError(
            LOCK_FIELD_ARITY,
            f"'version' node takes exactly one argument, got {len(args)}",
        )
    val = args[0]
    as_int = value_as_int(val)
    if as_int is None:
        raise MilpaError(
            LOCK_FIELD_TYPE,
            f"'version' must be an integer, got {val!r}",
            got=val,
        )
    return as_int


def _parse_top_strategy(node: KdlNode) -> str:
    """Parse the top-level ``strategy`` node → strategy name string.

    The strategy node is optional (pre-v1.0 compat). If present and has
    exactly one string arg, use it. If present but malformed, we still
    default to "maxver" (fail-open for diagnostics — the strategy field is
    informational, not load-bearing for parse correctness).
    """
    args = node_args(node)
    if len(args) == 1:
        s = value_as_str(args[0])
        if s is not None:
            return s
    return "maxver"


def _parse_dep(node: KdlNode) -> LockedDep:
    """Parse a ``dep`` block into a ``LockedDep``."""
    dep_name = _require_dep_name(node)

    identity: str | None = None
    version: str = "0.0.0"
    src_dir: str = ""
    requires: tuple[str, ...] = ()
    active_flags: tuple[str, ...] = ()
    provenances: list[ProvenanceRecord] = []
    dep_decl: str | None = None  # S6: additive dep_decl pin (§3.7)
    cond_requires: list[CondRequire] = []  # S4: additive cond-require annotations
    aliases: tuple[str, ...] = ()  # Phase B: alternate names for deduped deps
    # Read-compat: accumulate legacy self_mirrors URLs for conversion (§3.7)
    legacy_self_mirror_urls: list[str] = []

    for child in node_children(node):
        cname = node_name(child)
        if cname == "identity":
            identity = _parse_dep_identity(child, dep_name)
        elif cname == "version":
            version = _parse_dep_scalar_str(child, dep_name, "version")
        elif cname == "src_dir":
            src_dir = _parse_dep_scalar_str(child, dep_name, "src_dir")
            # Security: validate src_dir at the lockfile parse boundary.
            # A poisoned milpa.lock with unsafe chars in src_dir would flow to
            # nim.cfg --path: on frozen reconstruction.  Reuse the SSOT predicate
            # (contains_unsafe_char from manifest.py); mirrors Rust lockfile.rs.
            if src_dir and contains_unsafe_char(src_dir):
                raise MilpaError(
                    LOCK_SRC_DIR_UNSAFE,
                    f"dep {dep_name!r}: lockfile 'src_dir' value contains a "
                    f"control character or line separator — rejected to prevent "
                    f"nim.cfg injection via a poisoned milpa.lock",
                    dep=dep_name,
                )
        elif cname == "requires":
            requires = _parse_dep_requires(child)
        elif cname == "aliases":
            aliases = _parse_dep_aliases(child)
        elif cname == "active_flags":
            active_flags = _parse_dep_active_flags(child)
        elif cname == "self_mirrors":
            # Read-compat (§3.7): old self_mirrors → declared provenance records.
            # Collect URLs; convert after parsing all children so provenance
            # blocks (if present) are already accumulated.
            legacy_self_mirror_urls.extend(_parse_dep_self_mirrors(child))
        elif cname == "provenance":
            provenances.append(_parse_provenance_block(child, dep_name))
        elif cname == "dep_decl":
            # S6: forward-compat parse — silently ignored when absent or malformed.
            args = node_args(child)
            if len(args) == 1:
                dep_decl = value_as_str(args[0])
        elif cname == "cond-require":
            # S4: parse additive cond-require annotation (RFC §3.4).
            cr = _parse_cond_require(child)
            if cr is not None:
                cond_requires.append(cr)
        # other unknown child nodes are silently skipped (forward compat)

    # Read-compat §3.7: convert legacy self_mirrors URLs to declared git provenances.
    # Each URL becomes a GitProvenanceRecord(origin="declared", url=url, ref=None, commit_sha=None).
    for url in legacy_self_mirror_urls:
        provenances.append(GitProvenanceRecord(url=url, origin="declared"))

    return LockedDep(
        name=dep_name,
        identity=identity,
        version=version,
        src_dir=src_dir,
        requires=requires,
        provenances=tuple(provenances),
        active_flags=active_flags,
        dep_decl=dep_decl,
        cond_requires=tuple(cond_requires),
        aliases=aliases,
    )


def _require_dep_name(node: KdlNode) -> str:
    """Extract the dep name from the positional arg of a ``dep`` node.

    Validates the name against the dep-name charset [A-Za-z0-9_-]+ (SSOT:
    ``manifest.valid_dep_name``).  A poisoned
    lockfile with a name like ``../evil`` (containing ``/``) would otherwise
    flow to ``nim.cfg --path:`` and ``deps_dir / name``.  We use the charset
    predicate here, NOT ``contains_unsafe_char``, because ``/`` and ``.`` are
    not control characters.
    """
    args = node_args(node)
    if len(args) != 1:
        raise MilpaError(
            LOCK_DEP_NAME_ARITY,
            f"dep node requires exactly one string argument (the name), "
            f"got {len(args)} args",
        )
    name = value_as_str(args[0])
    if name is None:
        raise MilpaError(
            LOCK_DEP_NAME_ARITY,
            f"dep node name argument must be a string, got {args[0]!r}",
        )
    # R8-S1 security fix: validate dep name charset at the lockfile parse
    # boundary.  Mirrors the manifest parse boundary check (MAN-DEP-NAME-INVALID).
    if not valid_dep_name(name):
        raise MilpaError(
            LOCK_DEP_NAME_INVALID,
            f"dep name {name!r} contains characters outside [A-Za-z0-9_-] — "
            "rejected to prevent path traversal and nim.cfg injection via a "
            "poisoned milpa.lock",
            name=name,
        )
    return name


def _parse_dep_identity(node: KdlNode, dep_name: str) -> str:
    """Parse the ``identity`` child of a dep block."""
    args = node_args(node)
    if len(args) != 1:
        raise MilpaError(
            LOCK_DEP_FIELD_ARITY,
            f"dep {dep_name!r}: 'identity' must have exactly one string value",
            dep=dep_name,
        )
    val = args[0]
    # Validate multihash format (lockfile-schema.md §3.1)
    return _parse_dep_identity_str(val, dep_name)


def _parse_dep_scalar_str(node: KdlNode, dep_name: str, field: str) -> str:
    """Parse a dep child node that takes exactly one string arg."""
    args = node_args(node)
    if len(args) != 1:
        raise MilpaError(
            LOCK_DEP_FIELD_ARITY,
            f"dep {dep_name!r}: {field!r} must have exactly one string value, "
            f"got {len(args)} args",
            dep=dep_name,
            field=field,
        )
    s = value_as_str(args[0])
    if s is None:
        raise MilpaError(
            LOCK_DEP_FIELD_ARITY,
            f"dep {dep_name!r}: {field!r} value must be a string, got {args[0]!r}",
            dep=dep_name,
            field=field,
        )
    return s


def _parse_dep_requires(node: KdlNode) -> tuple[str, ...]:
    """Parse the ``requires`` child node — zero or more string args."""
    return tuple(s for a in node_args(node) if (s := value_as_str(a)) is not None)


def _parse_dep_active_flags(node: KdlNode) -> tuple[str, ...]:
    """Parse the ``active_flags`` child node — zero or more string args."""
    return tuple(s for a in node_args(node) if (s := value_as_str(a)) is not None)


def _parse_dep_aliases(node: KdlNode) -> tuple[str, ...]:
    """Parse the ``aliases`` child node — zero or more string args.

    Returned tuple is lexicographically sorted (canonical form per §3.8).

    Each alias is validated against the dep-name charset [A-Za-z0-9_-]+
    (same SSOT predicate as dep names — R8-S1 security fix).  Aliases reach
    the same filesystem and nim.cfg sinks as the primary dep name.
    """
    aliases = []
    for a in node_args(node):
        s = value_as_str(a)
        if s is None:
            continue
        if not valid_dep_name(s):
            raise MilpaError(
                LOCK_DEP_NAME_INVALID,
                f"dep alias {s!r} contains characters outside [A-Za-z0-9_-] — "
                "rejected to prevent path traversal and nim.cfg injection via a "
                "poisoned milpa.lock",
                name=s,
            )
        aliases.append(s)
    return tuple(sorted(aliases))


def _parse_dep_self_mirrors(node: KdlNode) -> tuple[str, ...]:
    """Parse the ``self_mirrors`` child node.

    Accepts both plain strings and (url)-annotated values. The raw kdl-py
    entry value must be accessed to detect the url tag. We use node_args
    which strips annotations — both forms return a str through value_as_str.
    """
    return tuple(s for a in node_args(node) if (s := value_as_str(a)) is not None)


def _parse_cond_require(node: KdlNode) -> "CondRequire | None":
    """Parse a ``cond-require`` child node (RFC §3.4 / S4).

    Inline form (single predicate as props):
        ``cond-require "name" platform="linux"``
        ``cond-require "name" platform=(not)"linux"``

    Block form (≥2 predicates as ``when`` children):
        ``cond-require "name" { when platform="macosx" when platform=(not)"linux" }``

    Returns ``None`` (lenient/forward-compat) if the node is malformed
    (missing name arg, unknown shape).  Unknown extra fields are skipped.
    """
    # arg0 = require name
    args = node_args(node)
    if not args:
        return None
    name = value_as_str(args[0])
    if name is None:
        return None

    predicates: list[Predicate] = []

    children = node_children(node)
    if children:
        # Block form: each child MUST be a "when" node with exactly one prop.
        for child in children:
            if node_name(child) != "when":
                continue  # skip unknown child nodes (forward compat)
            props = node_props(child)
            for key in props:
                # M1: whitelist-validate the predicate name from untrusted input.
                # Keys outside the known vocabulary are silently dropped
                # (forward-compat lenient — same as "skip unknown nodes").
                if key not in _KNOWN_PREDICATE_NAMES:
                    continue
                val = node_prop_str(child, key)
                if val is None:
                    continue
                tag = node_prop_tag(child, key)
                predicates.append(
                    Predicate(name=key, values=(val,), negated=(tag == "not"))
                )
    else:
        # Inline form: each prop is one predicate.
        props = node_props(node)
        for key in props:
            # M1: whitelist-validate the predicate name from untrusted input.
            if key not in _KNOWN_PREDICATE_NAMES:
                continue
            val = node_prop_str(node, key)
            if val is None:
                continue
            tag = node_prop_tag(node, key)
            predicates.append(
                Predicate(name=key, values=(val,), negated=(tag == "not"))
            )

    if not predicates:
        return None
    return CondRequire(name=name, predicates=tuple(predicates))


def _parse_provenance_block(node: KdlNode, dep_name: str) -> ProvenanceRecord:
    """Parse a ``provenance { ... }`` block into a ProvenanceRecord."""
    # Collect all scalar child fields into a dict
    fields: dict[str, str] = {}
    for child in node_children(node):
        cname = node_name(child)
        child_args = node_args(child)
        if len(child_args) != 1:
            raise MilpaError(
                LOCK_PROV_FIELD_ARITY,
                f"dep {dep_name!r}: provenance field {cname!r} must have "
                f"exactly one value, got {len(child_args)}",
                dep=dep_name,
                field=cname,
            )
        raw = child_args[0]
        s = value_as_str(raw)
        if s is None:
            raise MilpaError(
                LOCK_PROV_FIELD_ARITY,
                f"dep {dep_name!r}: provenance field {cname!r} must be a "
                f"string, got {raw!r}",
                dep=dep_name,
                field=cname,
            )
        fields[cname] = s

    # kind discriminator is required
    kind = fields.get("kind")
    if kind is None:
        raise MilpaError(
            LOCK_PROV_KIND_MISSING,
            f"dep {dep_name!r}: provenance block missing 'kind' discriminator",
            dep=dep_name,
        )

    # origin field: default "observed" when absent (back-compat: existing lockfiles
    # without origin are all observed). Per spec §4.
    origin = fields.get("origin", "observed")

    if kind == "git":
        return GitProvenanceRecord(
            url=_req_field(fields, "url", dep_name),
            ref=fields.get("ref"),
            commit_sha=fields.get("commit_sha"),
            origin=origin,
        )
    if kind == "tarball":
        return TarballProvenanceRecord(
            url=_req_field(fields, "url", dep_name),
            sha256=fields.get("sha256"),
            origin=origin,
        )
    if kind == "local":
        return LocalProvenanceRecord(
            path=_req_field(fields, "path", dep_name),
            origin=origin,
        )
    if kind == "member":
        return MemberProvenanceRecord(
            name=_req_field(fields, "name", dep_name),
            origin=origin,
        )
    if kind == "oci":
        return OciProvenanceRecord(
            registry=_req_field(fields, "registry", dep_name),
            repository=_req_field(fields, "repository", dep_name),
            digest=_req_field(fields, "digest", dep_name),
            origin=origin,
        )
    if kind == "registry":
        # Read-compat only (§4.6); writer never emits this
        return RegistryProvenanceRecord(
            name=_req_field(fields, "name", dep_name),
            tag=fields.get("tag"),
            commit_sha=fields.get("commit_sha"),
            origin=origin,
        )

    raise MilpaError(
        LOCK_PROV_KIND_UNKNOWN,
        f"dep {dep_name!r}: unknown provenance kind {kind!r} "
        f"(known: git, tarball, local, member, oci, registry)",
        dep=dep_name,
        kind=kind,
    )


def _req_field(fields: dict[str, str], key: str, dep_name: str) -> str:
    """Return a required provenance field, raising LOCK-PROV-FIELD-MISSING if absent."""
    val = fields.get(key)
    if val is None:
        raise MilpaError(
            LOCK_PROV_FIELD_MISSING,
            f"dep {dep_name!r}: provenance missing required field {key!r}",
            dep=dep_name,
            field=key,
        )
    return val


# ---------------------------------------------------------------------------
# 4c — from_graph + format_lockfile (byte-exact hand-rolled templating)
# ---------------------------------------------------------------------------


def from_graph(graph: ResolvedGraph, *, strategy: str = "maxver") -> Lockfile:
    """Convert a ResolvedGraph into a Lockfile.

    Deps are sorted lexicographically by name (lockfile-schema.md §2.3 +
    §2.4 + resolver-semantics.md §4.4). Same graph always produces
    byte-identical lockfile text.
    """
    deps = tuple(
        sorted(
            (_locked_from_resolved(d) for d in graph.deps),
            key=lambda d: d.name,
        )
    )
    return Lockfile(deps=deps, strategy=strategy)


def _locked_from_resolved(d: ResolvedDep) -> LockedDep:
    """Translate a ResolvedDep into a LockedDep."""
    return LockedDep(
        name=d.name,
        identity=d.identity,
        version=d.version,
        src_dir=d.src_dir,
        # Sort lexicographically — requires is accumulated in BFS arrival order
        # which is non-deterministic across parallel-fetch runs. Lexicographic
        # order is the spec's single canonical ordering rule (§3.4 / §4.4).
        requires=tuple(sorted(d.requires)),
        provenances=d.provenances,
        active_flags=d.active_flags,
        # S6: carry the dep_decl hash from the resolver through to the lockfile pin.
        dep_decl=d.dep_decl,
        # S4: carry cond_requires (sorted by (name, canonical-predicate-string)).
        cond_requires=d.cond_requires,
        # Phase B: carry dedup aliases from ResolvedDep (lex-sorted by dedup pass).
        aliases=d.aliases,
    )


# ---------------------------------------------------------------------------
# Predicate-name whitelist (M1: validate untrusted lockfile keys)
#
# Only these keys are accepted when PARSING a cond-require node from a
# (potentially attacker-controlled) lockfile.  Keys outside the set are
# silently dropped (forward-compat lenient, same spirit as "skip unknown
# child nodes").  The whitelist must stay in sync with spec/lockfile-schema.md
# §3.5 and manifest-grammar.md §6.
_KNOWN_PREDICATE_NAMES: frozenset[str] = frozenset(
    {"platform", "arch", "nim", "milpa", "flag"}
)

# ---------------------------------------------------------------------------
# _kdl_str — SSOT for string escaping (lockfile-schema.md §2.4)
#
# Escapes: \ → \\, " → \", control chars U+0000–U+001F → \u{NNNN},
# everything else verbatim. No named escapes (\n, \t, etc.) — the spec
# says "\u{NNNN}" for all control chars; for simplicity we use the unicode
# escape form for all U+0000–U+001F uniformly.
# ---------------------------------------------------------------------------

_CTRL_ESCAPES: dict[str, str] = {
    "\\": "\\\\",
    '"': '\\"',
}


def _kdl_str(s: str) -> str:
    r"""Return ``s`` as a double-quoted, KDL 2.0-escaped string literal.

    SSOT for string escaping in the lockfile emitter. Every string value
    emitted by ``format_lockfile`` passes through this function.

    Escape rules (lockfile-schema.md §2.4):
      \\  →  \\\\  (backslash escape)
      "   →  \\"   (double-quote escape)
      U+0000–U+001F → \u{NNNN}  (control chars in hex)
      everything else → verbatim (valid KDL 2.0 string content)
    """
    out: list[str] = []
    for ch in s:
        esc = _CTRL_ESCAPES.get(ch)
        if esc is not None:
            out.append(esc)
        elif ord(ch) < 0x20:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _format_predicate_prop(pred: Predicate) -> str:
    """Emit one predicate as ``key="value"`` or ``key=(not)"value"`` (RFC §3.4.1).

    The prop key is ``pred.name``; value is ``pred.values[0]`` (every predicate
    produced by this pipeline is single-value — v0 invariant per spec §3.5 /
    lockfile-schema §3.5). Multi-value (OR) predicates are not supported in v0;
    the guard below enforces the invariant so violations surface as an explicit
    error rather than silently truncating values[1:] (and are not stripped under
    ``python -O`` as a bare ``assert`` would be).
    Negation uses the KDL type-annotation form ``(not)"value"`` — verbatim from
    ``manifest-grammar.md §6``.
    """
    if len(pred.values) != 1:
        raise ValueError(
            f"_format_predicate_prop: predicate {pred.name!r} has {len(pred.values)} values "
            f"but only single-value predicates are supported in v0 (spec §3.5). "
            f"Multi-value (OR) emission is not implemented."
        )
    val = _kdl_str(pred.values[0])
    if pred.negated:
        return f'{pred.name}=(not){val}'
    return f'{pred.name}={val}'


def cond_require_sort_key(cr: "CondRequire") -> "tuple[str, str]":
    """Total sort key for a ``CondRequire``: ``(name, canonical-predicate-string)``.

    Using name alone is NOT a total order when same-name entries exist (a dep in
    ≥2 when-branches).  The predicate string makes the key total and deterministic
    across impls regardless of source order (C1 fix, §2.4).

    The per-predicate string is built by calling ``_format_predicate_prop`` so
    that KDL string escaping is shared with the emitter — sort order cannot drift
    from emission order even if a predicate value ever contains ``"`` or ``\\``.
    """
    pred_strs = ",".join(_format_predicate_prop(p) for p in cr.predicates)
    return (cr.name, pred_strs)


def _format_cond_require(cr: "CondRequire") -> list[str]:
    """Emit a ``cond-require`` node (RFC §3.4.1).

    Single predicate → inline property form:
        ``    cond-require "name" key="value"``

    Multiple predicates (AND) → block form:
        ``    cond-require "name" {``
        ``        when key="value"``
        ``        ...``
        ``    }``
    """
    name_str = _kdl_str(cr.name)
    if len(cr.predicates) == 1:
        prop = _format_predicate_prop(cr.predicates[0])
        return [f"    cond-require {name_str} {prop}"]
    else:
        out = [f"    cond-require {name_str} {{"]
        for pred in cr.predicates:
            prop = _format_predicate_prop(pred)
            out.append(f"        when {prop}")
        out.append("    }")
        return out


def format_lockfile(lockfile: Lockfile) -> str:
    """Render a ``Lockfile`` to byte-exact KDL 2.0 text.

    Implements the canonical serialization rules from lockfile-schema.md §2.4.
    The output is deterministic: same logical lockfile → identical bytes.

    Layout:
      1. Header comment
      2. ``version 1`` (integer, unquoted)
      3. ``strategy "<name>"``
      4. Blank line
      5. dep blocks (lexicographic order), each followed by blank line
      6. File ends with the blank line after the last dep block (last byte = 0x0A)
    """
    lines: list[str] = [
        _HEADER,
        f"version {lockfile.version}",
        f"strategy {_kdl_str(lockfile.strategy)}",
        "",
    ]
    for dep in lockfile.deps:
        lines.append(f"dep {_kdl_str(dep.name)} {{")
        # identity — emitted only when not None
        if dep.identity is not None:
            lines.append(f"    identity {_kdl_str(dep.identity)}")
        lines.append(f"    version {_kdl_str(dep.version)}")
        lines.append(f"    src_dir {_kdl_str(dep.src_dir)}")
        # requires — always emitted; bare when empty, args when non-empty
        if dep.requires:
            req_args = " ".join(_kdl_str(r) for r in dep.requires)
            lines.append(f"    requires {req_args}")
        else:
            lines.append("    requires")
        # cond-require — S4: additive annotation nodes.
        # Emitted immediately after requires. Omitted when empty (byte-identical
        # for deps with no conditional requires). Sort at emission for
        # determinism (lockfile-schema.md §2.4 / RFC §3.4.1).
        # Delegates to cond_require_sort_key (module-level SSOT) so escaping
        # is shared with _format_predicate_prop and cannot drift (C1 fix).
        for cr in sorted(dep.cond_requires, key=cond_require_sort_key):
            lines.extend(_format_cond_require(cr))
        # aliases — Phase B dedup: alternate names for deduped deps (§3.8).
        # Omitted entirely when empty; args are lex-sorted by convention.
        if dep.aliases:
            alias_args = " ".join(_kdl_str(a) for a in sorted(dep.aliases))
            lines.append(f"    aliases {alias_args}")
        # active_flags — omitted when empty
        if dep.active_flags:
            flag_args = " ".join(_kdl_str(f) for f in dep.active_flags)
            lines.append(f"    active_flags {flag_args}")
        # dep_decl pin — S6: emitted only when present (forward-compat additive)
        if dep.dep_decl is not None:
            lines.append(f"    dep_decl {_kdl_str(dep.dep_decl)}")
        # provenance blocks — sorted by canonical key (§4.0): declared < observed;
        # git < tarball < oci < local < member < registry; then (primary, secondary).
        # NOTE: self_mirrors is NEVER emitted (D-provenance: removed from schema).
        for prov in sorted(dep.provenances, key=_provenance_sort_key):
            lines.append("    provenance {")
            for pline in _format_provenance_fields(prov):
                lines.append(f"        {pline}")
            lines.append("    }")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _format_provenance_fields(p: ProvenanceRecord) -> list[str]:
    """Emit origin + kind + kind-specific fields for a provenance block.

    Field order per kind (lockfile-schema.md §2.4, D-provenance amendment):
      all kinds: origin (ALWAYS first) / kind (second) / kind-specific fields
      git:      origin / kind / url / ref / commit_sha
      tarball:  origin / kind / url / sha256
      local:    origin / kind / path
      member:   origin / kind / name
      oci:      origin / kind / registry / repository / digest
      registry: origin / kind / name / tag / commit_sha  (read-compat round-trip)

    origin is ALWAYS emitted (never omitted), regardless of value.
    Optional fields (ref, commit_sha, sha256, tag) are omitted when None.
    """
    # origin is always first, always emitted.
    out = [f"origin {_kdl_str(p.origin)}", f"kind {_kdl_str(p.kind)}"]
    if isinstance(p, GitProvenanceRecord):
        out.append(f"url {_kdl_str(p.url)}")
        if p.ref is not None:
            out.append(f"ref {_kdl_str(p.ref)}")
        if p.commit_sha is not None:
            out.append(f"commit_sha {_kdl_str(p.commit_sha)}")
    elif isinstance(p, TarballProvenanceRecord):
        out.append(f"url {_kdl_str(p.url)}")
        if p.sha256 is not None:
            out.append(f"sha256 {_kdl_str(p.sha256)}")
    elif isinstance(p, LocalProvenanceRecord):
        out.append(f"path {_kdl_str(p.path)}")
    elif isinstance(p, MemberProvenanceRecord):
        out.append(f"name {_kdl_str(p.name)}")
    elif isinstance(p, OciProvenanceRecord):
        out.append(f"registry {_kdl_str(p.registry)}")
        out.append(f"repository {_kdl_str(p.repository)}")
        out.append(f"digest {_kdl_str(p.digest)}")
    elif isinstance(p, RegistryProvenanceRecord):
        out.append(f"name {_kdl_str(p.name)}")
        if p.tag is not None:
            out.append(f"tag {_kdl_str(p.tag)}")
        if p.commit_sha is not None:
            out.append(f"commit_sha {_kdl_str(p.commit_sha)}")
    return out


def write_lockfile(lockfile: Lockfile, path: Path) -> Path:
    """Write lockfile KDL text to ``path`` atomically.  Returns the path.

    Atomic discipline: format the content, write to a sibling temp file in the
    same directory as *path*, then ``os.replace(tmp, path)`` — a POSIX atomic
    rename.  The temp file lives in the target's parent so the rename is
    always same-filesystem; EXDEV (cross-device rename failure) is structurally
    impossible.  If formatting or the write raises, the temp file is removed
    and the exception propagates — no temp files are ever left behind.
    """
    import contextlib
    import os

    path.parent.mkdir(parents=True, exist_ok=True)
    # Build a unique temp name in the same directory as the target.
    tmp = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    try:
        tmp.write_text(format_lockfile(lockfile), encoding="utf-8")
        os.replace(tmp, path)
    except Exception:
        with contextlib.suppress(OSError):
            tmp.unlink(missing_ok=True)
        raise
    return path


def load_lockfile(path: Path) -> Lockfile:
    """Read and parse a lockfile from disk.

    Raises ``MilpaError(LOCK_FILE_NOT_FOUND)`` / ``MilpaError(LOCK_FILE_UNREADABLE)``
    on I/O failure.
    """
    from milpa.errors import LOCK_FILE_NOT_FOUND, LOCK_FILE_UNREADABLE

    try:
        text = path.read_text()
    except FileNotFoundError as exc:
        raise MilpaError(
            LOCK_FILE_NOT_FOUND,
            f"lockfile not found: {path}",
            path=str(path),
        ) from exc
    except OSError as exc:
        raise MilpaError(
            LOCK_FILE_UNREADABLE,
            f"cannot read lockfile {path}: {exc}",
            path=str(path),
        ) from exc
    return parse_lockfile(text)


# ---------------------------------------------------------------------------
# 4e — Verification
# ---------------------------------------------------------------------------


def verify_against_graph(
    lockfile: Lockfile,
    graph: ResolvedGraph,
) -> None:
    """Verify that the resolved graph matches the lockfile dep-for-dep.

    Checks (lockfile-schema.md §6.1):
      - Every dep in the graph has a corresponding lockfile entry (by name).
      - Every dep in the lockfile has a corresponding graph entry.
      - For every dep in both: identity fields match exactly.

    Raises ``MilpaError(LOCK_GRAPH_MISMATCH)`` on any divergence.
    Collects ALL mismatches before raising (not fail-fast).
    """
    locked_by_name = {d.name: d for d in lockfile.deps}
    graph_by_name = {d.name: d for d in graph.deps}

    errors: list[str] = []
    for name in sorted(graph_by_name.keys() - locked_by_name.keys()):
        errors.append(
            f"dep {name!r} is in the resolved graph but absent from the lockfile"
        )
    for name in sorted(locked_by_name.keys() - graph_by_name.keys()):
        errors.append(
            f"dep {name!r} is in the lockfile but absent from the resolved graph"
        )
    for name in sorted(graph_by_name.keys() & locked_by_name.keys()):
        locked = locked_by_name[name]
        actual = graph_by_name[name]
        if locked.identity != actual.identity:
            errors.append(
                f"dep {name!r}: identity mismatch — "
                f"lockfile={locked.identity!r}, graph={actual.identity!r}"
            )

    if errors:
        raise MilpaError(
            LOCK_GRAPH_MISMATCH,
            "lockfile does not match resolved graph:\n  " + "\n  ".join(errors),
            mismatches=errors,
        )


def _classify_dep_path(dep_path: Path) -> str | None:
    """Classify a ``_deps/<name>`` path into one of four states.

    Returns a divergence string if the path is in states (b), (c), or (d);
    returns None if the path is in state (a) (symlink present + store readable).

    States (RFC rfc-content-addressed-identity.md Phase C §6 item 6):
      (a) symlink present + store entry readable ⇒ None (pass)
      (b) dangling symlink (is_symlink() true, exists() false) ⇒ "dangling" divergence
      (c) symlink resolves but store read raises OSError ⇒ CAS-STORE-IO-ERROR divergence
      (d) no entry at all (not a symlink, not exists) ⇒ "missing" divergence

    Note: non-symlink directories/files that *do* exist fall through to (a) and
    are handled by the caller's is_dir() + identity-hash checks.
    """
    name = dep_path.name
    is_link = dep_path.is_symlink()
    exists = dep_path.exists()  # follows symlinks

    if is_link and not exists:
        # State (b): dangling symlink — store entry GC'd or store not mounted.
        return (
            f"{name}: dangling symlink — store entry gone or store not mounted "
            f"(target: {dep_path})"
        )

    if not is_link and not exists:
        # State (d): genuinely absent — nothing at _deps/<name>.
        return f"{name}: missing from {dep_path.parent}/"

    # is_link && exists, OR !is_link && exists (plain dir/file):
    # Both cases proceed to identity hashing. If the hash raises an OSError,
    # that is state (c).
    return None  # Not a structural failure; caller checks identity.


def _is_local_dep(locked: "LockedDep") -> bool:
    """Return True iff the dep has at least one LocalProvenanceRecord.

    Used by verify_lockfile_against_deps to dispatch on provenance kind
    (lockfile-schema.md §6.2 NORMATIVE: local → liveness-only; others →
    identity hash-compare).
    """
    return any(isinstance(p, LocalProvenanceRecord) for p in locked.provenances)


def _verify_local_dep_liveness(
    name: str,
    dep_path: Path,
) -> str | None:
    """Liveness check for a local-provenance dep (lockfile-schema.md §6.2.1).

    Returns a divergence string for states (b), (c), (d); returns None for
    state (a) (symlink present + target is a reachable directory).

    States:
      (a) symlink present + target dir reachable → None (pass)
      (b) dangling symlink (is_symlink true, exists false) → "dangling"
      (c) plain dir, not a symlink → "expected symlink, found directory"
      (d) no entry at all → "missing from"
    """
    is_link = dep_path.is_symlink()
    exists = dep_path.exists()  # follows symlinks

    if is_link and not exists:
        # State (b): dangling — source tree deleted or moved.
        return (
            f"{name}: dangling symlink — source tree gone or moved "
            f"(target: {dep_path})"
        )

    if not is_link and not exists:
        # State (d): genuinely absent.
        return f"{name}: missing from {dep_path.parent}/"

    if not is_link and exists:
        # State (c): plain directory (or file) — not a symlink.
        # This means the local dep was overwritten by a non-symlink entry
        # (e.g. copied by a git fetcher or manually extracted).
        return (
            f"{name}: expected symlink to source tree, found plain directory at {dep_path}"
        )

    # is_link && exists: state (a) — live symlink to an existing dir.
    return None


def verify_lockfile_against_deps(
    lockfile: Lockfile,
    deps_dir: Path,
) -> list[str]:
    """Verify every lockfile dep against ``deps_dir/<name>/`` on disk.

    Dispatches on provenance kind (lockfile-schema.md §6.2 NORMATIVE):

    - LOCAL deps: liveness-only check (§6.2.1) — symlink resolves to an
      existing directory. No content hash is computed or compared.
    - All other deps: four-state structural check + identity hash-compare
      (§6.2.2).

    Also checks:
      - For each alias in dep.aliases: ``_deps/<alias>`` must be a symlink
        pointing at the same store entry as the canonical. Absence, dangling,
        or wrong-target ⇒ VERIFY-ALIAS-SYMLINK-MISSING.
      - Any entry under ``deps_dir/`` (excluding hidden entries and declared
        alias names) that has no corresponding lockfile entry is extra.

    Returns a list of divergence strings (may be empty). Does NOT raise —
    the caller decides whether to treat divergences as a hard error.
    Collects ALL divergences before returning (not fail-fast).
    """
    import os as _os
    divergences: list[str] = []
    locked_by_name = {d.name: d for d in lockfile.deps}

    # Build the set of all expected names (canonical + alias) so the extra-dep
    # scan does not flag alias symlinks as unexpected.
    expected_names: set[str] = set(locked_by_name.keys())
    for locked in lockfile.deps:
        expected_names.update(locked.aliases)

    for name, locked in sorted(locked_by_name.items()):
        dep_path = deps_dir / name

        # --- dispatch on provenance kind (§6.2 NORMATIVE) ---
        if _is_local_dep(locked):
            # LOCAL: liveness-only (§6.2.1). No hash compare.
            liveness_err = _verify_local_dep_liveness(name, dep_path)
            if liveness_err is not None:
                divergences.append(liveness_err)
            # No alias checks for local deps (local deps are not deduped into
            # CAS entries that multiple names could share).
            continue

        # --- four-state structural classification (§6.2.2) ---
        structural = _classify_dep_path(dep_path)
        if structural is not None:
            divergences.append(structural)
            continue

        # State (a) or plain dir/file: proceed to is_dir + identity check.
        if not dep_path.is_dir():
            divergences.append(
                f"{name}: expected directory at {dep_path}, found something else"
            )
            continue

        # State (a): attempt identity hash.  An OSError here is state (c).
        # A MilpaError (e.g. ID-NON-UTF8-RELPATH on a malformed entry) is also
        # caught and recorded as a divergence — matches Rust "cannot hash" branch
        # (lockfile.rs ~1050-1053).  Both paths continue the loop (no early abort).
        try:
            actual = compute_content_hash(dep_path)
        except OSError as exc:
            divergences.append(
                f"{name}: [{CAS_STORE_IO_ERROR}] I/O error reading store entry — {exc}"
            )
            continue
        except MilpaError as exc:
            divergences.append(
                f"{name}: cannot hash — {exc}"
            )
            continue

        expected = locked.identity
        if expected != actual:
            divergences.append(
                f"{name}: identity mismatch — "
                f"lockfile says {(expected or '<none>')[:23]}..., "
                f"actual {actual[:23]}..."
            )

        # --- §6.4 alias verification ---
        # canonical_target is the resolved (real) path of the store entry so we
        # can compare alias targets byte-for-byte.
        try:
            canonical_target = _os.path.realpath(dep_path)
        except OSError:
            canonical_target = None

        for alias in sorted(locked.aliases):
            alias_path = deps_dir / alias
            alias_is_link = alias_path.is_symlink()
            alias_exists = alias_path.exists()

            if not alias_is_link or not alias_exists:
                # Missing or dangling alias.
                divergences.append(
                    f"{alias}: [{VERIFY_ALIAS_SYMLINK_MISSING}] alias symlink "
                    f"absent or dangling for canonical '{name}'"
                )
                continue

            # Alias exists: verify it points at the same store entry.
            try:
                alias_target = _os.path.realpath(alias_path)
            except OSError:
                alias_target = None

            if canonical_target is None or alias_target != canonical_target:
                divergences.append(
                    f"{alias}: [{VERIFY_ALIAS_SYMLINK_MISSING}] alias symlink "
                    f"points to different store entry than canonical '{name}'"
                )

    # --- extra-dep scan (excludes hidden entries + declared alias names) ---
    if deps_dir.exists() and deps_dir.is_dir():
        for entry in sorted(deps_dir.iterdir()):
            if entry.name.startswith("."):
                continue
            if entry.name not in expected_names:
                divergences.append(
                    f"{entry.name}: extra dep in {deps_dir}/ not in lockfile"
                )

    return divergences
