"""milpa.lock — reproducible-build snapshot of a resolved dep graph.

The lockfile records two distinct kinds of data per dep:

  - **Identity**: `identity` field (multihash-encoded sha256 of source
    tree per #34). The canonical 'what'. Trust-independent,
    recomputable from bytes alone. This is the field consumers verify
    against.
  - **Provenance**: one or more `ProvenanceRecord` entries. Each
    records "where these bytes came from" — URL, ref, commit sha,
    local path, workspace member name, etc. Trust-dependent; the git
    server / mirror / registry could disagree without notice. A
    single identity may have multiple provenances (Phase D #37 lights
    up multi-provenance application; #33 ships the schema with
    exactly one per dep).

See docs/identity-and-provenance.md for the model and
docs/rfc-content-addressed-identity.md §Proposed model for the
schema design.

Format is KDL. The `version` field is present from day one (a v1.0
lockfile starts at version 1) but pre-1.0 we evolve the schema by
editing v1 in place — no parallel codepaths, no migrations. Once
real consumers exist we will bump the version and grow proper
upgrade support.

Library vs application:
  The lockfile format is identical for both. Whether the lockfile is
  committed to version control depends on the manifest's `kind`:
    library     → don't commit (downstream consumers re-resolve)
    application → commit (deterministic builds)
  That decision belongs to the CLI / manifest layer, not here.
"""

from dataclasses import dataclass
from pathlib import Path

import kdl

from .error_codes import lockfile_codes as _LC  # noqa: F401 — populates catalog
from .fetchers.git import GitProvenance
from .fetchers.oci import OciProvenance
from .fetchers.tarball import TarballProvenance
from .identity import IdentityError, compute_content_hash, parse_identity
from .resolver import ResolvedDep, ResolvedGraph
from .solver import Version


LOCKFILE_SCHEMA_VERSION = 1
_HEADER = "// generated by milpa; reproducible build snapshot"


# ---------------------------------------------------------------------------
# ProvenanceRecord discriminated union (#33)
# ---------------------------------------------------------------------------
# Each variant captures the descriptive metadata for "where these
# bytes came from" per kind. Distinct from milpa.fetchers.types.Provenance
# which is "how to fetch from this source." The lockfile records
# provenance after the fact; the fetcher protocol uses Provenance
# before the fact.


@dataclass(frozen=True)
class GitProvenanceRecord:
    """Provenance for a git-fetched dep."""
    url: str
    ref: str | None
    commit_sha: str | None
    kind: str = "git"


@dataclass(frozen=True)
class TarballProvenanceRecord:
    """Provenance for a tarball-fetched dep."""
    url: str
    sha256: str | None       # archive sha256 (provenance receipt, NOT identity)
    kind: str = "tarball"


@dataclass(frozen=True)
class LocalProvenanceRecord:
    """Provenance for a local-path dep. `path` is the as-declared
    string (relative to project root)."""
    path: str
    kind: str = "local"


@dataclass(frozen=True)
class MemberProvenanceRecord:
    """Provenance for a workspace-internal member reference."""
    name: str
    kind: str = "member"


@dataclass(frozen=True)
class OciProvenanceRecord:
    """Provenance for an OCI-artifact-fetched dep (milpa#97). Mirrors
    fetchers.oci.OciProvenance; the digest is the immutable pin."""
    registry: str
    repository: str
    digest: str
    kind: str = "oci"


@dataclass(frozen=True)
class RegistryProvenanceRecord:
    """Provenance for a registry-resolved dep.

    READ-COMPAT ONLY (milpa#97): the writer never emits this again — named
    deps now write git/oci records. Kept so existing `milpa.lock`s with
    `kind "registry"` still parse; the dataclass is removed only once
    straggler old locks are regenerated (not on #97's critical path)."""
    name: str
    tag: str | None
    commit_sha: str | None
    kind: str = "registry"


ProvenanceRecord = (
    GitProvenanceRecord
    | TarballProvenanceRecord
    | LocalProvenanceRecord
    | MemberProvenanceRecord
    | OciProvenanceRecord
    | RegistryProvenanceRecord
)


# ---------------------------------------------------------------------------
# Lockfile data model
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LockedDep:
    """A single dep entry in a lockfile.

    `identity` is the multihash-encoded content hash (#34). The
    `provenances` tuple records one or more ProvenanceRecord entries
    describing where the bytes came from. #33 ships with exactly one
    provenance per dep; #37 (Phase D) lights up multi-provenance.

    `active_flags` (#23) records the feature flag set active for this
    dep in the resolved graph. Empty tuple = no flags (or all defaults
    apply); omitted from emitted KDL when empty to keep diffs minimal.
    """
    name: str
    identity: str | None
    version: str
    src_dir: str
    requires: tuple[str, ...]
    provenances: tuple[ProvenanceRecord, ...]
    active_flags: tuple[str, ...] = ()
    # Self-mirrors harvested from this dep's milpa.kdl (#79).
    # Cached so subsequent resolves can fall through to them even
    # when the primary fetch fails before discovery.
    self_mirrors: tuple[str, ...] = ()


@dataclass(frozen=True)
class Lockfile:
    deps: tuple[LockedDep, ...]
    strategy: str = "maxver"
    version: int = LOCKFILE_SCHEMA_VERSION


class LockfileError(Exception):
    """Raised on malformed lockfile text or graph/lockfile mismatch.

    Carries a stable `code` (a `LOCK-*` slug from the error catalog) so
    callers can assert on condition rather than brittle message strings."""

    def __init__(self, message: str, *, code: str) -> None:
        self.code = code
        super().__init__(message)


# ---------------------------------------------------------------------------
# from_graph — bridge ResolvedDep (flat) → LockedDep (structured)
# ---------------------------------------------------------------------------


def from_graph(graph: ResolvedGraph, *, strategy: str = "maxver") -> Lockfile:
    """Convert a ResolvedGraph into a Lockfile.

    Deps are sorted by name for deterministic output — same graph
    always produces byte-identical lockfile text. `strategy` records
    which resolution strategy produced this lockfile (for diagnostics).
    """
    deps = tuple(sorted(
        (_locked_from_resolved(d) for d in graph.deps),
        key=lambda d: d.name,
    ))
    return Lockfile(deps=deps, strategy=strategy)


def _locked_from_resolved(d: ResolvedDep) -> LockedDep:
    """Translate a flat ResolvedDep into a structured LockedDep with
    the appropriate ProvenanceRecord variant based on the source
    field's prefix."""
    return LockedDep(
        name=d.name,
        identity=d.identity,
        version=_format_version(d.version),
        src_dir=d.src_dir,
        # Sort lexicographically: `requires` is accumulated in BFS
        # arrival order, which is not reproducible across parallel-fetch
        # runs or independent implementations. Lexicographic order is
        # the spec's single canonical ordering rule (lockfile-schema
        # §3.4 / resolver-semantics §4.4).
        requires=tuple(sorted(d.requires)),
        provenances=(_provenance_from_resolved(d),),
        active_flags=getattr(d, "active_flags", ()),
        self_mirrors=getattr(d, "self_mirrors", ()),
    )


def _provenance_from_resolved(d: ResolvedDep) -> ProvenanceRecord:
    """Reconstruct the lockfile ProvenanceRecord for a resolved dep.

    Primary path (#97 / Option A): dispatch on the type of the typed
    `provenance` object the resolver carried. This is the single source
    of truth — no source-string parsing, so the OCI case (whose flat
    `oci:{registry}/{repository}@{digest}` string is genuinely ambiguous
    to split) reconstructs cleanly by type.

    Fallback: when `provenance` is None (the synthetic root and workspace
    members — both never fetched, so they carry only a `source` marker),
    parse the `source` string. Named deps now always carry a typed git/oci
    provenance (milpa#97), so no `registry:` source string is ever
    produced; the bare-git arm remains a defensive catch-all."""
    # Dispatch lives here (the serialization layer) rather than as
    # Provenance.to_record() on the fetcher types: that would make
    # fetchers/* depend on lockfile record types — wrong layering
    # direction (fetchers are a lower layer than the lockfile).
    prov = d.provenance
    if isinstance(prov, GitProvenance):
        # commit_sha is the RESOLVED sha from the receipt (d.sha), not the
        # provenance's pin field — matches the legacy git arm exactly.
        return GitProvenanceRecord(url=prov.url, ref=prov.ref, commit_sha=d.sha)
    if isinstance(prov, TarballProvenance):
        # Preserve the declared expected_sha256 — this is the archive hash
        # recorded in the manifest (provenance receipt). Previously this was
        # incorrectly set to None, silently losing the declared hash (M11).
        return TarballProvenanceRecord(url=prov.url, sha256=prov.expected_sha256)
    if isinstance(prov, OciProvenance):
        return OciProvenanceRecord(
            registry=prov.registry,
            repository=prov.repository,
            digest=prov.digest,
        )
    # NOTE: LocalProvenance is intentionally absent here. _process_local in
    # resolver.py deliberately leaves provenance=None on local dep candidates
    # (see its comment: the typed LocalProvenance.path is absolute, but the
    # lockfile records the *declared relative* path). Local deps always reach
    # the source-string fallback below.
    if prov is not None:
        raise ValueError(
            f"dep {d.name!r}: unexpected typed provenance {type(prov).__name__!r} "
            f"— add a lockfile record arm for this provenance kind"
        )

    # --- None provenance: source-string fallback ---
    # Legitimate for: synthetic root, workspace members, local deps.
    src = d.source
    if src.startswith("local:"):
        return LocalProvenanceRecord(path=src[len("local:"):])
    if src.startswith("tarball:"):
        return TarballProvenanceRecord(url=src[len("tarball:"):], sha256=None)
    if src.startswith("member:"):
        return MemberProvenanceRecord(name=src[len("member:"):])
    return GitProvenanceRecord(url=src, ref=d.ref, commit_sha=d.sha)


def _format_version(v: Version) -> str:
    """Format a Version as a lossless semver string.

    Emits major.minor.patch[-pre][+build]. Build metadata is preserved
    for round-trip even though it is ignored for ordering and equality.
    Accepts both Version objects and bare 3-tuples (backward compat for
    tests and call sites that pass raw tuples).
    """
    if isinstance(v, Version):
        from .solver import _format_version_str
        return _format_version_str(v)
    # Bare tuple (e.g. (0, 0, 1)) — emit the release triple only.
    return f"{v[0]}.{v[1]}.{v[2]}"


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------


def parse_lockfile(text: str) -> Lockfile:
    """Parse KDL lockfile text into a Lockfile value."""
    try:
        doc = kdl.parse(text)
    except kdl.errors.ParseError as e:
        raise LockfileError(
            f"KDL syntax error: {e}", code="LOCK-KDL-SYNTAX"
        ) from e

    deps: list[LockedDep] = []
    strategy: str = "maxver"
    version: int | None = None
    for node in doc.nodes:
        if node.name == "version":
            version = _scalar_int(node, "version")
        elif node.name == "strategy":
            if len(node.args) == 1 and isinstance(node.args[0], str):
                strategy = node.args[0]
        elif node.name == "dep":
            deps.append(_parse_dep(node))

    if version is None:
        raise LockfileError(
            "lockfile missing required 'version' node",
            code="LOCK-VERSION-MISSING",
        )
    if version != LOCKFILE_SCHEMA_VERSION:
        raise LockfileError(
            f"unsupported lockfile schema version {version} "
            f"(this milpa understands version {LOCKFILE_SCHEMA_VERSION})",
            code="LOCK-VERSION-UNSUPPORTED",
        )

    return Lockfile(deps=tuple(deps), strategy=strategy, version=version)


def _scalar_int(node: kdl.Node, field_name: str) -> int:
    if len(node.args) != 1:
        raise LockfileError(
            f"{field_name!r} takes exactly one value",
            code="LOCK-FIELD-ARITY",
        )
    val = node.args[0]
    try:
        return int(val)  # type: ignore[arg-type]
    except (TypeError, ValueError) as e:
        raise LockfileError(
            f"{field_name!r} must be an integer (got {val!r})",
            code="LOCK-FIELD-TYPE",
        ) from e


def _parse_dep(node: kdl.Node) -> LockedDep:
    """Parse a dep block: identity + version + src_dir + requires +
    one-or-more provenance { ... } blocks."""
    name = _dep_name(node)
    identity = None
    version = "0.0.0"
    src_dir = ""
    requires: tuple[str, ...] = ()
    active_flags: tuple[str, ...] = ()
    self_mirrors: tuple[str, ...] = ()
    provenances: list[ProvenanceRecord] = []

    for child in node.nodes:
        if child.name == "identity":
            val = _scalar_str(child, name, "identity")
            try:
                identity = parse_identity(val)
            except IdentityError as e:
                raise LockfileError(
                    f"dep {name!r}: invalid identity — {e}",
                    code="LOCK-DEP-IDENTITY-INVALID",
                ) from e
        elif child.name == "version":
            version = _scalar_str(child, name, "version")
        elif child.name == "src_dir":
            src_dir = _scalar_str(child, name, "src_dir")
        elif child.name == "requires":
            requires = tuple(a for a in child.args if isinstance(a, str))
        elif child.name == "active_flags":
            active_flags = tuple(a for a in child.args if isinstance(a, str))
        elif child.name == "self_mirrors":
            # Accept both bare strings and (url)-annotated values (parsed
            # as ParseResult by kdl-py). url_value_to_str handles both and
            # returns "" for any other type — filter those out post-call so
            # no empty strings enter self_mirrors.
            from .kdl_util import url_value_to_str
            self_mirrors = tuple(
                s for a in child.args
                if (s := url_value_to_str(a))
            )
        elif child.name == "provenance":
            provenances.append(_parse_provenance_block(child, name))
        else:
            continue

    return LockedDep(
        name=name,
        identity=identity,
        version=version,
        src_dir=src_dir,
        requires=requires,
        provenances=tuple(provenances),
        active_flags=active_flags,
        self_mirrors=self_mirrors,
    )


def _parse_provenance_block(node: kdl.Node, dep_name: str) -> ProvenanceRecord:
    """Parse a `provenance { kind "..." ... }` block."""
    fields: dict[str, object] = {}
    for child in node.nodes:
        if len(child.args) != 1:
            raise LockfileError(
                f"dep {dep_name!r}: provenance field {child.name!r} "
                f"must have exactly one value",
                code="LOCK-PROV-FIELD-ARITY",
            )
        fields[child.name] = child.args[0]
    kind = fields.get("kind")
    if not isinstance(kind, str):
        raise LockfileError(
            f"dep {dep_name!r}: provenance block missing 'kind' discriminator",
            code="LOCK-PROV-KIND-MISSING",
        )
    if kind == "git":
        return GitProvenanceRecord(
            url=_required_str(fields, "url", dep_name),
            ref=_optional_str(fields, "ref"),
            commit_sha=_optional_str(fields, "commit_sha"),
        )
    if kind == "tarball":
        return TarballProvenanceRecord(
            url=_required_str(fields, "url", dep_name),
            sha256=_optional_str(fields, "sha256"),
        )
    if kind == "local":
        return LocalProvenanceRecord(
            path=_required_str(fields, "path", dep_name),
        )
    if kind == "member":
        return MemberProvenanceRecord(
            name=_required_str(fields, "name", dep_name),
        )
    if kind == "oci":
        return OciProvenanceRecord(
            registry=_required_str(fields, "registry", dep_name),
            repository=_required_str(fields, "repository", dep_name),
            digest=_required_str(fields, "digest", dep_name),
        )
    if kind == "registry":
        return RegistryProvenanceRecord(
            name=_required_str(fields, "name", dep_name),
            tag=_optional_str(fields, "tag"),
            commit_sha=_optional_str(fields, "commit_sha"),
        )
    raise LockfileError(
        f"dep {dep_name!r}: unknown provenance kind {kind!r} "
        f"(supported: git, tarball, local, member, oci, registry)",
        code="LOCK-PROV-KIND-UNKNOWN",
    )


def _dep_name(node: kdl.Node) -> str:
    if len(node.args) != 1 or not isinstance(node.args[0], str):
        raise LockfileError(
            "dep node requires exactly one string argument (the name)",
            code="LOCK-DEP-NAME-ARITY",
        )
    return node.args[0]


def _scalar_str(node: kdl.Node, dep_name: str, field_name: str) -> str:
    if len(node.args) != 1 or not isinstance(node.args[0], str):
        raise LockfileError(
            f"dep {dep_name!r} field {field_name!r} must have exactly one string value",
            code="LOCK-DEP-FIELD-ARITY",
        )
    return node.args[0]


def _required_str(fields: dict, key: str, dep_name: str) -> str:
    val = fields.get(key)
    if not isinstance(val, str):
        raise LockfileError(
            f"dep {dep_name!r}: provenance missing required field {key!r}",
            code="LOCK-PROV-FIELD-MISSING",
        )
    return val


def _optional_str(fields: dict, key: str) -> str | None:
    val = fields.get(key)
    if val is None:
        return None
    return val if isinstance(val, str) else None


# ---------------------------------------------------------------------------
# Formatter
# ---------------------------------------------------------------------------


_KDL_ESCAPES = {
    '"': '\\"',
    "\\": "\\\\",
    "\n": "\\n",
    "\r": "\\r",
    "\t": "\\t",
    "\b": "\\b",
    "\f": "\\f",
}


def _kdl_str(s: str) -> str:
    """Return `s` as a double-quoted, KDL-escaped string literal.

    The single source of truth for emitting a KDL string value in a
    lockfile (R11, lockfile-schema §7). Escapes `"`, `\\`, and control
    characters so the output is valid KDL that `parse_lockfile` recovers
    byte-for-value — the parser uses the real KDL grammar (which unescapes
    on read), so the writer MUST escape on write or the round-trip breaks.
    """
    out = []
    for ch in s:
        esc = _KDL_ESCAPES.get(ch)
        if esc is not None:
            out.append(esc)
        elif ord(ch) < 0x20:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def format_lockfile(lockfile: Lockfile) -> str:
    """Render a Lockfile to KDL text."""
    lines = [
        _HEADER,
        f"version {lockfile.version}",
        f"strategy {_kdl_str(lockfile.strategy)}",
        "",
    ]
    for dep in lockfile.deps:
        lines.append(f"dep {_kdl_str(dep.name)} {{")
        if dep.identity is not None:
            lines.append(f"    identity {_kdl_str(dep.identity)}")
        lines.append(f"    version {_kdl_str(dep.version)}")
        lines.append(f"    src_dir {_kdl_str(dep.src_dir)}")
        if dep.requires:
            req_args = " ".join(_kdl_str(r) for r in dep.requires)
            lines.append(f'    requires {req_args}')
        else:
            lines.append("    requires")
        if dep.active_flags:
            flag_args = " ".join(_kdl_str(f) for f in dep.active_flags)
            lines.append(f'    active_flags {flag_args}')
        if dep.self_mirrors:
            sm_args = " ".join(f"(url){_kdl_str(u)}" for u in dep.self_mirrors)
            lines.append(f'    self_mirrors {sm_args}')
        for prov in dep.provenances:
            lines.append("    provenance {")
            for line in _format_provenance_fields(prov):
                lines.append(f"        {line}")
            lines.append("    }")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _format_provenance_fields(p: ProvenanceRecord) -> list[str]:
    """Emit the kind discriminator + kind-specific fields for a
    provenance block."""
    out = [f"kind {_kdl_str(p.kind)}"]
    if isinstance(p, GitProvenanceRecord):
        out.append(f"url {_kdl_str(p.url)}")
        if p.ref is not None:
            out.append(f"ref {_kdl_str(p.ref)}")
        if p.commit_sha is not None:
            out.append(f"commit_sha {_kdl_str(p.commit_sha)}")
    elif isinstance(p, TarballProvenanceRecord):
        out.append(f"url {_kdl_str(p.url)}")
        if p.sha256 is not None:
            out.append(f"sha256 {_kdl_str(p.sha256)}")
    elif isinstance(p, LocalProvenanceRecord):
        out.append(f"path {_kdl_str(p.path)}")
    elif isinstance(p, MemberProvenanceRecord):
        out.append(f"name {_kdl_str(p.name)}")
    elif isinstance(p, OciProvenanceRecord):
        out.append(f"registry {_kdl_str(p.registry)}")
        out.append(f"repository {_kdl_str(p.repository)}")
        out.append(f"digest {_kdl_str(p.digest)}")
    elif isinstance(p, RegistryProvenanceRecord):
        out.append(f"name {_kdl_str(p.name)}")
        if p.tag is not None:
            out.append(f"tag {_kdl_str(p.tag)}")
        if p.commit_sha is not None:
            out.append(f"commit_sha {_kdl_str(p.commit_sha)}")
    return out


def write_lockfile(lockfile: Lockfile, path: Path) -> Path:
    """Write lockfile KDL text to `path`. Returns the path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(format_lockfile(lockfile))
    return path


def load_lockfile(path: Path) -> Lockfile:
    """Read and parse a lockfile from disk."""
    try:
        text = path.read_text()
    except FileNotFoundError as e:
        raise LockfileError(
            f"lockfile not found: {path}", code="LOCK-FILE-NOT-FOUND"
        ) from e
    except OSError as e:
        raise LockfileError(
            f"cannot read lockfile {path}: {e}", code="LOCK-FILE-UNREADABLE"
        ) from e
    return parse_lockfile(text)


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


def verify_against_graph(
    lockfile: Lockfile,
    graph: ResolvedGraph,
) -> None:
    """Confirm the graph matches the lockfile dep-for-dep."""
    locked_by_name = {d.name: d for d in lockfile.deps}
    graph_by_name = {d.name: d for d in graph.deps}

    errors: list[str] = []
    for name in graph_by_name.keys() - locked_by_name.keys():
        errors.append(f"unexpected dep {name!r} in resolved graph (not in lockfile)")
    for name in locked_by_name.keys() - graph_by_name.keys():
        errors.append(f"locked dep {name!r} is missing from resolved graph")
    for name in graph_by_name.keys() & locked_by_name.keys():
        locked = locked_by_name[name]
        actual = graph_by_name[name]
        if locked.identity != actual.identity:
            errors.append(
                f"identity mismatch for {name!r}: "
                f"locked={locked.identity!r}, actual={actual.identity!r}"
            )

    if errors:
        raise LockfileError(
            "lockfile does not match resolved graph:\n  " + "\n  ".join(errors),
            code="LOCK-GRAPH-MISMATCH",
        )


def verify_lockfile_against_deps(
    lockfile: Lockfile,
    deps_dir: Path,
) -> list[str]:
    """Walk deps_dir/<name>/ for each locked dep and verify its
    identity matches the lockfile's recorded value."""
    divergences: list[str] = []
    locked_by_name = {d.name: d for d in lockfile.deps}

    for name, locked in locked_by_name.items():
        dep_path = deps_dir / name
        if not dep_path.exists():
            divergences.append(f"{name}: missing from {deps_dir}/")
            continue
        if not dep_path.is_dir():
            divergences.append(
                f"{name}: expected directory at {dep_path}, found something else"
            )
            continue
        actual = compute_content_hash(dep_path)
        expected = locked.identity
        if expected != actual:
            divergences.append(
                f"{name}: identity mismatch — "
                f"lockfile says {(expected or '<none>')[:23]}..., "
                f"actual {actual[:23]}..."
            )

    if deps_dir.exists() and deps_dir.is_dir():
        for entry in deps_dir.iterdir():
            if entry.name.startswith("."):
                continue
            if entry.name not in locked_by_name:
                divergences.append(
                    f"{entry.name}: extra dep in {deps_dir}/ not in lockfile"
                )

    return divergences


def verify_workspace_against_disk(
    workspace,  # Workspace from milpa.workspace
    lockfile: Lockfile,
) -> list[str]:
    """Workspace-aware drift detection.

    Each lockfile entry's first provenance determines its verification
    location: a MemberProvenanceRecord routes to the workspace member;
    everything else routes to <root>/_deps/<name>/.
    """
    members_by_name = {m.name: m for m in workspace.members}
    deps_dir = workspace.root / "_deps"
    divergences: list[str] = []

    for locked in lockfile.deps:
        member_target: Path | None = None
        if locked.provenances:
            first = locked.provenances[0]
            if isinstance(first, MemberProvenanceRecord):
                member = members_by_name.get(first.name)
                if member is None:
                    divergences.append(
                        f"{locked.name}: lockfile references workspace member "
                        f"{first.name!r} that is not in the current workspace"
                    )
                    continue
                member_target = member.directory

        target = member_target if member_target is not None else deps_dir / locked.name

        if not target.exists():
            divergences.append(f"{locked.name}: missing from {target}")
            continue
        if not target.is_dir():
            divergences.append(
                f"{locked.name}: expected directory at {target}, found something else"
            )
            continue
        actual = compute_content_hash(target)
        if locked.identity != actual:
            divergences.append(
                f"{locked.name}: identity mismatch — "
                f"lockfile says {(locked.identity or '<none>')[:23]}..., "
                f"actual {actual[:23]}..."
            )
    return divergences
