"""nim.cfg emission from a resolved dep graph.

Generates a `nim.cfg` file at the consuming project's root with one
``--path:`` line per resolved dep. The Nim compiler reads this file
automatically when invoked from the project directory and adds the
listed paths to its import search — no nimble involvement needed.

Owns:
  - format_nimcfg(graph, *, deps_dir, self_src_dir, flag_defines) -> str
  - format_workspace_nimcfgs(workspace, graph, flag_defines) -> dict[str, str]  [S9d/S11]

Spec references: lockfile-schema.md §7.1–7.4 (normative); §7.5 (feature-flag
-d: defines, un-deferred by RFC #23 S6); §7.6 (workspace per-member emission);
§3.8 (workspace feature unification — S11).
"""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
from typing import TYPE_CHECKING

from milpa.lockfile import (
    MemberProvenanceRecord,
    ResolvedDep,
    ResolvedGraph,
    RootProvenanceRecord,
)
from milpa.version import DepKey, dep_dir_name

if TYPE_CHECKING:
    from milpa.workspace import LoadedMember, LoadedWorkspace

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: The normative three-line header (§7.1). Stored without its trailing newline;
#: the emission logic joins lines and adds newlines.
_HEADER_LINES = (
    "# generated by milpa; do not edit",
    "# manifest: milpa.kdl",
    "# lockfile: milpa.lock",
)


# ---------------------------------------------------------------------------
# format_nimcfg — normative single-package emitter (§7.1–7.4)
# ---------------------------------------------------------------------------


def format_nimcfg(
    graph: ResolvedGraph,
    *,
    deps_dir: Path = Path("_deps"),
    self_src_dir: str = "",
    flag_defines: dict[str, dict[str, tuple[str, ...]]] | None = None,
) -> str:
    """Render *graph* into ``nim.cfg`` text (lockfile-schema.md §7.1–7.5).

    Emission order (§7.4 / §7.5):

    1. File-level header comment (§7.1) — always present, even for an empty
       graph.
    2. Self src-dir path — ``--path:"<self_src_dir>"`` — emitted first (before
       dep paths) when *self_src_dir* is non-empty, so self-modules shadow
       same-named dep import paths.
    3. Dep ``--path:`` lines — one per dep, sorted lexicographically by dep name
       (resolver-semantics.md §4.4 — the single canonical ordering rule; a
       toposort's sibling tie-break is not reproducible across implementations).
    4. Feature-flag ``-d:`` defines (§7.5) — emitted when *flag_defines* is
       provided. The block is separated from the ``--path:`` block by a blank
       line; ``-d:`` symbols are lexicographically ordered across all active
       flags of all deps (reproducibility). Defines come from the manifest, not
       the lockfile (SSOT — see RFC #23 §3.6). Callers must pre-compute
       *flag_defines* from each dep's manifest: ``dep_name → flag_name →
       defines_symbols``. When a flag has no explicit ``defines``, the
       childless convention applies: ``-d:<pkg>_<flag>`` (RFC §3.6, normative).

    When groups (2)+(3) are both empty the file contains only the header
    (§7.4: "Groups (1) and (2) are omitted when empty"). The file ends with a
    single trailing ``\\n`` — not a blank line (§7.4 NOTE).

    All paths use POSIX separators regardless of host OS (§7.2).

    *flag_defines* is ``None`` (default) for callers that do not yet supply
    manifest flag tables; no ``-d:`` lines are emitted in that case.
    """
    path_lines: list[str] = []

    if self_src_dir:
        path_lines.append(f'--path:"{self_src_dir}"')

    # Lexicographic by dep_dir_name — spec's single canonical ordering rule.
    # For qualified deps, sort by ``@<ns>/<name>`` so the order matches the
    # on-disk layout and the lockfile sort order (both use dep_dir_name).
    ordered = sorted(graph.deps, key=lambda d: dep_dir_name(d.name, d.namespace))
    for dep in ordered:
        # §14.5: the standalone root's own self-satisfying entry gets NO
        # --path: line here — its source directory is already emitted as the
        # self_src_dir line above (it IS the root); a --path: pointing at
        # "_deps/<name>" would reference a directory that is never created
        # (the root's tree is never staged into _deps/).
        if _is_root_self_dep(dep):
            continue
        path_lines.append(f'--path:"{_path_for(dep, deps_dir)}"')
        # B-nimcfg: emit one --path: per alias (lex-sorted, already sorted on dep).
        # Each alias path mirrors the canonical: _deps/<alias>[/<src_dir>].
        for alias in dep.aliases:
            alias_path = deps_dir.as_posix() + "/" + alias
            if dep.src_dir:
                alias_path += "/" + dep.src_dir
            path_lines.append(f'--path:"{alias_path}"')

    # §7.5 feature-flag defines — un-deferred (RFC #23 S6).
    # Collect all -d: symbols across all deps with active flags.
    define_symbols: list[str] = []
    if flag_defines is not None:
        for dep in ordered:
            if _is_root_self_dep(dep) or not dep.active_flags:
                continue
            dep_flag_table = flag_defines.get(dep.name, {})
            for flag_name in dep.active_flags:
                if flag_name in dep_flag_table:
                    syms = dep_flag_table[flag_name]
                    if syms:
                        define_symbols.extend(syms)
                    else:
                        # Childless-convention: -d:<pkg>_<flag>
                        define_symbols.append(f"{dep.name}_{flag_name}")
    # Lexicographic order across all emitted symbols (reproducibility, §3.6).
    define_symbols.sort()

    if path_lines:
        parts = [*_HEADER_LINES, "", *path_lines]
        if define_symbols:
            # Blank line separator between --path: block and -d: block (§7.5).
            parts.append("")
            parts.extend(f"-d:{sym}" for sym in define_symbols)
        return "\n".join(parts) + "\n"
    else:
        # No deps, no self src-dir: header only, trailing newline (§7.4).
        return "\n".join(_HEADER_LINES) + "\n"


def build_flag_defines(
    graph: ResolvedGraph,
    deps_dir: Path,
) -> dict[str, dict[str, tuple[str, ...]]]:
    """Build the ``flag_defines`` map for :func:`format_nimcfg` (§7.5 S6, RFC #23 §3.6).

    Reads each dep's ``milpa.kdl`` from ``deps_dir/<name>/milpa.kdl`` (SSOT —
    defines live in the manifest, not the lockfile).  Missing or unparseable
    manifests produce an empty flag table for that dep (warn-and-skip, not an
    error — not every dep has a ``milpa.kdl``).

    Returns ``dep_name → flag_name → defines_symbols``.
    """
    from milpa.manifest import parse_manifest  # local import to avoid circular dependency

    result: dict[str, dict[str, tuple[str, ...]]] = {}
    for dep in graph.deps:
        # C1: qualified deps live at ``@<ns>/<name>/``, not ``<name>/``.
        _dir_entry = dep_dir_name(dep.name, dep.namespace)
        dep_manifest = deps_dir / _dir_entry / "milpa.kdl"
        if not dep_manifest.is_file():
            continue
        try:
            dm = parse_manifest(dep_manifest.read_text(encoding="utf-8"))
        except Exception:
            continue
        result[dep.name] = {f.name: f.defines for f in dm.flags}
    return result


def _path_for(dep: ResolvedDep, deps_dir: Path) -> str:
    """Compute ``<deps_dir>/<dir_entry>[/<src_dir>]`` in POSIX form (§7.3).

    *deps_dir* may be a relative Path like ``Path("_deps")``; ``as_posix()``
    yields ``"_deps"`` which is correct.  An absolute Path gives ``"/abs/path"``.

    C1 (rfc-resolver-correctness.md): uses ``dep_dir_name`` so qualified deps
    emit ``--path:"_deps/@<ns>/<name>[/src]"`` (Windows-safe, no ``::``).
    """
    _dir_entry = dep_dir_name(dep.name, dep.namespace)
    base = deps_dir.as_posix() + "/" + _dir_entry
    if dep.src_dir:
        base += "/" + dep.src_dir
    return base


# ---------------------------------------------------------------------------
# format_workspace_nimcfgs — per-member nim.cfg emission (S9d / §7.6)
# ---------------------------------------------------------------------------


def format_workspace_nimcfgs(
    workspace: LoadedWorkspace,
    graph: ResolvedGraph,
    flag_defines: dict[str, dict[str, tuple[str, ...]]] | None = None,
) -> dict[str, str]:
    """Per-member ``nim.cfg`` emitter for workspace projects (§7.6 / S11 §3.8).

    Returns a ``dict`` mapping each member's as-declared workspace-relative
    ``rel_path`` to its ``nim.cfg`` text.

    Per-member layout (§7.6):
    - Each member receives only the deps in its transitive closure.
    - Emission order per member (S7, §5.9 / Breadth-P3d):
        1. **Self src-dir first**: if the member's manifest has ``src_dir`` set,
           ``--path:"<src_dir>"`` is emitted FIRST (self-module shadowing priority
           — same rule as single-package ``format_nimcfg``).
        2. **Dep paths lex-sorted by name**: external deps (git/tarball/named) via
           ``<root_to_member>/_deps/<name>[/src]`` and member-to-member references
           ``<rel_to_other_member>[/src_dir]``, both expressed relative from the
           member dir.

    S11 (RFC #23 §3.8): workspace feature unification — each member's nim.cfg
    includes the ``-d:`` defines for ALL flags active on shared deps in the
    workspace graph (the unified ``dep.active_flags``), not only that member's
    own requests.  Pass ``flag_defines`` (built by ``build_flag_defines``) to
    enable this; the map is the same SSOT used for single-package emission.

    ``workspace`` is a ``LoadedWorkspace``; typed as ``object`` to avoid
    circular imports (nimcfg.py must not import workspace.py).
    """
    # Build lookup structures from the workspace and graph.
    # member.rel_path → member.abs_dir (LoadedMember fields accessed by name)
    member_by_name: dict[str, LoadedMember] = {}
    for m in workspace.members:
        member_by_name[m.manifest.name] = m

    workspace_root: Path = workspace.root_dir

    # Build graph lookups. KEY BY THE QUALIFIED SOLVER-VAR, not the bare name:
    # ``ResolvedDep.requires`` entries are qualified solver-variable strings
    # (``ns1::foo``), so a bare-name index silently misses a namespace-qualified
    # transitive dep — dropping it AND its whole subtree from the member's
    # nim.cfg --path closure with no error (R2). A member's own key is
    # ``DepKey(member_name, None).solver_var()`` == the bare member name, so the
    # member lookup below is unaffected.
    dep_by_name: dict[str, ResolvedDep] = {
        DepKey(name=d.name, namespace=d.namespace).solver_var(): d for d in graph.deps
    }

    out: dict[str, str] = {}

    for member in workspace.members:
        member_name: str = member.manifest.name
        member_abs_dir: Path = member.abs_dir
        member_rel_path: str = member.rel_path

        # Compute transitive closure for this member (excluding member itself).
        closure = _member_dep_closure(graph, dep_by_name, member_name)

        # Sort lexicographically by dep name (§4.4 / §7.4).
        closure_sorted = sorted(closure, key=lambda d: d.name)

        path_lines: list[str] = []

        # S7 (#93): emit member's own src_dir FIRST (self-module shadowing
        # priority) — mirrors format_nimcfg's self-first rule (nimcfg.py:85-86).
        # Only emitted when the member itself has a src_dir declared.
        member_src_dir: str = member.manifest.src_dir  # "" when absent
        if member_src_dir:
            path_lines.append(f'--path:"{member_src_dir}"')

        for dep in closure_sorted:
            target = _dep_target(
                dep, workspace_root, member_by_name
            )
            rel = _relpath_posix(target, member_abs_dir)
            path_lines.append(f'--path:"{rel}"')

        # S11 §3.8: compute unified -d: defines from active_flags on closure deps.
        # Uses the same logic as format_nimcfg §7.5 — active_flags on each dep
        # are already the workspace-wide union (all members' requests merged by
        # the resolver's shared dep_active_flags map).
        define_symbols: list[str] = []
        if flag_defines is not None:
            for dep in closure_sorted:
                if not dep.active_flags:
                    continue
                dep_flag_table = flag_defines.get(dep.name, {})
                for flag_name in dep.active_flags:
                    if flag_name in dep_flag_table:
                        syms = dep_flag_table[flag_name]
                        if syms:
                            define_symbols.extend(syms)
                        else:
                            # Childless-convention: -d:<pkg>_<flag>
                            define_symbols.append(f"{dep.name}_{flag_name}")
            define_symbols.sort()

        if path_lines:
            parts = [*_HEADER_LINES, "", *path_lines]
            if define_symbols:
                parts.append("")
                parts.extend(f"-d:{sym}" for sym in define_symbols)
            text = "\n".join(parts) + "\n"
        else:
            text = "\n".join(_HEADER_LINES) + "\n"

        out[member_rel_path] = text

    return out


def _dep_target(
    dep: ResolvedDep,
    workspace_root: Path,
    member_by_name: Mapping[str, LoadedMember],
) -> Path:
    """Compute the absolute source path for ``dep``.

    For workspace members: ``member.abs_dir[/src_dir]``.
    For external deps:     ``workspace_root/_deps/<name>[/src_dir]``.
    """
    if _is_member_dep(dep) and dep.name in member_by_name:
        base: Path = member_by_name[dep.name].abs_dir
    else:
        # C1: qualified deps live at ``_deps/@<ns>/<name>``.
        _dir_entry = dep_dir_name(dep.name, dep.namespace)
        base = workspace_root / "_deps" / _dir_entry

    if dep.src_dir:
        return base / dep.src_dir
    return base


def _is_member_dep(dep: ResolvedDep) -> bool:
    """True when the dep has a MemberProvenanceRecord (workspace member)."""
    return any(isinstance(p, MemberProvenanceRecord) for p in dep.provenances)


def _is_root_self_dep(dep: ResolvedDep) -> bool:
    """True when the dep has a RootProvenanceRecord (§14 root-self entry)."""
    return any(isinstance(p, RootProvenanceRecord) for p in dep.provenances)


def _member_dep_closure(
    graph: ResolvedGraph,
    dep_by_name: dict[str, ResolvedDep],
    member_name: str,
) -> list[ResolvedDep]:
    """Return the transitive closure reachable from ``member_name``.

    Excludes the member itself. Mirrors Rust ``member_dep_closure``.
    """
    visited: set[str] = set()
    result: list[ResolvedDep] = []

    def _visit(name: str) -> None:
        if name in visited:
            return
        dep = dep_by_name.get(name)
        if dep is None:
            return
        visited.add(name)
        for req in dep.requires:
            _visit(req)
        result.append(dep)

    member_dep = dep_by_name.get(member_name)
    if member_dep is not None:
        for req in member_dep.requires:
            _visit(req)

    return result


def _relpath_posix(target: Path, base: Path) -> str:
    """Return a POSIX relative path from ``base`` directory to ``target``.

    Equivalent to ``os.path.relpath(target, start=base)`` but in POSIX form.
    Both paths should be absolute.
    """
    target_parts = target.parts
    base_parts = base.parts

    # Find the common prefix length.
    common = 0
    for t, b in zip(target_parts, base_parts, strict=False):
        if t == b:
            common += 1
        else:
            break

    up = len(base_parts) - common
    down = target_parts[common:]

    parts: list[str] = [".."] * up + list(down)
    if not parts:
        return "."
    return "/".join(parts)
