"""milpa.lock — reproducible-build snapshot of a resolved dep graph.

Owns:
  - ProvenanceRecord discriminated union (6 variants + 1 read-compat variant)
  - LockedDep, Lockfile — lockfile data model
  - ResolvedDep, ResolvedGraph — resolver output types (owned here to avoid
    forward-import cycles: resolver.py imports and *produces* these types;
    lockfile.py owns them so from_graph/verify need no fetcher/resolver import)
  - parse_lockfile(text) -> Lockfile
  - from_graph(graph, *, strategy) -> Lockfile
  - format_lockfile(lock) -> str  — byte-exact hand-rolled templating (SSOT)
  - verify_against_graph(lockfile, graph) -> None
  - verify_lockfile_against_deps(lockfile, deps_dir) -> list[str]

Layering: lockfile.py ← resolver.py (resolver imports ResolvedDep/ResolvedGraph
from lockfile, not the other way). See RFC §4.2.

Format: KDL 2.0 via kdl_io.parse_kdl(text, context="lockfile") for parsing.
Emission is hand-rolled string templating — the lockfile NEVER goes through a
KDL AST emitter. _kdl_str is the single source of truth for string escaping.

ProvenanceRecord kinds (lockfile-schema.md §4):
    git      — §4.1: url (req), ref (opt), commit_sha (opt)
    tarball  — §4.2: url (req), sha256 (opt, TOFU receipt)
    local    — §4.3: path (req, as-declared relative)
    member   — §4.4: name (req, workspace member name)
    oci      — §4.5: registry/repository/digest (all req)
    registry — §4.6: read-compat only; writer never emits this kind
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from milpa.errors import (
    LOCK_DEP_FIELD_ARITY,
    LOCK_DEP_IDENTITY_INVALID,
    LOCK_DEP_NAME_ARITY,
    LOCK_DEPDECL_PIN_MISSING,
    LOCK_FIELD_ARITY,
    LOCK_FIELD_TYPE,
    LOCK_GRAPH_MISMATCH,
    LOCK_PROV_FIELD_ARITY,
    LOCK_PROV_FIELD_MISSING,
    LOCK_PROV_KIND_MISSING,
    LOCK_PROV_KIND_UNKNOWN,
    LOCK_VERSION_MISSING,
    LOCK_VERSION_UNSUPPORTED,
    VERIFY_EDGE_MISMATCH,
    MilpaError,
)
from milpa.identity import compute_content_hash
from milpa.kdl_io import (
    KdlNode,
    node_args,
    node_children,
    node_name,
    nodes,
    parse_kdl,
    value_as_int,
    value_as_str,
)

# ---------------------------------------------------------------------------
# Schema constant
# ---------------------------------------------------------------------------

LOCKFILE_SCHEMA_VERSION: int = 1
_HEADER = "// generated by milpa; reproducible build snapshot"

# ---------------------------------------------------------------------------
# ProvenanceRecord — 6 variants + 1 read-compat (lockfile-schema.md §4)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class GitProvenanceRecord:
    """Provenance for a git-fetched dep (§4.1).

    url is required. ref and commit_sha are optional — omitted when None.
    commit_sha is the resolved SHA from the fetch receipt, not the manifest ref.
    """

    url: str
    ref: str | None = None
    commit_sha: str | None = None
    kind: str = field(default="git", init=False)


@dataclass(frozen=True)
class TarballProvenanceRecord:
    """Provenance for a tarball-fetched dep (§4.2).

    url is required. sha256 is optional on first fetch (TOFU model — §5);
    once pinned it is preserved on all subsequent lockfile writes.
    sha256 records the archive hash (transport integrity), NOT the identity
    (source-tree hash). These are orthogonal fields.
    """

    url: str
    sha256: str | None = None
    kind: str = field(default="tarball", init=False)


@dataclass(frozen=True)
class LocalProvenanceRecord:
    """Provenance for a local-path dep (§4.3).

    path is the as-declared relative path from the project root. NOT resolved
    to absolute — portability across machines with the same workspace layout.
    """

    path: str
    kind: str = field(default="local", init=False)


@dataclass(frozen=True)
class MemberProvenanceRecord:
    """Provenance for a workspace-internal member reference (§4.4)."""

    name: str
    kind: str = field(default="member", init=False)


@dataclass(frozen=True)
class OciProvenanceRecord:
    """Provenance for an OCI-artifact dep (§4.5).

    All three fields are required. digest is the immutable content-addressed
    pin (e.g. sha256:…).
    """

    registry: str
    repository: str
    digest: str
    kind: str = field(default="oci", init=False)


@dataclass(frozen=True)
class RegistryProvenanceRecord:
    """READ-COMPAT ONLY (lockfile-schema.md §4.6).

    The writer never emits this kind — named deps now resolve to git/oci via
    tianguis. The parser must still accept `registry` provenance blocks in
    existing lockfiles. This class is retained until straggler old lockfiles are
    regenerated; it will be removed in a future schema version.
    """

    name: str
    tag: str | None = None
    commit_sha: str | None = None
    kind: str = field(default="registry", init=False)


#: Discriminated union of all provenance record variants.
ProvenanceRecord = (
    GitProvenanceRecord
    | TarballProvenanceRecord
    | LocalProvenanceRecord
    | MemberProvenanceRecord
    | OciProvenanceRecord
    | RegistryProvenanceRecord
)

# ---------------------------------------------------------------------------
# Lockfile data model
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LockedDep:
    """A single dep entry in a lockfile (lockfile-schema.md §3).

    identity: multihash-encoded content hash (sha256:<64hex>). May be None for
      deps not yet content-hashed (Phase A partial).
    version: semver string. Parser default when absent: "0.0.0". Emitter writes
      "0.0.1" for non-versioned dep kinds (url/tarball/local/member/oci).
    src_dir: relative path from dep root to Nim source dir. Empty string = root.
    requires: direct transitive dep names, sorted lexicographically.
    provenances: exactly one ProvenanceRecord per dep (Phase D #37 adds multi).
    active_flags: feature flags active for this dep; omitted from KDL when empty.
    self_mirrors: URLs from this dep's milpa.kdl mirrors block (#79); cached for
      fallback fetching; omitted from KDL when empty.
    """

    name: str
    identity: str | None
    version: str
    src_dir: str
    requires: tuple[str, ...]
    provenances: tuple[ProvenanceRecord, ...]
    active_flags: tuple[str, ...] = ()
    self_mirrors: tuple[str, ...] = ()
    # S6: additive dep_decl pin (§3.7). Emitted only when present (dep resolved
    # via DepDeclEdgeSource). Forward-compat: older/absent = None = fine; no
    # lockfile schema bump (lockfile-schema.md §3.7).
    dep_decl: str | None = None


@dataclass(frozen=True)
class Lockfile:
    """Parsed or constructed lockfile."""

    deps: tuple[LockedDep, ...]
    strategy: str = "maxver"
    version: int = LOCKFILE_SCHEMA_VERSION


# ---------------------------------------------------------------------------
# ResolvedDep + ResolvedGraph
#
# These types are defined here (not in resolver.py) to avoid a forward import
# cycle: resolver.py imports and *produces* these; lockfile.py consumes them
# in from_graph/verify_against_graph. The layering mirrors Rust's milpa_types
# crate which co-locates Lockfile/ResolvedGraph types.
#
# Minimal fields — only what from_graph and verify_against_graph actually need.
# resolver.py (S9) will import these and populate them.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ResolvedDep:
    """A single dep in a resolved graph.

    name:       dep name
    identity:   multihash-encoded content hash (may be None)
    version:    resolved version string (e.g. "1.2.3", "0.0.1" for non-versioned)
    src_dir:    relative path to Nim sources within the dep root
    requires:   names of direct transitive deps (order not guaranteed — sorted
                by from_graph when building LockedDep)
    provenance: typed ProvenanceRecord describing origin (set by the resolver
                at fetch time; None for the synthetic root dep)
    active_flags: feature flags active for this dep
    self_mirrors: mirror URLs from this dep's milpa.kdl
    """

    name: str
    identity: str | None
    version: str
    src_dir: str
    requires: tuple[str, ...]
    provenance: ProvenanceRecord | None = None
    active_flags: tuple[str, ...] = ()
    self_mirrors: tuple[str, ...] = ()
    # S6: the dep_decl hash this resolution was computed against (from the index
    # pointer, carried through _Candidate → ResolvedDep → LockedDep → lockfile).
    # None for non-indexed deps (URL/tarball/local/member) and for named deps
    # whose index entry has no dep_decl pointer yet.
    dep_decl: str | None = None


@dataclass(frozen=True)
class ResolvedGraph:
    """Complete set of resolved deps produced by the resolver.

    ``cert`` carries the ``SolveSuccess`` certificate (``solver.py``) when
    the resolver builds it.  Typed ``Any`` to avoid a circular import
    (lockfile.py ← resolver.py ← solver.py; lockfile.py MUST NOT import
    solver.py).  The CLI's certificate flag reads this field; all other
    consumers ignore it.  ``None`` means no certificate was built.
    """

    deps: tuple[ResolvedDep, ...]
    cert: Any = None  # SolveSuccess | None


# ---------------------------------------------------------------------------
# 4a helpers — _validate_identity (lockfile parse uses its own inline raising)
# ---------------------------------------------------------------------------


def _parse_identity_for_lockfile(val: Any, dep_name: str) -> str:
    """Validate a multihash identity string for a lockfile dep.

    Wraps the identity checks inline (avoids importing identity.parse_identity
    which raises MilpaError with ID_* codes; here we re-raise as
    LOCK_DEP_IDENTITY_INVALID per the lockfile error catalog).
    """
    # Check 1: string
    if not isinstance(val, str):
        raise MilpaError(
            LOCK_DEP_IDENTITY_INVALID,
            f"dep {dep_name!r}: identity must be a string, got {type(val).__name__!r}",
            dep=dep_name,
        )
    # Check 2: has ':' separator
    if ":" not in val:
        raise MilpaError(
            LOCK_DEP_IDENTITY_INVALID,
            f"dep {dep_name!r}: identity {val!r} missing algorithm prefix "
            f"(expected '<algorithm>:<digest>')",
            dep=dep_name,
            identity=val,
        )
    algorithm, _, digest = val.partition(":")
    # Check 3: supported algorithm
    if algorithm not in {"sha256"}:
        raise MilpaError(
            LOCK_DEP_IDENTITY_INVALID,
            f"dep {dep_name!r}: identity {val!r} uses unsupported algorithm "
            f"{algorithm!r} (supported: sha256)",
            dep=dep_name,
            identity=val,
        )
    # Check 4: digest length
    if len(digest) != 64:
        raise MilpaError(
            LOCK_DEP_IDENTITY_INVALID,
            f"dep {dep_name!r}: sha256 digest must be exactly 64 hex chars, "
            f"got {len(digest)}",
            dep=dep_name,
            identity=val,
        )
    # Check 5: lowercase hex
    if not all(c in "0123456789abcdef" for c in digest):
        raise MilpaError(
            LOCK_DEP_IDENTITY_INVALID,
            f"dep {dep_name!r}: identity {val!r} digest contains non-lowercase-hex chars",
            dep=dep_name,
            identity=val,
        )
    return val


# ---------------------------------------------------------------------------
# 4b — parse_lockfile
# ---------------------------------------------------------------------------


def parse_lockfile(text: str) -> Lockfile:
    """Parse KDL 2.0 lockfile text into a ``Lockfile`` value.

    Raises ``MilpaError`` with LOCK-* slugs on any parse error.
    Defaults: strategy = "maxver" (tolerates pre-v1.0 lockfiles without the
    strategy node, per lockfile-schema.md §2.2).
    """
    doc = parse_kdl(text, context="lockfile")

    deps: list[LockedDep] = []
    strategy: str = "maxver"
    schema_version: int | None = None

    for node in nodes(doc):
        name = node_name(node)
        if name == "version":
            schema_version = _parse_top_version(node)
        elif name == "strategy":
            strategy = _parse_top_strategy(node)
        elif name == "dep":
            deps.append(_parse_dep(node))
        # Any other top-level node is silently ignored for forward compat

    if schema_version is None:
        raise MilpaError(
            LOCK_VERSION_MISSING,
            "lockfile missing required 'version' node",
        )
    if schema_version != LOCKFILE_SCHEMA_VERSION:
        raise MilpaError(
            LOCK_VERSION_UNSUPPORTED,
            f"unsupported lockfile schema version {schema_version} "
            f"(this milpa understands version {LOCKFILE_SCHEMA_VERSION})",
            got=schema_version,
            supported=LOCKFILE_SCHEMA_VERSION,
        )

    return Lockfile(deps=tuple(deps), strategy=strategy, version=schema_version)


def _parse_top_version(node: KdlNode) -> int:
    """Parse the top-level ``version`` node → schema version integer."""
    args = node_args(node)
    if len(args) != 1:
        raise MilpaError(
            LOCK_FIELD_ARITY,
            f"'version' node takes exactly one argument, got {len(args)}",
        )
    val = args[0]
    as_int = value_as_int(val)
    if as_int is None:
        raise MilpaError(
            LOCK_FIELD_TYPE,
            f"'version' must be an integer, got {val!r}",
            got=val,
        )
    return as_int


def _parse_top_strategy(node: KdlNode) -> str:
    """Parse the top-level ``strategy`` node → strategy name string.

    The strategy node is optional (pre-v1.0 compat). If present and has
    exactly one string arg, use it. If present but malformed, we still
    default to "maxver" (fail-open for diagnostics — the strategy field is
    informational, not load-bearing for parse correctness).
    """
    args = node_args(node)
    if len(args) == 1:
        s = value_as_str(args[0])
        if s is not None:
            return s
    return "maxver"


def _parse_dep(node: KdlNode) -> LockedDep:
    """Parse a ``dep`` block into a ``LockedDep``."""
    dep_name = _require_dep_name(node)

    identity: str | None = None
    version: str = "0.0.0"
    src_dir: str = ""
    requires: tuple[str, ...] = ()
    active_flags: tuple[str, ...] = ()
    self_mirrors: tuple[str, ...] = ()
    provenances: list[ProvenanceRecord] = []
    dep_decl: str | None = None  # S6: additive dep_decl pin (§3.7)

    for child in node_children(node):
        cname = node_name(child)
        if cname == "identity":
            identity = _parse_dep_identity(child, dep_name)
        elif cname == "version":
            version = _parse_dep_scalar_str(child, dep_name, "version")
        elif cname == "src_dir":
            src_dir = _parse_dep_scalar_str(child, dep_name, "src_dir")
        elif cname == "requires":
            requires = _parse_dep_requires(child)
        elif cname == "active_flags":
            active_flags = _parse_dep_active_flags(child)
        elif cname == "self_mirrors":
            self_mirrors = _parse_dep_self_mirrors(child)
        elif cname == "provenance":
            provenances.append(_parse_provenance_block(child, dep_name))
        elif cname == "dep_decl":
            # S6: forward-compat parse — silently ignored when absent or malformed.
            args = node_args(child)
            if len(args) == 1:
                dep_decl = value_as_str(args[0])
        # other unknown child nodes are silently skipped (forward compat)

    return LockedDep(
        name=dep_name,
        identity=identity,
        version=version,
        src_dir=src_dir,
        requires=requires,
        provenances=tuple(provenances),
        active_flags=active_flags,
        self_mirrors=self_mirrors,
        dep_decl=dep_decl,
    )


def _require_dep_name(node: KdlNode) -> str:
    """Extract the dep name from the positional arg of a ``dep`` node."""
    args = node_args(node)
    if len(args) != 1:
        raise MilpaError(
            LOCK_DEP_NAME_ARITY,
            f"dep node requires exactly one string argument (the name), "
            f"got {len(args)} args",
        )
    name = value_as_str(args[0])
    if name is None:
        raise MilpaError(
            LOCK_DEP_NAME_ARITY,
            f"dep node name argument must be a string, got {args[0]!r}",
        )
    return name


def _parse_dep_identity(node: KdlNode, dep_name: str) -> str:
    """Parse the ``identity`` child of a dep block."""
    args = node_args(node)
    if len(args) != 1:
        raise MilpaError(
            LOCK_DEP_FIELD_ARITY,
            f"dep {dep_name!r}: 'identity' must have exactly one string value",
            dep=dep_name,
        )
    val = args[0]
    # Validate multihash format (lockfile-schema.md §3.1)
    return _parse_identity_for_lockfile(val, dep_name)


def _parse_dep_scalar_str(node: KdlNode, dep_name: str, field: str) -> str:
    """Parse a dep child node that takes exactly one string arg."""
    args = node_args(node)
    if len(args) != 1:
        raise MilpaError(
            LOCK_DEP_FIELD_ARITY,
            f"dep {dep_name!r}: {field!r} must have exactly one string value, "
            f"got {len(args)} args",
            dep=dep_name,
            field=field,
        )
    s = value_as_str(args[0])
    if s is None:
        raise MilpaError(
            LOCK_DEP_FIELD_ARITY,
            f"dep {dep_name!r}: {field!r} value must be a string, got {args[0]!r}",
            dep=dep_name,
            field=field,
        )
    return s


def _parse_dep_requires(node: KdlNode) -> tuple[str, ...]:
    """Parse the ``requires`` child node — zero or more string args."""
    return tuple(s for a in node_args(node) if (s := value_as_str(a)) is not None)


def _parse_dep_active_flags(node: KdlNode) -> tuple[str, ...]:
    """Parse the ``active_flags`` child node — zero or more string args."""
    return tuple(s for a in node_args(node) if (s := value_as_str(a)) is not None)


def _parse_dep_self_mirrors(node: KdlNode) -> tuple[str, ...]:
    """Parse the ``self_mirrors`` child node.

    Accepts both plain strings and (url)-annotated values. The raw kdl-py
    entry value must be accessed to detect the url tag. We use node_args
    which strips annotations — both forms return a str through value_as_str.
    """
    return tuple(s for a in node_args(node) if (s := value_as_str(a)) is not None)


def _parse_provenance_block(node: KdlNode, dep_name: str) -> ProvenanceRecord:
    """Parse a ``provenance { ... }`` block into a ProvenanceRecord."""
    # Collect all scalar child fields into a dict
    fields: dict[str, str] = {}
    for child in node_children(node):
        cname = node_name(child)
        child_args = node_args(child)
        if len(child_args) != 1:
            raise MilpaError(
                LOCK_PROV_FIELD_ARITY,
                f"dep {dep_name!r}: provenance field {cname!r} must have "
                f"exactly one value, got {len(child_args)}",
                dep=dep_name,
                field=cname,
            )
        raw = child_args[0]
        s = value_as_str(raw)
        if s is None:
            raise MilpaError(
                LOCK_PROV_FIELD_ARITY,
                f"dep {dep_name!r}: provenance field {cname!r} must be a "
                f"string, got {raw!r}",
                dep=dep_name,
                field=cname,
            )
        fields[cname] = s

    # kind discriminator is required
    kind = fields.get("kind")
    if kind is None:
        raise MilpaError(
            LOCK_PROV_KIND_MISSING,
            f"dep {dep_name!r}: provenance block missing 'kind' discriminator",
            dep=dep_name,
        )

    if kind == "git":
        return GitProvenanceRecord(
            url=_req_field(fields, "url", dep_name),
            ref=fields.get("ref"),
            commit_sha=fields.get("commit_sha"),
        )
    if kind == "tarball":
        return TarballProvenanceRecord(
            url=_req_field(fields, "url", dep_name),
            sha256=fields.get("sha256"),
        )
    if kind == "local":
        return LocalProvenanceRecord(
            path=_req_field(fields, "path", dep_name),
        )
    if kind == "member":
        return MemberProvenanceRecord(
            name=_req_field(fields, "name", dep_name),
        )
    if kind == "oci":
        return OciProvenanceRecord(
            registry=_req_field(fields, "registry", dep_name),
            repository=_req_field(fields, "repository", dep_name),
            digest=_req_field(fields, "digest", dep_name),
        )
    if kind == "registry":
        # Read-compat only (§4.6); writer never emits this
        return RegistryProvenanceRecord(
            name=_req_field(fields, "name", dep_name),
            tag=fields.get("tag"),
            commit_sha=fields.get("commit_sha"),
        )

    raise MilpaError(
        LOCK_PROV_KIND_UNKNOWN,
        f"dep {dep_name!r}: unknown provenance kind {kind!r} "
        f"(known: git, tarball, local, member, oci, registry)",
        dep=dep_name,
        kind=kind,
    )


def _req_field(fields: dict[str, str], key: str, dep_name: str) -> str:
    """Return a required provenance field, raising LOCK-PROV-FIELD-MISSING if absent."""
    val = fields.get(key)
    if val is None:
        raise MilpaError(
            LOCK_PROV_FIELD_MISSING,
            f"dep {dep_name!r}: provenance missing required field {key!r}",
            dep=dep_name,
            field=key,
        )
    return val


# ---------------------------------------------------------------------------
# 4c — from_graph + format_lockfile (byte-exact hand-rolled templating)
# ---------------------------------------------------------------------------


def from_graph(graph: ResolvedGraph, *, strategy: str = "maxver") -> Lockfile:
    """Convert a ResolvedGraph into a Lockfile.

    Deps are sorted lexicographically by name (lockfile-schema.md §2.3 +
    §2.4 + resolver-semantics.md §4.4). Same graph always produces
    byte-identical lockfile text.
    """
    deps = tuple(
        sorted(
            (_locked_from_resolved(d) for d in graph.deps),
            key=lambda d: d.name,
        )
    )
    return Lockfile(deps=deps, strategy=strategy)


def _locked_from_resolved(d: ResolvedDep) -> LockedDep:
    """Translate a ResolvedDep into a LockedDep."""
    return LockedDep(
        name=d.name,
        identity=d.identity,
        version=d.version,
        src_dir=d.src_dir,
        # Sort lexicographically — requires is accumulated in BFS arrival order
        # which is non-deterministic across parallel-fetch runs. Lexicographic
        # order is the spec's single canonical ordering rule (§3.4 / §4.4).
        requires=tuple(sorted(d.requires)),
        provenances=(d.provenance,) if d.provenance is not None else (),
        active_flags=d.active_flags,
        self_mirrors=d.self_mirrors,
        # S6: carry the dep_decl hash from the resolver through to the lockfile pin.
        dep_decl=d.dep_decl,
    )


# ---------------------------------------------------------------------------
# _kdl_str — SSOT for string escaping (lockfile-schema.md §2.4)
#
# Escapes: \ → \\, " → \", control chars U+0000–U+001F → \u{NNNN},
# everything else verbatim. No named escapes (\n, \t, etc.) — the spec
# says "\u{NNNN}" for all control chars; for simplicity we use the unicode
# escape form for all U+0000–U+001F uniformly.
# ---------------------------------------------------------------------------

_CTRL_ESCAPES: dict[str, str] = {
    "\\": "\\\\",
    '"': '\\"',
}


def _kdl_str(s: str) -> str:
    r"""Return ``s`` as a double-quoted, KDL 2.0-escaped string literal.

    SSOT for string escaping in the lockfile emitter. Every string value
    emitted by ``format_lockfile`` passes through this function.

    Escape rules (lockfile-schema.md §2.4):
      \\  →  \\\\  (backslash escape)
      "   →  \\"   (double-quote escape)
      U+0000–U+001F → \u{NNNN}  (control chars in hex)
      everything else → verbatim (valid KDL 2.0 string content)
    """
    out: list[str] = []
    for ch in s:
        esc = _CTRL_ESCAPES.get(ch)
        if esc is not None:
            out.append(esc)
        elif ord(ch) < 0x20:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def format_lockfile(lockfile: Lockfile) -> str:
    """Render a ``Lockfile`` to byte-exact KDL 2.0 text.

    Implements the canonical serialization rules from lockfile-schema.md §2.4.
    The output is deterministic: same logical lockfile → identical bytes.

    Layout:
      1. Header comment
      2. ``version 1`` (integer, unquoted)
      3. ``strategy "<name>"``
      4. Blank line
      5. dep blocks (lexicographic order), each followed by blank line
      6. File ends with the blank line after the last dep block (last byte = 0x0A)
    """
    lines: list[str] = [
        _HEADER,
        f"version {lockfile.version}",
        f"strategy {_kdl_str(lockfile.strategy)}",
        "",
    ]
    for dep in lockfile.deps:
        lines.append(f"dep {_kdl_str(dep.name)} {{")
        # identity — emitted only when not None
        if dep.identity is not None:
            lines.append(f"    identity {_kdl_str(dep.identity)}")
        lines.append(f"    version {_kdl_str(dep.version)}")
        lines.append(f"    src_dir {_kdl_str(dep.src_dir)}")
        # requires — always emitted; bare when empty, args when non-empty
        if dep.requires:
            req_args = " ".join(_kdl_str(r) for r in dep.requires)
            lines.append(f"    requires {req_args}")
        else:
            lines.append("    requires")
        # active_flags — omitted when empty
        if dep.active_flags:
            flag_args = " ".join(_kdl_str(f) for f in dep.active_flags)
            lines.append(f"    active_flags {flag_args}")
        # self_mirrors — omitted when empty; (url) annotation per §2.4
        if dep.self_mirrors:
            sm_args = " ".join(f"(url){_kdl_str(u)}" for u in dep.self_mirrors)
            lines.append(f"    self_mirrors {sm_args}")
        # dep_decl pin — S6: emitted only when present (forward-compat additive)
        if dep.dep_decl is not None:
            lines.append(f"    dep_decl {_kdl_str(dep.dep_decl)}")
        # provenance block
        for prov in dep.provenances:
            lines.append("    provenance {")
            for pline in _format_provenance_fields(prov):
                lines.append(f"        {pline}")
            lines.append("    }")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _format_provenance_fields(p: ProvenanceRecord) -> list[str]:
    """Emit the kind discriminator + kind-specific fields for a provenance block.

    Field order per kind (lockfile-schema.md §2.4):
      git:      kind / url / ref / commit_sha
      tarball:  kind / url / sha256
      local:    kind / path
      member:   kind / name
      oci:      kind / registry / repository / digest
      registry: kind / name / tag / commit_sha  (read-compat; writer uses this too
                for any RegistryProvenanceRecord that may be round-tripped)

    Optional fields (ref, commit_sha, sha256, tag) are omitted when None.
    """
    out = [f"kind {_kdl_str(p.kind)}"]
    if isinstance(p, GitProvenanceRecord):
        out.append(f"url {_kdl_str(p.url)}")
        if p.ref is not None:
            out.append(f"ref {_kdl_str(p.ref)}")
        if p.commit_sha is not None:
            out.append(f"commit_sha {_kdl_str(p.commit_sha)}")
    elif isinstance(p, TarballProvenanceRecord):
        out.append(f"url {_kdl_str(p.url)}")
        if p.sha256 is not None:
            out.append(f"sha256 {_kdl_str(p.sha256)}")
    elif isinstance(p, LocalProvenanceRecord):
        out.append(f"path {_kdl_str(p.path)}")
    elif isinstance(p, MemberProvenanceRecord):
        out.append(f"name {_kdl_str(p.name)}")
    elif isinstance(p, OciProvenanceRecord):
        out.append(f"registry {_kdl_str(p.registry)}")
        out.append(f"repository {_kdl_str(p.repository)}")
        out.append(f"digest {_kdl_str(p.digest)}")
    elif isinstance(p, RegistryProvenanceRecord):
        out.append(f"name {_kdl_str(p.name)}")
        if p.tag is not None:
            out.append(f"tag {_kdl_str(p.tag)}")
        if p.commit_sha is not None:
            out.append(f"commit_sha {_kdl_str(p.commit_sha)}")
    return out


def write_lockfile(lockfile: Lockfile, path: Path) -> Path:
    """Write lockfile KDL text to ``path``. Returns the path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(format_lockfile(lockfile))
    return path


def load_lockfile(path: Path) -> Lockfile:
    """Read and parse a lockfile from disk.

    Raises ``MilpaError(LOCK_FILE_NOT_FOUND)`` / ``MilpaError(LOCK_FILE_UNREADABLE)``
    on I/O failure.
    """
    from milpa.errors import LOCK_FILE_NOT_FOUND, LOCK_FILE_UNREADABLE

    try:
        text = path.read_text()
    except FileNotFoundError as exc:
        raise MilpaError(
            LOCK_FILE_NOT_FOUND,
            f"lockfile not found: {path}",
            path=str(path),
        ) from exc
    except OSError as exc:
        raise MilpaError(
            LOCK_FILE_UNREADABLE,
            f"cannot read lockfile {path}: {exc}",
            path=str(path),
        ) from exc
    return parse_lockfile(text)


# ---------------------------------------------------------------------------
# 4e — Verification
# ---------------------------------------------------------------------------


def verify_against_graph(
    lockfile: Lockfile,
    graph: ResolvedGraph,
) -> None:
    """Verify that the resolved graph matches the lockfile dep-for-dep.

    Checks (lockfile-schema.md §6.1):
      - Every dep in the graph has a corresponding lockfile entry (by name).
      - Every dep in the lockfile has a corresponding graph entry.
      - For every dep in both: identity fields match exactly.

    Raises ``MilpaError(LOCK_GRAPH_MISMATCH)`` on any divergence.
    Collects ALL mismatches before raising (not fail-fast).
    """
    locked_by_name = {d.name: d for d in lockfile.deps}
    graph_by_name = {d.name: d for d in graph.deps}

    errors: list[str] = []
    for name in sorted(graph_by_name.keys() - locked_by_name.keys()):
        errors.append(
            f"dep {name!r} is in the resolved graph but absent from the lockfile"
        )
    for name in sorted(locked_by_name.keys() - graph_by_name.keys()):
        errors.append(
            f"dep {name!r} is in the lockfile but absent from the resolved graph"
        )
    for name in sorted(graph_by_name.keys() & locked_by_name.keys()):
        locked = locked_by_name[name]
        actual = graph_by_name[name]
        if locked.identity != actual.identity:
            errors.append(
                f"dep {name!r}: identity mismatch — "
                f"lockfile={locked.identity!r}, graph={actual.identity!r}"
            )

    if errors:
        raise MilpaError(
            LOCK_GRAPH_MISMATCH,
            "lockfile does not match resolved graph:\n  " + "\n  ".join(errors),
            mismatches=errors,
        )


def verify_lockfile_against_deps(
    lockfile: Lockfile,
    deps_dir: Path,
) -> list[str]:
    """Verify every lockfile dep against ``deps_dir/<name>/`` on disk.

    Checks (lockfile-schema.md §6.2):
      - Each dep directory must exist and be a directory.
      - The computed content_hash must match the lockfile's ``identity``.
      - Any directory under ``deps_dir/`` (excluding hidden entries) that has
        no corresponding lockfile entry is reported as an extra dep.

    Returns a list of divergence strings (may be empty). Does NOT raise —
    the caller decides whether to treat divergences as a hard error.
    Collects ALL divergences before returning (not fail-fast).
    """
    divergences: list[str] = []
    locked_by_name = {d.name: d for d in lockfile.deps}

    for name, locked in sorted(locked_by_name.items()):
        dep_path = deps_dir / name
        if not dep_path.exists():
            divergences.append(f"{name}: missing from {deps_dir}/")
            continue
        if not dep_path.is_dir():
            divergences.append(
                f"{name}: expected directory at {dep_path}, found something else"
            )
            continue
        actual = compute_content_hash(dep_path)
        expected = locked.identity
        if expected != actual:
            divergences.append(
                f"{name}: identity mismatch — "
                f"lockfile says {(expected or '<none>')[:23]}..., "
                f"actual {actual[:23]}..."
            )

    if deps_dir.exists() and deps_dir.is_dir():
        for entry in sorted(deps_dir.iterdir()):
            if entry.name.startswith("."):
                continue
            if entry.name not in locked_by_name:
                divergences.append(
                    f"{entry.name}: extra dep in {deps_dir}/ not in lockfile"
                )

    return divergences
