//! `milpa.kdl` serialization (RFC §6 S13; manifest-grammar §8; mirrors
//! `manifest.py:format_manifest`).
//!
//! The inverse of the package parser: render a [`Manifest`] back to canonical
//! `milpa.kdl` text. Deterministic, **insertion-stable** dep order, URL/tarball
//! values carry the recommended `(url)` annotation. Comment-preserving
//! serialization is out of scope (the mutating verbs warn that hand-written
//! comments are dropped on rewrite).

use crate::{Dep, Manifest, OverrideTarget, Predicate, Workspace};

const HEADER: &str = "// generated by milpa; edit by hand or via `milpa add` / `milpa remove`";

/// Render a [`Manifest`] to `milpa.kdl` text (trailing newline included).
pub fn format_manifest(m: &Manifest) -> String {
    let mut lines: Vec<String> = vec![HEADER.to_string(), String::new()];

    if m.spec_version_explicit {
        lines.push(format!("spec-version {}", m.spec_version));
        lines.push(String::new());
    }
    if let Some(name) = &m.name {
        lines.push(format!("name \"{name}\""));
        lines.push(String::new());
    }
    if !m.src_dir.is_empty() {
        lines.push(format!("src_dir \"{}\"", m.src_dir));
        lines.push(String::new());
    }
    if !m.cas_dir.is_empty() {
        lines.push("cas {".to_string());
        lines.push(format!("    dir \"{}\"", m.cas_dir));
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.deps.is_empty() {
        lines.push("deps {".to_string());
        for dep in &m.deps {
            lines.push(format_dep_line(dep));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.dev_deps.is_empty() {
        lines.push("dev-deps {".to_string());
        for dep in &m.dev_deps {
            lines.push(format_dep_line(dep));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.overrides.is_empty() {
        lines.push("overrides {".to_string());
        for ov in &m.overrides {
            match &ov.target {
                OverrideTarget::Git { url, git_ref } => {
                    lines.push(format!(
                        "    pkg \"{}\" git=(url)\"{}\" ref=\"{}\"",
                        ov.name, url, git_ref
                    ));
                }
                OverrideTarget::Local { path } => {
                    lines.push(format!(
                        "    pkg \"{}\" local=\"{}\"",
                        ov.name, path
                    ));
                }
                OverrideTarget::Member { member_name } => {
                    lines.push(format!("    pkg \"{}\" {{", ov.name));
                    lines.push(format!("        member \"{}\"", member_name));
                    lines.push("    }".to_string());
                }
            }
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.self_mirrors.is_empty() {
        lines.push("mirrors {".to_string());
        for url in &m.self_mirrors {
            lines.push(format!("    mirror (url)\"{url}\""));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    // S7: skip auto-injected flags (implied by `optional=#true` on the dep).
    let explicit_flags: Vec<_> = m
        .flags
        .iter()
        .filter(|fd| !m.optional_auto_flags.contains(&fd.name))
        .collect();
    if !explicit_flags.is_empty() {
        lines.push("flags {".to_string());
        for fd in explicit_flags {
            let mut head = format!(
                "    \"{}\" default={}",
                fd.name,
                if fd.default { "#true" } else { "#false" }
            );
            if !fd.description.is_empty() {
                head.push_str(&format!(" description=\"{}\"", fd.description));
            }
            let has_block = !fd.defines.is_empty()
                || !fd.enables_same_pkg.is_empty()
                || !fd.enables_cross_pkg.is_empty()
                || !fd.conflicts.is_empty();
            if !has_block {
                lines.push(head);
            } else {
                lines.push(format!("{head} {{"));
                if !fd.defines.is_empty() {
                    let args: Vec<String> =
                        fd.defines.iter().map(|d| format!("\"{d}\"")).collect();
                    lines.push(format!("        defines {}", args.join(" ")));
                }
                // enables — canonical single-node form (RFC §3.1.1).
                if !fd.enables_same_pkg.is_empty() || !fd.enables_cross_pkg.is_empty() {
                    let same_pkg_args: Vec<String> = fd
                        .enables_same_pkg
                        .iter()
                        .map(|n| format!("\"{n}\""))
                        .collect();
                    if fd.enables_cross_pkg.is_empty() {
                        // No cross-pkg: single-line form.
                        lines.push(format!("        enables {}", same_pkg_args.join(" ")));
                    } else {
                        // Cross-pkg present: block form.
                        let enables_head = if same_pkg_args.is_empty() {
                            "        enables".to_string()
                        } else {
                            format!("        enables {}", same_pkg_args.join(" "))
                        };
                        lines.push(format!("{enables_head} {{"));
                        for cpe in &fd.enables_cross_pkg {
                            if cpe.flag_requests.is_empty() {
                                lines.push(format!("            {}", cpe.dep));
                            } else {
                                lines.push(format!("            {} {{", cpe.dep));
                                for fr in &cpe.flag_requests {
                                    if fr.enabled {
                                        lines.push(format!("                flag \"{}\"", fr.name));
                                    } else {
                                        lines.push(format!(
                                            "                flag \"{}\" #false",
                                            fr.name
                                        ));
                                    }
                                }
                                lines.push("            }".to_string());
                            }
                        }
                        lines.push("        }".to_string());
                    }
                }
                if !fd.conflicts.is_empty() {
                    let conflict_args: Vec<String> =
                        fd.conflicts.iter().map(|n| format!("\"{n}\"")).collect();
                    lines.push(format!("        conflicts {}", conflict_args.join(" ")));
                }
                lines.push("    }".to_string());
            }
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }

    lines.push(format!("kind \"{}\"", m.kind));
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

const WORKSPACE_HEADER: &str =
    "// generated by milpa; edit by hand or via `milpa workspace add-member` / `milpa workspace remove-member`";

/// Render a [`Workspace`] to `milpa.kdl` text (trailing newline included).
///
/// Byte-identical to the Python `manifest.py:format_workspace_manifest`.
/// Comments are dropped (canonical re-serialization — manifest-grammar §8 + §3.F).
pub fn format_workspace_manifest(ws: &Workspace) -> String {
    let mut lines: Vec<String> = vec![WORKSPACE_HEADER.to_string(), String::new()];

    // name (optional on workspace root)
    if let Some(name) = &ws.name {
        lines.push(format!("name \"{name}\""));
        lines.push(String::new());
    }

    // workspace { member "..." }
    lines.push("workspace {".to_string());
    for member_path in &ws.members {
        lines.push(format!("    member \"{member_path}\""));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    // overrides { pkg "name" ... }
    if !ws.overrides.is_empty() {
        lines.push("overrides {".to_string());
        for ov in &ws.overrides {
            match &ov.target {
                OverrideTarget::Git { url, git_ref } => {
                    lines.push(format!(
                        "    pkg \"{}\" git=(url)\"{}\" ref=\"{}\"",
                        ov.name, url, git_ref
                    ));
                }
                OverrideTarget::Local { path } => {
                    lines.push(format!("    pkg \"{}\" local=\"{}\"", ov.name, path));
                }
                OverrideTarget::Member { member_name } => {
                    lines.push(format!("    pkg \"{}\" {{", ov.name));
                    lines.push(format!("        member \"{member_name}\""));
                    lines.push("    }".to_string());
                }
            }
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }

    // flags { "<name>" default=#true/#false ... }
    // Workspace flags: no optional-auto-flags to skip (workspace has no deps).
    if !ws.flags.is_empty() {
        lines.push("flags {".to_string());
        for fd in &ws.flags {
            let mut head = format!(
                "    \"{}\" default={}",
                fd.name,
                if fd.default { "#true" } else { "#false" }
            );
            if !fd.description.is_empty() {
                head.push_str(&format!(" description=\"{}\"", fd.description));
            }
            let has_block = !fd.defines.is_empty()
                || !fd.enables_same_pkg.is_empty()
                || !fd.enables_cross_pkg.is_empty()
                || !fd.conflicts.is_empty();
            if !has_block {
                lines.push(head);
            } else {
                lines.push(format!("{head} {{"));
                if !fd.defines.is_empty() {
                    let args: Vec<String> =
                        fd.defines.iter().map(|d| format!("\"{d}\"")).collect();
                    lines.push(format!("        defines {}", args.join(" ")));
                }
                if !fd.enables_same_pkg.is_empty() || !fd.enables_cross_pkg.is_empty() {
                    let same_pkg_args: Vec<String> = fd
                        .enables_same_pkg
                        .iter()
                        .map(|n| format!("\"{n}\""))
                        .collect();
                    if fd.enables_cross_pkg.is_empty() {
                        lines.push(format!("        enables {}", same_pkg_args.join(" ")));
                    } else {
                        let enables_head = if same_pkg_args.is_empty() {
                            "        enables".to_string()
                        } else {
                            format!("        enables {}", same_pkg_args.join(" "))
                        };
                        lines.push(format!("{enables_head} {{"));
                        for cpe in &fd.enables_cross_pkg {
                            if cpe.flag_requests.is_empty() {
                                lines.push(format!("            {}", cpe.dep));
                            } else {
                                lines.push(format!("            {} {{", cpe.dep));
                                for fr in &cpe.flag_requests {
                                    if fr.enabled {
                                        lines.push(format!("                flag \"{}\"", fr.name));
                                    } else {
                                        lines.push(format!(
                                            "                flag \"{}\" #false",
                                            fr.name
                                        ));
                                    }
                                }
                                lines.push("            }".to_string());
                            }
                        }
                        lines.push("        }".to_string());
                    }
                }
                if !fd.conflicts.is_empty() {
                    let conflict_args: Vec<String> =
                        fd.conflicts.iter().map(|n| format!("\"{n}\"")).collect();
                    lines.push(format!("        conflicts {}", conflict_args.join(" ")));
                }
                lines.push("    }".to_string());
            }
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }

    // Strip trailing blank lines so the file ends cleanly after the last block.
    while lines.last().map(|l| l.is_empty()).unwrap_or(false) {
        lines.pop();
    }

    let mut out = lines.join("\n");
    out.push('\n');
    out
}

/// Render a sequence of single-value predicates as inline KDL properties.
///
/// Used to build the property string for a `when` node header.
/// All predicates MUST have exactly one value (multi-value predicates can only
/// appear on UrlDep child nodes, never on `when` node headers).
///
/// Returns a space-prefixed string like ` platform="linux" flag="extras"`
/// or an empty string when `preds` is empty.
fn format_predicate_props(preds: &[&Predicate]) -> String {
    let mut parts: Vec<String> = Vec::new();
    for pred in preds {
        debug_assert_eq!(
            pred.values.len(),
            1,
            "format_predicate_props: predicate {:?} has {} values — only single-value predicates \
             are valid on `when` node headers",
            pred.name,
            pred.values.len()
        );
        let v = &pred.values[0];
        if pred.negated {
            parts.push(format!("{}=(not)\"{v}\"", pred.name));
        } else {
            parts.push(format!("{}=\"{v}\"", pred.name));
        }
    }
    if parts.is_empty() {
        String::new()
    } else {
        format!(" {}", parts.join(" "))
    }
}

/// One deps-block child as a KDL line (or multi-line block for a URL dep with
/// mirrors / multi-value predicates / flag requests).
///
/// §8 round-trip: deps with explicit when-predicates are wrapped in a
/// `when <preds> { <dep-node> }` grouping block so their predicates survive
/// a format → parse cycle.  UrlDep predicates are emitted inline/as child-nodes
/// on the dep node itself (existing behaviour preserved).  For NamedDep,
/// LocalDep, TarballDep, and MemberDep the wrapping form is the only valid
/// form because those node types do not accept predicate properties directly.
fn format_dep_line(dep: &Dep) -> String {
    match dep {
        Dep::Url(u) => {
            let mut head = format!(
                "    \"{}\" git=(url)\"{}\" ref=\"{}\"",
                u.name, u.git, u.git_ref
            );
            // S7: emit `optional=#true` and strip the auto-injected gate predicate.
            if u.optional {
                head.push_str(" optional=#true");
            }
            let serializable_preds: Vec<&_> = if u.optional {
                let auto_gate_name = "flag";
                let auto_gate_val = u.name.as_str();
                u.predicates
                    .iter()
                    .filter(|p| {
                        !(p.name == auto_gate_name
                            && p.values.len() == 1
                            && p.values[0] == auto_gate_val
                            && !p.negated)
                    })
                    .collect()
            } else {
                u.predicates.iter().collect()
            };
            let inline: Vec<&_> = serializable_preds
                .iter()
                .copied()
                .filter(|p| p.values.len() == 1)
                .collect();
            let child: Vec<&_> = serializable_preds
                .iter()
                .copied()
                .filter(|p| p.values.len() > 1)
                .collect();
            for p in &inline {
                let v = &p.values[0];
                if p.negated {
                    head.push_str(&format!(" {}=(not)\"{v}\"", p.name));
                } else {
                    head.push_str(&format!(" {}=\"{v}\"", p.name));
                }
            }
            if u.mirrors.is_empty() && child.is_empty() && u.flag_requests.is_empty() {
                return head;
            }
            let mut block = vec![format!("{head} {{")];
            for p in &child {
                let args: Vec<String> = p
                    .values
                    .iter()
                    .map(|v| {
                        if p.negated {
                            format!("(not)\"{v}\"")
                        } else {
                            format!("\"{v}\"")
                        }
                    })
                    .collect();
                block.push(format!("        {} {}", p.name, args.join(" ")));
            }
            for url in &u.mirrors {
                block.push(format!("        mirror (url)\"{url}\""));
            }
            for fr in &u.flag_requests {
                if fr.enabled {
                    block.push(format!("        flag \"{}\"", fr.name));
                } else {
                    block.push(format!("        flag \"{}\" #false", fr.name));
                }
            }
            block.push("    }".to_string());
            block.join("\n")
        }
        Dep::Member(m) => {
            // MemberDep predicates come exclusively from enclosing when blocks
            // (MAN-DEP-MEMBER-PROPS forbids inline properties).  Wrap if non-empty.
            if !m.predicates.is_empty() {
                let preds: Vec<&_> = m.predicates.iter().collect();
                let when_props = format_predicate_props(&preds);
                let inner = format!("        member \"{}\"", m.name);
                format!("    when{when_props} {{\n{inner}\n    }}")
            } else {
                format!("    member \"{}\"", m.name)
            }
        }
        Dep::Local(l) => {
            let node_body = format!("\"{}\" local=\"{}\"", l.name, l.path);
            if !l.predicates.is_empty() {
                let preds: Vec<&_> = l.predicates.iter().collect();
                let when_props = format_predicate_props(&preds);
                let inner = format!("        {node_body}");
                format!("    when{when_props} {{\n{inner}\n    }}")
            } else {
                format!("    {node_body}")
            }
        }
        Dep::Tarball(t) => {
            let mut parts = vec![
                format!("\"{}\"", t.name),
                format!("tarball=(url)\"{}\"", t.url),
            ];
            if let Some(sha) = &t.sha256 {
                parts.push(format!("sha256=\"{sha}\""));
            }
            if t.strip_components != 0 {
                parts.push(format!("strip_components={}", t.strip_components));
            }
            let node_body = parts.join(" ");
            if !t.predicates.is_empty() {
                let preds: Vec<&_> = t.predicates.iter().collect();
                let when_props = format_predicate_props(&preds);
                let inner = format!("        {node_body}");
                format!("    when{when_props} {{\n{inner}\n    }}")
            } else {
                format!("    {node_body}")
            }
        }
        Dep::Named(n) => {
            // S7: strip the auto-injected gate predicate (flag=<depname>) — it's
            // implied by optional=#true and must not be double-emitted as a when-block
            // predicate.  All other predicates (from outer when blocks) ARE serialized.
            let when_preds: Vec<&_> = if n.optional {
                let auto_gate_val = n.name.as_str();
                n.predicates
                    .iter()
                    .filter(|p| {
                        !(p.name == "flag"
                            && p.values.len() == 1
                            && p.values[0] == auto_gate_val
                            && !p.negated)
                    })
                    .collect()
            } else {
                n.predicates.iter().collect()
            };

            // Build the dep node body (without leading indentation — added below).
            let mut head = match &n.constraint {
                None => format!("\"{}\"", n.name),
                Some(c) => format!("\"{}\" \"{c}\"", n.name),
            };
            // S7: emit `optional=#true`.
            if n.optional {
                head.push_str(" optional=#true");
            }

            if !n.flag_requests.is_empty() {
                // Multi-line block form for flag_requests (§3.1.5, S3 RFC #23).
                if !when_preds.is_empty() {
                    let when_props = format_predicate_props(&when_preds);
                    let mut inner_lines = vec![format!("        {head} {{")];
                    for fr in &n.flag_requests {
                        if fr.enabled {
                            inner_lines.push(format!("            flag \"{}\"", fr.name));
                        } else {
                            inner_lines.push(format!("            flag \"{}\" #false", fr.name));
                        }
                    }
                    inner_lines.push("        }".to_string());
                    let inner = inner_lines.join("\n");
                    format!("    when{when_props} {{\n{inner}\n    }}")
                } else {
                    let mut block = vec![format!("    {head} {{")];
                    for fr in &n.flag_requests {
                        if fr.enabled {
                            block.push(format!("        flag \"{}\"", fr.name));
                        } else {
                            block.push(format!("        flag \"{}\" #false", fr.name));
                        }
                    }
                    block.push("    }".to_string());
                    block.join("\n")
                }
            } else if !when_preds.is_empty() {
                let when_props = format_predicate_props(&when_preds);
                let inner = format!("        {head}");
                format!("    when{when_props} {{\n{inner}\n    }}")
            } else {
                format!("    {head}")
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{NamedDep, UrlDep};

    fn base() -> Manifest {
        Manifest {
            name: Some("myapp".into()),
            kind: "application".into(),
            src_dir: String::new(),
            deps: Vec::new(),
            dev_deps: Vec::new(),
            overrides: Vec::new(),
            flags: Vec::new(),
            self_mirrors: Vec::new(),
            cas_dir: String::new(),
            spec_version: 1,
            spec_version_explicit: false,
            attestation_policy: crate::AttestationPolicy::Permissive,
            optional_auto_flags: std::collections::BTreeSet::new(),
        }
    }

    #[test]
    fn minimal_manifest_round_trips() {
        let m = base();
        let text = format_manifest(&m);
        assert!(text.contains("name \"myapp\""));
        assert!(text.ends_with("kind \"application\"\n"));
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed, m);
    }

    #[test]
    fn url_and_named_deps_round_trip_with_url_annotation() {
        let mut m = base();
        m.deps = vec![
            Dep::Url(UrlDep {
                name: "foo".into(),
                git: "https://e/foo.git".into(),
                git_ref: "main".into(),
                mirrors: Vec::new(),
                predicates: Vec::new(),
                flag_requests: Vec::new(),
                optional: false,
            }),
            Dep::Named(NamedDep {
                name: "bar".into(),
                constraint: Some(">= 1.0.0".into()),
                parsed_constraint: Some(
                    milpa_solver::VersionSet::from_constraint(Some(">= 1.0.0")).unwrap(),
                ),
                flag_requests: Vec::new(),
                optional: false,
                predicates: Vec::new(),
            }),
        ];
        let text = format_manifest(&m);
        assert!(text.contains("git=(url)\"https://e/foo.git\" ref=\"main\""));
        assert!(text.contains("\"bar\" \">= 1.0.0\""));
        // Insertion-stable + round-trips.
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed.deps, m.deps);
    }

    #[test]
    fn no_deps_omits_the_block() {
        let text = format_manifest(&base());
        assert!(!text.contains("deps {"));
    }

    // -----------------------------------------------------------------------
    // Conditional-dep round-trip tests (§8 / #163)
    // Predicates must survive format → parse for ALL 5 dep forms.
    // -----------------------------------------------------------------------

    fn pkg(text: &str) -> crate::Manifest {
        match crate::parse_document(text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        }
    }

    fn platform_pred(value: &str) -> Predicate {
        Predicate {
            name: "platform".into(),
            values: vec![value.into()],
            negated: false,
        }
    }

    #[test]
    fn local_dep_with_predicate_round_trips() {
        let mut m = base();
        m.deps = vec![Dep::Local(crate::LocalDep {
            name: "locallib".into(),
            path: "../locallib".into(),
            predicates: vec![platform_pred("linux")],
        })];
        let text = format_manifest(&m);
        // Must use when-block form.
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        assert!(text.contains("platform=\"linux\""), "expected predicate in:\n{text}");
        let reparsed = pkg(&text);
        assert_eq!(reparsed.deps.len(), 1);
        let dep = match &reparsed.deps[0] {
            Dep::Local(l) => l,
            other => panic!("expected Local dep, got {other:?}"),
        };
        assert_eq!(dep.path, "../locallib");
        assert_eq!(dep.predicates.len(), 1);
        assert_eq!(dep.predicates[0].name, "platform");
        assert_eq!(dep.predicates[0].values, vec!["linux"]);
        assert!(!dep.predicates[0].negated);
    }

    #[test]
    fn tarball_dep_with_predicate_round_trips() {
        let mut m = base();
        m.deps = vec![Dep::Tarball(crate::TarballDep {
            name: "tarlib".into(),
            url: "https://example.com/tarlib.tar.gz".into(),
            sha256: None,
            strip_components: 0,
            predicates: vec![platform_pred("macosx")],
        })];
        let text = format_manifest(&m);
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        assert!(text.contains("platform=\"macosx\""), "expected predicate in:\n{text}");
        let reparsed = pkg(&text);
        assert_eq!(reparsed.deps.len(), 1);
        let dep = match &reparsed.deps[0] {
            Dep::Tarball(t) => t,
            other => panic!("expected Tarball dep, got {other:?}"),
        };
        assert_eq!(dep.url, "https://example.com/tarlib.tar.gz");
        assert_eq!(dep.predicates.len(), 1);
        assert_eq!(dep.predicates[0].name, "platform");
        assert_eq!(dep.predicates[0].values, vec!["macosx"]);
    }

    #[test]
    fn member_dep_with_predicate_parse_error() {
        // S1b: MemberDep with predicates formats into a when-gated member node,
        // which is a parse-time category error (MAN-MEMBER-WHEN-GATED).
        // The formatter still emits the when-wrapped form; re-parsing raises the
        // new error rather than succeeding.
        let mut m = base();
        m.deps = vec![Dep::Member(crate::MemberDep {
            name: "submember".into(),
            predicates: vec![platform_pred("linux")],
        })];
        let text = format_manifest(&m);
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        assert!(text.contains("member \"submember\""), "expected member node in:\n{text}");
        let err = crate::parse_manifest(&text).unwrap_err();
        assert_eq!(err.code(), "MAN-MEMBER-WHEN-GATED");
    }

    #[test]
    fn named_dep_with_predicate_round_trips() {
        let mut m = base();
        m.deps = vec![Dep::Named(NamedDep {
            name: "mylib".into(),
            constraint: None,
            parsed_constraint: None,
            flag_requests: Vec::new(),
            optional: false,
            predicates: vec![platform_pred("linux")],
        })];
        let text = format_manifest(&m);
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        assert!(text.contains("platform=\"linux\""), "expected predicate in:\n{text}");
        let reparsed = pkg(&text);
        assert_eq!(reparsed.deps.len(), 1);
        let dep = match &reparsed.deps[0] {
            Dep::Named(n) => n,
            other => panic!("expected Named dep, got {other:?}"),
        };
        assert_eq!(dep.name, "mylib");
        assert_eq!(dep.predicates.len(), 1);
        assert_eq!(dep.predicates[0].name, "platform");
        assert_eq!(dep.predicates[0].values, vec!["linux"]);
    }

    #[test]
    fn named_dep_with_predicate_and_flag_requests_round_trips() {
        let mut m = base();
        m.flags = vec![crate::FlagDecl {
            name: "ssl".into(),
            default: false,
            description: String::new(),
            defines: Vec::new(),
            enables_same_pkg: Vec::new(),
            enables_cross_pkg: Vec::new(),
            conflicts: Vec::new(),
        }];
        m.deps = vec![Dep::Named(NamedDep {
            name: "platformlib".into(),
            constraint: None,
            parsed_constraint: None,
            flag_requests: vec![crate::FlagRequest {
                name: "ssl".into(),
                enabled: true,
            }],
            optional: false,
            predicates: vec![platform_pred("linux")],
        })];
        let text = format_manifest(&m);
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        let reparsed = pkg(&text);
        let dep = match &reparsed.deps[0] {
            Dep::Named(n) => n,
            other => panic!("expected Named dep, got {other:?}"),
        };
        assert_eq!(dep.flag_requests.len(), 1);
        assert_eq!(dep.flag_requests[0].name, "ssl");
        assert_eq!(dep.predicates.len(), 1);
        assert_eq!(dep.predicates[0].name, "platform");
    }

    #[test]
    fn parse_format_parse_cycle_preserves_conditional_dep() {
        // parse(format(parse(src))) == parse(src) — full cycle for LocalDep.
        let src = "name \"mypkg\"\ndeps {\n    when platform=\"linux\" {\n        \"mylib\" local=\"./mylib\"\n    }\n}\nkind \"library\"\n";
        let m1 = pkg(src);
        let text = format_manifest(&m1);
        let m2 = pkg(&text);
        assert_eq!(m2.deps.len(), 1);
        let d1 = match &m1.deps[0] {
            Dep::Local(l) => l,
            other => panic!("expected Local, got {other:?}"),
        };
        let d2 = match &m2.deps[0] {
            Dep::Local(l) => l,
            other => panic!("expected Local, got {other:?}"),
        };
        assert_eq!(d2.name, d1.name);
        assert_eq!(d2.predicates, d1.predicates);
    }

    #[test]
    fn no_predicate_deps_unchanged() {
        // Unconditional LocalDep/TarballDep/MemberDep must NOT gain a when-block.
        let mut m = base();
        m.deps = vec![
            Dep::Local(crate::LocalDep {
                name: "locallib".into(),
                path: "./locallib".into(),
                predicates: Vec::new(),
            }),
            Dep::Member(crate::MemberDep {
                name: "sub".into(),
                predicates: Vec::new(),
            }),
        ];
        let text = format_manifest(&m);
        assert!(!text.contains("when"), "unexpected when-block in:\n{text}");
    }
}
