//! `milpa.kdl` serialization (RFC §6 S13; manifest-grammar §8; mirrors
//! `manifest.py:format_manifest`).
//!
//! The inverse of the package parser: render a [`Manifest`] back to canonical
//! `milpa.kdl` text. Deterministic, **insertion-stable** dep order, URL/tarball
//! values carry the recommended `(url)` annotation. Comment-preserving
//! serialization is out of scope (the mutating verbs warn that hand-written
//! comments are dropped on rewrite).

use crate::{Dep, Manifest, OverrideTarget, Predicate, Workspace};

const HEADER: &str = "// generated by milpa; edit by hand or via `milpa add` / `milpa remove`";

/// Escape a string for KDL 2.0 double-quoted form.
///
/// Matches Python's `_kdl_str` byte-for-byte (manifest.py:~2408):
/// backslash → `\\`, double-quote → `\"`, newline → `\n`,
/// carriage-return → `\r`, tab → `\t`.  Backslash is replaced first so
/// that the subsequent replacements do not double-escape the newly inserted
/// backslashes.
fn kdl_str(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Render a [`crate::TrustPolicy`] to its manifest wire string.
fn trust_policy_str(p: &crate::TrustPolicy) -> &'static str {
    match p {
        crate::TrustPolicy::Strict => "strict",
        crate::TrustPolicy::Warn => "warn",
        crate::TrustPolicy::Off => "off",
    }
}

/// Render one `overrides {}` `pkg` rule (S8/S8b, rfc-origin-as-identity.md
/// §7 B5) — single source of truth shared by `format_manifest` and
/// `format_workspace_manifest` (both packages and a workspace root use the
/// IDENTICAL override grammar; mirrors Python's `_format_override_line`,
/// which unifies the same previously-duplicated logic). Returns the line(s)
/// to push (more than one only for the `Member` block form).
fn format_override_lines(ov: &crate::Override) -> Vec<String> {
    let version_suffix = ov
        .version
        .as_ref()
        .map(|v| format!(" version=\"{}\"", milpa_solver::format_version_str(v)))
        .unwrap_or_default();
    match &ov.target {
        OverrideTarget::Git { url, git_ref, subpath } => {
            let subpath_suffix = subpath
                .as_ref()
                .map(|s| format!(" subpath=\"{}\"", kdl_str(s)))
                .unwrap_or_default();
            vec![format!(
                "    pkg \"{}\" git=(url)\"{}\" ref=\"{}\"{}{}",
                kdl_str(&ov.name), kdl_str(url), kdl_str(git_ref), subpath_suffix, version_suffix
            )]
        }
        OverrideTarget::Local { path } => {
            vec![format!(
                "    pkg \"{}\" local=\"{}\"{}",
                kdl_str(&ov.name), kdl_str(path), version_suffix
            )]
        }
        OverrideTarget::Oci { registry, repository, digest, subpath } => {
            let subpath_suffix = subpath
                .as_ref()
                .map(|s| format!(" subpath=\"{}\"", kdl_str(s)))
                .unwrap_or_default();
            vec![format!(
                "    pkg \"{}\" oci=\"{}/{}\" digest=\"{}\"{}{}",
                kdl_str(&ov.name), kdl_str(registry), kdl_str(repository), kdl_str(digest),
                subpath_suffix, version_suffix
            )]
        }
        OverrideTarget::Tarball { url, sha256, strip_components, subpath } => {
            let mut parts = vec![
                format!("    pkg \"{}\"", kdl_str(&ov.name)),
                format!("tarball=(url)\"{}\"", kdl_str(url)),
            ];
            if let Some(s) = sha256 {
                parts.push(format!("sha256=\"{}\"", kdl_str(s)));
            }
            if *strip_components != 0 {
                parts.push(format!("strip_components={strip_components}"));
            }
            if let Some(s) = subpath {
                parts.push(format!("subpath=\"{}\"", kdl_str(s)));
            }
            if let Some(v) = &ov.version {
                parts.push(format!("version=\"{}\"", milpa_solver::format_version_str(v)));
            }
            vec![parts.join(" ")]
        }
        OverrideTarget::Registry { name, namespace } => {
            let ns_suffix = namespace
                .as_ref()
                .map(|ns| format!(" namespace=\"{}\"", kdl_str(ns)))
                .unwrap_or_default();
            vec![format!(
                "    pkg \"{}\" named=\"{}\"{}{}",
                kdl_str(&ov.name), kdl_str(name), ns_suffix, version_suffix
            )]
        }
        OverrideTarget::Member { member_name } => {
            vec![
                format!("    pkg \"{}\"{} {{", kdl_str(&ov.name), version_suffix),
                format!("        member \"{}\"", kdl_str(member_name)),
                "    }".to_string(),
            ]
        }
    }
}

/// Render a [`Manifest`] to `milpa.kdl` text (trailing newline included).
pub fn format_manifest(m: &Manifest) -> String {
    let mut lines: Vec<String> = vec![HEADER.to_string(), String::new()];

    if m.spec_version_explicit {
        lines.push(format!("spec-version {}", m.spec_version));
        lines.push(String::new());
    }
    if let Some(name) = &m.name {
        lines.push(format!("name \"{}\"", kdl_str(name)));
        lines.push(String::new());
    }
    // version — A1 (§3 Axis A (b) step 1): the package's own declared release
    // version, present iff `m.version` is set (absent-stays-absent, mirroring
    // spec-version above — no default value to fall back to).
    if let Some(version) = &m.version {
        lines.push(format!("version \"{}\"", milpa_solver::format_version_str(version)));
        lines.push(String::new());
    }
    // resolution { strategy "..."; exclude-newer "..." } — C3 (§3 Axis C /
    // §5) + D1 (§3 Axis D). Emitted only when there is actual content
    // (either child set); an empty/absent block is behaviorally identical
    // at the effective-strategy/exclude-newer precedence point, so there is
    // nothing to preserve on round-trip for the empty case.
    if let Some(resolution) = m.resolution {
        if resolution.strategy.is_some() || resolution.exclude_newer.is_some() {
            lines.push("resolution {".to_string());
            if let Some(strategy) = resolution.strategy {
                lines.push(format!("    strategy \"{}\"", strategy.as_str()));
            }
            if let Some(ts) = resolution.exclude_newer {
                lines.push(format!(
                    "    exclude-newer \"{}\"",
                    milpa_types::format_iso8601_timestamp(&ts)
                ));
            }
            lines.push("}".to_string());
            lines.push(String::new());
        }
    }
    if !m.src_dir.is_empty() {
        lines.push(format!("src_dir \"{}\"", kdl_str(&m.src_dir)));
        lines.push(String::new());
    }
    if !m.cas_dir.is_empty() {
        lines.push("cas {".to_string());
        lines.push(format!("    dir \"{}\"", kdl_str(&m.cas_dir)));
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.deps.is_empty() {
        lines.push("deps {".to_string());
        for dep in &m.deps {
            lines.push(format_dep_line(dep));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.dev_deps.is_empty() {
        lines.push("dev-deps {".to_string());
        for dep in &m.dev_deps {
            lines.push(format_dep_line(dep));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.overrides.is_empty() {
        lines.push("overrides {".to_string());
        for ov in &m.overrides {
            lines.extend(format_override_lines(ov));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.self_mirrors.is_empty() {
        lines.push("mirrors {".to_string());
        for url in &m.self_mirrors {
            lines.push(format!("    mirror (url)\"{}\"", kdl_str(url)));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    // provides { module "..." ... } — S7 (rfc-origin-as-identity.md §4.6).
    if !m.provides.is_empty() {
        lines.push("provides {".to_string());
        for module in &m.provides {
            lines.push(format!("    module \"{}\"", kdl_str(module)));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    // S7: skip auto-injected flags (implied by `optional=#true` on the dep).
    let explicit_flags: Vec<_> = m
        .flags
        .iter()
        .filter(|fd| !m.optional_auto_flags.contains(&fd.name))
        .collect();
    if !explicit_flags.is_empty() {
        lines.push("flags {".to_string());
        for fd in explicit_flags {
            let mut head = format!(
                "    \"{}\" default={}",
                kdl_str(&fd.name),
                if fd.default { "#true" } else { "#false" }
            );
            if !fd.description.is_empty() {
                head.push_str(&format!(" description=\"{}\"", kdl_str(&fd.description)));
            }
            let has_block = !fd.defines.is_empty()
                || !fd.enables_same_pkg.is_empty()
                || !fd.enables_cross_pkg.is_empty()
                || !fd.conflicts.is_empty();
            if !has_block {
                lines.push(head);
            } else {
                lines.push(format!("{head} {{"));
                if !fd.defines.is_empty() {
                    let args: Vec<String> =
                        fd.defines.iter().map(|d| format!("\"{}\"", kdl_str(d))).collect();
                    lines.push(format!("        defines {}", args.join(" ")));
                }
                // enables — canonical single-node form (RFC §3.1.1).
                if !fd.enables_same_pkg.is_empty() || !fd.enables_cross_pkg.is_empty() {
                    let same_pkg_args: Vec<String> = fd
                        .enables_same_pkg
                        .iter()
                        .map(|n| format!("\"{}\"", kdl_str(n)))
                        .collect();
                    if fd.enables_cross_pkg.is_empty() {
                        // No cross-pkg: single-line form.
                        lines.push(format!("        enables {}", same_pkg_args.join(" ")));
                    } else {
                        // Cross-pkg present: block form.
                        let enables_head = if same_pkg_args.is_empty() {
                            "        enables".to_string()
                        } else {
                            format!("        enables {}", same_pkg_args.join(" "))
                        };
                        lines.push(format!("{enables_head} {{"));
                        for cpe in &fd.enables_cross_pkg {
                            // cpe.dep is charset-validated [A-Za-z0-9_-]+ — emitted bare.
                            if cpe.flag_requests.is_empty() {
                                lines.push(format!("            {}", cpe.dep));
                            } else {
                                lines.push(format!("            {} {{", cpe.dep));
                                for fr in &cpe.flag_requests {
                                    if fr.enabled {
                                        lines.push(format!("                flag \"{}\"", kdl_str(&fr.name)));
                                    } else {
                                        lines.push(format!(
                                            "                flag \"{}\" #false",
                                            kdl_str(&fr.name)
                                        ));
                                    }
                                }
                                lines.push("            }".to_string());
                            }
                        }
                        lines.push("        }".to_string());
                    }
                }
                if !fd.conflicts.is_empty() {
                    let conflict_args: Vec<String> =
                        fd.conflicts.iter().map(|n| format!("\"{}\"", kdl_str(n))).collect();
                    lines.push(format!("        conflicts {}", conflict_args.join(" ")));
                }
                lines.push("    }".to_string());
            }
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }

    // index-trust / index-trust-signer / index-trust-bundle / entry-trust /
    // index-history — emitted AFTER deps/dev-deps/overrides/mirrors/provides/flags
    // and immediately before `kind` (the canonical order, byte-identical to
    // manifest.py's serializer). present-stays-present / absent-stays-absent:
    // *_explicit (not a non-default-value check) triggers emission, matching the
    // WS-INDEX-TRUST-ON-MEMBER "WHERE it's declared, not what value" semantics.
    // Without this, add / remove / add-member / remove-member round-trips
    // silently reverted a declared policy back to warn — a fail-open.
    if m.index_trust_policy_explicit {
        lines.push(format!("index-trust \"{}\"", trust_policy_str(&m.index_trust_policy)));
        lines.push(String::new());
    }
    if let Some(signer) = &m.index_trust_signer {
        lines.push(format!("index-trust-signer \"{}\"", kdl_str(signer)));
        lines.push(String::new());
    }
    if let Some(bundle) = &m.index_trust_bundle {
        lines.push(format!("index-trust-bundle \"{}\"", kdl_str(bundle)));
        lines.push(String::new());
    }
    if m.entry_trust_policy_explicit {
        lines.push(format!("entry-trust \"{}\"", trust_policy_str(&m.entry_trust_policy)));
        lines.push(String::new());
    }
    if m.index_history_policy_explicit {
        lines.push(format!("index-history \"{}\"", trust_policy_str(&m.index_history_policy)));
        lines.push(String::new());
    }

    lines.push(format!("kind \"{}\"", kdl_str(&m.kind)));
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

const WORKSPACE_HEADER: &str =
    "// generated by milpa; edit by hand or via `milpa workspace add-member` / `milpa workspace remove-member`";

/// Render a [`Workspace`] to `milpa.kdl` text (trailing newline included).
///
/// Byte-identical to the Python `manifest.py:format_workspace_manifest`.
/// Comments are dropped (canonical re-serialization — manifest-grammar §8 + §3.F).
pub fn format_workspace_manifest(ws: &Workspace) -> String {
    let mut lines: Vec<String> = vec![WORKSPACE_HEADER.to_string(), String::new()];

    // name (optional on workspace root)
    if let Some(name) = &ws.name {
        lines.push(format!("name \"{}\"", kdl_str(name)));
        lines.push(String::new());
    }

    // resolution { strategy "..."; exclude-newer "..." } — C3 (§3 Axis C /
    // §5) + D1 (§3 Axis D), root-only. Emitted right after `name`.
    // (index-trust/entry-trust/index-history are now emitted after the
    // workspace/overrides/flags blocks, matching manifest.py — see below.)
    if let Some(resolution) = ws.resolution {
        if resolution.strategy.is_some() || resolution.exclude_newer.is_some() {
            lines.push("resolution {".to_string());
            if let Some(strategy) = resolution.strategy {
                lines.push(format!("    strategy \"{}\"", strategy.as_str()));
            }
            if let Some(ts) = resolution.exclude_newer {
                lines.push(format!(
                    "    exclude-newer \"{}\"",
                    milpa_types::format_iso8601_timestamp(&ts)
                ));
            }
            lines.push("}".to_string());
            lines.push(String::new());
        }
    }

    // workspace { member "..." }
    lines.push("workspace {".to_string());
    for member_path in &ws.members {
        lines.push(format!("    member \"{}\"", kdl_str(member_path)));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    // overrides { pkg "name" ... }
    if !ws.overrides.is_empty() {
        lines.push("overrides {".to_string());
        for ov in &ws.overrides {
            lines.extend(format_override_lines(ov));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }

    // flags { "<name>" default=#true/#false ... }
    // Workspace flags: no optional-auto-flags to skip (workspace has no deps).
    if !ws.flags.is_empty() {
        lines.push("flags {".to_string());
        for fd in &ws.flags {
            let mut head = format!(
                "    \"{}\" default={}",
                kdl_str(&fd.name),
                if fd.default { "#true" } else { "#false" }
            );
            if !fd.description.is_empty() {
                head.push_str(&format!(" description=\"{}\"", kdl_str(&fd.description)));
            }
            let has_block = !fd.defines.is_empty()
                || !fd.enables_same_pkg.is_empty()
                || !fd.enables_cross_pkg.is_empty()
                || !fd.conflicts.is_empty();
            if !has_block {
                lines.push(head);
            } else {
                lines.push(format!("{head} {{"));
                if !fd.defines.is_empty() {
                    let args: Vec<String> =
                        fd.defines.iter().map(|d| format!("\"{}\"", kdl_str(d))).collect();
                    lines.push(format!("        defines {}", args.join(" ")));
                }
                if !fd.enables_same_pkg.is_empty() || !fd.enables_cross_pkg.is_empty() {
                    let same_pkg_args: Vec<String> = fd
                        .enables_same_pkg
                        .iter()
                        .map(|n| format!("\"{}\"", kdl_str(n)))
                        .collect();
                    if fd.enables_cross_pkg.is_empty() {
                        lines.push(format!("        enables {}", same_pkg_args.join(" ")));
                    } else {
                        let enables_head = if same_pkg_args.is_empty() {
                            "        enables".to_string()
                        } else {
                            format!("        enables {}", same_pkg_args.join(" "))
                        };
                        lines.push(format!("{enables_head} {{"));
                        for cpe in &fd.enables_cross_pkg {
                            // cpe.dep is charset-validated [A-Za-z0-9_-]+ — emitted bare.
                            if cpe.flag_requests.is_empty() {
                                lines.push(format!("            {}", cpe.dep));
                            } else {
                                lines.push(format!("            {} {{", cpe.dep));
                                for fr in &cpe.flag_requests {
                                    if fr.enabled {
                                        lines.push(format!("                flag \"{}\"", kdl_str(&fr.name)));
                                    } else {
                                        lines.push(format!(
                                            "                flag \"{}\" #false",
                                            kdl_str(&fr.name)
                                        ));
                                    }
                                }
                                lines.push("            }".to_string());
                            }
                        }
                        lines.push("        }".to_string());
                    }
                }
                if !fd.conflicts.is_empty() {
                    let conflict_args: Vec<String> =
                        fd.conflicts.iter().map(|n| format!("\"{}\"", kdl_str(n))).collect();
                    lines.push(format!("        conflicts {}", conflict_args.join(" ")));
                }
                lines.push("    }".to_string());
            }
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }

    // index-trust / index-trust-signer / index-trust-bundle / entry-trust /
    // index-history — root-authority policy fields (spec §3.4.7: the workspace
    // root is the resolution root for these). Emitted AFTER the workspace block,
    // overrides, and flags — byte-identical to manifest.py's workspace
    // serializer (resolving the previously out-of-scope Python/Rust ordering
    // divergence). Emission is keyed on *_explicit (present-stays-present /
    // absent-stays-absent), NOT on the value, so a redundant `index-trust
    // "warn"` survives a format→parse round trip instead of silently reverting.
    if ws.index_trust_policy_explicit {
        lines.push(format!("index-trust \"{}\"", trust_policy_str(&ws.index_trust_policy)));
        lines.push(String::new());
    }
    if let Some(signer) = &ws.index_trust_signer {
        lines.push(format!("index-trust-signer \"{}\"", kdl_str(signer)));
        lines.push(String::new());
    }
    if let Some(bundle) = &ws.index_trust_bundle {
        lines.push(format!("index-trust-bundle \"{}\"", kdl_str(bundle)));
        lines.push(String::new());
    }
    if ws.entry_trust_policy_explicit {
        lines.push(format!("entry-trust \"{}\"", trust_policy_str(&ws.entry_trust_policy)));
        lines.push(String::new());
    }
    if ws.index_history_policy_explicit {
        lines.push(format!("index-history \"{}\"", trust_policy_str(&ws.index_history_policy)));
        lines.push(String::new());
    }

    // Strip trailing blank lines so the file ends cleanly after the last block.
    while lines.last().map(|l| l.is_empty()).unwrap_or(false) {
        lines.pop();
    }

    let mut out = lines.join("\n");
    out.push('\n');
    out
}

/// Render a sequence of single-value predicates as inline KDL properties.
///
/// Used to build the property string for a `when` node header.
/// All predicates MUST have exactly one value (multi-value predicates can only
/// appear on UrlDep child nodes, never on `when` node headers).
///
/// Returns a space-prefixed string like ` platform="linux" flag="extras"`
/// or an empty string when `preds` is empty.
fn format_predicate_props(preds: &[&Predicate]) -> String {
    let mut parts: Vec<String> = Vec::new();
    for pred in preds {
        debug_assert_eq!(
            pred.values.len(),
            1,
            "format_predicate_props: predicate {:?} has {} values — only single-value predicates \
             are valid on `when` node headers",
            pred.name,
            pred.values.len()
        );
        let v = &pred.values[0];
        if pred.negated {
            parts.push(format!("{}=(not)\"{}\"", pred.name, kdl_str(v)));
        } else {
            parts.push(format!("{}=\"{}\"", pred.name, kdl_str(v)));
        }
    }
    if parts.is_empty() {
        String::new()
    } else {
        format!(" {}", parts.join(" "))
    }
}

/// One deps-block child as a KDL line (or multi-line block for a URL dep with
/// mirrors / multi-value predicates / flag requests).
///
/// §8 round-trip: deps with explicit when-predicates are wrapped in a
/// `when <preds> { <dep-node> }` grouping block so their predicates survive
/// a format → parse cycle.  UrlDep predicates are emitted inline/as child-nodes
/// on the dep node itself (existing behaviour preserved).  For NamedDep,
/// LocalDep, TarballDep, and MemberDep the wrapping form is the only valid
/// form because those node types do not accept predicate properties directly.
fn format_dep_line(dep: &Dep) -> String {
    match dep {
        Dep::Url(u) => {
            let mut head = format!(
                "    \"{}\" git=(url)\"{}\" ref=\"{}\"",
                kdl_str(&u.name), kdl_str(&u.git), kdl_str(&u.git_ref)
            );
            // version= annotation — A3b (§3 Axis A (b) step 4), Cargo's
            // {git, ref, version} pattern. Present iff u.version is set.
            if let Some(version) = &u.version {
                head.push_str(&format!(" version=\"{}\"", milpa_solver::format_version_str(version)));
            }
            // subpath= — rfc-origin-as-identity.md §4.1/S8. Present iff u.subpath is set.
            if let Some(subpath) = &u.subpath {
                head.push_str(&format!(" subpath=\"{}\"", kdl_str(subpath)));
            }
            // S7: emit `optional=#true` and strip the auto-injected gate predicate.
            if u.optional {
                head.push_str(" optional=#true");
            }
            let serializable_preds: Vec<&_> = if u.optional {
                let auto_gate_name = "flag";
                let auto_gate_val = u.name.as_str();
                u.predicates
                    .iter()
                    .filter(|p| {
                        !(p.name == auto_gate_name
                            && p.values.len() == 1
                            && p.values[0] == auto_gate_val
                            && !p.negated)
                    })
                    .collect()
            } else {
                u.predicates.iter().collect()
            };
            let inline: Vec<&_> = serializable_preds
                .iter()
                .copied()
                .filter(|p| p.values.len() == 1)
                .collect();
            let child: Vec<&_> = serializable_preds
                .iter()
                .copied()
                .filter(|p| p.values.len() > 1)
                .collect();
            for p in &inline {
                let v = &p.values[0];
                if p.negated {
                    head.push_str(&format!(" {}=(not)\"{}\"", p.name, kdl_str(v)));
                } else {
                    head.push_str(&format!(" {}=\"{}\"", p.name, kdl_str(v)));
                }
            }
            if u.mirrors.is_empty() && child.is_empty() && u.flag_requests.is_empty() {
                return head;
            }
            let mut block = vec![format!("{head} {{")];
            for p in &child {
                let args: Vec<String> = p
                    .values
                    .iter()
                    .map(|v| {
                        if p.negated {
                            format!("(not)\"{}\"", kdl_str(v))
                        } else {
                            format!("\"{}\"", kdl_str(v))
                        }
                    })
                    .collect();
                block.push(format!("        {} {}", p.name, args.join(" ")));
            }
            for url in &u.mirrors {
                block.push(format!("        mirror (url)\"{}\"", kdl_str(url)));
            }
            for fr in &u.flag_requests {
                if fr.enabled {
                    block.push(format!("        flag \"{}\"", kdl_str(&fr.name)));
                } else {
                    block.push(format!("        flag \"{}\" #false", kdl_str(&fr.name)));
                }
            }
            block.push("    }".to_string());
            block.join("\n")
        }
        Dep::Member(m) => {
            // MemberDep predicates come exclusively from enclosing when blocks
            // (MAN-DEP-MEMBER-PROPS forbids inline properties).  Wrap if non-empty.
            if !m.predicates.is_empty() {
                let preds: Vec<&_> = m.predicates.iter().collect();
                let when_props = format_predicate_props(&preds);
                let inner = format!("        member \"{}\"", kdl_str(&m.name));
                format!("    when{when_props} {{\n{inner}\n    }}")
            } else {
                format!("    member \"{}\"", kdl_str(&m.name))
            }
        }
        Dep::Local(l) => {
            let mut node_body = format!("\"{}\" local=\"{}\"", kdl_str(&l.name), kdl_str(&l.path));
            if let Some(version) = &l.version {
                node_body.push_str(&format!(" version=\"{}\"", milpa_solver::format_version_str(version)));
            }
            if !l.predicates.is_empty() {
                let preds: Vec<&_> = l.predicates.iter().collect();
                let when_props = format_predicate_props(&preds);
                let inner = format!("        {node_body}");
                format!("    when{when_props} {{\n{inner}\n    }}")
            } else {
                format!("    {node_body}")
            }
        }
        Dep::Tarball(t) => {
            let mut parts = vec![
                format!("\"{}\"", kdl_str(&t.name)),
                format!("tarball=(url)\"{}\"", kdl_str(&t.url)),
            ];
            if let Some(sha) = &t.sha256 {
                parts.push(format!("sha256=\"{}\"", kdl_str(sha)));
            }
            if t.strip_components != 0 {
                parts.push(format!("strip_components={}", t.strip_components));
            }
            if let Some(version) = &t.version {
                parts.push(format!("version=\"{}\"", milpa_solver::format_version_str(version)));
            }
            if let Some(subpath) = &t.subpath {
                parts.push(format!("subpath=\"{}\"", kdl_str(subpath)));
            }
            let node_body = parts.join(" ");
            if !t.predicates.is_empty() {
                let preds: Vec<&_> = t.predicates.iter().collect();
                let when_props = format_predicate_props(&preds);
                let inner = format!("        {node_body}");
                format!("    when{when_props} {{\n{inner}\n    }}")
            } else {
                format!("    {node_body}")
            }
        }
        Dep::Named(n) => {
            // S7: strip the auto-injected gate predicate (flag=<depname>) — it's
            // implied by optional=#true and must not be double-emitted as a when-block
            // predicate.  All other predicates (from outer when blocks) ARE serialized.
            let when_preds: Vec<&_> = if n.optional {
                let auto_gate_val = n.name.as_str();
                n.predicates
                    .iter()
                    .filter(|p| {
                        !(p.name == "flag"
                            && p.values.len() == 1
                            && p.values[0] == auto_gate_val
                            && !p.negated)
                    })
                    .collect()
            } else {
                n.predicates.iter().collect()
            };

            // Build the dep node body (without leading indentation — added below).
            // S5b: emit `namespace="..."` attribute in canonical form (never slash).
            let ns_attr = match &n.namespace {
                Some(ns) => format!(" namespace=\"{}\"", kdl_str(ns)),
                None => String::new(),
            };
            // ns_attr is either "" or " namespace=\"ns\"" (with a leading space).
            // Result: `"name"`, `"name" "c"`, `"name" namespace="ns"`, or
            //         `"name" namespace="ns" "c"` — always single-spaced.
            let name_part = format!("\"{}\"{}",  kdl_str(&n.name), ns_attr);
            let mut head = match &n.constraint {
                None => name_part,
                Some(c) => format!("{} \"{}\"", name_part, kdl_str(c)),
            };
            // S7: emit `optional=#true`.
            if n.optional {
                head.push_str(" optional=#true");
            }

            if !n.flag_requests.is_empty() {
                // Multi-line block form for flag_requests (§3.1.5, S3 RFC #23).
                if !when_preds.is_empty() {
                    let when_props = format_predicate_props(&when_preds);
                    let mut inner_lines = vec![format!("        {head} {{")];
                    for fr in &n.flag_requests {
                        if fr.enabled {
                            inner_lines.push(format!("            flag \"{}\"", kdl_str(&fr.name)));
                        } else {
                            inner_lines.push(format!("            flag \"{}\" #false", kdl_str(&fr.name)));
                        }
                    }
                    inner_lines.push("        }".to_string());
                    let inner = inner_lines.join("\n");
                    format!("    when{when_props} {{\n{inner}\n    }}")
                } else {
                    let mut block = vec![format!("    {head} {{")];
                    for fr in &n.flag_requests {
                        if fr.enabled {
                            block.push(format!("        flag \"{}\"", kdl_str(&fr.name)));
                        } else {
                            block.push(format!("        flag \"{}\" #false", kdl_str(&fr.name)));
                        }
                    }
                    block.push("    }".to_string());
                    block.join("\n")
                }
            } else if !when_preds.is_empty() {
                let when_props = format_predicate_props(&when_preds);
                let inner = format!("        {head}");
                format!("    when{when_props} {{\n{inner}\n    }}")
            } else {
                format!("    {head}")
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{NamedDep, UrlDep};

    fn base() -> Manifest {
        Manifest {
            name: Some("myapp".into()),
            kind: "application".into(),
            src_dir: String::new(),
            deps: Vec::new(),
            dev_deps: Vec::new(),
            overrides: Vec::new(),
            flags: Vec::new(),
            self_mirrors: Vec::new(),
            cas_dir: String::new(),
            spec_version: 1,
            spec_version_explicit: false,
            version: None,
            attestation_policy: crate::TrustPolicy::Warn,
            // S4 (RFC attestation-v1-normative.md): index-trust + entry-trust
            // defaults flipped warn -> strict; index-history stays warn.
            index_trust_policy: crate::TrustPolicy::Strict,
            index_trust_signer: None,
            index_trust_bundle: None,
            index_trust_policy_explicit: false,
            entry_trust_policy: crate::TrustPolicy::Strict,
            entry_trust_policy_explicit: false,
            index_history_policy: crate::TrustPolicy::Warn,
            index_history_policy_explicit: false,
            resolution: None,
            provides: Vec::new(),
            optional_auto_flags: std::collections::BTreeSet::new(),
        }
    }

    #[test]
    fn minimal_manifest_round_trips() {
        let m = base();
        let text = format_manifest(&m);
        assert!(text.contains("name \"myapp\""));
        assert!(text.ends_with("kind \"application\"\n"));
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed, m);
    }

    #[test]
    fn url_and_named_deps_round_trip_with_url_annotation() {
        let mut m = base();
        m.deps = vec![
            Dep::Url(UrlDep { subpath: None,
                name: "foo".into(),
                git: "https://e/foo.git".into(),
                git_ref: "main".into(),
                mirrors: Vec::new(),
                predicates: Vec::new(),
                flag_requests: Vec::new(),
                optional: false,
                version: None,
            }),
            Dep::Named(NamedDep {
                name: "bar".into(),
                constraint: Some(">= 1.0.0".into()),
                parsed_constraint: Some(
                    milpa_solver::VersionSet::from_constraint(Some(">= 1.0.0")).unwrap(),
                ),
                flag_requests: Vec::new(),
                optional: false,
                predicates: Vec::new(),
                namespace: None,
            }),
        ];
        let text = format_manifest(&m);
        assert!(text.contains("git=(url)\"https://e/foo.git\" ref=\"main\""));
        assert!(text.contains("\"bar\" \">= 1.0.0\""));
        // Insertion-stable + round-trips.
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed.deps, m.deps);
    }

    #[test]
    fn no_deps_omits_the_block() {
        let text = format_manifest(&base());
        assert!(!text.contains("deps {"));
    }

    // -----------------------------------------------------------------------
    // A1 (rfc-resolution-semantics.md §3 Axis A (b) step 1 / §5): top-level
    // package `version` field round-trip. The hand-rolled per-field emitter
    // has silently dropped a new field before when an emit line was
    // forgotten — this pins the field so a future omission fails loudly.
    // -----------------------------------------------------------------------

    #[test]
    fn package_version_emitted_only_when_present() {
        let m_absent = base();
        let mut m_present = base();
        m_present.version = Some(milpa_types::Version::release(1, 2, 3));
        assert!(!format_manifest(&m_absent).contains("version"));
        assert!(format_manifest(&m_present).contains("version \"1.2.3\""));
    }

    #[test]
    fn package_version_round_trips() {
        let mut m = base();
        m.version = Some(milpa_types::Version::release(1, 2, 3));
        let text = format_manifest(&m);
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed, m);
    }

    // -----------------------------------------------------------------------
    // C3 (rfc-resolution-semantics.md §3 Axis C / §5): manifest
    // `resolution { strategy }` block round-trip — same silent-drop trap as
    // the package `version` field above.
    // -----------------------------------------------------------------------

    #[test]
    fn resolution_strategy_emitted_only_when_present() {
        let m_absent = base();
        let mut m_empty = base();
        m_empty.resolution = Some(crate::Resolution {
            strategy: None,
            exclude_newer: None,
        });
        let mut m_present = base();
        m_present.resolution = Some(crate::Resolution {
            strategy: Some(milpa_solver::Strategy::Semver),
            exclude_newer: None,
        });
        assert!(!format_manifest(&m_absent).contains("resolution"));
        assert!(!format_manifest(&m_empty).contains("resolution"));
        assert!(format_manifest(&m_present).contains("strategy \"semver\""));
    }

    #[test]
    fn resolution_strategy_round_trips() {
        let mut m = base();
        m.resolution = Some(crate::Resolution {
            strategy: Some(milpa_solver::Strategy::LowestDirect),
            exclude_newer: None,
        });
        let text = format_manifest(&m);
        assert!(text.contains("strategy \"lowest-direct\""));
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(
            reparsed.resolution.and_then(|r| r.strategy),
            Some(milpa_solver::Strategy::LowestDirect)
        );
    }

    // -----------------------------------------------------------------------
    // D1 (rfc-resolution-semantics.md §3 Axis D): manifest
    // `resolution { exclude-newer }` block round-trip.
    // -----------------------------------------------------------------------

    #[test]
    fn resolution_exclude_newer_emitted_only_when_present() {
        let m_absent = base();
        let mut m_empty = base();
        m_empty.resolution = Some(crate::Resolution {
            strategy: None,
            exclude_newer: None,
        });
        let mut m_present = base();
        m_present.resolution = Some(crate::Resolution {
            strategy: None,
            exclude_newer: milpa_types::parse_iso8601_timestamp("2026-01-01T00:00:00Z"),
        });
        assert!(!format_manifest(&m_absent).contains("resolution"));
        assert!(!format_manifest(&m_empty).contains("resolution"));
        assert!(format_manifest(&m_present).contains("exclude-newer \"2026-01-01T00:00:00Z\""));
    }

    #[test]
    fn resolution_exclude_newer_round_trips() {
        let mut m = base();
        m.resolution = Some(crate::Resolution {
            strategy: None,
            exclude_newer: milpa_types::parse_iso8601_timestamp("2026-06-15T12:30:45Z"),
        });
        let text = format_manifest(&m);
        assert!(text.contains("exclude-newer \"2026-06-15T12:30:45Z\""));
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(
            reparsed.resolution.and_then(|r| r.exclude_newer),
            milpa_types::parse_iso8601_timestamp("2026-06-15T12:30:45Z")
        );
    }

    #[test]
    fn resolution_strategy_and_exclude_newer_both_round_trip() {
        let mut m = base();
        m.resolution = Some(crate::Resolution {
            strategy: Some(milpa_solver::Strategy::Minver),
            exclude_newer: milpa_types::parse_iso8601_timestamp("2026-01-01T00:00:00Z"),
        });
        let text = format_manifest(&m);
        assert!(text.contains("strategy \"minver\""));
        assert!(text.contains("exclude-newer \"2026-01-01T00:00:00Z\""));
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        let r = reparsed.resolution.unwrap();
        assert_eq!(r.strategy, Some(milpa_solver::Strategy::Minver));
        assert_eq!(
            r.exclude_newer,
            milpa_types::parse_iso8601_timestamp("2026-01-01T00:00:00Z")
        );
    }

    /// A3b (§3 Axis A (b) step 4): a UrlDep's `version=` annotation
    /// round-trips through format→parse (the hand-rolled emitter has
    /// silently dropped a new field before — pin the round-trip, not just
    /// the parse).
    #[test]
    fn url_dep_version_annotation_round_trips() {
        let mut m = base();
        m.deps = vec![Dep::Url(UrlDep { subpath: None,
            name: "foo".into(),
            git: "https://e/foo.git".into(),
            git_ref: "main".into(),
            mirrors: Vec::new(),
            predicates: Vec::new(),
            flag_requests: Vec::new(),
            optional: false,
            version: Some(milpa_solver::parse_version("1.2.3").unwrap()),
        })];
        let text = format_manifest(&m);
        assert!(text.contains("version=\"1.2.3\""), "text:\n{text}");
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed, m);
    }

    #[test]
    fn local_dep_version_annotation_round_trips() {
        let mut m = base();
        m.deps = vec![Dep::Local(crate::LocalDep {
            name: "foo".into(),
            path: "../foo".into(),
            predicates: Vec::new(),
            version: Some(milpa_solver::parse_version("0.5.0").unwrap()),
        })];
        let text = format_manifest(&m);
        assert!(text.contains("version=\"0.5.0\""), "text:\n{text}");
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed, m);
    }

    #[test]
    fn tarball_dep_version_annotation_round_trips() {
        let mut m = base();
        m.deps = vec![Dep::Tarball(crate::TarballDep { subpath: None,
            name: "foo".into(),
            url: "https://example.com/foo.tar.gz".into(),
            sha256: None,
            strip_components: 0,
            predicates: Vec::new(),
            version: Some(milpa_solver::parse_version("3.0.0").unwrap()),
        })];
        let text = format_manifest(&m);
        assert!(text.contains("version=\"3.0.0\""), "text:\n{text}");
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed, m);
    }

    /// A3b/D-A3: an override rule's `version=` annotation round-trips
    /// (orthogonal to the target form — tested on the git form here).
    #[test]
    fn override_version_annotation_round_trips() {
        let mut m = base();
        m.overrides = vec![crate::Override {
            name: "foo".into(),
            target: OverrideTarget::Git {
                url: "https://github.com/fork/foo.git".into(),
                git_ref: "dev".into(),
                subpath: None,
            },
            version: Some(milpa_solver::parse_version("2.0.0").unwrap()),
        }];
        let text = format_manifest(&m);
        assert!(text.contains("version=\"2.0.0\""), "text:\n{text}");
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed, m);
    }

    // -----------------------------------------------------------------------
    // Conditional-dep round-trip tests (§8 / #163)
    // Predicates must survive format → parse for ALL 5 dep forms.
    // -----------------------------------------------------------------------

    fn pkg(text: &str) -> crate::Manifest {
        match crate::parse_document(text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        }
    }

    fn platform_pred(value: &str) -> Predicate {
        Predicate {
            name: "platform".into(),
            values: vec![value.into()],
            negated: false,
        }
    }

    #[test]
    fn local_dep_with_predicate_round_trips() {
        let mut m = base();
        m.deps = vec![Dep::Local(crate::LocalDep {
            name: "locallib".into(),
            path: "../locallib".into(),
            predicates: vec![platform_pred("linux")],
            version: None,
        })];
        let text = format_manifest(&m);
        // Must use when-block form.
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        assert!(text.contains("platform=\"linux\""), "expected predicate in:\n{text}");
        let reparsed = pkg(&text);
        assert_eq!(reparsed.deps.len(), 1);
        let dep = match &reparsed.deps[0] {
            Dep::Local(l) => l,
            other => panic!("expected Local dep, got {other:?}"),
        };
        assert_eq!(dep.path, "../locallib");
        assert_eq!(dep.predicates.len(), 1);
        assert_eq!(dep.predicates[0].name, "platform");
        assert_eq!(dep.predicates[0].values, vec!["linux"]);
        assert!(!dep.predicates[0].negated);
    }

    #[test]
    fn tarball_dep_with_predicate_round_trips() {
        let mut m = base();
        m.deps = vec![Dep::Tarball(crate::TarballDep { subpath: None,
            name: "tarlib".into(),
            url: "https://example.com/tarlib.tar.gz".into(),
            sha256: None,
            strip_components: 0,
            predicates: vec![platform_pred("macosx")],
            version: None,
        })];
        let text = format_manifest(&m);
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        assert!(text.contains("platform=\"macosx\""), "expected predicate in:\n{text}");
        let reparsed = pkg(&text);
        assert_eq!(reparsed.deps.len(), 1);
        let dep = match &reparsed.deps[0] {
            Dep::Tarball(t) => t,
            other => panic!("expected Tarball dep, got {other:?}"),
        };
        assert_eq!(dep.url, "https://example.com/tarlib.tar.gz");
        assert_eq!(dep.predicates.len(), 1);
        assert_eq!(dep.predicates[0].name, "platform");
        assert_eq!(dep.predicates[0].values, vec!["macosx"]);
    }

    #[test]
    fn member_dep_with_predicate_parse_error() {
        // S1b: MemberDep with predicates formats into a when-gated member node,
        // which is a parse-time category error (MAN-MEMBER-WHEN-GATED).
        // The formatter still emits the when-wrapped form; re-parsing raises the
        // new error rather than succeeding.
        let mut m = base();
        m.deps = vec![Dep::Member(crate::MemberDep {
            name: "submember".into(),
            predicates: vec![platform_pred("linux")],
        })];
        let text = format_manifest(&m);
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        assert!(text.contains("member \"submember\""), "expected member node in:\n{text}");
        let err = crate::parse_manifest(&text).unwrap_err();
        assert_eq!(err.code(), "MAN-MEMBER-WHEN-GATED");
    }

    #[test]
    fn named_dep_with_predicate_round_trips() {
        let mut m = base();
        m.deps = vec![Dep::Named(NamedDep {
            name: "mylib".into(),
            constraint: None,
            parsed_constraint: None,
            flag_requests: Vec::new(),
            optional: false,
            predicates: vec![platform_pred("linux")],
            namespace: None,
        })];
        let text = format_manifest(&m);
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        assert!(text.contains("platform=\"linux\""), "expected predicate in:\n{text}");
        let reparsed = pkg(&text);
        assert_eq!(reparsed.deps.len(), 1);
        let dep = match &reparsed.deps[0] {
            Dep::Named(n) => n,
            other => panic!("expected Named dep, got {other:?}"),
        };
        assert_eq!(dep.name, "mylib");
        assert_eq!(dep.predicates.len(), 1);
        assert_eq!(dep.predicates[0].name, "platform");
        assert_eq!(dep.predicates[0].values, vec!["linux"]);
    }

    #[test]
    fn named_dep_with_predicate_and_flag_requests_round_trips() {
        let mut m = base();
        m.flags = vec![crate::FlagDecl {
            name: "ssl".into(),
            default: false,
            description: String::new(),
            defines: Vec::new(),
            enables_same_pkg: Vec::new(),
            enables_cross_pkg: Vec::new(),
            conflicts: Vec::new(),
        }];
        m.deps = vec![Dep::Named(NamedDep {
            name: "platformlib".into(),
            constraint: None,
            parsed_constraint: None,
            flag_requests: vec![crate::FlagRequest {
                name: "ssl".into(),
                enabled: true,
            }],
            optional: false,
            predicates: vec![platform_pred("linux")],
            namespace: None,
        })];
        let text = format_manifest(&m);
        assert!(text.contains("when"), "expected when-block in:\n{text}");
        let reparsed = pkg(&text);
        let dep = match &reparsed.deps[0] {
            Dep::Named(n) => n,
            other => panic!("expected Named dep, got {other:?}"),
        };
        assert_eq!(dep.flag_requests.len(), 1);
        assert_eq!(dep.flag_requests[0].name, "ssl");
        assert_eq!(dep.predicates.len(), 1);
        assert_eq!(dep.predicates[0].name, "platform");
    }

    #[test]
    fn parse_format_parse_cycle_preserves_conditional_dep() {
        // parse(format(parse(src))) == parse(src) — full cycle for LocalDep.
        let src = "name \"mypkg\"\ndeps {\n    when platform=\"linux\" {\n        \"mylib\" local=\"./mylib\"\n    }\n}\nkind \"library\"\n";
        let m1 = pkg(src);
        let text = format_manifest(&m1);
        let m2 = pkg(&text);
        assert_eq!(m2.deps.len(), 1);
        let d1 = match &m1.deps[0] {
            Dep::Local(l) => l,
            other => panic!("expected Local, got {other:?}"),
        };
        let d2 = match &m2.deps[0] {
            Dep::Local(l) => l,
            other => panic!("expected Local, got {other:?}"),
        };
        assert_eq!(d2.name, d1.name);
        assert_eq!(d2.predicates, d1.predicates);
    }

    #[test]
    fn no_predicate_deps_unchanged() {
        // Unconditional LocalDep/TarballDep/MemberDep must NOT gain a when-block.
        let mut m = base();
        m.deps = vec![
            Dep::Local(crate::LocalDep {
                name: "locallib".into(),
                path: "./locallib".into(),
                predicates: Vec::new(),
                version: None,
            }),
            Dep::Member(crate::MemberDep {
                name: "sub".into(),
                predicates: Vec::new(),
            }),
        ];
        let text = format_manifest(&m);
        assert!(!text.contains("when"), "unexpected when-block in:\n{text}");
    }

    // -----------------------------------------------------------------------
    // F2 — KDL string escaping: values with `"`, `\`, and control chars
    // -----------------------------------------------------------------------

    /// `kdl_str` helper must escape exactly as Python's `_kdl_str`.
    #[test]
    fn kdl_str_escapes_special_chars() {
        assert_eq!(kdl_str("hello"), "hello");
        assert_eq!(kdl_str(r#"say "hi""#), r#"say \"hi\""#);
        assert_eq!(kdl_str("back\\slash"), "back\\\\slash");
        assert_eq!(kdl_str("line\nfeed"), "line\\nfeed");
        assert_eq!(kdl_str("carriage\rreturn"), "carriage\\rreturn");
        assert_eq!(kdl_str("tab\there"), "tab\\there");
        // Backslash is escaped BEFORE quote (order matters for idempotency).
        assert_eq!(kdl_str("a\\\"b"), "a\\\\\\\"b");
    }

    /// A flag description containing `"` and `\` must serialize to valid escaped
    /// KDL and round-trip cleanly (parse(serialize(m)) == m).
    #[test]
    fn flag_description_with_special_chars_round_trips() {
        let mut m = base();
        m.flags = vec![crate::FlagDecl {
            name: "ssl".into(),
            default: false,
            description: r#"enables "SSL" support, path=C:\certs"#.into(),
            defines: Vec::new(),
            enables_same_pkg: Vec::new(),
            enables_cross_pkg: Vec::new(),
            conflicts: Vec::new(),
        }];
        let text = format_manifest(&m);
        // The description must NOT appear verbatim (unescaped " would break KDL).
        assert!(
            !text.contains(r#"description="enables "SSL""#),
            "unescaped quote leaked into KDL output:\n{text}"
        );
        // Must contain the properly escaped form.
        assert!(
            text.contains(r#"description="enables \"SSL\" support, path=C:\\certs""#),
            "expected escaped description in:\n{text}"
        );
        // Must round-trip: parse back and recover the original description.
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed.flags.len(), 1);
        assert_eq!(
            reparsed.flags[0].description,
            r#"enables "SSL" support, path=C:\certs"#
        );
    }

    /// A workspace manifest with a flag description containing `"` and `\`
    /// must serialize to valid escaped KDL and round-trip cleanly.
    #[test]
    fn workspace_flag_description_with_special_chars_round_trips() {
        let ws = crate::Workspace {
            name: Some("my-ws".into()),
            members: vec!["member-a".into()],
            overrides: Vec::new(),
            flags: vec![crate::FlagDecl {
                name: "ci".into(),
                default: false,
                description: r#"for "CI" builds, base=C:\build"#.into(),
                defines: Vec::new(),
                enables_same_pkg: Vec::new(),
                enables_cross_pkg: Vec::new(),
                conflicts: Vec::new(),
            }],
            ..Default::default()
        };
        let text = format_workspace_manifest(&ws);
        // Must contain the properly escaped form.
        assert!(
            text.contains(r#"description="for \"CI\" builds, base=C:\\build""#),
            "expected escaped description in:\n{text}"
        );
        // Must round-trip.
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Workspace(w) => w,
            other => panic!("expected workspace, got {other:?}"),
        };
        assert_eq!(reparsed.flags.len(), 1);
        assert_eq!(
            reparsed.flags[0].description,
            r#"for "CI" builds, base=C:\build"#
        );
    }

    // -------------------------------------------------------------------
    // RD-M2 (code-review): index-trust / -signer / -bundle round-trip.
    // Previously format_manifest/format_workspace_manifest emitted none of
    // the three fields, so add-member/remove-member (and package add/remove,
    // which round-trip through mutate_manifest_file → format_manifest) would
    // silently revert a declared "strict" policy back to the implicit "warn"
    // default on the very next write — a fail-open (spec/manifest-grammar.md
    // §8 semantic round-trip).
    // -------------------------------------------------------------------

    #[test]
    fn package_manifest_index_trust_strict_signer_bundle_round_trips() {
        let mut m = base();
        m.index_trust_policy = crate::TrustPolicy::Strict;
        m.index_trust_policy_explicit = true;
        m.index_trust_signer = Some(
            "https://github.com/acme/reg/.github/workflows/publish.yaml@refs/heads/main".into(),
        );
        m.index_trust_bundle = Some("file:///etc/milpa/trust-bundle.json".into());

        let text = format_manifest(&m);
        assert!(text.contains("index-trust \"strict\""), "missing index-trust node:\n{text}");
        assert!(text.contains("index-trust-signer"), "missing index-trust-signer node:\n{text}");
        assert!(text.contains("index-trust-bundle"), "missing index-trust-bundle node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed.index_trust_policy, m.index_trust_policy);
        assert_eq!(reparsed.index_trust_policy_explicit, m.index_trust_policy_explicit);
        assert_eq!(reparsed.index_trust_signer, m.index_trust_signer);
        assert_eq!(reparsed.index_trust_bundle, m.index_trust_bundle);
        assert_eq!(reparsed, m, "full manifest must round-trip byte-for-semantic-equivalence");
    }

    /// A manifest that never declared `index-trust` at all must NOT gain one
    /// on round-trip (absent-stays-absent — the flip side of the above test).
    #[test]
    fn package_manifest_without_index_trust_stays_absent() {
        let m = base();
        let text = format_manifest(&m);
        assert!(!text.contains("index-trust"), "must not fabricate an index-trust node:\n{text}");
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert!(!reparsed.index_trust_policy_explicit);
    }

    #[test]
    fn workspace_manifest_index_trust_strict_signer_bundle_round_trips() {
        let ws = crate::Workspace {
            name: Some("my-ws".into()),
            members: vec!["member-a".into()],
            overrides: Vec::new(),
            flags: Vec::new(),
            index_trust_policy: crate::TrustPolicy::Strict,
            index_trust_policy_explicit: true,
            index_trust_signer: Some(
                "https://github.com/acme/reg/.github/workflows/publish.yaml@refs/heads/main".into(),
            ),
            index_trust_bundle: Some("file:///etc/milpa/trust-bundle.json".into()),
            entry_trust_policy: crate::TrustPolicy::Strict, // S4 default (undeclared axis)
            entry_trust_policy_explicit: false,
            index_history_policy: crate::TrustPolicy::Warn,
            index_history_policy_explicit: false,
            resolution: None,
        };

        let text = format_workspace_manifest(&ws);
        assert!(text.contains("index-trust \"strict\""), "missing index-trust node:\n{text}");
        assert!(text.contains("index-trust-signer"), "missing index-trust-signer node:\n{text}");
        assert!(text.contains("index-trust-bundle"), "missing index-trust-bundle node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Workspace(w) => w,
            other => panic!("expected workspace, got {other:?}"),
        };
        assert_eq!(reparsed.index_trust_policy, ws.index_trust_policy);
        assert_eq!(reparsed.index_trust_policy_explicit, ws.index_trust_policy_explicit);
        assert_eq!(reparsed.index_trust_signer, ws.index_trust_signer);
        assert_eq!(reparsed.index_trust_bundle, ws.index_trust_bundle);
        assert_eq!(reparsed, ws);
    }

    /// RD-M2 follow-up (Medium finding): a workspace root that hand-authors
    /// the legal-but-redundant `index-trust "warn"` (same value as the
    /// implicit default) must still round-trip byte-for-byte through
    /// `milpa workspace add-member`/`remove-member` — mirrors
    /// `package_manifest_index_trust_strict_signer_bundle_round_trips` and
    /// the Python `WorkspaceManifest.index_trust_policy_explicit` behavior.
    /// Before this fix, emission was gated on `index_trust_policy != Warn`
    /// (value-based), so an explicit `"warn"` declaration silently vanished
    /// on the next rewrite.
    #[test]
    fn workspace_manifest_index_trust_warn_explicit_round_trips() {
        let mut ws = crate::Workspace {
            name: Some("my-ws".into()),
            members: vec!["member-a".into()],
            overrides: Vec::new(),
            flags: Vec::new(),
            ..Default::default()
        };
        ws.index_trust_policy = crate::TrustPolicy::Warn;
        ws.index_trust_policy_explicit = true;

        let text = format_workspace_manifest(&ws);
        assert!(text.contains("index-trust \"warn\""), "missing explicit index-trust node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Workspace(w) => w,
            other => panic!("expected workspace, got {other:?}"),
        };
        assert_eq!(reparsed.index_trust_policy, ws.index_trust_policy);
        assert_eq!(reparsed.index_trust_policy_explicit, ws.index_trust_policy_explicit);
        assert_eq!(reparsed, ws);
    }

    /// Flip side: a workspace that never declared `index-trust` at all must
    /// NOT gain one on round-trip (absent-stays-absent).
    #[test]
    fn workspace_manifest_without_index_trust_stays_absent() {
        let ws = crate::Workspace {
            name: Some("my-ws".into()),
            members: vec!["member-a".into()],
            overrides: Vec::new(),
            flags: Vec::new(),
            ..Default::default()
        };
        let text = format_workspace_manifest(&ws);
        assert!(!text.contains("index-trust"), "must not fabricate an index-trust node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Workspace(w) => w,
            other => panic!("expected workspace, got {other:?}"),
        };
        assert!(!reparsed.index_trust_policy_explicit);
    }

    // P3a (RFC per-entry-attestation.md §4): entry-trust round-trip tests —
    // mirror the index-trust ones above.

    #[test]
    fn package_manifest_entry_trust_strict_round_trips() {
        let mut m = base();
        m.entry_trust_policy = crate::TrustPolicy::Strict;
        m.entry_trust_policy_explicit = true;

        let text = format_manifest(&m);
        assert!(text.contains("entry-trust \"strict\""), "missing entry-trust node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed.entry_trust_policy, m.entry_trust_policy);
        assert_eq!(reparsed.entry_trust_policy_explicit, m.entry_trust_policy_explicit);
        assert_eq!(reparsed, m);
    }

    /// A manifest that never declared `entry-trust` at all must NOT gain one
    /// on round-trip (absent-stays-absent).
    #[test]
    fn package_manifest_without_entry_trust_stays_absent() {
        let m = base();
        let text = format_manifest(&m);
        assert!(!text.contains("entry-trust"), "must not fabricate an entry-trust node:\n{text}");
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert!(!reparsed.entry_trust_policy_explicit);
    }

    /// Explicit `entry-trust "warn"` (matching the default value) must still
    /// survive a round trip — the absent-stays-absent rule is about WHERE the
    /// field is declared, not what value it holds.
    #[test]
    fn package_manifest_entry_trust_warn_explicit_round_trips() {
        let mut m = base();
        m.entry_trust_policy = crate::TrustPolicy::Warn;
        m.entry_trust_policy_explicit = true;

        let text = format_manifest(&m);
        assert!(text.contains("entry-trust \"warn\""), "missing explicit entry-trust node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed.entry_trust_policy, m.entry_trust_policy);
        assert_eq!(reparsed.entry_trust_policy_explicit, m.entry_trust_policy_explicit);
    }

    #[test]
    fn workspace_manifest_entry_trust_strict_round_trips() {
        let mut ws = crate::Workspace {
            name: Some("my-ws".into()),
            members: vec!["member-a".into()],
            overrides: Vec::new(),
            flags: Vec::new(),
            ..Default::default()
        };
        ws.entry_trust_policy = crate::TrustPolicy::Strict;
        ws.entry_trust_policy_explicit = true;

        let text = format_workspace_manifest(&ws);
        assert!(text.contains("entry-trust \"strict\""), "missing entry-trust node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Workspace(w) => w,
            other => panic!("expected workspace, got {other:?}"),
        };
        assert_eq!(reparsed.entry_trust_policy, ws.entry_trust_policy);
        assert_eq!(reparsed.entry_trust_policy_explicit, ws.entry_trust_policy_explicit);
        assert_eq!(reparsed, ws);
    }

    /// Flip side: a workspace that never declared `entry-trust` at all must
    /// NOT gain one on round-trip (absent-stays-absent).
    #[test]
    fn workspace_manifest_without_entry_trust_stays_absent() {
        let ws = crate::Workspace {
            name: Some("my-ws".into()),
            members: vec!["member-a".into()],
            overrides: Vec::new(),
            flags: Vec::new(),
            ..Default::default()
        };
        let text = format_workspace_manifest(&ws);
        assert!(!text.contains("entry-trust"), "must not fabricate an entry-trust node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Workspace(w) => w,
            other => panic!("expected workspace, got {other:?}"),
        };
        assert!(!reparsed.entry_trust_policy_explicit);
    }

    // A workspace member manifest declaring `entry-trust` must raise
    // `WS-ENTRY-TRUST-ON-MEMBER` — proven at the `milpa-core` workspace-load
    // layer (`workspace_tests.rs`), not here; this crate only proves the
    // per-manifest parse/format round-trip.

    // A3 (rfc-registry-append-only.md §2): index-history round-trip tests —
    // mirror the entry-trust ones above.

    #[test]
    fn package_manifest_index_history_strict_round_trips() {
        let mut m = base();
        m.index_history_policy = crate::TrustPolicy::Strict;
        m.index_history_policy_explicit = true;

        let text = format_manifest(&m);
        assert!(text.contains("index-history \"strict\""), "missing index-history node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed.index_history_policy, m.index_history_policy);
        assert_eq!(reparsed.index_history_policy_explicit, m.index_history_policy_explicit);
        assert_eq!(reparsed, m);
    }

    /// A manifest that never declared `index-history` at all must NOT gain
    /// one on round-trip (absent-stays-absent).
    #[test]
    fn package_manifest_without_index_history_stays_absent() {
        let m = base();
        let text = format_manifest(&m);
        assert!(!text.contains("index-history"), "must not fabricate an index-history node:\n{text}");
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert!(!reparsed.index_history_policy_explicit);
    }

    /// Explicit `index-history "warn"` (matching the default value) must
    /// still survive a round trip — the absent-stays-absent rule is about
    /// WHERE the field is declared, not what value it holds.
    #[test]
    fn package_manifest_index_history_warn_explicit_round_trips() {
        let mut m = base();
        m.index_history_policy = crate::TrustPolicy::Warn;
        m.index_history_policy_explicit = true;

        let text = format_manifest(&m);
        assert!(text.contains("index-history \"warn\""), "missing explicit index-history node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed.index_history_policy, m.index_history_policy);
        assert_eq!(reparsed.index_history_policy_explicit, m.index_history_policy_explicit);
    }

    #[test]
    fn workspace_manifest_index_history_strict_round_trips() {
        let mut ws = crate::Workspace {
            name: Some("my-ws".into()),
            members: vec!["member-a".into()],
            overrides: Vec::new(),
            flags: Vec::new(),
            ..Default::default()
        };
        ws.index_history_policy = crate::TrustPolicy::Strict;
        ws.index_history_policy_explicit = true;

        let text = format_workspace_manifest(&ws);
        assert!(text.contains("index-history \"strict\""), "missing index-history node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Workspace(w) => w,
            other => panic!("expected workspace, got {other:?}"),
        };
        assert_eq!(reparsed.index_history_policy, ws.index_history_policy);
        assert_eq!(reparsed.index_history_policy_explicit, ws.index_history_policy_explicit);
        assert_eq!(reparsed, ws);
    }

    /// Flip side: a workspace that never declared `index-history` at all
    /// must NOT gain one on round-trip (absent-stays-absent).
    #[test]
    fn workspace_manifest_without_index_history_stays_absent() {
        let ws = crate::Workspace {
            name: Some("my-ws".into()),
            members: vec!["member-a".into()],
            overrides: Vec::new(),
            flags: Vec::new(),
            ..Default::default()
        };
        let text = format_workspace_manifest(&ws);
        assert!(!text.contains("index-history"), "must not fabricate an index-history node:\n{text}");

        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Workspace(w) => w,
            other => panic!("expected workspace, got {other:?}"),
        };
        assert!(!reparsed.index_history_policy_explicit);
    }

    // A workspace member manifest declaring `index-history` must raise
    // `WS-INDEX-HISTORY-ON-MEMBER` — proven at the `milpa-core` workspace-load
    // layer (`workspace_tests.rs`), not here; this crate only proves the
    // per-manifest parse/format round-trip.
}
