//! `milpa.kdl` serialization (RFC §6 S13; manifest-grammar §8; mirrors
//! `manifest.py:format_manifest`).
//!
//! The inverse of the package parser: render a [`Manifest`] back to canonical
//! `milpa.kdl` text. Deterministic, **insertion-stable** dep order, URL/tarball
//! values carry the recommended `(url)` annotation. Comment-preserving
//! serialization is out of scope (the mutating verbs warn that hand-written
//! comments are dropped on rewrite).

use crate::{Dep, Manifest};

const HEADER: &str = "// generated by milpa; edit by hand or via `milpa add` / `milpa remove`";

/// Render a [`Manifest`] to `milpa.kdl` text (trailing newline included).
pub fn format_manifest(m: &Manifest) -> String {
    let mut lines: Vec<String> = vec![HEADER.to_string(), String::new()];

    if m.spec_version_explicit {
        lines.push(format!("spec-version {}", m.spec_version));
        lines.push(String::new());
    }
    if let Some(name) = &m.name {
        lines.push(format!("name \"{name}\""));
        lines.push(String::new());
    }
    if !m.src_dir.is_empty() {
        lines.push(format!("src_dir \"{}\"", m.src_dir));
        lines.push(String::new());
    }
    if !m.cas_dir.is_empty() {
        lines.push("cas {".to_string());
        lines.push(format!("    dir \"{}\"", m.cas_dir));
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.deps.is_empty() {
        lines.push("deps {".to_string());
        for dep in &m.deps {
            lines.push(format_dep_line(dep));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.dev_deps.is_empty() {
        lines.push("dev-deps {".to_string());
        for dep in &m.dev_deps {
            lines.push(format_dep_line(dep));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.overrides.is_empty() {
        lines.push("overrides {".to_string());
        for ov in &m.overrides {
            lines.push(format!(
                "    pkg \"{}\" git=(url)\"{}\" ref=\"{}\"",
                ov.name, ov.git, ov.git_ref
            ));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.self_mirrors.is_empty() {
        lines.push("mirrors {".to_string());
        for url in &m.self_mirrors {
            lines.push(format!("    mirror (url)\"{url}\""));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    if !m.flags.is_empty() {
        lines.push("flags {".to_string());
        for fd in &m.flags {
            let mut head = format!(
                "    \"{}\" default={}",
                fd.name,
                if fd.default { "#true" } else { "#false" }
            );
            if !fd.description.is_empty() {
                head.push_str(&format!(" description=\"{}\"", fd.description));
            }
            if fd.defines.is_empty() {
                lines.push(head);
            } else {
                lines.push(format!("{head} {{"));
                let args: Vec<String> = fd.defines.iter().map(|d| format!("\"{d}\"")).collect();
                lines.push(format!("        defines {}", args.join(" ")));
                lines.push("    }".to_string());
            }
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }

    lines.push(format!("kind \"{}\"", m.kind));
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

/// One deps-block child as a KDL line (or multi-line block for a URL dep with
/// mirrors / multi-value predicates / flag requests).
fn format_dep_line(dep: &Dep) -> String {
    match dep {
        Dep::Url(u) => {
            let mut head = format!(
                "    \"{}\" git=(url)\"{}\" ref=\"{}\"",
                u.name, u.git, u.git_ref
            );
            let inline: Vec<&_> = u
                .predicates
                .iter()
                .filter(|p| p.values.len() == 1)
                .collect();
            let child: Vec<&_> = u.predicates.iter().filter(|p| p.values.len() > 1).collect();
            for p in &inline {
                let v = &p.values[0];
                if p.negated {
                    head.push_str(&format!(" {}=(not)\"{v}\"", p.name));
                } else {
                    head.push_str(&format!(" {}=\"{v}\"", p.name));
                }
            }
            if u.mirrors.is_empty() && child.is_empty() && u.flag_requests.is_empty() {
                return head;
            }
            let mut block = vec![format!("{head} {{")];
            for p in &child {
                let args: Vec<String> = p
                    .values
                    .iter()
                    .map(|v| {
                        if p.negated {
                            format!("(not)\"{v}\"")
                        } else {
                            format!("\"{v}\"")
                        }
                    })
                    .collect();
                block.push(format!("        {} {}", p.name, args.join(" ")));
            }
            for url in &u.mirrors {
                block.push(format!("        mirror (url)\"{url}\""));
            }
            for fr in &u.flag_requests {
                if fr.enabled {
                    block.push(format!("        flag \"{}\"", fr.name));
                } else {
                    block.push(format!("        flag \"{}\" #false", fr.name));
                }
            }
            block.push("    }".to_string());
            block.join("\n")
        }
        Dep::Local(l) => format!("    \"{}\" local=\"{}\"", l.name, l.path),
        Dep::Member(m) => format!("    member \"{}\"", m.name),
        Dep::Tarball(t) => {
            let mut parts = vec![
                format!("    \"{}\"", t.name),
                format!("tarball=(url)\"{}\"", t.url),
            ];
            if let Some(sha) = &t.sha256 {
                parts.push(format!("sha256=\"{sha}\""));
            }
            if t.strip_components != 0 {
                parts.push(format!("strip_components={}", t.strip_components));
            }
            parts.join(" ")
        }
        Dep::Named(n) => match &n.constraint {
            None => format!("    \"{}\"", n.name),
            Some(c) => format!("    \"{}\" \"{c}\"", n.name),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{NamedDep, UrlDep};

    fn base() -> Manifest {
        Manifest {
            name: Some("myapp".into()),
            kind: "application".into(),
            src_dir: String::new(),
            deps: Vec::new(),
            dev_deps: Vec::new(),
            overrides: Vec::new(),
            flags: Vec::new(),
            self_mirrors: Vec::new(),
            cas_dir: String::new(),
            spec_version: 1,
            spec_version_explicit: false,
            attestation_policy: crate::AttestationPolicy::Permissive,
        }
    }

    #[test]
    fn minimal_manifest_round_trips() {
        let m = base();
        let text = format_manifest(&m);
        assert!(text.contains("name \"myapp\""));
        assert!(text.ends_with("kind \"application\"\n"));
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed, m);
    }

    #[test]
    fn url_and_named_deps_round_trip_with_url_annotation() {
        let mut m = base();
        m.deps = vec![
            Dep::Url(UrlDep {
                name: "foo".into(),
                git: "https://e/foo.git".into(),
                git_ref: "main".into(),
                mirrors: Vec::new(),
                predicates: Vec::new(),
                flag_requests: Vec::new(),
            }),
            Dep::Named(NamedDep {
                name: "bar".into(),
                constraint: Some(">= 1.0.0".into()),
                parsed_constraint: Some(
                    milpa_solver::VersionSet::from_constraint(Some(">= 1.0.0")).unwrap(),
                ),
            }),
        ];
        let text = format_manifest(&m);
        assert!(text.contains("git=(url)\"https://e/foo.git\" ref=\"main\""));
        assert!(text.contains("\"bar\" \">= 1.0.0\""));
        // Insertion-stable + round-trips.
        let reparsed = match crate::parse_document(&text).unwrap() {
            crate::ManifestDoc::Package(p) => p,
            other => panic!("expected package, got {other:?}"),
        };
        assert_eq!(reparsed.deps, m.deps);
    }

    #[test]
    fn no_deps_omits_the_block() {
        let text = format_manifest(&base());
        assert!(!text.contains("deps {"));
    }
}
